/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package property

import (
	"context"
	"fmt"

	fleetappsmanagementsdk "github.com/oracle/oci-go-sdk/v65/fleetappsmanagement"
	fleetappsmanagementv1beta1 "github.com/oracle/oci-service-operator/api/fleetappsmanagement/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// PropertyServiceClient is the handwritten extension seam for Property runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*PropertyServiceManager).WithClient.
type PropertyServiceClient interface {
	CreateOrUpdate(context.Context, *fleetappsmanagementv1beta1.Property, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *fleetappsmanagementv1beta1.Property) (bool, error)
}

type defaultPropertyServiceClient struct {
	generatedruntime.ServiceClient[*fleetappsmanagementv1beta1.Property]
}

var _ PropertyServiceClient = defaultPropertyServiceClient{}

var newPropertyServiceClient = func(manager *PropertyServiceManager) PropertyServiceClient {
	sdkClient, err := fleetappsmanagementsdk.NewFleetAppsManagementAdminClientWithConfigurationProvider(manager.Provider)
	hooks := newPropertyRuntimeHooks(manager, sdkClient)
	config := buildPropertyGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Property OCI client: %w", err)
	}
	delegate := defaultPropertyServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*fleetappsmanagementv1beta1.Property](config),
	}
	return wrapPropertyGeneratedClient(hooks, delegate)
}
