/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package lustrefilesystem

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	lustrefilestoragev1beta1 "github.com/oracle/oci-service-operator/api/lustrefilestorage/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type LustreFileSystemServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client LustreFileSystemServiceClient
}

var _ servicemanager.OSOKServiceManager = (*LustreFileSystemServiceManager)(nil)

func NewLustreFileSystemServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *LustreFileSystemServiceManager {
	manager := &LustreFileSystemServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newLustreFileSystemServiceClient(manager)
	return manager
}

func NewLustreFileSystemServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *LustreFileSystemServiceManager {
	return NewLustreFileSystemServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *LustreFileSystemServiceManager) WithClient(client LustreFileSystemServiceClient) *LustreFileSystemServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *LustreFileSystemServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *LustreFileSystemServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *LustreFileSystemServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *LustreFileSystemServiceManager) convert(obj runtime.Object) (*lustrefilestoragev1beta1.LustreFileSystem, error) {
	resource, ok := obj.(*lustrefilestoragev1beta1.LustreFileSystem)
	if !ok {
		return nil, fmt.Errorf("expected *lustrefilestoragev1beta1.LustreFileSystem, got %T", obj)
	}
	return resource, nil
}

func (c *LustreFileSystemServiceManager) status(resource *lustrefilestoragev1beta1.LustreFileSystem) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
