/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package listing

import (
	"context"
	"fmt"

	marketplacesdk "github.com/oracle/oci-go-sdk/v65/marketplace"
	marketplacev1beta1 "github.com/oracle/oci-service-operator/api/marketplace/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ListingServiceClient is the handwritten extension seam for Listing runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*ListingServiceManager).WithClient.
type ListingServiceClient interface {
	CreateOrUpdate(context.Context, *marketplacev1beta1.Listing, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *marketplacev1beta1.Listing) (bool, error)
}

type defaultListingServiceClient struct {
	generatedruntime.ServiceClient[*marketplacev1beta1.Listing]
}

var _ ListingServiceClient = defaultListingServiceClient{}

var newListingServiceClient = func(manager *ListingServiceManager) ListingServiceClient {
	sdkClient, err := marketplacesdk.NewMarketplaceClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*marketplacev1beta1.Listing]{
		Kind:    "Listing",
		SDKName: "Listing",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &marketplacesdk.GetListingRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetListing(ctx, *request.(*marketplacesdk.GetListingRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &marketplacesdk.ListListingsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListListings(ctx, *request.(*marketplacesdk.ListListingsRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize Listing OCI client: %w", err)
	}
	return defaultListingServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*marketplacev1beta1.Listing](config),
	}
}
