apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/filestorage.oracle.com_exports.yaml
- bases/filestorage.oracle.com_filesystems.yaml
- bases/filestorage.oracle.com_filesystemsnapshotpolicies.yaml
- bases/filestorage.oracle.com_mounttargets.yaml
- bases/filestorage.oracle.com_outboundconnectors.yaml
- bases/filestorage.oracle.com_quotarules.yaml
- bases/filestorage.oracle.com_replications.yaml
- bases/filestorage.oracle.com_snapshots.yaml
