/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package targetasset

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	cloudmigrationsv1beta1 "github.com/oracle/oci-service-operator/api/cloudmigrations/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type TargetAssetServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client TargetAssetServiceClient
}

var _ servicemanager.OSOKServiceManager = (*TargetAssetServiceManager)(nil)

func NewTargetAssetServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *TargetAssetServiceManager {
	manager := &TargetAssetServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newTargetAssetServiceClient(manager)
	return manager
}

func NewTargetAssetServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *TargetAssetServiceManager {
	return NewTargetAssetServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *TargetAssetServiceManager) WithClient(client TargetAssetServiceClient) *TargetAssetServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *TargetAssetServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *TargetAssetServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *TargetAssetServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *TargetAssetServiceManager) convert(obj runtime.Object) (*cloudmigrationsv1beta1.TargetAsset, error) {
	resource, ok := obj.(*cloudmigrationsv1beta1.TargetAsset)
	if !ok {
		return nil, fmt.Errorf("expected *cloudmigrationsv1beta1.TargetAsset, got %T", obj)
	}
	return resource, nil
}

func (c *TargetAssetServiceManager) status(resource *cloudmigrationsv1beta1.TargetAsset) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
