/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package opsi

import (
	"context"

	opsiv1beta1 "github.com/oracle/oci-service-operator/api/opsi/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// OperationsInsightsWarehouseReconciler reconciles a OperationsInsightsWarehouse object.
type OperationsInsightsWarehouseReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=opsi.oracle.com,resources=operationsinsightswarehouses,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=opsi.oracle.com,resources=operationsinsightswarehouses/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=opsi.oracle.com,resources=operationsinsightswarehouses/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *OperationsInsightsWarehouseReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	operationsInsightsWarehouse := &opsiv1beta1.OperationsInsightsWarehouse{}
	return r.Reconciler.Reconcile(ctx, req, operationsInsightsWarehouse)
}

// SetupWithManager sets up the controller with the Manager.
func (r *OperationsInsightsWarehouseReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&opsiv1beta1.OperationsInsightsWarehouse{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
