/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package attachment

import (
	"context"
	"fmt"

	marketplaceprivateoffersdk "github.com/oracle/oci-go-sdk/v65/marketplaceprivateoffer"
	marketplaceprivateofferv1beta1 "github.com/oracle/oci-service-operator/api/marketplaceprivateoffer/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AttachmentServiceClient is the handwritten extension seam for Attachment runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*AttachmentServiceManager).WithClient.
type AttachmentServiceClient interface {
	CreateOrUpdate(context.Context, *marketplaceprivateofferv1beta1.Attachment, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *marketplaceprivateofferv1beta1.Attachment) (bool, error)
}

type defaultAttachmentServiceClient struct {
	generatedruntime.ServiceClient[*marketplaceprivateofferv1beta1.Attachment]
}

var _ AttachmentServiceClient = defaultAttachmentServiceClient{}

var newAttachmentServiceClient = func(manager *AttachmentServiceManager) AttachmentServiceClient {
	sdkClient, err := marketplaceprivateoffersdk.NewAttachmentClientWithConfigurationProvider(manager.Provider)
	hooks := newAttachmentRuntimeHooks(manager, sdkClient)
	config := buildAttachmentGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Attachment OCI client: %w", err)
	}
	delegate := defaultAttachmentServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*marketplaceprivateofferv1beta1.Attachment](config),
	}
	return wrapAttachmentGeneratedClient(hooks, delegate)
}
