/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package costtrackingtag

import (
	"context"
	"fmt"

	identitysdk "github.com/oracle/oci-go-sdk/v65/identity"
	identityv1beta1 "github.com/oracle/oci-service-operator/api/identity/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// CostTrackingTagServiceClient is the handwritten extension seam for CostTrackingTag runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*CostTrackingTagServiceManager).WithClient.
type CostTrackingTagServiceClient interface {
	CreateOrUpdate(context.Context, *identityv1beta1.CostTrackingTag, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *identityv1beta1.CostTrackingTag) (bool, error)
}

type defaultCostTrackingTagServiceClient struct {
	generatedruntime.ServiceClient[*identityv1beta1.CostTrackingTag]
}

var _ CostTrackingTagServiceClient = defaultCostTrackingTagServiceClient{}

var newCostTrackingTagServiceClient = func(manager *CostTrackingTagServiceManager) CostTrackingTagServiceClient {
	sdkClient, err := identitysdk.NewIdentityClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*identityv1beta1.CostTrackingTag]{
		Kind:    "CostTrackingTag",
		SDKName: "CostTrackingTag",
		Log:     manager.Log,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.ListCostTrackingTagsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListCostTrackingTags(ctx, *request.(*identitysdk.ListCostTrackingTagsRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize CostTrackingTag OCI client: %w", err)
	}
	return defaultCostTrackingTagServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*identityv1beta1.CostTrackingTag](config),
	}
}
