//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/oracle/oci-service-operator/pkg/shared"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAnalyticsInstance) DeepCopyInto(out *ResourceAnalyticsInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAnalyticsInstance.
func (in *ResourceAnalyticsInstance) DeepCopy() *ResourceAnalyticsInstance {
	if in == nil {
		return nil
	}
	out := new(ResourceAnalyticsInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceAnalyticsInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAnalyticsInstanceAdwAdminPassword) DeepCopyInto(out *ResourceAnalyticsInstanceAdwAdminPassword) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAnalyticsInstanceAdwAdminPassword.
func (in *ResourceAnalyticsInstanceAdwAdminPassword) DeepCopy() *ResourceAnalyticsInstanceAdwAdminPassword {
	if in == nil {
		return nil
	}
	out := new(ResourceAnalyticsInstanceAdwAdminPassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAnalyticsInstanceList) DeepCopyInto(out *ResourceAnalyticsInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceAnalyticsInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAnalyticsInstanceList.
func (in *ResourceAnalyticsInstanceList) DeepCopy() *ResourceAnalyticsInstanceList {
	if in == nil {
		return nil
	}
	out := new(ResourceAnalyticsInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceAnalyticsInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAnalyticsInstanceSpec) DeepCopyInto(out *ResourceAnalyticsInstanceSpec) {
	*out = *in
	out.AdwAdminPassword = in.AdwAdminPassword
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAnalyticsInstanceSpec.
func (in *ResourceAnalyticsInstanceSpec) DeepCopy() *ResourceAnalyticsInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceAnalyticsInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAnalyticsInstanceStatus) DeepCopyInto(out *ResourceAnalyticsInstanceStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAnalyticsInstanceStatus.
func (in *ResourceAnalyticsInstanceStatus) DeepCopy() *ResourceAnalyticsInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceAnalyticsInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancyAttachment) DeepCopyInto(out *TenancyAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancyAttachment.
func (in *TenancyAttachment) DeepCopy() *TenancyAttachment {
	if in == nil {
		return nil
	}
	out := new(TenancyAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenancyAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancyAttachmentList) DeepCopyInto(out *TenancyAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenancyAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancyAttachmentList.
func (in *TenancyAttachmentList) DeepCopy() *TenancyAttachmentList {
	if in == nil {
		return nil
	}
	out := new(TenancyAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenancyAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancyAttachmentSpec) DeepCopyInto(out *TenancyAttachmentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancyAttachmentSpec.
func (in *TenancyAttachmentSpec) DeepCopy() *TenancyAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(TenancyAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancyAttachmentStatus) DeepCopyInto(out *TenancyAttachmentStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancyAttachmentStatus.
func (in *TenancyAttachmentStatus) DeepCopy() *TenancyAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(TenancyAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}
