apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/ons.oracle.com_confirmsubscriptions.yaml
- bases/ons.oracle.com_subscriptions.yaml
- bases/ons.oracle.com_topics.yaml
- bases/ons.oracle.com_unsubscriptions.yaml
