/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PrivateEndpointSpec defines the desired state of PrivateEndpoint.
type PrivateEndpointSpec struct {
	// The OCID of a compartment.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// An array of DNS zone names.
	// Example: `[ "app.examplecorp.com", "app.examplecorp2.com" ]`
	// +kubebuilder:validation:Required
	DnsZones []string `json:"dnsZones"`
	// The OCID of a subnet.
	// +kubebuilder:validation:Required
	SubnetId string `json:"subnetId"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// A user-friendly description. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description string `json:"description,omitempty"`
	// A user-friendly name. It does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName string `json:"displayName,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The maximum number of hosts to be accessed through the private endpoint. This value is used
	// to calculate the relevant CIDR block and should be a multiple of 256.  If the value is not a
	// multiple of 256, it is rounded up to the next multiple of 256. For example, 300 is rounded up
	// to 512.
	// +kubebuilder:validation:Optional
	MaxHostCount int `json:"maxHostCount,omitempty"`
	// An array of network security group OCIDs.
	// +kubebuilder:validation:Optional
	NsgIds []string `json:"nsgIds,omitempty"`
	// An array of fqdn/port pairs used to create private endpoint. Each object is a simple key-value pair with FQDN as key and port number as value.
	// [ { fqdn: "scan1.oracle.com", port: "1521"}, { fqdn: "scan2.oracle.com", port: "1521" } ]
	// +kubebuilder:validation:Optional
	ScanDetails []PrivateEndpointScanDetail `json:"scanDetails,omitempty"`
}

// PrivateEndpointScanDetail defines nested fields for PrivateEndpoint.ScanDetail.
type PrivateEndpointScanDetail struct {
	// A fully-qualified domain name (FQDN).
	// +kubebuilder:validation:Optional
	Fqdn string `json:"fqdn,omitempty"`
	// The port number of the FQDN
	// +kubebuilder:validation:Optional
	Port string `json:"port,omitempty"`
}

// PrivateEndpointStatus defines the observed state of PrivateEndpoint.
type PrivateEndpointStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID of a compartment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// A user-friendly name. It does not have to be unique. Avoid entering confidential information.
	DisplayName string `json:"displayName,omitempty"`
	// An array of DNS zone names.
	// Example: `[ "app.examplecorp.com", "app.examplecorp2.com" ]`
	DnsZones []string `json:"dnsZones,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The OCID of a private endpoint.
	Id string `json:"id,omitempty"`
	// The current state of this private endpoint.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The OCID of the user who created the resource.
	OwnerPrincipalId string `json:"ownerPrincipalId,omitempty"`
	// The OCID of a subnet.
	SubnetId string `json:"subnetId,omitempty"`
	// The date and time the resource was created, expressed in RFC 3339 (https://tools.ietf.org/html/rfc3339) timestamp format.
	// Example: `2018-04-03T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the resource was updated, expressed in RFC 3339 (https://tools.ietf.org/html/rfc3339) timestamp format.
	// Example: `2018-04-03T21:10:29.600Z`
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// A user-friendly description. Avoid entering confidential information.
	Description string `json:"description,omitempty"`
	// The detailed messages about the lifecycle state.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// The maximum number of hosts to be accessed through the private endpoint. This value is used
	// to calculate the relevant CIDR block and should be a multiple of 256.  If the value is not a
	// multiple of 256, it is rounded up to the next multiple of 256. For example, 300 is rounded up
	// to 512.
	MaxHostCount int `json:"maxHostCount,omitempty"`
	// An array of network security group OCIDs.
	NsgIds []string `json:"nsgIds,omitempty"`
	// The username of the user who created the resource.  If the username of the owner does not exist,
	// `null` will be returned and the caller should refer to the ownerPrincipalId value instead.
	OwnerUserName string `json:"ownerUserName,omitempty"`
	// An array of fqdn/port pairs used to create private endpoint. Each object is a simple key-value pair with FQDN as key and port number as value.
	// [ { fqdn: "scan1.oracle.com", port: "1521"}, { fqdn: "scan2.oracle.com", port: "1521" } ]
	ScanDetails []PrivateEndpointScanDetail `json:"scanDetails,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the PrivateEndpoint",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the PrivateEndpoint",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// PrivateEndpoint is the Schema for the privateendpoints API.
type PrivateEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PrivateEndpointSpec   `json:"spec,omitempty"`
	Status PrivateEndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// PrivateEndpointList contains a list of PrivateEndpoint.
type PrivateEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivateEndpoint `json:"items"`
}

func init() {
	SchemeBuilder.Register(&PrivateEndpoint{}, &PrivateEndpointList{})
}
