/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package customprotectionrule

import (
	"context"
	"fmt"

	waassdk "github.com/oracle/oci-go-sdk/v65/waas"
	waasv1beta1 "github.com/oracle/oci-service-operator/api/waas/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// CustomProtectionRuleServiceClient is the handwritten extension seam for CustomProtectionRule runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*CustomProtectionRuleServiceManager).WithClient.
type CustomProtectionRuleServiceClient interface {
	CreateOrUpdate(context.Context, *waasv1beta1.CustomProtectionRule, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *waasv1beta1.CustomProtectionRule) (bool, error)
}

type defaultCustomProtectionRuleServiceClient struct {
	generatedruntime.ServiceClient[*waasv1beta1.CustomProtectionRule]
}

var _ CustomProtectionRuleServiceClient = defaultCustomProtectionRuleServiceClient{}

var newCustomProtectionRuleServiceClient = func(manager *CustomProtectionRuleServiceManager) CustomProtectionRuleServiceClient {
	sdkClient, err := waassdk.NewWaasClientWithConfigurationProvider(manager.Provider)
	hooks := newCustomProtectionRuleRuntimeHooks(manager, sdkClient)
	config := buildCustomProtectionRuleGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize CustomProtectionRule OCI client: %w", err)
	}
	delegate := defaultCustomProtectionRuleServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*waasv1beta1.CustomProtectionRule](config),
	}
	return wrapCustomProtectionRuleGeneratedClient(hooks, delegate)
}
