/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package fsucycle

import (
	"context"
	"fmt"

	fleetsoftwareupdatesdk "github.com/oracle/oci-go-sdk/v65/fleetsoftwareupdate"
	fleetsoftwareupdatev1beta1 "github.com/oracle/oci-service-operator/api/fleetsoftwareupdate/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// FsuCycleServiceClient is the handwritten extension seam for FsuCycle runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*FsuCycleServiceManager).WithClient.
type FsuCycleServiceClient interface {
	CreateOrUpdate(context.Context, *fleetsoftwareupdatev1beta1.FsuCycle, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *fleetsoftwareupdatev1beta1.FsuCycle) (bool, error)
}

type defaultFsuCycleServiceClient struct {
	generatedruntime.ServiceClient[*fleetsoftwareupdatev1beta1.FsuCycle]
}

var _ FsuCycleServiceClient = defaultFsuCycleServiceClient{}

var newFsuCycleServiceClient = func(manager *FsuCycleServiceManager) FsuCycleServiceClient {
	sdkClient, err := fleetsoftwareupdatesdk.NewFleetSoftwareUpdateClientWithConfigurationProvider(manager.Provider)
	hooks := newFsuCycleRuntimeHooks(manager, sdkClient)
	config := buildFsuCycleGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize FsuCycle OCI client: %w", err)
	}
	delegate := defaultFsuCycleServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*fleetsoftwareupdatev1beta1.FsuCycle](config),
	}
	return wrapFsuCycleGeneratedClient(hooks, delegate)
}
