/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package networkloadbalancer

import (
	"context"

	networkloadbalancersdk "github.com/oracle/oci-go-sdk/v65/networkloadbalancer"
	networkloadbalancerv1beta1 "github.com/oracle/oci-service-operator/api/networkloadbalancer/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type NetworkLoadBalancerRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *networkloadbalancerv1beta1.NetworkLoadBalancer, string) (any, error)
	BuildUpdateBody func(context.Context, *networkloadbalancerv1beta1.NetworkLoadBalancer, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]
	StatusHooks         generatedruntime.StatusHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]
	ParityHooks         generatedruntime.ParityHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]
	Async               generatedruntime.AsyncHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]
	DeleteHooks         generatedruntime.DeleteHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]
	Create              runtimeOperationHooks[networkloadbalancersdk.CreateNetworkLoadBalancerRequest, networkloadbalancersdk.CreateNetworkLoadBalancerResponse]
	Get                 runtimeOperationHooks[networkloadbalancersdk.GetNetworkLoadBalancerRequest, networkloadbalancersdk.GetNetworkLoadBalancerResponse]
	List                runtimeOperationHooks[networkloadbalancersdk.ListNetworkLoadBalancersRequest, networkloadbalancersdk.ListNetworkLoadBalancersResponse]
	Update              runtimeOperationHooks[networkloadbalancersdk.UpdateNetworkLoadBalancerRequest, networkloadbalancersdk.UpdateNetworkLoadBalancerResponse]
	Delete              runtimeOperationHooks[networkloadbalancersdk.DeleteNetworkLoadBalancerRequest, networkloadbalancersdk.DeleteNetworkLoadBalancerResponse]
	WrapGeneratedClient []func(NetworkLoadBalancerServiceClient) NetworkLoadBalancerServiceClient
}

type NetworkLoadBalancerRuntimeHooksMutator func(*NetworkLoadBalancerServiceManager, *NetworkLoadBalancerRuntimeHooks)

var networkloadbalancerRuntimeHooksMutators []NetworkLoadBalancerRuntimeHooksMutator

func registerNetworkLoadBalancerRuntimeHooksMutator(mutator NetworkLoadBalancerRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	networkloadbalancerRuntimeHooksMutators = append(networkloadbalancerRuntimeHooksMutators, mutator)
}
func newNetworkLoadBalancerDefaultRuntimeHooks(sdkClient networkloadbalancersdk.NetworkLoadBalancerClient) NetworkLoadBalancerRuntimeHooks {
	return NetworkLoadBalancerRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]{},
		StatusHooks:     generatedruntime.StatusHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]{},
		ParityHooks:     generatedruntime.ParityHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]{},
		Async:           generatedruntime.AsyncHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*networkloadbalancerv1beta1.NetworkLoadBalancer]{},
		Create: runtimeOperationHooks[networkloadbalancersdk.CreateNetworkLoadBalancerRequest, networkloadbalancersdk.CreateNetworkLoadBalancerResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateNetworkLoadBalancerDetails", RequestName: "CreateNetworkLoadBalancerDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkloadbalancersdk.CreateNetworkLoadBalancerRequest) (networkloadbalancersdk.CreateNetworkLoadBalancerResponse, error) {
				return sdkClient.CreateNetworkLoadBalancer(ctx, request)
			},
		},
		Get: runtimeOperationHooks[networkloadbalancersdk.GetNetworkLoadBalancerRequest, networkloadbalancersdk.GetNetworkLoadBalancerResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkLoadBalancerId", RequestName: "networkLoadBalancerId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request networkloadbalancersdk.GetNetworkLoadBalancerRequest) (networkloadbalancersdk.GetNetworkLoadBalancerResponse, error) {
				return sdkClient.GetNetworkLoadBalancer(ctx, request)
			},
		},
		List: runtimeOperationHooks[networkloadbalancersdk.ListNetworkLoadBalancersRequest, networkloadbalancersdk.ListNetworkLoadBalancersResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkloadbalancersdk.ListNetworkLoadBalancersRequest) (networkloadbalancersdk.ListNetworkLoadBalancersResponse, error) {
				return sdkClient.ListNetworkLoadBalancers(ctx, request)
			},
		},
		Update: runtimeOperationHooks[networkloadbalancersdk.UpdateNetworkLoadBalancerRequest, networkloadbalancersdk.UpdateNetworkLoadBalancerResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkLoadBalancerId", RequestName: "networkLoadBalancerId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateNetworkLoadBalancerDetails", RequestName: "UpdateNetworkLoadBalancerDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkloadbalancersdk.UpdateNetworkLoadBalancerRequest) (networkloadbalancersdk.UpdateNetworkLoadBalancerResponse, error) {
				return sdkClient.UpdateNetworkLoadBalancer(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[networkloadbalancersdk.DeleteNetworkLoadBalancerRequest, networkloadbalancersdk.DeleteNetworkLoadBalancerResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkLoadBalancerId", RequestName: "networkLoadBalancerId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request networkloadbalancersdk.DeleteNetworkLoadBalancerRequest) (networkloadbalancersdk.DeleteNetworkLoadBalancerResponse, error) {
				return sdkClient.DeleteNetworkLoadBalancer(ctx, request)
			},
		},
		WrapGeneratedClient: []func(NetworkLoadBalancerServiceClient) NetworkLoadBalancerServiceClient{},
	}
}

func newNetworkLoadBalancerRuntimeHooks(manager *NetworkLoadBalancerServiceManager, sdkClient networkloadbalancersdk.NetworkLoadBalancerClient) NetworkLoadBalancerRuntimeHooks {
	hooks := newNetworkLoadBalancerDefaultRuntimeHooks(sdkClient)
	for _, mutator := range networkloadbalancerRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildNetworkLoadBalancerGeneratedRuntimeConfig(
	manager *NetworkLoadBalancerServiceManager,
	hooks NetworkLoadBalancerRuntimeHooks,
) generatedruntime.Config[*networkloadbalancerv1beta1.NetworkLoadBalancer] {
	return generatedruntime.Config[*networkloadbalancerv1beta1.NetworkLoadBalancer]{
		Kind:            "NetworkLoadBalancer",
		SDKName:         "NetworkLoadBalancer",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &networkloadbalancersdk.CreateNetworkLoadBalancerRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*networkloadbalancersdk.CreateNetworkLoadBalancerRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &networkloadbalancersdk.GetNetworkLoadBalancerRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*networkloadbalancersdk.GetNetworkLoadBalancerRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &networkloadbalancersdk.ListNetworkLoadBalancersRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*networkloadbalancersdk.ListNetworkLoadBalancersRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &networkloadbalancersdk.UpdateNetworkLoadBalancerRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*networkloadbalancersdk.UpdateNetworkLoadBalancerRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &networkloadbalancersdk.DeleteNetworkLoadBalancerRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*networkloadbalancersdk.DeleteNetworkLoadBalancerRequest))
			},
		},
	}
}

func wrapNetworkLoadBalancerGeneratedClient(
	hooks NetworkLoadBalancerRuntimeHooks,
	delegate NetworkLoadBalancerServiceClient,
) NetworkLoadBalancerServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
