/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package dataintegration

import (
	"context"

	dataintegrationv1beta1 "github.com/oracle/oci-service-operator/api/dataintegration/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// FunctionLibraryReconciler reconciles a FunctionLibrary object.
type FunctionLibraryReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=dataintegration.oracle.com,resources=functionlibraries,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=dataintegration.oracle.com,resources=functionlibraries/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=dataintegration.oracle.com,resources=functionlibraries/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *FunctionLibraryReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	functionLibrary := &dataintegrationv1beta1.FunctionLibrary{}
	return r.Reconciler.Reconcile(ctx, req, functionLibrary)
}

// SetupWithManager sets up the controller with the Manager.
func (r *FunctionLibraryReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&dataintegrationv1beta1.FunctionLibrary{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
