/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package rediscluster

import (
	"context"
	"fmt"

	redissdk "github.com/oracle/oci-go-sdk/v65/redis"
	redisv1beta1 "github.com/oracle/oci-service-operator/api/redis/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// RedisClusterServiceClient is the handwritten extension seam for RedisCluster runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*RedisClusterServiceManager).WithClient.
type RedisClusterServiceClient interface {
	CreateOrUpdate(context.Context, *redisv1beta1.RedisCluster, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *redisv1beta1.RedisCluster) (bool, error)
}

type defaultRedisClusterServiceClient struct {
	generatedruntime.ServiceClient[*redisv1beta1.RedisCluster]
}

var _ RedisClusterServiceClient = defaultRedisClusterServiceClient{}

var newRedisClusterServiceClient = func(manager *RedisClusterServiceManager) RedisClusterServiceClient {
	sdkClient, err := redissdk.NewRedisClusterClientWithConfigurationProvider(manager.Provider)
	hooks := newRedisClusterRuntimeHooks(manager, sdkClient)
	config := buildRedisClusterGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize RedisCluster OCI client: %w", err)
	}
	delegate := defaultRedisClusterServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*redisv1beta1.RedisCluster](config),
	}
	return wrapRedisClusterGeneratedClient(hooks, delegate)
}
