#
# Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: core.oracle.com/v1beta1
kind: ServiceGateway
metadata:
  name: osok-service-gateway-${OSOK_E2E_SUFFIX}
spec:
  compartmentId: ${OCI_COMPARTMENT_ID}
  vcnId: ${OCI_VCN_ID}
  displayName: osok-service-gateway-${OSOK_E2E_SUFFIX}
  services: []
  blockTraffic: true
  freeformTags:
    osok-e2e-phase: create
