apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/securityattribute.oracle.com_securityattributenamespaces.yaml
- bases/securityattribute.oracle.com_securityattributes.yaml
