/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CloudVmClusterUpdateSpec defines the desired state of CloudVmClusterUpdate.
type CloudVmClusterUpdateSpec struct {
}

// CloudVmClusterUpdateStatus defines the observed state of CloudVmClusterUpdate.
type CloudVmClusterUpdateStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the CloudVmClusterUpdate",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the CloudVmClusterUpdate",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// CloudVmClusterUpdate is the Schema for the cloudvmclusterupdates API.
type CloudVmClusterUpdate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CloudVmClusterUpdateSpec   `json:"spec,omitempty"`
	Status CloudVmClusterUpdateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// CloudVmClusterUpdateList contains a list of CloudVmClusterUpdate.
type CloudVmClusterUpdateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudVmClusterUpdate `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CloudVmClusterUpdate{}, &CloudVmClusterUpdateList{})
}
