/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package natrule

import (
	"context"

	networkfirewallsdk "github.com/oracle/oci-go-sdk/v65/networkfirewall"
	networkfirewallv1beta1 "github.com/oracle/oci-service-operator/api/networkfirewall/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type NatRuleRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *networkfirewallv1beta1.NatRule, string) (any, error)
	BuildUpdateBody func(context.Context, *networkfirewallv1beta1.NatRule, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*networkfirewallv1beta1.NatRule]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*networkfirewallv1beta1.NatRule]
	StatusHooks         generatedruntime.StatusHooks[*networkfirewallv1beta1.NatRule]
	ParityHooks         generatedruntime.ParityHooks[*networkfirewallv1beta1.NatRule]
	Async               generatedruntime.AsyncHooks[*networkfirewallv1beta1.NatRule]
	DeleteHooks         generatedruntime.DeleteHooks[*networkfirewallv1beta1.NatRule]
	Create              runtimeOperationHooks[networkfirewallsdk.CreateNatRuleRequest, networkfirewallsdk.CreateNatRuleResponse]
	Get                 runtimeOperationHooks[networkfirewallsdk.GetNatRuleRequest, networkfirewallsdk.GetNatRuleResponse]
	List                runtimeOperationHooks[networkfirewallsdk.ListNatRulesRequest, networkfirewallsdk.ListNatRulesResponse]
	Update              runtimeOperationHooks[networkfirewallsdk.UpdateNatRuleRequest, networkfirewallsdk.UpdateNatRuleResponse]
	Delete              runtimeOperationHooks[networkfirewallsdk.DeleteNatRuleRequest, networkfirewallsdk.DeleteNatRuleResponse]
	WrapGeneratedClient []func(NatRuleServiceClient) NatRuleServiceClient
}

type NatRuleRuntimeHooksMutator func(*NatRuleServiceManager, *NatRuleRuntimeHooks)

var natruleRuntimeHooksMutators []NatRuleRuntimeHooksMutator

func registerNatRuleRuntimeHooksMutator(mutator NatRuleRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	natruleRuntimeHooksMutators = append(natruleRuntimeHooksMutators, mutator)
}
func newNatRuleDefaultRuntimeHooks(sdkClient networkfirewallsdk.NetworkFirewallClient) NatRuleRuntimeHooks {
	return NatRuleRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*networkfirewallv1beta1.NatRule]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*networkfirewallv1beta1.NatRule]{},
		StatusHooks:     generatedruntime.StatusHooks[*networkfirewallv1beta1.NatRule]{},
		ParityHooks:     generatedruntime.ParityHooks[*networkfirewallv1beta1.NatRule]{},
		Async:           generatedruntime.AsyncHooks[*networkfirewallv1beta1.NatRule]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*networkfirewallv1beta1.NatRule]{},
		Create: runtimeOperationHooks[networkfirewallsdk.CreateNatRuleRequest, networkfirewallsdk.CreateNatRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "CreateNatRuleDetails", RequestName: "CreateNatRuleDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.CreateNatRuleRequest) (networkfirewallsdk.CreateNatRuleResponse, error) {
				return sdkClient.CreateNatRule(ctx, request)
			},
		},
		Get: runtimeOperationHooks[networkfirewallsdk.GetNatRuleRequest, networkfirewallsdk.GetNatRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "NatRuleName", RequestName: "natRuleName", Contribution: "path", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.GetNatRuleRequest) (networkfirewallsdk.GetNatRuleResponse, error) {
				return sdkClient.GetNatRule(ctx, request)
			},
		},
		List: runtimeOperationHooks[networkfirewallsdk.ListNatRulesRequest, networkfirewallsdk.ListNatRulesResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: true}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "NatRulePriorityOrder", RequestName: "natRulePriorityOrder", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.ListNatRulesRequest) (networkfirewallsdk.ListNatRulesResponse, error) {
				return sdkClient.ListNatRules(ctx, request)
			},
		},
		Update: runtimeOperationHooks[networkfirewallsdk.UpdateNatRuleRequest, networkfirewallsdk.UpdateNatRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "NatRuleName", RequestName: "natRuleName", Contribution: "path", PreferResourceID: false}, {FieldName: "UpdateNatRuleDetails", RequestName: "UpdateNatRuleDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.UpdateNatRuleRequest) (networkfirewallsdk.UpdateNatRuleResponse, error) {
				return sdkClient.UpdateNatRule(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[networkfirewallsdk.DeleteNatRuleRequest, networkfirewallsdk.DeleteNatRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "NatRuleName", RequestName: "natRuleName", Contribution: "path", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.DeleteNatRuleRequest) (networkfirewallsdk.DeleteNatRuleResponse, error) {
				return sdkClient.DeleteNatRule(ctx, request)
			},
		},
		WrapGeneratedClient: []func(NatRuleServiceClient) NatRuleServiceClient{},
	}
}

func newNatRuleRuntimeHooks(manager *NatRuleServiceManager, sdkClient networkfirewallsdk.NetworkFirewallClient) NatRuleRuntimeHooks {
	hooks := newNatRuleDefaultRuntimeHooks(sdkClient)
	for _, mutator := range natruleRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildNatRuleGeneratedRuntimeConfig(
	manager *NatRuleServiceManager,
	hooks NatRuleRuntimeHooks,
) generatedruntime.Config[*networkfirewallv1beta1.NatRule] {
	return generatedruntime.Config[*networkfirewallv1beta1.NatRule]{
		Kind:            "NatRule",
		SDKName:         "NatRule",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.CreateNatRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*networkfirewallsdk.CreateNatRuleRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.GetNatRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*networkfirewallsdk.GetNatRuleRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.ListNatRulesRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*networkfirewallsdk.ListNatRulesRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.UpdateNatRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*networkfirewallsdk.UpdateNatRuleRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.DeleteNatRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*networkfirewallsdk.DeleteNatRuleRequest))
			},
		},
	}
}

func wrapNatRuleGeneratedClient(
	hooks NatRuleRuntimeHooks,
	delegate NatRuleServiceClient,
) NatRuleServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
