/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package peer

import (
	"context"
	"fmt"

	blockchainsdk "github.com/oracle/oci-go-sdk/v65/blockchain"
	blockchainv1beta1 "github.com/oracle/oci-service-operator/api/blockchain/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// PeerServiceClient is the handwritten extension seam for Peer runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*PeerServiceManager).WithClient.
type PeerServiceClient interface {
	CreateOrUpdate(context.Context, *blockchainv1beta1.Peer, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *blockchainv1beta1.Peer) (bool, error)
}

type defaultPeerServiceClient struct {
	generatedruntime.ServiceClient[*blockchainv1beta1.Peer]
}

var _ PeerServiceClient = defaultPeerServiceClient{}

var newPeerServiceClient = func(manager *PeerServiceManager) PeerServiceClient {
	sdkClient, err := blockchainsdk.NewBlockchainPlatformClientWithConfigurationProvider(manager.Provider)
	hooks := newPeerRuntimeHooks(manager, sdkClient)
	config := buildPeerGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Peer OCI client: %w", err)
	}
	delegate := defaultPeerServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*blockchainv1beta1.Peer](config),
	}
	return wrapPeerGeneratedClient(hooks, delegate)
}
