/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package core

import (
	"context"

	corev1beta1 "github.com/oracle/oci-service-operator/api/core/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// TunnelCpeDeviceConfigReconciler reconciles a TunnelCpeDeviceConfig object.
type TunnelCpeDeviceConfigReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=core.oracle.com,resources=tunnelcpedeviceconfigs,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core.oracle.com,resources=tunnelcpedeviceconfigs/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=core.oracle.com,resources=tunnelcpedeviceconfigs/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *TunnelCpeDeviceConfigReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	tunnelCpeDeviceConfig := &corev1beta1.TunnelCpeDeviceConfig{}
	return r.Reconciler.Reconcile(ctx, req, tunnelCpeDeviceConfig)
}

// SetupWithManager sets up the controller with the Manager.
func (r *TunnelCpeDeviceConfigReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&corev1beta1.TunnelCpeDeviceConfig{})
	return builder.
		WithEventFilter(predicate.GenerationChangedPredicate{}).
		Complete(r)
}
