apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/queue.oracle.com_channels.yaml
- bases/queue.oracle.com_messages.yaml
- bases/queue.oracle.com_queues.yaml
- bases/queue.oracle.com_stats.yaml
- bases/queue.oracle.com_workrequesterrors.yaml
- bases/queue.oracle.com_workrequestlogs.yaml
- bases/queue.oracle.com_workrequests.yaml
