---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - containerengine.oracle.com
  resources:
  - addonoptions
  - addons
  - clusterendpointconfigs
  - clustermigratetonativevcnstatuses
  - clusteroptions
  - clusters
  - credentialrotationstatuses
  - kubeconfigs
  - nodepooloptions
  - nodepools
  - nodes
  - podshapes
  - virtualnodepools
  - virtualnodes
  - workloadmappings
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerengine.oracle.com
  resources:
  - addonoptions/finalizers
  - addons/finalizers
  - clusterendpointconfigs/finalizers
  - clustermigratetonativevcnstatuses/finalizers
  - clusteroptions/finalizers
  - clusters/finalizers
  - credentialrotationstatuses/finalizers
  - kubeconfigs/finalizers
  - nodepooloptions/finalizers
  - nodepools/finalizers
  - nodes/finalizers
  - podshapes/finalizers
  - virtualnodepools/finalizers
  - virtualnodes/finalizers
  - workloadmappings/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - containerengine.oracle.com
  resources:
  - addonoptions/status
  - addons/status
  - clusterendpointconfigs/status
  - clustermigratetonativevcnstatuses/status
  - clusteroptions/status
  - clusters/status
  - credentialrotationstatuses/status
  - kubeconfigs/status
  - nodepooloptions/status
  - nodepools/status
  - nodes/status
  - podshapes/status
  - virtualnodepools/status
  - virtualnodes/status
  - workloadmappings/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
