/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package subscription

import (
	"context"
	"fmt"

	onssdk "github.com/oracle/oci-go-sdk/v65/ons"
	onsv1beta1 "github.com/oracle/oci-service-operator/api/ons/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// SubscriptionServiceClient is the handwritten extension seam for Subscription runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*SubscriptionServiceManager).WithClient.
type SubscriptionServiceClient interface {
	CreateOrUpdate(context.Context, *onsv1beta1.Subscription, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *onsv1beta1.Subscription) (bool, error)
}

type defaultSubscriptionServiceClient struct {
	generatedruntime.ServiceClient[*onsv1beta1.Subscription]
}

var _ SubscriptionServiceClient = defaultSubscriptionServiceClient{}

var newSubscriptionServiceClient = func(manager *SubscriptionServiceManager) SubscriptionServiceClient {
	sdkClient, err := onssdk.NewNotificationDataPlaneClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*onsv1beta1.Subscription]{
		Kind:    "Subscription",
		SDKName: "Subscription",
		Log:     manager.Log,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &onssdk.CreateSubscriptionRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.CreateSubscription(ctx, *request.(*onssdk.CreateSubscriptionRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &onssdk.GetSubscriptionRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetSubscription(ctx, *request.(*onssdk.GetSubscriptionRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &onssdk.ListSubscriptionsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListSubscriptions(ctx, *request.(*onssdk.ListSubscriptionsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &onssdk.UpdateSubscriptionRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateSubscription(ctx, *request.(*onssdk.UpdateSubscriptionRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &onssdk.DeleteSubscriptionRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteSubscription(ctx, *request.(*onssdk.DeleteSubscriptionRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize Subscription OCI client: %w", err)
	}
	return defaultSubscriptionServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*onsv1beta1.Subscription](config),
	}
}
