/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package project

import (
	"context"
	"fmt"

	datasciencesdk "github.com/oracle/oci-go-sdk/v65/datascience"
	datasciencev1beta1 "github.com/oracle/oci-service-operator/api/datascience/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ProjectServiceClient is the handwritten extension seam for Project runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*ProjectServiceManager).WithClient.
type ProjectServiceClient interface {
	CreateOrUpdate(context.Context, *datasciencev1beta1.Project, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *datasciencev1beta1.Project) (bool, error)
}

type defaultProjectServiceClient struct {
	generatedruntime.ServiceClient[*datasciencev1beta1.Project]
}

var _ ProjectServiceClient = defaultProjectServiceClient{}

var newProjectServiceClient = func(manager *ProjectServiceManager) ProjectServiceClient {
	sdkClient, err := datasciencesdk.NewDataScienceClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*datasciencev1beta1.Project]{
		Kind:    "Project",
		SDKName: "Project",
		Log:     manager.Log,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &datasciencesdk.CreateProjectRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.CreateProject(ctx, *request.(*datasciencesdk.CreateProjectRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &datasciencesdk.GetProjectRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetProject(ctx, *request.(*datasciencesdk.GetProjectRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &datasciencesdk.ListProjectsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListProjects(ctx, *request.(*datasciencesdk.ListProjectsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &datasciencesdk.UpdateProjectRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateProject(ctx, *request.(*datasciencesdk.UpdateProjectRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &datasciencesdk.DeleteProjectRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteProject(ctx, *request.(*datasciencesdk.DeleteProjectRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize Project OCI client: %w", err)
	}
	return defaultProjectServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*datasciencev1beta1.Project](config),
	}
}
