/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package namespace

import (
	"context"
	"fmt"

	datacatalogsdk "github.com/oracle/oci-go-sdk/v65/datacatalog"
	datacatalogv1beta1 "github.com/oracle/oci-service-operator/api/datacatalog/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// NamespaceServiceClient is the handwritten extension seam for Namespace runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*NamespaceServiceManager).WithClient.
type NamespaceServiceClient interface {
	CreateOrUpdate(context.Context, *datacatalogv1beta1.Namespace, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *datacatalogv1beta1.Namespace) (bool, error)
}

type defaultNamespaceServiceClient struct {
	generatedruntime.ServiceClient[*datacatalogv1beta1.Namespace]
}

var _ NamespaceServiceClient = defaultNamespaceServiceClient{}

var newNamespaceServiceClient = func(manager *NamespaceServiceManager) NamespaceServiceClient {
	sdkClient, err := datacatalogsdk.NewDataCatalogClientWithConfigurationProvider(manager.Provider)
	hooks := newNamespaceRuntimeHooks(manager, sdkClient)
	config := buildNamespaceGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Namespace OCI client: %w", err)
	}
	delegate := defaultNamespaceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*datacatalogv1beta1.Namespace](config),
	}
	return wrapNamespaceGeneratedClient(hooks, delegate)
}
