/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package version

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	mysqlv1beta1 "github.com/oracle/oci-service-operator/api/mysql/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type VersionServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client VersionServiceClient
}

var _ servicemanager.OSOKServiceManager = (*VersionServiceManager)(nil)

func NewVersionServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *VersionServiceManager {
	manager := &VersionServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newVersionServiceClient(manager)
	return manager
}

func NewVersionServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *VersionServiceManager {
	return NewVersionServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *VersionServiceManager) WithClient(client VersionServiceClient) *VersionServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *VersionServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *VersionServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *VersionServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *VersionServiceManager) convert(obj runtime.Object) (*mysqlv1beta1.Version, error) {
	resource, ok := obj.(*mysqlv1beta1.Version)
	if !ok {
		return nil, fmt.Errorf("expected *mysqlv1beta1.Version, got %T", obj)
	}
	return resource, nil
}

func (c *VersionServiceManager) status(resource *mysqlv1beta1.Version) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
