apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/dns.oracle.com_steeringpolicies.yaml
- bases/dns.oracle.com_steeringpolicyattachments.yaml
- bases/dns.oracle.com_tsigkeys.yaml
- bases/dns.oracle.com_views.yaml
- bases/dns.oracle.com_zones.yaml
