/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	analyticsv1beta1 "github.com/oracle/oci-service-operator/api/analytics/v1beta1"
	analyticscontrollers "github.com/oracle/oci-service-operator/controllers/analytics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	analyticsanalyticsinstanceservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/analytics/analyticsinstance"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "analytics",
		AddToScheme: analyticsv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&analyticscontrollers.AnalyticsInstanceReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"AnalyticsInstance",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return analyticsanalyticsinstanceservicemanager.NewAnalyticsInstanceServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup AnalyticsInstance controller: %w", err)
			}
			return nil
		},
	})
}
