/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	eventsv1beta1 "github.com/oracle/oci-service-operator/api/events/v1beta1"
	eventscontrollers "github.com/oracle/oci-service-operator/controllers/events"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	eventsruleservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/events/rule"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "events",
		AddToScheme: eventsv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&eventscontrollers.RuleReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"Rule",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return eventsruleservicemanager.NewRuleServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup Rule controller: %w", err)
			}
			return nil
		},
	})
}
