/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	marketplacev1beta1 "github.com/oracle/oci-service-operator/api/marketplace/v1beta1"
	marketplacecontrollers "github.com/oracle/oci-service-operator/controllers/marketplace"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	marketplaceacceptedagreementservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/marketplace/acceptedagreement"
	marketplacepublicationservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/marketplace/publication"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "marketplace",
		AddToScheme: marketplacev1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&marketplacecontrollers.AcceptedAgreementReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"AcceptedAgreement",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return marketplaceacceptedagreementservicemanager.NewAcceptedAgreementServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup AcceptedAgreement controller: %w", err)
			}
			if err := (&marketplacecontrollers.PublicationReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"Publication",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return marketplacepublicationservicemanager.NewPublicationServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup Publication controller: %w", err)
			}
			return nil
		},
	})
}
