/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConfirmSubscriptionSpec defines the desired state of ConfirmSubscription.
type ConfirmSubscriptionSpec struct {
}

// ConfirmSubscriptionStatus defines the observed state of ConfirmSubscription.
type ConfirmSubscriptionStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The name of the subscribed topic.
	TopicName string `json:"topicName,omitempty"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the topic associated with the specified subscription.
	TopicId string `json:"topicId,omitempty"`
	// A locator that corresponds to the subscription protocol.
	// For example, an email address for a subscription that uses the `EMAIL` protocol, or a URL for a subscription that uses an HTTP-based protocol.
	Endpoint string `json:"endpoint,omitempty"`
	// The URL for unsubscribing from the topic.
	UnsubscribeUrl string `json:"unsubscribeUrl,omitempty"`
	// A human-readable string indicating the status of the subscription confirmation.
	Message string `json:"message,omitempty"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the subscription specified in the request.
	SubscriptionId string `json:"subscriptionId,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the ConfirmSubscription",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the ConfirmSubscription",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// ConfirmSubscription is the Schema for the confirmsubscriptions API.
type ConfirmSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ConfirmSubscriptionSpec   `json:"spec,omitempty"`
	Status ConfirmSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// ConfirmSubscriptionList contains a list of ConfirmSubscription.
type ConfirmSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfirmSubscription `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ConfirmSubscription{}, &ConfirmSubscriptionList{})
}
