/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SubscriptionSpec defines the desired state of Subscription.
type SubscriptionSpec struct {
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the topic for the subscription.
	// +kubebuilder:validation:Required
	TopicId string `json:"topicId"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment for the subscription.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The protocol used for the subscription.
	// Allowed values:
	//   * `CUSTOM_HTTPS`
	//   * `EMAIL`
	//   * `HTTPS` (deprecated; for PagerDuty endpoints, use `PAGERDUTY`)
	//   * `ORACLE_FUNCTIONS`
	//   * `PAGERDUTY`
	//   * `SLACK`
	//   * `SMS`
	// For information about subscription protocols, see
	// To create a subscription (https://docs.cloud.oracle.com/iaas/Content/Notification/Tasks/managingtopicsandsubscriptions.htm#createSub).
	// +kubebuilder:validation:Required
	Protocol string `json:"protocol"`
	// A locator that corresponds to the subscription protocol.
	// For example, an email address for a subscription that uses the `EMAIL` protocol, or a URL for a subscription that uses an HTTP-based protocol.
	// HTTP-based protocols use URL endpoints that begin with "http:" or "https:".
	// A URL cannot exceed 512 characters.
	// Avoid entering confidential information.
	// For protocol-specific endpoint formats and steps to get or create endpoints, see
	// To create a subscription (https://docs.cloud.oracle.com/iaas/Content/Notification/Tasks/managingtopicsandsubscriptions.htm#createSub).
	// +kubebuilder:validation:Required
	Endpoint string `json:"endpoint"`
	// Metadata for the subscription.
	// +kubebuilder:validation:Optional
	Metadata string `json:"metadata,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The delivery policy of the subscription. Stored as a JSON string.
	// +kubebuilder:validation:Optional
	DeliveryPolicy SubscriptionDeliveryPolicy `json:"deliveryPolicy,omitempty"`
}

// SubscriptionDeliveryPolicyBackoffRetryPolicy defines nested fields for Subscription.DeliveryPolicy.BackoffRetryPolicy.
type SubscriptionDeliveryPolicyBackoffRetryPolicy struct {
	// The maximum retry duration in milliseconds. Default value is `7200000` (2 hours).
	// +kubebuilder:validation:Required
	MaxRetryDuration int `json:"maxRetryDuration"`
	// The type of delivery policy.
	// +kubebuilder:validation:Required
	PolicyType string `json:"policyType"`
}

// SubscriptionDeliveryPolicy defines nested fields for Subscription.DeliveryPolicy.
type SubscriptionDeliveryPolicy struct {
	// +kubebuilder:validation:Optional
	BackoffRetryPolicy SubscriptionDeliveryPolicyBackoffRetryPolicy `json:"backoffRetryPolicy,omitempty"`
}

// SubscriptionDeliveryPolicyObservedState defines nested fields for Subscription.DeliveryPolicy.
type SubscriptionDeliveryPolicyObservedState struct {
	// +kubebuilder:validation:Optional
	BackoffRetryPolicy SubscriptionDeliveryPolicyBackoffRetryPolicy `json:"backoffRetryPolicy,omitempty"`
}

// SubscriptionStatus defines the observed state of Subscription.
type SubscriptionStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the subscription.
	Id string `json:"id,omitempty"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the associated topic.
	TopicId string `json:"topicId,omitempty"`
	// The protocol used for the subscription.
	// Allowed values:
	//   * `CUSTOM_HTTPS`
	//   * `EMAIL`
	//   * `HTTPS` (deprecated; for PagerDuty endpoints, use `PAGERDUTY`)
	//   * `ORACLE_FUNCTIONS`
	//   * `PAGERDUTY`
	//   * `SLACK`
	//   * `SMS`
	// For information about subscription protocols, see
	// To create a subscription (https://docs.cloud.oracle.com/iaas/Content/Notification/Tasks/managingtopicsandsubscriptions.htm#createSub).
	Protocol string `json:"protocol,omitempty"`
	// A locator that corresponds to the subscription protocol.
	// For example, an email address for a subscription that uses the `EMAIL` protocol, or a URL for a subscription that uses an HTTP-based protocol.
	Endpoint string `json:"endpoint,omitempty"`
	// The lifecycle state of the subscription. The status of a new subscription is PENDING; when confirmed, the subscription status changes to ACTIVE.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment for the subscription.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The time when this suscription was created.
	CreatedTime int64 `json:"createdTime,omitempty"`
	// The delivery policy of the subscription. Stored as a JSON string.
	DeliverPolicy string `json:"deliverPolicy,omitempty"`
	// For optimistic concurrency control. See `if-match`.
	Etag string `json:"etag,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags    map[string]shared.MapValue              `json:"definedTags,omitempty"`
	DeliveryPolicy SubscriptionDeliveryPolicyObservedState `json:"deliveryPolicy,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the Subscription",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the Subscription",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// Subscription is the Schema for the subscriptions API.
type Subscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SubscriptionSpec   `json:"spec,omitempty"`
	Status SubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// SubscriptionList contains a list of Subscription.
type SubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subscription `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Subscription{}, &SubscriptionList{})
}
