/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package workspace

import (
	"context"
	"fmt"

	dataintegrationsdk "github.com/oracle/oci-go-sdk/v65/dataintegration"
	dataintegrationv1beta1 "github.com/oracle/oci-service-operator/api/dataintegration/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// WorkspaceServiceClient is the handwritten extension seam for Workspace runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*WorkspaceServiceManager).WithClient.
type WorkspaceServiceClient interface {
	CreateOrUpdate(context.Context, *dataintegrationv1beta1.Workspace, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *dataintegrationv1beta1.Workspace) (bool, error)
}

type defaultWorkspaceServiceClient struct {
	generatedruntime.ServiceClient[*dataintegrationv1beta1.Workspace]
}

var _ WorkspaceServiceClient = defaultWorkspaceServiceClient{}

var newWorkspaceServiceClient = func(manager *WorkspaceServiceManager) WorkspaceServiceClient {
	sdkClient, err := dataintegrationsdk.NewDataIntegrationClientWithConfigurationProvider(manager.Provider)
	hooks := newWorkspaceRuntimeHooks(manager, sdkClient)
	config := buildWorkspaceGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Workspace OCI client: %w", err)
	}
	delegate := defaultWorkspaceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*dataintegrationv1beta1.Workspace](config),
	}
	return wrapWorkspaceGeneratedClient(hooks, delegate)
}
