/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LogSpec defines the desired state of Log.
type LogSpec struct {
	// The user-friendly display name. This must be unique within the enclosing resource,
	// and it's changeable. Avoid entering confidential information.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// The logType that the log object is for, whether custom or service.
	// +kubebuilder:validation:Required
	LogType string `json:"logType"`
	// Whether or not this resource is currently enabled.
	// +kubebuilder:validation:Optional
	IsEnabled bool `json:"isEnabled,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a
	// namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no
	// predefined name, type, or namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// +kubebuilder:validation:Optional
	Configuration LogConfiguration `json:"configuration,omitempty"`
	// Log retention duration in 30-day increments (30, 60, 90 and so on until 180).
	// +kubebuilder:validation:Optional
	RetentionDuration int `json:"retentionDuration,omitempty"`
}

// LogConfigurationSource defines nested fields for Log.Configuration.Source.
type LogConfigurationSource struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	SourceType string `json:"sourceType,omitempty"`
	// Service generating log.
	// +kubebuilder:validation:Required
	Service string `json:"service"`
	// The unique identifier of the resource emitting the log.
	// +kubebuilder:validation:Required
	Resource string `json:"resource"`
	// Log object category.
	// +kubebuilder:validation:Required
	Category string `json:"category"`
	// Log category parameters are stored here.
	// +kubebuilder:validation:Optional
	Parameters map[string]string `json:"parameters,omitempty"`
}

// LogConfigurationArchiving defines nested fields for Log.Configuration.Archiving.
type LogConfigurationArchiving struct {
	// True if archiving enabled. This field is now deprecated, you should use Service Connector Hub to enable archiving.
	// +kubebuilder:validation:Optional
	IsEnabled bool `json:"isEnabled,omitempty"`
}

// LogConfiguration defines nested fields for Log.Configuration.
type LogConfiguration struct {
	// +kubebuilder:validation:Required
	Source LogConfigurationSource `json:"source"`
	// The OCID of the compartment that the resource belongs to.
	// +kubebuilder:validation:Optional
	CompartmentId string `json:"compartmentId,omitempty"`
	// +kubebuilder:validation:Optional
	Archiving LogConfigurationArchiving `json:"archiving,omitempty"`
}

// LogConfigurationSourceObservedState defines nested fields for Log.Configuration.Source.
type LogConfigurationSourceObservedState struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	SourceType string `json:"sourceType,omitempty"`
	// Service generating log.
	// +kubebuilder:validation:Required
	Service string `json:"service"`
	// The unique identifier of the resource emitting the log.
	// +kubebuilder:validation:Required
	Resource string `json:"resource"`
	// Log object category.
	// +kubebuilder:validation:Required
	Category string `json:"category"`
	// Log category parameters are stored here.
	// +kubebuilder:validation:Optional
	Parameters map[string]string `json:"parameters,omitempty"`
}

// LogConfigurationObservedState defines nested fields for Log.Configuration.
type LogConfigurationObservedState struct {
	// +kubebuilder:validation:Required
	Source LogConfigurationSourceObservedState `json:"source"`
	// The OCID of the compartment that the resource belongs to.
	// +kubebuilder:validation:Optional
	CompartmentId string `json:"compartmentId,omitempty"`
	// +kubebuilder:validation:Optional
	Archiving LogConfigurationArchiving `json:"archiving,omitempty"`
}

// LogStatus defines the observed state of Log.
type LogStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID of the resource.
	Id string `json:"id,omitempty"`
	// Log group OCID.
	LogGroupId string `json:"logGroupId,omitempty"`
	// The user-friendly display name. This must be unique within the enclosing resource,
	// and it's changeable. Avoid entering confidential information.
	DisplayName string `json:"displayName,omitempty"`
	// The logType that the log object is for, whether custom or service.
	LogType string `json:"logType,omitempty"`
	// The pipeline state.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The OCID of the tenancy.
	TenancyId string `json:"tenancyId,omitempty"`
	// Whether or not this resource is currently enabled.
	IsEnabled bool `json:"isEnabled,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a
	// namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no
	// predefined name, type, or namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags  map[string]string             `json:"freeformTags,omitempty"`
	Configuration LogConfigurationObservedState `json:"configuration,omitempty"`
	// Time the resource was created.
	TimeCreated string `json:"timeCreated,omitempty"`
	// Time the resource was last modified.
	TimeLastModified string `json:"timeLastModified,omitempty"`
	// Log retention duration in 30-day increments (30, 60, 90 and so on until 180).
	RetentionDuration int `json:"retentionDuration,omitempty"`
	// The OCID of the compartment that the resource belongs to.
	CompartmentId string `json:"compartmentId,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the Log",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the Log",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// Log is the Schema for the logs API.
type Log struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   LogSpec   `json:"spec,omitempty"`
	Status LogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// LogList contains a list of Log.
type LogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Log `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Log{}, &LogList{})
}
