/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package securityrule

import (
	"context"

	networkfirewallsdk "github.com/oracle/oci-go-sdk/v65/networkfirewall"
	networkfirewallv1beta1 "github.com/oracle/oci-service-operator/api/networkfirewall/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type SecurityRuleRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *networkfirewallv1beta1.SecurityRule, string) (any, error)
	BuildUpdateBody func(context.Context, *networkfirewallv1beta1.SecurityRule, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*networkfirewallv1beta1.SecurityRule]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*networkfirewallv1beta1.SecurityRule]
	StatusHooks         generatedruntime.StatusHooks[*networkfirewallv1beta1.SecurityRule]
	ParityHooks         generatedruntime.ParityHooks[*networkfirewallv1beta1.SecurityRule]
	Async               generatedruntime.AsyncHooks[*networkfirewallv1beta1.SecurityRule]
	DeleteHooks         generatedruntime.DeleteHooks[*networkfirewallv1beta1.SecurityRule]
	Create              runtimeOperationHooks[networkfirewallsdk.CreateSecurityRuleRequest, networkfirewallsdk.CreateSecurityRuleResponse]
	Get                 runtimeOperationHooks[networkfirewallsdk.GetSecurityRuleRequest, networkfirewallsdk.GetSecurityRuleResponse]
	List                runtimeOperationHooks[networkfirewallsdk.ListSecurityRulesRequest, networkfirewallsdk.ListSecurityRulesResponse]
	Update              runtimeOperationHooks[networkfirewallsdk.UpdateSecurityRuleRequest, networkfirewallsdk.UpdateSecurityRuleResponse]
	Delete              runtimeOperationHooks[networkfirewallsdk.DeleteSecurityRuleRequest, networkfirewallsdk.DeleteSecurityRuleResponse]
	WrapGeneratedClient []func(SecurityRuleServiceClient) SecurityRuleServiceClient
}

type SecurityRuleRuntimeHooksMutator func(*SecurityRuleServiceManager, *SecurityRuleRuntimeHooks)

var securityruleRuntimeHooksMutators []SecurityRuleRuntimeHooksMutator

func registerSecurityRuleRuntimeHooksMutator(mutator SecurityRuleRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	securityruleRuntimeHooksMutators = append(securityruleRuntimeHooksMutators, mutator)
}
func newSecurityRuleDefaultRuntimeHooks(sdkClient networkfirewallsdk.NetworkFirewallClient) SecurityRuleRuntimeHooks {
	return SecurityRuleRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*networkfirewallv1beta1.SecurityRule]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*networkfirewallv1beta1.SecurityRule]{},
		StatusHooks:     generatedruntime.StatusHooks[*networkfirewallv1beta1.SecurityRule]{},
		ParityHooks:     generatedruntime.ParityHooks[*networkfirewallv1beta1.SecurityRule]{},
		Async:           generatedruntime.AsyncHooks[*networkfirewallv1beta1.SecurityRule]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*networkfirewallv1beta1.SecurityRule]{},
		Create: runtimeOperationHooks[networkfirewallsdk.CreateSecurityRuleRequest, networkfirewallsdk.CreateSecurityRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "CreateSecurityRuleDetails", RequestName: "CreateSecurityRuleDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.CreateSecurityRuleRequest) (networkfirewallsdk.CreateSecurityRuleResponse, error) {
				return sdkClient.CreateSecurityRule(ctx, request)
			},
		},
		Get: runtimeOperationHooks[networkfirewallsdk.GetSecurityRuleRequest, networkfirewallsdk.GetSecurityRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "SecurityRuleName", RequestName: "securityRuleName", Contribution: "path", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.GetSecurityRuleRequest) (networkfirewallsdk.GetSecurityRuleResponse, error) {
				return sdkClient.GetSecurityRule(ctx, request)
			},
		},
		List: runtimeOperationHooks[networkfirewallsdk.ListSecurityRulesRequest, networkfirewallsdk.ListSecurityRulesResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: true}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "SecurityRulePriorityOrder", RequestName: "securityRulePriorityOrder", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.ListSecurityRulesRequest) (networkfirewallsdk.ListSecurityRulesResponse, error) {
				return sdkClient.ListSecurityRules(ctx, request)
			},
		},
		Update: runtimeOperationHooks[networkfirewallsdk.UpdateSecurityRuleRequest, networkfirewallsdk.UpdateSecurityRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "SecurityRuleName", RequestName: "securityRuleName", Contribution: "path", PreferResourceID: false}, {FieldName: "UpdateSecurityRuleDetails", RequestName: "UpdateSecurityRuleDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.UpdateSecurityRuleRequest) (networkfirewallsdk.UpdateSecurityRuleResponse, error) {
				return sdkClient.UpdateSecurityRule(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[networkfirewallsdk.DeleteSecurityRuleRequest, networkfirewallsdk.DeleteSecurityRuleResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkFirewallPolicyId", RequestName: "networkFirewallPolicyId", Contribution: "path", PreferResourceID: false}, {FieldName: "SecurityRuleName", RequestName: "securityRuleName", Contribution: "path", PreferResourceID: false}},
			Call: func(ctx context.Context, request networkfirewallsdk.DeleteSecurityRuleRequest) (networkfirewallsdk.DeleteSecurityRuleResponse, error) {
				return sdkClient.DeleteSecurityRule(ctx, request)
			},
		},
		WrapGeneratedClient: []func(SecurityRuleServiceClient) SecurityRuleServiceClient{},
	}
}

func newSecurityRuleRuntimeHooks(manager *SecurityRuleServiceManager, sdkClient networkfirewallsdk.NetworkFirewallClient) SecurityRuleRuntimeHooks {
	hooks := newSecurityRuleDefaultRuntimeHooks(sdkClient)
	for _, mutator := range securityruleRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildSecurityRuleGeneratedRuntimeConfig(
	manager *SecurityRuleServiceManager,
	hooks SecurityRuleRuntimeHooks,
) generatedruntime.Config[*networkfirewallv1beta1.SecurityRule] {
	return generatedruntime.Config[*networkfirewallv1beta1.SecurityRule]{
		Kind:            "SecurityRule",
		SDKName:         "SecurityRule",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.CreateSecurityRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*networkfirewallsdk.CreateSecurityRuleRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.GetSecurityRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*networkfirewallsdk.GetSecurityRuleRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.ListSecurityRulesRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*networkfirewallsdk.ListSecurityRulesRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.UpdateSecurityRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*networkfirewallsdk.UpdateSecurityRuleRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &networkfirewallsdk.DeleteSecurityRuleRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*networkfirewallsdk.DeleteSecurityRuleRequest))
			},
		},
	}
}

func wrapSecurityRuleGeneratedClient(
	hooks SecurityRuleRuntimeHooks,
	delegate SecurityRuleServiceClient,
) SecurityRuleServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
