---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - psql.oracle.com
  resources:
  - backups
  - configurations
  - connectiondetails
  - dbsystemdbinstances
  - dbsystems
  - defaultconfigurations
  - primarydbinstances
  - shapes
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - psql.oracle.com
  resources:
  - backups/finalizers
  - configurations/finalizers
  - connectiondetails/finalizers
  - dbsystemdbinstances/finalizers
  - dbsystems/finalizers
  - defaultconfigurations/finalizers
  - primarydbinstances/finalizers
  - shapes/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - psql.oracle.com
  resources:
  - backups/status
  - configurations/status
  - connectiondetails/status
  - dbsystemdbinstances/status
  - dbsystems/status
  - defaultconfigurations/status
  - primarydbinstances/status
  - shapes/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
