/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RecordSpec defines the desired state of Record.
type RecordSpec struct {
	// The name is automatically assigned by the service. It is unique and immutable.
	// +kubebuilder:validation:Required
	Name string `json:"name"`
	// The OCID of the dataset to associate the record with.
	// +kubebuilder:validation:Required
	DatasetId string `json:"datasetId"`
	// The OCID of the compartment for the record. This is tied to the dataset. It is not changeable on the record itself.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// +kubebuilder:validation:Required
	SourceDetails RecordSourceDetails `json:"sourceDetails"`
	// +kubebuilder:validation:Optional
	RecordMetadata RecordMetadata `json:"recordMetadata,omitempty"`
	// A simple key-value pair that is applied without any predefined name, type, or scope. It exists for cross-compatibility only.
	// For example: `{"bar-key": "value"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For example: `{"foo-namespace": {"bar-key": "value"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// RecordSourceDetails defines nested fields for Record.SourceDetails.
type RecordSourceDetails struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	SourceType string `json:"sourceType,omitempty"`
	// The path relative to the prefix specified in the dataset source details (file name).
	// +kubebuilder:validation:Optional
	RelativePath string `json:"relativePath,omitempty"`
	// The offset into the file containing the content.
	// +kubebuilder:validation:Optional
	Offset float32 `json:"offset,omitempty"`
	// The length from offset into the file containing the content.
	// +kubebuilder:validation:Optional
	Length float32 `json:"length,omitempty"`
}

// RecordMetadata defines nested fields for Record.RecordMetadata.
type RecordMetadata struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	RecordType string `json:"recordType,omitempty"`
	// Job id ocid of OCR batch call.
	// +kubebuilder:validation:Optional
	JobId string `json:"jobId,omitempty"`
	// Height of the image record.
	// +kubebuilder:validation:Optional
	Height int `json:"height,omitempty"`
	// Width of the image record.
	// +kubebuilder:validation:Optional
	Width int `json:"width,omitempty"`
	// Depth of the image record.
	// +kubebuilder:validation:Optional
	Depth int `json:"depth,omitempty"`
}

// RecordStatus defines the observed state of Record.
type RecordStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID of the record.
	Id string `json:"id,omitempty"`
	// The name is created by the user. It is unique and immutable.
	Name string `json:"name,omitempty"`
	// The date and time the resource was created, in the timestamp format defined by RFC3339.
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the resource was updated, in the timestamp format defined by RFC3339.
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The OCID of the dataset to associate the record with.
	DatasetId string `json:"datasetId,omitempty"`
	// The OCID of the compartment for the task.
	CompartmentId string              `json:"compartmentId,omitempty"`
	SourceDetails RecordSourceDetails `json:"sourceDetails,omitempty"`
	// Whether or not the record has been labeled and has associated annotations.
	IsLabeled bool `json:"isLabeled,omitempty"`
	// The lifecycle state of the record.
	// ACTIVE - The record is active and ready for labeling.
	// INACTIVE - The record has been marked as inactive and should not be used for labeling.
	// DELETED - The record has been deleted and is no longer available for labeling.
	LifecycleState string         `json:"lifecycleState,omitempty"`
	RecordMetadata RecordMetadata `json:"recordMetadata,omitempty"`
	// A simple key-value pair that is applied without any predefined name, type, or scope. It exists for cross-compatibility only.
	// For example: `{"bar-key": "value"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For example: `{"foo-namespace": {"bar-key": "value"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Name",type="string",JSONPath=".spec.name",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the Record",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the Record",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// Record is the Schema for the records API.
type Record struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RecordSpec   `json:"spec,omitempty"`
	Status RecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// RecordList contains a list of Record.
type RecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Record `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Record{}, &RecordList{})
}
