/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package dashboard

import (
	"context"
	"fmt"

	dashboardservicesdk "github.com/oracle/oci-go-sdk/v65/dashboardservice"
	dashboardservicev1beta1 "github.com/oracle/oci-service-operator/api/dashboardservice/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DashboardServiceClient is the handwritten extension seam for Dashboard runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DashboardServiceManager).WithClient.
type DashboardServiceClient interface {
	CreateOrUpdate(context.Context, *dashboardservicev1beta1.Dashboard, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *dashboardservicev1beta1.Dashboard) (bool, error)
}

type defaultDashboardServiceClient struct {
	generatedruntime.ServiceClient[*dashboardservicev1beta1.Dashboard]
}

var _ DashboardServiceClient = defaultDashboardServiceClient{}

var newDashboardServiceClient = func(manager *DashboardServiceManager) DashboardServiceClient {
	sdkClient, err := dashboardservicesdk.NewDashboardClientWithConfigurationProvider(manager.Provider)
	hooks := newDashboardRuntimeHooks(manager, sdkClient)
	config := buildDashboardGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Dashboard OCI client: %w", err)
	}
	delegate := defaultDashboardServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*dashboardservicev1beta1.Dashboard](config),
	}
	return wrapDashboardGeneratedClient(hooks, delegate)
}
