/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package datasafe

import (
	"context"

	datasafev1beta1 "github.com/oracle/oci-service-operator/api/datasafe/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MaskingPolicyReconciler reconciles a MaskingPolicy object.
type MaskingPolicyReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=datasafe.oracle.com,resources=maskingpolicies,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=datasafe.oracle.com,resources=maskingpolicies/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=datasafe.oracle.com,resources=maskingpolicies/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *MaskingPolicyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	maskingPolicy := &datasafev1beta1.MaskingPolicy{}
	return r.Reconciler.Reconcile(ctx, req, maskingPolicy)
}

// SetupWithManager sets up the controller with the Manager.
func (r *MaskingPolicyReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&datasafev1beta1.MaskingPolicy{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
