/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package publicipbyipaddress

import (
	"context"
	"fmt"

	coresdk "github.com/oracle/oci-go-sdk/v65/core"
	corev1beta1 "github.com/oracle/oci-service-operator/api/core/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// PublicIpByIpAddressServiceClient is the handwritten extension seam for PublicIpByIpAddress runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*PublicIpByIpAddressServiceManager).WithClient.
type PublicIpByIpAddressServiceClient interface {
	CreateOrUpdate(context.Context, *corev1beta1.PublicIpByIpAddress, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *corev1beta1.PublicIpByIpAddress) (bool, error)
}

type defaultPublicIpByIpAddressServiceClient struct {
	generatedruntime.ServiceClient[*corev1beta1.PublicIpByIpAddress]
}

var _ PublicIpByIpAddressServiceClient = defaultPublicIpByIpAddressServiceClient{}

var newPublicIpByIpAddressServiceClient = func(manager *PublicIpByIpAddressServiceManager) PublicIpByIpAddressServiceClient {
	sdkClient, err := coresdk.NewVirtualNetworkClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*corev1beta1.PublicIpByIpAddress]{
		Kind:    "PublicIpByIpAddress",
		SDKName: "PublicIpByIpAddress",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.GetPublicIpByIpAddressRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetPublicIpByIpAddress(ctx, *request.(*coresdk.GetPublicIpByIpAddressRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize PublicIpByIpAddress OCI client: %w", err)
	}
	return defaultPublicIpByIpAddressServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*corev1beta1.PublicIpByIpAddress](config),
	}
}
