/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package alarm

import (
	"context"
	"fmt"

	monitoringsdk "github.com/oracle/oci-go-sdk/v65/monitoring"
	monitoringv1beta1 "github.com/oracle/oci-service-operator/api/monitoring/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AlarmServiceClient is the handwritten extension seam for Alarm runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*AlarmServiceManager).WithClient.
type AlarmServiceClient interface {
	CreateOrUpdate(context.Context, *monitoringv1beta1.Alarm, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *monitoringv1beta1.Alarm) (bool, error)
}

type defaultAlarmServiceClient struct {
	generatedruntime.ServiceClient[*monitoringv1beta1.Alarm]
}

func newAlarmRuntimeSemantics() *generatedruntime.Semantics {
	return &generatedruntime.Semantics{
		FormalService: "monitoring",
		FormalSlug:    "alarm",
		Async: &generatedruntime.AsyncSemantics{
			Strategy:             "lifecycle",
			Runtime:              "generatedruntime",
			FormalClassification: "lifecycle",
		},
		StatusProjection:  "required",
		SecretSideEffects: "none",
		FinalizerPolicy:   "retain-until-confirmed-delete",
		Lifecycle: generatedruntime.LifecycleSemantics{
			ProvisioningStates: []string{},
			UpdatingStates:     []string{},
			ActiveStates:       []string{"ACTIVE"},
		},
		Delete: generatedruntime.DeleteSemantics{
			Policy:         "required",
			PendingStates:  []string{"DELETING"},
			TerminalStates: []string{"DELETED"},
		},
		List: &generatedruntime.ListSemantics{
			ResponseItemsField: "Items",
			MatchFields:        []string{"compartmentId", "displayName", "lifecycleState"},
		},
		Mutation: generatedruntime.MutationSemantics{
			Mutable:       []string{"body", "definedTags", "destinations", "displayName", "freeformTags", "isEnabled", "isNotificationsPerMetricDimensionEnabled", "messageFormat", "metricCompartmentId", "metricCompartmentIdInSubtree", "namespace", "pendingDuration", "query", "repeatNotificationDuration", "resolution", "resourceGroup", "severity", "suppression"},
			ForceNew:      []string{"compartmentId"},
			ConflictsWith: map[string][]string{},
		},
		Hooks: generatedruntime.HookSet{
			Create: []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
			Update: []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
			Delete: []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		CreateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "read-after-write",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
		},
		UpdateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "read-after-write",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
		},
		DeleteFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "confirm-delete",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		AuxiliaryOperations: []generatedruntime.AuxiliaryOperation{},
		Unsupported:         []generatedruntime.UnsupportedSemantic{},
	}
}

var _ AlarmServiceClient = defaultAlarmServiceClient{}

var newAlarmServiceClient = func(manager *AlarmServiceManager) AlarmServiceClient {
	sdkClient, err := monitoringsdk.NewMonitoringClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*monitoringv1beta1.Alarm]{
		Kind:      "Alarm",
		SDKName:   "Alarm",
		Log:       manager.Log,
		Semantics: newAlarmRuntimeSemantics(),
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &monitoringsdk.CreateAlarmRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.CreateAlarm(ctx, *request.(*monitoringsdk.CreateAlarmRequest))
			},
			Fields: []generatedruntime.RequestField{{FieldName: "CreateAlarmDetails", RequestName: "CreateAlarmDetails", Contribution: "body", PreferResourceID: false}},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &monitoringsdk.GetAlarmRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetAlarm(ctx, *request.(*monitoringsdk.GetAlarmRequest))
			},
			Fields: []generatedruntime.RequestField{{FieldName: "AlarmId", RequestName: "alarmId", Contribution: "path", PreferResourceID: true}},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &monitoringsdk.ListAlarmsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListAlarms(ctx, *request.(*monitoringsdk.ListAlarmsRequest))
			},
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentIdInSubtree", RequestName: "compartmentIdInSubtree", Contribution: "query", PreferResourceID: false}},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &monitoringsdk.UpdateAlarmRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateAlarm(ctx, *request.(*monitoringsdk.UpdateAlarmRequest))
			},
			Fields: []generatedruntime.RequestField{{FieldName: "AlarmId", RequestName: "alarmId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateAlarmDetails", RequestName: "UpdateAlarmDetails", Contribution: "body", PreferResourceID: false}},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &monitoringsdk.DeleteAlarmRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteAlarm(ctx, *request.(*monitoringsdk.DeleteAlarmRequest))
			},
			Fields: []generatedruntime.RequestField{{FieldName: "AlarmId", RequestName: "alarmId", Contribution: "path", PreferResourceID: true}},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize Alarm OCI client: %w", err)
	}
	return defaultAlarmServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*monitoringv1beta1.Alarm](config),
	}
}
