/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package redis

import (
	"context"

	redisv1beta1 "github.com/oracle/oci-service-operator/api/redis/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// RedisClusterReconciler reconciles a RedisCluster object.
type RedisClusterReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=redis.oracle.com,resources=redisclusters,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=redis.oracle.com,resources=redisclusters/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=redis.oracle.com,resources=redisclusters/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *RedisClusterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	redisCluster := &redisv1beta1.RedisCluster{}
	return r.Reconciler.Reconcile(ctx, req, redisCluster)
}

// SetupWithManager sets up the controller with the Manager.
func (r *RedisClusterReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&redisv1beta1.RedisCluster{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
