/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VirtualNodeSpec defines the desired state of VirtualNode.
type VirtualNodeSpec struct {
}

// VirtualNodeStatus defines the observed state of VirtualNode.
type VirtualNodeStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The ocid of the virtual node.
	Id string `json:"id,omitempty"`
	// The name of the virtual node.
	DisplayName string `json:"displayName,omitempty"`
	// The ocid of the virtual node pool this virtual node belongs to.
	VirtualNodePoolId string `json:"virtualNodePoolId,omitempty"`
	// The version of Kubernetes this virtual node is running.
	KubernetesVersion string `json:"kubernetesVersion,omitempty"`
	// The name of the availability domain in which this virtual node is placed
	AvailabilityDomain string `json:"availabilityDomain,omitempty"`
	// The fault domain of this virtual node.
	FaultDomain string `json:"faultDomain,omitempty"`
	// The OCID of the subnet in which this Virtual Node is placed.
	SubnetId string `json:"subnetId,omitempty"`
	// NSG Ids applied to virtual node vnic.
	NsgIds []string `json:"nsgIds,omitempty"`
	// The private IP address of this Virtual Node.
	PrivateIp string `json:"privateIp,omitempty"`
	// An error that may be associated with the virtual node.
	VirtualNodeError string `json:"virtualNodeError,omitempty"`
	// The state of the Virtual Node.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// Details about the state of the Virtual Node.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// The time at which the virtual node was created.
	TimeCreated string `json:"timeCreated,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Usage of system tag keys. These predefined keys are scoped to namespaces.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the VirtualNode",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the VirtualNode",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// VirtualNode is the Schema for the virtualnodes API.
type VirtualNode struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VirtualNodeSpec   `json:"spec,omitempty"`
	Status VirtualNodeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// VirtualNodeList contains a list of VirtualNode.
type VirtualNodeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VirtualNode `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VirtualNode{}, &VirtualNodeList{})
}
