---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rover.oracle.com
  resources:
  - roverclusters
  - rovernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rover.oracle.com
  resources:
  - roverclusters/finalizers
  - rovernodes/finalizers
  verbs:
  - update
- apiGroups:
  - rover.oracle.com
  resources:
  - roverclusters/status
  - rovernodes/status
  verbs:
  - get
  - patch
  - update
