/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BootVolumeKmsKeySpec defines the desired state of BootVolumeKmsKey.
type BootVolumeKmsKeySpec struct {
	// The OCID of the new Vault service key to assign to protect the specified volume.
	// This key has to be a valid Vault service key, and policies must exist to allow the user and the Block Volume service to access this key.
	// If you specify the same OCID as the previous key's OCID, the Block Volume service will use it to regenerate a volume encryption key.
	// +kubebuilder:validation:Optional
	KmsKeyId string `json:"kmsKeyId,omitempty"`
}

// BootVolumeKmsKeyStatus defines the observed state of BootVolumeKmsKey.
type BootVolumeKmsKeyStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the BootVolumeKmsKey",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the BootVolumeKmsKey",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// BootVolumeKmsKey is the Schema for the bootvolumekmskeies API.
type BootVolumeKmsKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BootVolumeKmsKeySpec   `json:"spec,omitempty"`
	Status BootVolumeKmsKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// BootVolumeKmsKeyList contains a list of BootVolumeKmsKey.
type BootVolumeKmsKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BootVolumeKmsKey `json:"items"`
}

func init() {
	SchemeBuilder.Register(&BootVolumeKmsKey{}, &BootVolumeKmsKeyList{})
}
