/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DrgRouteTableSpec defines the desired state of DrgRouteTable.
type DrgRouteTableSpec struct {
	Id                           shared.OCID       `json:"id,omitempty"`
	CompartmentId                shared.OCID       `json:"compartmentId,omitempty"`
	DrgId                        string            `json:"drgId,omitempty"`
	DisplayName                  string            `json:"displayName,omitempty"`
	FreeformTags                 map[string]string `json:"freeformTags,omitempty"`
	ImportDrgRouteDistributionId string            `json:"importDrgRouteDistributionId,omitempty"`
	IsEcmpEnabled                bool              `json:"isEcmpEnabled,omitempty"`
	TimeCreated                  string            `json:"timeCreated,omitempty"`
	LifecycleState               string            `json:"lifecycleState,omitempty"`
}

// DrgRouteTableStatus defines the observed state of DrgRouteTable.
type DrgRouteTableStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the DrgRouteTable",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the DrgRouteTable",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// DrgRouteTable is the Schema for the drgroutetables API.
type DrgRouteTable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DrgRouteTableSpec   `json:"spec,omitempty"`
	Status DrgRouteTableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// DrgRouteTableList contains a list of DrgRouteTable.
type DrgRouteTableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DrgRouteTable `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DrgRouteTable{}, &DrgRouteTableList{})
}
