/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IPSecConnectionTunnelSecurityAssociationSpec defines the desired state of IPSecConnectionTunnelSecurityAssociation.
type IPSecConnectionTunnelSecurityAssociationSpec struct {
}

// IPSecConnectionTunnelSecurityAssociationStatus defines the observed state of IPSecConnectionTunnelSecurityAssociation.
type IPSecConnectionTunnelSecurityAssociationStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The IP address and mask of the partner subnet used in policy based VPNs or static routes.
	CpeSubnet string `json:"cpeSubnet,omitempty"`
	// The IP address and mask of the local subnet used in policy based VPNs or static routes.
	OracleSubnet string `json:"oracleSubnet,omitempty"`
	// The IPSec tunnel's phase one status.
	TunnelSaStatus string `json:"tunnelSaStatus,omitempty"`
	// Current state if the IPSec tunnel status is not `UP`, including phase one and phase two details and a possible reason the tunnel is not `UP`.
	TunnelSaErrorInfo string `json:"tunnelSaErrorInfo,omitempty"`
	// Time in the current state, in seconds.
	Time string `json:"time,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the IPSecConnectionTunnelSecurityAssociation",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the IPSecConnectionTunnelSecurityAssociation",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// IPSecConnectionTunnelSecurityAssociation is the Schema for the ipsecconnectiontunnelsecurityassociations API.
type IPSecConnectionTunnelSecurityAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   IPSecConnectionTunnelSecurityAssociationSpec   `json:"spec,omitempty"`
	Status IPSecConnectionTunnelSecurityAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// IPSecConnectionTunnelSecurityAssociationList contains a list of IPSecConnectionTunnelSecurityAssociation.
type IPSecConnectionTunnelSecurityAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IPSecConnectionTunnelSecurityAssociation `json:"items"`
}

func init() {
	SchemeBuilder.Register(&IPSecConnectionTunnelSecurityAssociation{}, &IPSecConnectionTunnelSecurityAssociationList{})
}
