/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VolumeBackupPolicyAssignmentSpec defines the desired state of VolumeBackupPolicyAssignment.
type VolumeBackupPolicyAssignmentSpec struct {
	Id            shared.OCID `json:"id,omitempty"`
	CompartmentId shared.OCID `json:"compartmentId,omitempty"`
	AssetId       string      `json:"assetId,omitempty"`
	PolicyId      string      `json:"policyId,omitempty"`
	TimeCreated   string      `json:"timeCreated,omitempty"`
}

// VolumeBackupPolicyAssignmentStatus defines the observed state of VolumeBackupPolicyAssignment.
type VolumeBackupPolicyAssignmentStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the VolumeBackupPolicyAssignment",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the VolumeBackupPolicyAssignment",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// VolumeBackupPolicyAssignment is the Schema for the volumebackuppolicyassignments API.
type VolumeBackupPolicyAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VolumeBackupPolicyAssignmentSpec   `json:"spec,omitempty"`
	Status VolumeBackupPolicyAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// VolumeBackupPolicyAssignmentList contains a list of VolumeBackupPolicyAssignment.
type VolumeBackupPolicyAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VolumeBackupPolicyAssignment `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VolumeBackupPolicyAssignment{}, &VolumeBackupPolicyAssignmentList{})
}
