---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - keymanagement.oracle.com
  resources:
  - ekmsprivateendpoints
  - vaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keymanagement.oracle.com
  resources:
  - ekmsprivateendpoints/finalizers
  - vaults/finalizers
  verbs:
  - update
- apiGroups:
  - keymanagement.oracle.com
  resources:
  - ekmsprivateendpoints/status
  - vaults/status
  verbs:
  - get
  - patch
  - update
