---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - keymanagement.oracle.com
  resources:
  - ekmsprivateendpoints
  - hsmclusters
  - hsmpartitions
  - precousercredentials
  - vaultreplicas
  - vaults
  - vaultusages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keymanagement.oracle.com
  resources:
  - ekmsprivateendpoints/finalizers
  - hsmclusters/finalizers
  - hsmpartitions/finalizers
  - precousercredentials/finalizers
  - vaultreplicas/finalizers
  - vaults/finalizers
  - vaultusages/finalizers
  verbs:
  - update
- apiGroups:
  - keymanagement.oracle.com
  resources:
  - ekmsprivateendpoints/status
  - hsmclusters/status
  - hsmpartitions/status
  - precousercredentials/status
  - vaultreplicas/status
  - vaults/status
  - vaultusages/status
  verbs:
  - get
  - patch
  - update
