/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package webappfirewallpolicy

import (
	"context"
	"fmt"

	wafsdk "github.com/oracle/oci-go-sdk/v65/waf"
	wafv1beta1 "github.com/oracle/oci-service-operator/api/waf/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// WebAppFirewallPolicyServiceClient is the handwritten extension seam for WebAppFirewallPolicy runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*WebAppFirewallPolicyServiceManager).WithClient.
type WebAppFirewallPolicyServiceClient interface {
	CreateOrUpdate(context.Context, *wafv1beta1.WebAppFirewallPolicy, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *wafv1beta1.WebAppFirewallPolicy) (bool, error)
}

type defaultWebAppFirewallPolicyServiceClient struct {
	generatedruntime.ServiceClient[*wafv1beta1.WebAppFirewallPolicy]
}

var _ WebAppFirewallPolicyServiceClient = defaultWebAppFirewallPolicyServiceClient{}

var newWebAppFirewallPolicyServiceClient = func(manager *WebAppFirewallPolicyServiceManager) WebAppFirewallPolicyServiceClient {
	sdkClient, err := wafsdk.NewWafClientWithConfigurationProvider(manager.Provider)
	hooks := newWebAppFirewallPolicyRuntimeHooks(manager, sdkClient)
	config := buildWebAppFirewallPolicyGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize WebAppFirewallPolicy OCI client: %w", err)
	}
	delegate := defaultWebAppFirewallPolicyServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*wafv1beta1.WebAppFirewallPolicy](config),
	}
	return wrapWebAppFirewallPolicyGeneratedClient(hooks, delegate)
}
