/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package networkloadbalancer

import (
	"context"

	networkloadbalancerv1beta1 "github.com/oracle/oci-service-operator/api/networkloadbalancer/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// BackendSetReconciler reconciles a BackendSet object.
type BackendSetReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=networkloadbalancer.oracle.com,resources=backendsets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=networkloadbalancer.oracle.com,resources=backendsets/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=networkloadbalancer.oracle.com,resources=backendsets/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *BackendSetReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	backendSet := &networkloadbalancerv1beta1.BackendSet{}
	return r.Reconciler.Reconcile(ctx, req, backendSet)
}

// SetupWithManager sets up the controller with the Manager.
func (r *BackendSetReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&networkloadbalancerv1beta1.BackendSet{})
	return builder.
		WithEventFilter(predicate.GenerationChangedPredicate{}).
		Complete(r)
}
