/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SecurityAssessmentSpec defines the desired state of SecurityAssessment.
type SecurityAssessmentSpec struct {
	// The OCID of the compartment that contains the security assessment.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The display name of the security assessment.
	// +kubebuilder:validation:Optional
	DisplayName string `json:"displayName,omitempty"`
	// Description of the security assessment.
	// +kubebuilder:validation:Optional
	Description string `json:"description,omitempty"`
	// The OCID of the target database or target database group on which security assessment is to be run.
	// +kubebuilder:validation:Optional
	TargetId string `json:"targetId,omitempty"`
	// The type of security assessment resource whether it is individual or group resource. For individual target use type TARGET_DATABASE and for group resource use type TARGET_DATABASE_GROUP. If not provided, TARGET_DATABASE would be used as default value.
	// +kubebuilder:validation:Optional
	TargetType string `json:"targetType,omitempty"`
	// The type of the security assessment
	// +kubebuilder:validation:Optional
	Type string `json:"type,omitempty"`
	// The OCID of the template assessment. It will be required while creating the template baseline assessment.
	// +kubebuilder:validation:Optional
	TemplateAssessmentId string `json:"templateAssessmentId,omitempty"`
	// The OCID of the security assessment. The assessment should be of type SAVED.
	// It will be required while creating the template baseline assessment for individual targets to fetch the detailed information from an existing security assessment.
	// +kubebuilder:validation:Optional
	BaseSecurityAssessmentId string `json:"baseSecurityAssessmentId,omitempty"`
	// Indicates whether the assessment is scheduled to run.
	// +kubebuilder:validation:Optional
	IsAssessmentScheduled bool `json:"isAssessmentScheduled,omitempty"`
	// To schedule the assessment for running periodically, specify the schedule in this attribute.
	// Create or schedule one assessment per compartment. If not defined, the assessment runs immediately.
	// Format -
	// <version-string>;<version-specific-schedule>
	// Allowed version strings - "v1"
	// v1's version specific schedule -<ss> <mm> <hh> <day-of-week> <day-of-month>
	// Each of the above fields potentially introduce constraints. A workrequest is created only
	// when clock time satisfies all the constraints. Constraints introduced:
	// 1. seconds = <ss> (So, the allowed range for <ss> is [0, 59])
	// 2. minutes = <mm> (So, the allowed range for <mm> is [0, 59])
	// 3. hours = <hh> (So, the allowed range for <hh> is [0, 23])
	// <day-of-week> can be either '*' (without quotes or a number between 1(Monday) and 7(Sunday))
	// 4. No constraint introduced when it is '*'. When not, day of week must equal the given value
	// <day-of-month> can be either '*' (without quotes or a number between 1 and 28)
	// 5. No constraint introduced when it is '*'. When not, day of month must equal the given value
	// +kubebuilder:validation:Optional
	Schedule string `json:"schedule,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// SecurityAssessmentCheckReferences defines nested fields for SecurityAssessment.Check.References.
type SecurityAssessmentCheckReferences struct {
	// Relevant section from STIG.
	Stig string `json:"stig,omitempty"`
	// Relevant section from CIS.
	Cis string `json:"cis,omitempty"`
	// Relevant section from GDPR.
	Gdpr string `json:"gdpr,omitempty"`
	// Relevant section from OBP.
	Obp string `json:"obp,omitempty"`
	// Relevant section from ORP.
	Orp string `json:"orp,omitempty"`
}

// SecurityAssessmentCheck defines nested fields for SecurityAssessment.Check.
type SecurityAssessmentCheck struct {
	// A unique identifier for the check.
	Key string `json:"key,omitempty"`
	// The short title for the check.
	Title string `json:"title,omitempty"`
	// The explanation of the issue in this check. It explains the reason for the rule and, if a risk is reported, it may also explain the recommended actions for remediation.
	Remarks string `json:"remarks,omitempty"`
	// Provides information on whether the check is related to a CIS Oracle Database Benchmark recommendation, STIG rule, GDPR Article/Recital or related to the Oracle Recommended Practice.
	References SecurityAssessmentCheckReferences `json:"references,omitempty"`
	// The category to which the check belongs to.
	Category string `json:"category,omitempty"`
	// Provides a recommended approach to take to remediate the check reported.
	Oneline string `json:"oneline,omitempty"`
	// The severity of the check as suggested by Data Safe security assessment. This will be the default severity in the template baseline security assessment.
	SuggestedSeverity string `json:"suggestedSeverity,omitempty"`
}

// SecurityAssessmentStatisticsHighRisk defines nested fields for SecurityAssessment.Statistics.HighRisk.
type SecurityAssessmentStatisticsHighRisk struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatisticsMediumRisk defines nested fields for SecurityAssessment.Statistics.MediumRisk.
type SecurityAssessmentStatisticsMediumRisk struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatisticsLowRisk defines nested fields for SecurityAssessment.Statistics.LowRisk.
type SecurityAssessmentStatisticsLowRisk struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatisticsAdvisory defines nested fields for SecurityAssessment.Statistics.Advisory.
type SecurityAssessmentStatisticsAdvisory struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatisticsEvaluate defines nested fields for SecurityAssessment.Statistics.Evaluate.
type SecurityAssessmentStatisticsEvaluate struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatisticsPass defines nested fields for SecurityAssessment.Statistics.Pass.
type SecurityAssessmentStatisticsPass struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatisticsDeferred defines nested fields for SecurityAssessment.Statistics.Deferred.
type SecurityAssessmentStatisticsDeferred struct {
	// The number of targets that contributed to the counts at this risk level.
	TargetsCount int `json:"targetsCount,omitempty"`
	// The number of findings in the Auditing category.
	AuditingFindingsCount int `json:"auditingFindingsCount,omitempty"`
	// The number of findings in the Authorization Control category.
	AuthorizationControlFindingsCount int `json:"authorizationControlFindingsCount,omitempty"`
	// The number of findings in the Data Encryption category.
	DataEncryptionFindingsCount int `json:"dataEncryptionFindingsCount,omitempty"`
	// The number of findings in the Database Configuration category.
	DbConfigurationFindingsCount int `json:"dbConfigurationFindingsCount,omitempty"`
	// The number of findings in the Fine-Grained Access Control category.
	FineGrainedAccessControlFindingsCount int `json:"fineGrainedAccessControlFindingsCount,omitempty"`
	// The number of findings in the Privileges and Roles category.
	PrivilegesAndRolesFindingsCount int `json:"privilegesAndRolesFindingsCount,omitempty"`
	// The number of findings in the User Accounts category.
	UserAccountsFindingsCount int `json:"userAccountsFindingsCount,omitempty"`
}

// SecurityAssessmentStatistics defines nested fields for SecurityAssessment.Statistics.
type SecurityAssessmentStatistics struct {
	// The total number of targets in this security assessment.
	TargetsCount int                                    `json:"targetsCount,omitempty"`
	HighRisk     SecurityAssessmentStatisticsHighRisk   `json:"highRisk,omitempty"`
	MediumRisk   SecurityAssessmentStatisticsMediumRisk `json:"mediumRisk,omitempty"`
	LowRisk      SecurityAssessmentStatisticsLowRisk    `json:"lowRisk,omitempty"`
	Advisory     SecurityAssessmentStatisticsAdvisory   `json:"advisory,omitempty"`
	Evaluate     SecurityAssessmentStatisticsEvaluate   `json:"evaluate,omitempty"`
	Pass         SecurityAssessmentStatisticsPass       `json:"pass,omitempty"`
	Deferred     SecurityAssessmentStatisticsDeferred   `json:"deferred,omitempty"`
}

// SecurityAssessmentStatus defines the observed state of SecurityAssessment.
type SecurityAssessmentStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID of the security assessment.
	Id string `json:"id,omitempty"`
	// The date and time the security assessment was created, in the format defined by RFC3339 (https://tools.ietf.org/html/rfc3339).
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the security assessment was last updated, in the format defined by RFC3339 (https://tools.ietf.org/html/rfc3339).
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The OCID of the compartment that contains the security assessment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The display name of the security assessment.
	DisplayName string `json:"displayName,omitempty"`
	// Array of database target OCIDs.
	TargetIds []string `json:"targetIds,omitempty"`
	// The current state of the security assessment.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The type of this security assessment. The possible types are:
	// LATEST: The most up-to-date assessment that is running automatically for a target. It is system generated.
	// SAVED: A saved security assessment. LATEST assessments are always saved in order to maintain the history of runs. A SAVED assessment is also generated by a 'refresh' action (triggered by the user).
	// SAVE_SCHEDULE: The schedule for periodic saves of LATEST assessments.
	// COMPARTMENT: An automatically managed assessment type that stores all details of targets in one compartment.
	//  This type keeps an up-to-date assessment of all database risks in one compartment. It is automatically updated when
	//  the latest assessment or refresh action is executed. It is also automatically updated when a target is deleted or move to a different compartment.
	Type string `json:"type,omitempty"`
	// The date and time the security assessment was last executed, in the format defined by RFC3339 (https://tools.ietf.org/html/rfc3339).
	TimeLastAssessed string `json:"timeLastAssessed,omitempty"`
	// List containing maps as values.
	// Example: `{"Operations": [ {"CostCenter": "42"} ] }`
	IgnoredTargets []shared.JSONValue `json:"ignoredTargets,omitempty"`
	// List containing maps as values.
	// Example: `{"Operations": [ {"CostCenter": "42"} ] }`
	IgnoredAssessmentIds []shared.JSONValue `json:"ignoredAssessmentIds,omitempty"`
	// The version of the target database.
	TargetVersion string `json:"targetVersion,omitempty"`
	// The ocid of a security assessment which is of type TEMPLATE, this will be null or empty when type is TEMPLATE.
	TemplateAssessmentId string `json:"templateAssessmentId,omitempty"`
	// The ocid of a security assessment which is of type TEMPLATE_BASELINE, this will be null or empty when type is TEMPLATE_BASELINE.
	BaselineAssessmentId string `json:"baselineAssessmentId,omitempty"`
	// Indicates whether or not the security assessment is set as a baseline. This is applicable only for saved security assessments.
	IsBaseline bool `json:"isBaseline,omitempty"`
	// Indicates if the assessment has deviated from the baseline.
	IsDeviatedFromBaseline bool `json:"isDeviatedFromBaseline,omitempty"`
	// The OCID of the baseline against which the latest security assessment was compared.
	LastComparedBaselineId string `json:"lastComparedBaselineId,omitempty"`
	// Details about the current state of the security assessment.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// The OCID of the security assessment that is responsible for creating this scheduled save assessment.
	ScheduleSecurityAssessmentId string `json:"scheduleSecurityAssessmentId,omitempty"`
	// Indicates whether the security assessment was created by system or by a user.
	TriggeredBy string `json:"triggeredBy,omitempty"`
	// The description of the security assessment.
	Description string `json:"description,omitempty"`
	// Indicates whether the assessment is scheduled to run.
	IsAssessmentScheduled bool `json:"isAssessmentScheduled,omitempty"`
	// The OCID of the target database group that the group assessment is created for.
	TargetDatabaseGroupId string `json:"targetDatabaseGroupId,omitempty"`
	// Indicates whether the security assessment is for a target database or a target database group.
	TargetType string `json:"targetType,omitempty"`
	// The security checks to be evaluated for type template.
	Checks []SecurityAssessmentCheck `json:"checks,omitempty"`
	// Schedule to save the assessment periodically in the specified format:
	// <version-string>;<version-specific-schedule>
	// Allowed version strings - "v1"
	// v1's version specific schedule -<ss> <mm> <hh> <day-of-week> <day-of-month>
	// Each of the above fields potentially introduce constraints. A workrequest is created only
	// when clock time satisfies all the constraints. Constraints introduced:
	// 1. seconds = <ss> (So, the allowed range for <ss> is [0, 59])
	// 2. minutes = <mm> (So, the allowed range for <mm> is [0, 59])
	// 3. hours = <hh> (So, the allowed range for <hh> is [0, 23])
	// <day-of-week> can be either '*' (without quotes or a number between 1(Monday) and 7(Sunday))
	// 4. No constraint introduced when it is '*'. When not, day of week must equal the given value
	// <day-of-month> can be either '*' (without quotes or a number between 1 and 28)
	// 5. No constraint introduced when it is '*'. When not, day of month must equal the given value
	Schedule string `json:"schedule,omitempty"`
	// The summary of findings for the security assessment
	Link       string                       `json:"link,omitempty"`
	Statistics SecurityAssessmentStatistics `json:"statistics,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm)
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
	// List containing maps as values.
	// Example: `{"Operations": [ {"CostCenter": "42"} ] }`
	IgnoredTargetIds []shared.JSONValue `json:"ignoredTargetIds,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the SecurityAssessment",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the SecurityAssessment",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// SecurityAssessment is the Schema for the securityassessments API.
type SecurityAssessment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SecurityAssessmentSpec   `json:"spec,omitempty"`
	Status SecurityAssessmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// SecurityAssessmentList contains a list of SecurityAssessment.
type SecurityAssessmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityAssessment `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SecurityAssessment{}, &SecurityAssessmentList{})
}
