/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package dbsystemdbinstance

import (
	"context"
	"fmt"

	psqlsdk "github.com/oracle/oci-go-sdk/v65/psql"
	psqlv1beta1 "github.com/oracle/oci-service-operator/api/psql/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DbSystemDbInstanceServiceClient is the handwritten extension seam for DbSystemDbInstance runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*DbSystemDbInstanceServiceManager).WithClient.
type DbSystemDbInstanceServiceClient interface {
	CreateOrUpdate(context.Context, *psqlv1beta1.DbSystemDbInstance, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *psqlv1beta1.DbSystemDbInstance) (bool, error)
}

type defaultDbSystemDbInstanceServiceClient struct {
	generatedruntime.ServiceClient[*psqlv1beta1.DbSystemDbInstance]
}

var _ DbSystemDbInstanceServiceClient = defaultDbSystemDbInstanceServiceClient{}

var newDbSystemDbInstanceServiceClient = func(manager *DbSystemDbInstanceServiceManager) DbSystemDbInstanceServiceClient {
	sdkClient, err := psqlsdk.NewPostgresqlClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*psqlv1beta1.DbSystemDbInstance]{
		Kind:    "DbSystemDbInstance",
		SDKName: "DbSystemDbInstance",
		Log:     manager.Log,
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &psqlsdk.UpdateDbSystemDbInstanceRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateDbSystemDbInstance(ctx, *request.(*psqlsdk.UpdateDbSystemDbInstanceRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize DbSystemDbInstance OCI client: %w", err)
	}
	return defaultDbSystemDbInstanceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*psqlv1beta1.DbSystemDbInstance](config),
	}
}
