/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package batchtaskprofile

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	batchv1beta1 "github.com/oracle/oci-service-operator/api/batch/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type BatchTaskProfileServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client BatchTaskProfileServiceClient
}

var _ servicemanager.OSOKServiceManager = (*BatchTaskProfileServiceManager)(nil)

func NewBatchTaskProfileServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *BatchTaskProfileServiceManager {
	manager := &BatchTaskProfileServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newBatchTaskProfileServiceClient(manager)
	return manager
}

func NewBatchTaskProfileServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *BatchTaskProfileServiceManager {
	return NewBatchTaskProfileServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *BatchTaskProfileServiceManager) WithClient(client BatchTaskProfileServiceClient) *BatchTaskProfileServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *BatchTaskProfileServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *BatchTaskProfileServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *BatchTaskProfileServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *BatchTaskProfileServiceManager) convert(obj runtime.Object) (*batchv1beta1.BatchTaskProfile, error) {
	resource, ok := obj.(*batchv1beta1.BatchTaskProfile)
	if !ok {
		return nil, fmt.Errorf("expected *batchv1beta1.BatchTaskProfile, got %T", obj)
	}
	return resource, nil
}

func (c *BatchTaskProfileServiceManager) status(resource *batchv1beta1.BatchTaskProfile) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
