/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package datasafeprivateendpoint

import (
	"context"

	datasafesdk "github.com/oracle/oci-go-sdk/v65/datasafe"
	datasafev1beta1 "github.com/oracle/oci-service-operator/api/datasafe/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type DataSafePrivateEndpointRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *datasafev1beta1.DataSafePrivateEndpoint, string) (any, error)
	BuildUpdateBody func(context.Context, *datasafev1beta1.DataSafePrivateEndpoint, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*datasafev1beta1.DataSafePrivateEndpoint]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*datasafev1beta1.DataSafePrivateEndpoint]
	StatusHooks         generatedruntime.StatusHooks[*datasafev1beta1.DataSafePrivateEndpoint]
	ParityHooks         generatedruntime.ParityHooks[*datasafev1beta1.DataSafePrivateEndpoint]
	Async               generatedruntime.AsyncHooks[*datasafev1beta1.DataSafePrivateEndpoint]
	DeleteHooks         generatedruntime.DeleteHooks[*datasafev1beta1.DataSafePrivateEndpoint]
	Create              runtimeOperationHooks[datasafesdk.CreateDataSafePrivateEndpointRequest, datasafesdk.CreateDataSafePrivateEndpointResponse]
	Get                 runtimeOperationHooks[datasafesdk.GetDataSafePrivateEndpointRequest, datasafesdk.GetDataSafePrivateEndpointResponse]
	List                runtimeOperationHooks[datasafesdk.ListDataSafePrivateEndpointsRequest, datasafesdk.ListDataSafePrivateEndpointsResponse]
	Update              runtimeOperationHooks[datasafesdk.UpdateDataSafePrivateEndpointRequest, datasafesdk.UpdateDataSafePrivateEndpointResponse]
	Delete              runtimeOperationHooks[datasafesdk.DeleteDataSafePrivateEndpointRequest, datasafesdk.DeleteDataSafePrivateEndpointResponse]
	WrapGeneratedClient []func(DataSafePrivateEndpointServiceClient) DataSafePrivateEndpointServiceClient
}

type DataSafePrivateEndpointRuntimeHooksMutator func(*DataSafePrivateEndpointServiceManager, *DataSafePrivateEndpointRuntimeHooks)

var datasafeprivateendpointRuntimeHooksMutators []DataSafePrivateEndpointRuntimeHooksMutator

func registerDataSafePrivateEndpointRuntimeHooksMutator(mutator DataSafePrivateEndpointRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	datasafeprivateendpointRuntimeHooksMutators = append(datasafeprivateendpointRuntimeHooksMutators, mutator)
}
func newDataSafePrivateEndpointDefaultRuntimeHooks(sdkClient datasafesdk.DataSafeClient) DataSafePrivateEndpointRuntimeHooks {
	return DataSafePrivateEndpointRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*datasafev1beta1.DataSafePrivateEndpoint]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*datasafev1beta1.DataSafePrivateEndpoint]{},
		StatusHooks:     generatedruntime.StatusHooks[*datasafev1beta1.DataSafePrivateEndpoint]{},
		ParityHooks:     generatedruntime.ParityHooks[*datasafev1beta1.DataSafePrivateEndpoint]{},
		Async:           generatedruntime.AsyncHooks[*datasafev1beta1.DataSafePrivateEndpoint]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*datasafev1beta1.DataSafePrivateEndpoint]{},
		Create: runtimeOperationHooks[datasafesdk.CreateDataSafePrivateEndpointRequest, datasafesdk.CreateDataSafePrivateEndpointResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateDataSafePrivateEndpointDetails", RequestName: "CreateDataSafePrivateEndpointDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request datasafesdk.CreateDataSafePrivateEndpointRequest) (datasafesdk.CreateDataSafePrivateEndpointResponse, error) {
				return sdkClient.CreateDataSafePrivateEndpoint(ctx, request)
			},
		},
		Get: runtimeOperationHooks[datasafesdk.GetDataSafePrivateEndpointRequest, datasafesdk.GetDataSafePrivateEndpointResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "DataSafePrivateEndpointId", RequestName: "dataSafePrivateEndpointId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request datasafesdk.GetDataSafePrivateEndpointRequest) (datasafesdk.GetDataSafePrivateEndpointResponse, error) {
				return sdkClient.GetDataSafePrivateEndpoint(ctx, request)
			},
		},
		List: runtimeOperationHooks[datasafesdk.ListDataSafePrivateEndpointsRequest, datasafesdk.ListDataSafePrivateEndpointsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "VcnId", RequestName: "vcnId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentIdInSubtree", RequestName: "compartmentIdInSubtree", Contribution: "query", PreferResourceID: false}, {FieldName: "AccessLevel", RequestName: "accessLevel", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request datasafesdk.ListDataSafePrivateEndpointsRequest) (datasafesdk.ListDataSafePrivateEndpointsResponse, error) {
				return sdkClient.ListDataSafePrivateEndpoints(ctx, request)
			},
		},
		Update: runtimeOperationHooks[datasafesdk.UpdateDataSafePrivateEndpointRequest, datasafesdk.UpdateDataSafePrivateEndpointResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "DataSafePrivateEndpointId", RequestName: "dataSafePrivateEndpointId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateDataSafePrivateEndpointDetails", RequestName: "UpdateDataSafePrivateEndpointDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request datasafesdk.UpdateDataSafePrivateEndpointRequest) (datasafesdk.UpdateDataSafePrivateEndpointResponse, error) {
				return sdkClient.UpdateDataSafePrivateEndpoint(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[datasafesdk.DeleteDataSafePrivateEndpointRequest, datasafesdk.DeleteDataSafePrivateEndpointResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "DataSafePrivateEndpointId", RequestName: "dataSafePrivateEndpointId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request datasafesdk.DeleteDataSafePrivateEndpointRequest) (datasafesdk.DeleteDataSafePrivateEndpointResponse, error) {
				return sdkClient.DeleteDataSafePrivateEndpoint(ctx, request)
			},
		},
		WrapGeneratedClient: []func(DataSafePrivateEndpointServiceClient) DataSafePrivateEndpointServiceClient{},
	}
}

func newDataSafePrivateEndpointRuntimeHooks(manager *DataSafePrivateEndpointServiceManager, sdkClient datasafesdk.DataSafeClient) DataSafePrivateEndpointRuntimeHooks {
	hooks := newDataSafePrivateEndpointDefaultRuntimeHooks(sdkClient)
	for _, mutator := range datasafeprivateendpointRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildDataSafePrivateEndpointGeneratedRuntimeConfig(
	manager *DataSafePrivateEndpointServiceManager,
	hooks DataSafePrivateEndpointRuntimeHooks,
) generatedruntime.Config[*datasafev1beta1.DataSafePrivateEndpoint] {
	return generatedruntime.Config[*datasafev1beta1.DataSafePrivateEndpoint]{
		Kind:            "DataSafePrivateEndpoint",
		SDKName:         "DataSafePrivateEndpoint",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &datasafesdk.CreateDataSafePrivateEndpointRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*datasafesdk.CreateDataSafePrivateEndpointRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &datasafesdk.GetDataSafePrivateEndpointRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*datasafesdk.GetDataSafePrivateEndpointRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &datasafesdk.ListDataSafePrivateEndpointsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*datasafesdk.ListDataSafePrivateEndpointsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &datasafesdk.UpdateDataSafePrivateEndpointRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*datasafesdk.UpdateDataSafePrivateEndpointRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &datasafesdk.DeleteDataSafePrivateEndpointRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*datasafesdk.DeleteDataSafePrivateEndpointRequest))
			},
		},
	}
}

func wrapDataSafePrivateEndpointGeneratedClient(
	hooks DataSafePrivateEndpointRuntimeHooks,
	delegate DataSafePrivateEndpointServiceClient,
) DataSafePrivateEndpointServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
