/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AgentDependencySpec defines the desired state of AgentDependency.
type AgentDependencySpec struct {
	// Display name of the Agent dependency.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// Name of the dependency type. This should match the whitelisted enum of dependency names.
	// +kubebuilder:validation:Required
	DependencyName string `json:"dependencyName"`
	// Compartment identifier.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// Object storage namespace associated with the customer's tenancy.
	// +kubebuilder:validation:Required
	Namespace string `json:"namespace"`
	// Object storage bucket where the dependency is uploaded.
	// +kubebuilder:validation:Required
	Bucket string `json:"bucket"`
	// Name of the dependency object uploaded by the customer.
	// +kubebuilder:validation:Required
	ObjectName string `json:"objectName"`
	// Version of the Agent dependency.
	// +kubebuilder:validation:Optional
	DependencyVersion string `json:"dependencyVersion,omitempty"`
	// Description about the Agent dependency.
	// +kubebuilder:validation:Optional
	Description string `json:"description,omitempty"`
	// The freeform tags associated with this resource, if any. Each tag is a simple key-value pair with no
	// predefined name, type, or namespace/scope. For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The defined tags associated with this resource, if any. Each key is predefined and scoped to namespaces.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The system tags associated with this resource, if any. The system tags are set by Oracle cloud infrastructure services. Each key is predefined and scoped to namespaces.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{orcl-cloud: {free-tier-retain: true}}`
	// +kubebuilder:validation:Optional
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// AgentDependencyStatus defines the observed state of AgentDependency.
type AgentDependencyStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Unique identifier that is immutable on creation.
	Id string `json:"id,omitempty"`
	// Display name of the Agent dependency.
	DisplayName string `json:"displayName,omitempty"`
	// Compartment identifier
	CompartmentId string `json:"compartmentId,omitempty"`
	// Name of the dependency type. This should match the whitelisted enum of dependency names.
	DependencyName string `json:"dependencyName,omitempty"`
	// Object storage namespace associated with the customer's tenancy.
	Namespace string `json:"namespace,omitempty"`
	// Object storage bucket where the Agent dependency is uploaded.
	Bucket string `json:"bucket,omitempty"`
	// Name of the dependency object uploaded by the customer.
	ObjectName string `json:"objectName,omitempty"`
	// Version of the Agent dependency.
	DependencyVersion string `json:"dependencyVersion,omitempty"`
	// Description about the Agent dependency.
	Description string `json:"description,omitempty"`
	// The time when the AgentDependency was created. An RFC3339 formatted datetime string.
	TimeCreated string `json:"timeCreated,omitempty"`
	// The eTag associated with the dependency object returned by Object Storage.
	ETag string `json:"eTag,omitempty"`
	// The checksum associated with the dependency object returned by Object Storage.
	Checksum string `json:"checksum,omitempty"`
	// The current state of AgentDependency.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// A message describing the current state in more detail. For example, it can be used to provide actionable information for a resource in Failed state.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// The freeform tags associated with this resource, if any. Each tag is a simple key-value pair with no
	// predefined name, type, or namespace/scope. For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The defined tags associated with this resource, if any. Each key is predefined and scoped to namespaces.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The system tags associated with this resource, if any. The system tags are set by Oracle cloud infrastructure services. Each key is predefined and scoped to namespaces.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{orcl-cloud: {free-tier-retain: true}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the AgentDependency",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the AgentDependency",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// AgentDependency is the Schema for the agentdependencies API.
type AgentDependency struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AgentDependencySpec   `json:"spec,omitempty"`
	Status AgentDependencyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// AgentDependencyList contains a list of AgentDependency.
type AgentDependencyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AgentDependency `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AgentDependency{}, &AgentDependencyList{})
}
