/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package ipsecconnectiontunnelsharedsecret

import (
	"context"
	"fmt"

	coresdk "github.com/oracle/oci-go-sdk/v65/core"
	corev1beta1 "github.com/oracle/oci-service-operator/api/core/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// IPSecConnectionTunnelSharedSecretServiceClient is the handwritten extension seam for IPSecConnectionTunnelSharedSecret runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*IPSecConnectionTunnelSharedSecretServiceManager).WithClient.
type IPSecConnectionTunnelSharedSecretServiceClient interface {
	CreateOrUpdate(context.Context, *corev1beta1.IPSecConnectionTunnelSharedSecret, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *corev1beta1.IPSecConnectionTunnelSharedSecret) (bool, error)
}

type defaultIPSecConnectionTunnelSharedSecretServiceClient struct {
	generatedruntime.ServiceClient[*corev1beta1.IPSecConnectionTunnelSharedSecret]
}

var _ IPSecConnectionTunnelSharedSecretServiceClient = defaultIPSecConnectionTunnelSharedSecretServiceClient{}

var newIPSecConnectionTunnelSharedSecretServiceClient = func(manager *IPSecConnectionTunnelSharedSecretServiceManager) IPSecConnectionTunnelSharedSecretServiceClient {
	sdkClient, err := coresdk.NewVirtualNetworkClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*corev1beta1.IPSecConnectionTunnelSharedSecret]{
		Kind:    "IPSecConnectionTunnelSharedSecret",
		SDKName: "IPSecConnectionTunnelSharedSecret",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.GetIPSecConnectionTunnelSharedSecretRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetIPSecConnectionTunnelSharedSecret(ctx, *request.(*coresdk.GetIPSecConnectionTunnelSharedSecretRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.UpdateIPSecConnectionTunnelSharedSecretRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateIPSecConnectionTunnelSharedSecret(ctx, *request.(*coresdk.UpdateIPSecConnectionTunnelSharedSecretRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize IPSecConnectionTunnelSharedSecret OCI client: %w", err)
	}
	return defaultIPSecConnectionTunnelSharedSecretServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*corev1beta1.IPSecConnectionTunnelSharedSecret](config),
	}
}
