/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WlpAgentSpec defines the desired state of WlpAgent.
type WlpAgentSpec struct {
	// Compartment OCID of the host
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The version of the agent making the request
	// +kubebuilder:validation:Required
	AgentVersion string `json:"agentVersion"`
	// The certificate signed request containing domain, organization names, organization units, city, state, country, email and public key, among other certificate details, signed by private key
	// +kubebuilder:validation:Required
	CertificateSignedRequest string `json:"certificateSignedRequest"`
	// Concatenated OS name, OS version and agent architecture; for example, ubuntu_22.0_amd64.
	// +kubebuilder:validation:Required
	OsInfo string `json:"osInfo"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	// Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// WlpAgentLock defines nested fields for WlpAgent.Lock.
type WlpAgentLock struct {
	// Type of the lock.
	Type string `json:"type,omitempty"`
	// The ID of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	RelatedResourceId string `json:"relatedResourceId,omitempty"`
	// A message added by the creator of the lock. This is typically used to give an
	// indication of why the resource is locked.
	Message string `json:"message,omitempty"`
	// When the lock was created, in the format defined by RFC 3339.
	TimeCreated string `json:"timeCreated,omitempty"`
}

// WlpAgentStatus defines the observed state of WlpAgent.
type WlpAgentStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// OCID for WlpAgent
	Id string `json:"id,omitempty"`
	// Compartment OCID of WlpAgent.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The version of the agent
	AgentVersion string `json:"agentVersion,omitempty"`
	// The certificate ID returned by OCI certificates service
	CertificateId string `json:"certificateId,omitempty"`
	// OCID for instance in which WlpAgent is installed
	HostId string `json:"hostId,omitempty"`
	// TenantId of the host
	TenantId string `json:"tenantId,omitempty"`
	// The updated certificate signing request
	CertificateSignedRequest string `json:"certificateSignedRequest,omitempty"`
	// The date and time the WlpAgent was created. Format defined by RFC3339.
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the WlpAgent was updated. Format defined by RFC3339.
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// Locks associated with this resource.
	Locks []WlpAgentLock `json:"locks,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	// Avoid entering confidential information.
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// System tags can be viewed by users, but can only be created by the system.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the WlpAgent",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the WlpAgent",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// WlpAgent is the Schema for the wlpagents API.
type WlpAgent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WlpAgentSpec   `json:"spec,omitempty"`
	Status WlpAgentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// WlpAgentList contains a list of WlpAgent.
type WlpAgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WlpAgent `json:"items"`
}

func init() {
	SchemeBuilder.Register(&WlpAgent{}, &WlpAgentList{})
}
