/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package governancerulescontrolplane

import (
	"context"

	governancerulescontrolplanev1beta1 "github.com/oracle/oci-service-operator/api/governancerulescontrolplane/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// GovernanceRuleReconciler reconciles a GovernanceRule object.
type GovernanceRuleReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=governancerulescontrolplane.oracle.com,resources=governancerules,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=governancerulescontrolplane.oracle.com,resources=governancerules/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=governancerulescontrolplane.oracle.com,resources=governancerules/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *GovernanceRuleReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	governanceRule := &governancerulescontrolplanev1beta1.GovernanceRule{}
	return r.Reconciler.Reconcile(ctx, req, governanceRule)
}

// SetupWithManager sets up the controller with the Manager.
func (r *GovernanceRuleReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&governancerulescontrolplanev1beta1.GovernanceRule{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
