/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package functions

import (
	"context"

	functionsv1beta1 "github.com/oracle/oci-service-operator/api/functions/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// PbfListingVersionReconciler reconciles a PbfListingVersion object.
type PbfListingVersionReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=functions.oracle.com,resources=pbflistingversions,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=functions.oracle.com,resources=pbflistingversions/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=functions.oracle.com,resources=pbflistingversions/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *PbfListingVersionReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	pbfListingVersion := &functionsv1beta1.PbfListingVersion{}
	return r.Reconciler.Reconcile(ctx, req, pbfListingVersion)
}

// SetupWithManager sets up the controller with the Manager.
func (r *PbfListingVersionReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&functionsv1beta1.PbfListingVersion{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
