---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apigateway.oracle.com
  resources:
  - apigatewaydeployments
  - apigateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.oracle.com
  resources:
  - apigatewaydeployments/finalizers
  - apigateways/finalizers
  verbs:
  - update
- apiGroups:
  - apigateway.oracle.com
  resources:
  - apigatewaydeployments/status
  - apigateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - containerinstances.oracle.com
  resources:
  - containerinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerinstances.oracle.com
  resources:
  - containerinstances/finalizers
  verbs:
  - update
- apiGroups:
  - containerinstances.oracle.com
  resources:
  - containerinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.oracle.com
  resources:
  - drgs
  - instances
  - internetgateways
  - natgateways
  - networksecuritygroups
  - routetables
  - securitylists
  - servicegateways
  - subnets
  - vcns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oracle.com
  resources:
  - drgs/finalizers
  - instances/finalizers
  - internetgateways/finalizers
  - natgateways/finalizers
  - networksecuritygroups/finalizers
  - routetables/finalizers
  - securitylists/finalizers
  - servicegateways/finalizers
  - subnets/finalizers
  - vcns/finalizers
  verbs:
  - update
- apiGroups:
  - core.oracle.com
  resources:
  - drgs/status
  - instances/status
  - internetgateways/status
  - natgateways/status
  - networksecuritygroups/status
  - routetables/status
  - securitylists/status
  - servicegateways/status
  - subnets/status
  - vcns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataflow.oracle.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataflow.oracle.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - dataflow.oracle.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - functions.oracle.com
  resources:
  - applications
  - functions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - functions.oracle.com
  resources:
  - applications/finalizers
  - functions/finalizers
  verbs:
  - update
- apiGroups:
  - functions.oracle.com
  resources:
  - applications/status
  - functions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - identity.oracle.com
  resources:
  - compartments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.oracle.com
  resources:
  - compartments/finalizers
  verbs:
  - update
- apiGroups:
  - identity.oracle.com
  resources:
  - compartments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.oracle.com
  - psql.oracle.com
  resources:
  - dbsystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.oracle.com
  - psql.oracle.com
  resources:
  - dbsystems/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.oracle.com
  - psql.oracle.com
  resources:
  - dbsystems/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nosql.oracle.com
  resources:
  - tables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nosql.oracle.com
  resources:
  - tables/finalizers
  verbs:
  - update
- apiGroups:
  - nosql.oracle.com
  resources:
  - tables/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - objectstorage.oracle.com
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstorage.oracle.com
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - objectstorage.oracle.com
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - queue.oracle.com
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - queue.oracle.com
  resources:
  - queues/finalizers
  verbs:
  - update
- apiGroups:
  - queue.oracle.com
  resources:
  - queues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.oracle.com
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.oracle.com
  resources:
  - redisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.oracle.com
  resources:
  - redisclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - streaming.oracle.com
  resources:
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.oracle.com
  resources:
  - streams/finalizers
  verbs:
  - update
- apiGroups:
  - streaming.oracle.com
  resources:
  - streams/status
  verbs:
  - get
  - patch
  - update
