---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - containerengine.oracle.com
  resources:
  - addonoptions
  - addons
  - clusterendpointconfigs
  - clustermigratetonativevcnstatuses
  - clusteroptions
  - clusters
  - credentialrotationstatuses
  - kubeconfigs
  - nodepooloptions
  - nodepools
  - nodes
  - podshapes
  - virtualnodepools
  - virtualnodes
  - workloadmappings
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerengine.oracle.com
  resources:
  - addonoptions/finalizers
  - addons/finalizers
  - clusterendpointconfigs/finalizers
  - clustermigratetonativevcnstatuses/finalizers
  - clusteroptions/finalizers
  - clusters/finalizers
  - credentialrotationstatuses/finalizers
  - kubeconfigs/finalizers
  - nodepooloptions/finalizers
  - nodepools/finalizers
  - nodes/finalizers
  - podshapes/finalizers
  - virtualnodepools/finalizers
  - virtualnodes/finalizers
  - workloadmappings/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - containerengine.oracle.com
  resources:
  - addonoptions/status
  - addons/status
  - clusterendpointconfigs/status
  - clustermigratetonativevcnstatuses/status
  - clusteroptions/status
  - clusters/status
  - credentialrotationstatuses/status
  - kubeconfigs/status
  - nodepooloptions/status
  - nodepools/status
  - nodes/status
  - podshapes/status
  - virtualnodepools/status
  - virtualnodes/status
  - workloadmappings/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - identity.oracle.com
  resources:
  - alloweddomainlicensetypes
  - apikeies
  - authenticationpolicies
  - authtokens
  - availabilitydomains
  - bulkactionresourcetypes
  - bulkedittagsresourcetypes
  - compartments
  - costtrackingtags
  - customersecretkeies
  - dbcredentials
  - domains
  - dynamicgroups
  - faultdomains
  - groups
  - iamworkrequesterrors
  - iamworkrequestlogs
  - iamworkrequests
  - identityprovidergroups
  - identityproviders
  - idpgroupmappings
  - mfatotpdevices
  - networksources
  - oauthclientcredentials
  - orresetuipasswords
  - policies
  - regions
  - regionsubscriptions
  - smtpcredentials
  - standardtagnamespaces
  - standardtagtemplates
  - swiftpasswords
  - tagdefaults
  - taggingworkrequesterrors
  - taggingworkrequestlogs
  - taggingworkrequests
  - tagnamespaces
  - tags
  - tenancies
  - usercapabilities
  - usergroupmemberships
  - users
  - userstates
  - useruipasswordinformations
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.oracle.com
  resources:
  - alloweddomainlicensetypes/finalizers
  - apikeies/finalizers
  - authenticationpolicies/finalizers
  - authtokens/finalizers
  - availabilitydomains/finalizers
  - bulkactionresourcetypes/finalizers
  - bulkedittagsresourcetypes/finalizers
  - compartments/finalizers
  - costtrackingtags/finalizers
  - customersecretkeies/finalizers
  - dbcredentials/finalizers
  - domains/finalizers
  - dynamicgroups/finalizers
  - faultdomains/finalizers
  - groups/finalizers
  - iamworkrequesterrors/finalizers
  - iamworkrequestlogs/finalizers
  - iamworkrequests/finalizers
  - identityprovidergroups/finalizers
  - identityproviders/finalizers
  - idpgroupmappings/finalizers
  - mfatotpdevices/finalizers
  - networksources/finalizers
  - oauthclientcredentials/finalizers
  - orresetuipasswords/finalizers
  - policies/finalizers
  - regions/finalizers
  - regionsubscriptions/finalizers
  - smtpcredentials/finalizers
  - standardtagnamespaces/finalizers
  - standardtagtemplates/finalizers
  - swiftpasswords/finalizers
  - tagdefaults/finalizers
  - taggingworkrequesterrors/finalizers
  - taggingworkrequestlogs/finalizers
  - taggingworkrequests/finalizers
  - tagnamespaces/finalizers
  - tags/finalizers
  - tenancies/finalizers
  - usercapabilities/finalizers
  - usergroupmemberships/finalizers
  - users/finalizers
  - userstates/finalizers
  - useruipasswordinformations/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - identity.oracle.com
  resources:
  - alloweddomainlicensetypes/status
  - apikeies/status
  - authenticationpolicies/status
  - authtokens/status
  - availabilitydomains/status
  - bulkactionresourcetypes/status
  - bulkedittagsresourcetypes/status
  - compartments/status
  - costtrackingtags/status
  - customersecretkeies/status
  - dbcredentials/status
  - domains/status
  - dynamicgroups/status
  - faultdomains/status
  - groups/status
  - iamworkrequesterrors/status
  - iamworkrequestlogs/status
  - iamworkrequests/status
  - identityprovidergroups/status
  - identityproviders/status
  - idpgroupmappings/status
  - mfatotpdevices/status
  - networksources/status
  - oauthclientcredentials/status
  - orresetuipasswords/status
  - policies/status
  - regions/status
  - regionsubscriptions/status
  - smtpcredentials/status
  - standardtagnamespaces/status
  - standardtagtemplates/status
  - swiftpasswords/status
  - tagdefaults/status
  - taggingworkrequesterrors/status
  - taggingworkrequestlogs/status
  - taggingworkrequests/status
  - tagnamespaces/status
  - tags/status
  - tenancies/status
  - usercapabilities/status
  - usergroupmemberships/status
  - users/status
  - userstates/status
  - useruipasswordinformations/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.oracle.com
  resources:
  - backups
  - channels
  - configurations
  - dbsystems
  - heatwaveclustermemoryestimates
  - heatwaveclusters
  - replicas
  - shapes
  - versions
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.oracle.com
  resources:
  - backups/finalizers
  - channels/finalizers
  - configurations/finalizers
  - dbsystems/finalizers
  - heatwaveclustermemoryestimates/finalizers
  - heatwaveclusters/finalizers
  - replicas/finalizers
  - shapes/finalizers
  - versions/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.oracle.com
  resources:
  - backups/status
  - channels/status
  - configurations/status
  - dbsystems/status
  - heatwaveclustermemoryestimates/status
  - heatwaveclusters/status
  - replicas/status
  - shapes/status
  - versions/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nosql.oracle.com
  resources:
  - indices
  - replicas
  - rows
  - tables
  - tableusages
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nosql.oracle.com
  resources:
  - indices/finalizers
  - replicas/finalizers
  - rows/finalizers
  - tables/finalizers
  - tableusages/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - nosql.oracle.com
  resources:
  - indices/status
  - replicas/status
  - rows/status
  - tables/status
  - tableusages/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - objectstorage.oracle.com
  resources:
  - buckets
  - multipartuploadparts
  - multipartuploads
  - namespacemetadatas
  - namespaces
  - objectlifecyclepolicies
  - objects
  - objectstoragetiers
  - objectversions
  - preauthenticatedrequests
  - replicationpolicies
  - replicationsources
  - retentionrules
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstorage.oracle.com
  resources:
  - buckets/finalizers
  - multipartuploadparts/finalizers
  - multipartuploads/finalizers
  - namespacemetadatas/finalizers
  - namespaces/finalizers
  - objectlifecyclepolicies/finalizers
  - objects/finalizers
  - objectstoragetiers/finalizers
  - objectversions/finalizers
  - preauthenticatedrequests/finalizers
  - replicationpolicies/finalizers
  - replicationsources/finalizers
  - retentionrules/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - objectstorage.oracle.com
  resources:
  - buckets/status
  - multipartuploadparts/status
  - multipartuploads/status
  - namespacemetadatas/status
  - namespaces/status
  - objectlifecyclepolicies/status
  - objects/status
  - objectstoragetiers/status
  - objectversions/status
  - preauthenticatedrequests/status
  - replicationpolicies/status
  - replicationsources/status
  - retentionrules/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchclusters
  - opensearchversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchclusters/finalizers
  - opensearchversions/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchclusters/status
  - opensearchversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - psql.oracle.com
  resources:
  - backups
  - configurations
  - connectiondetails
  - dbsystemdbinstances
  - dbsystems
  - defaultconfigurations
  - primarydbinstances
  - shapes
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - psql.oracle.com
  resources:
  - backups/finalizers
  - configurations/finalizers
  - connectiondetails/finalizers
  - dbsystemdbinstances/finalizers
  - dbsystems/finalizers
  - defaultconfigurations/finalizers
  - primarydbinstances/finalizers
  - shapes/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - psql.oracle.com
  resources:
  - backups/status
  - configurations/status
  - connectiondetails/status
  - dbsystemdbinstances/status
  - dbsystems/status
  - defaultconfigurations/status
  - primarydbinstances/status
  - shapes/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.oracle.com
  resources:
  - redisclusters
  - workrequesterrors
  - workrequestlogs
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.oracle.com
  resources:
  - redisclusters/finalizers
  - workrequesterrors/finalizers
  - workrequestlogs/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - redis.oracle.com
  resources:
  - redisclusters/status
  - workrequesterrors/status
  - workrequestlogs/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - streaming.oracle.com
  resources:
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.oracle.com
  resources:
  - streams/finalizers
  verbs:
  - update
- apiGroups:
  - streaming.oracle.com
  resources:
  - streams/status
  verbs:
  - get
  - patch
  - update
