/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package dbserver

import (
	"context"
	"fmt"

	databasesdk "github.com/oracle/oci-go-sdk/v65/database"
	databasev1beta1 "github.com/oracle/oci-service-operator/api/database/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DbServerServiceClient is the handwritten extension seam for DbServer runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*DbServerServiceManager).WithClient.
type DbServerServiceClient interface {
	CreateOrUpdate(context.Context, *databasev1beta1.DbServer, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *databasev1beta1.DbServer) (bool, error)
}

type defaultDbServerServiceClient struct {
	generatedruntime.ServiceClient[*databasev1beta1.DbServer]
}

var _ DbServerServiceClient = defaultDbServerServiceClient{}

var newDbServerServiceClient = func(manager *DbServerServiceManager) DbServerServiceClient {
	sdkClient, err := databasesdk.NewDatabaseClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*databasev1beta1.DbServer]{
		Kind:    "DbServer",
		SDKName: "DbServer",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &databasesdk.GetDbServerRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetDbServer(ctx, *request.(*databasesdk.GetDbServerRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &databasesdk.ListDbServersRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListDbServers(ctx, *request.(*databasesdk.ListDbServersRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize DbServer OCI client: %w", err)
	}
	return defaultDbServerServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*databasev1beta1.DbServer](config),
	}
}
