#
# Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: core.oracle.com/v1beta1
kind: Drg
metadata:
  name: osok-drg-${OSOK_E2E_SUFFIX}
spec:
  compartmentId: ${OCI_COMPARTMENT_ID}
  displayName: osok-drg-updated-${OSOK_E2E_SUFFIX}
  freeformTags:
    osok-e2e-phase: update
