/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MultipartUploadPartSpec defines the desired state of MultipartUploadPart.
type MultipartUploadPartSpec struct {
	Id            shared.OCID `json:"id,omitempty"`
	CompartmentId shared.OCID `json:"compartmentId,omitempty"`
}

// MultipartUploadPartStatus defines the observed state of MultipartUploadPart.
type MultipartUploadPartStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the MultipartUploadPart",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the MultipartUploadPart",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// MultipartUploadPart is the Schema for the multipartuploadparts API.
type MultipartUploadPart struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MultipartUploadPartSpec   `json:"spec,omitempty"`
	Status MultipartUploadPartStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// MultipartUploadPartList contains a list of MultipartUploadPart.
type MultipartUploadPartList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MultipartUploadPart `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MultipartUploadPart{}, &MultipartUploadPartList{})
}
