/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReplicationPolicySpec defines the desired state of ReplicationPolicy.
type ReplicationPolicySpec struct {
	Id                    shared.OCID `json:"id,omitempty"`
	CompartmentId         shared.OCID `json:"compartmentId,omitempty"`
	Name                  string      `json:"name,omitempty"`
	DestinationRegionName string      `json:"destinationRegionName,omitempty"`
	DestinationBucketName string      `json:"destinationBucketName,omitempty"`
	TimeCreated           string      `json:"timeCreated,omitempty"`
	TimeLastSync          string      `json:"timeLastSync,omitempty"`
	Status                string      `json:"status,omitempty"`
	StatusMessage         string      `json:"statusMessage,omitempty"`
}

// ReplicationPolicyStatus defines the observed state of ReplicationPolicy.
type ReplicationPolicyStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Name",type="string",JSONPath=".spec.name",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the ReplicationPolicy",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the ReplicationPolicy",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// ReplicationPolicy is the Schema for the replicationpolicies API.
type ReplicationPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ReplicationPolicySpec   `json:"spec,omitempty"`
	Status ReplicationPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// ReplicationPolicyList contains a list of ReplicationPolicy.
type ReplicationPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReplicationPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReplicationPolicy{}, &ReplicationPolicyList{})
}
