/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ShapeSpec defines the desired state of Shape.
type ShapeSpec struct {
}

// ShapeStatus defines the observed state of Shape.
type ShapeStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The name of the shape used for the DB System.
	Name string `json:"name,omitempty"`
	// The number of CPU Cores the Instance provides. These are "OCPU"s.
	CpuCoreCount int `json:"cpuCoreCount,omitempty"`
	// The amount of RAM the Instance provides. This is an IEC base-2 number.
	MemorySizeInGBs int `json:"memorySizeInGBs,omitempty"`
	// What service features the shape is supported for.
	IsSupportedFor []string `json:"isSupportedFor,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the Shape",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the Shape",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// Shape is the Schema for the shapes API.
type Shape struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ShapeSpec   `json:"spec,omitempty"`
	Status ShapeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// ShapeList contains a list of Shape.
type ShapeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Shape `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Shape{}, &ShapeList{})
}
