/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GovernanceInstanceSpec defines the desired state of GovernanceInstance.
type GovernanceInstanceSpec struct {
	// The name for the GovernanceInstance.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// The licenseType being used.
	// +kubebuilder:validation:Required
	LicenseType string `json:"licenseType"`
	// The namespace for tenancy object storage.
	// +kubebuilder:validation:Required
	TenancyNamespace string `json:"tenancyNamespace"`
	// The OCID of the compartment where the GovernanceInstance resides.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// IDCS access token identifying a stripe and service administrator user.
	// +kubebuilder:validation:Required
	IdcsAccessToken string `json:"idcsAccessToken"`
	// The description of the GovernanceInstance.
	// +kubebuilder:validation:Optional
	Description string `json:"description,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Usage of system tag keys. These predefined keys are scoped to namespaces.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	// +kubebuilder:validation:Optional
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// GovernanceInstanceStatus defines the observed state of GovernanceInstance.
type GovernanceInstanceStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The name for the GovernanceInstance.
	DisplayName string `json:"displayName,omitempty"`
	// The OCID of the compartment where the GovernanceInstance resides.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The time the the GovernanceInstance was created in an RFC3339 formatted datetime string.
	TimeCreated string `json:"timeCreated,omitempty"`
	// The current state of the GovernanceInstance.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The unique OCID of the GovernanceInstance.
	Id string `json:"id,omitempty"`
	// The time the GovernanceInstance was updated in an RFC3339 formatted datetime string.
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The description of the GovernanceInstance.
	Description string `json:"description,omitempty"`
	// The licenseType being used.
	LicenseType string `json:"licenseType,omitempty"`
	// The namespace for tenancy object storage.
	TenancyNamespace string `json:"tenancyNamespace,omitempty"`
	// The access URL of the GovernanceInstance.
	InstanceUrl string `json:"instanceUrl,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Usage of system tag keys. These predefined keys are scoped to namespaces.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the GovernanceInstance",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the GovernanceInstance",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// GovernanceInstance is the Schema for the governanceinstances API.
type GovernanceInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   GovernanceInstanceSpec   `json:"spec,omitempty"`
	Status GovernanceInstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// GovernanceInstanceList contains a list of GovernanceInstance.
type GovernanceInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GovernanceInstance `json:"items"`
}

func init() {
	SchemeBuilder.Register(&GovernanceInstance{}, &GovernanceInstanceList{})
}
