/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package datacatalog

import (
	"context"

	datacatalogv1beta1 "github.com/oracle/oci-service-operator/api/datacatalog/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// FolderTagReconciler reconciles a FolderTag object.
type FolderTagReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=datacatalog.oracle.com,resources=foldertags,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=datacatalog.oracle.com,resources=foldertags/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=datacatalog.oracle.com,resources=foldertags/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *FolderTagReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	folderTag := &datacatalogv1beta1.FolderTag{}
	return r.Reconciler.Reconcile(ctx, req, folderTag)
}

// SetupWithManager sets up the controller with the Manager.
func (r *FolderTagReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&datacatalogv1beta1.FolderTag{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
