/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package iotdomain

import (
	"context"

	iotsdk "github.com/oracle/oci-go-sdk/v65/iot"
	iotv1beta1 "github.com/oracle/oci-service-operator/api/iot/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type IotDomainRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *iotv1beta1.IotDomain, string) (any, error)
	BuildUpdateBody func(context.Context, *iotv1beta1.IotDomain, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*iotv1beta1.IotDomain]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*iotv1beta1.IotDomain]
	StatusHooks         generatedruntime.StatusHooks[*iotv1beta1.IotDomain]
	ParityHooks         generatedruntime.ParityHooks[*iotv1beta1.IotDomain]
	Async               generatedruntime.AsyncHooks[*iotv1beta1.IotDomain]
	DeleteHooks         generatedruntime.DeleteHooks[*iotv1beta1.IotDomain]
	Create              runtimeOperationHooks[iotsdk.CreateIotDomainRequest, iotsdk.CreateIotDomainResponse]
	Get                 runtimeOperationHooks[iotsdk.GetIotDomainRequest, iotsdk.GetIotDomainResponse]
	List                runtimeOperationHooks[iotsdk.ListIotDomainsRequest, iotsdk.ListIotDomainsResponse]
	Update              runtimeOperationHooks[iotsdk.UpdateIotDomainRequest, iotsdk.UpdateIotDomainResponse]
	Delete              runtimeOperationHooks[iotsdk.DeleteIotDomainRequest, iotsdk.DeleteIotDomainResponse]
	WrapGeneratedClient []func(IotDomainServiceClient) IotDomainServiceClient
}

type IotDomainRuntimeHooksMutator func(*IotDomainServiceManager, *IotDomainRuntimeHooks)

var iotdomainRuntimeHooksMutators []IotDomainRuntimeHooksMutator

func registerIotDomainRuntimeHooksMutator(mutator IotDomainRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	iotdomainRuntimeHooksMutators = append(iotdomainRuntimeHooksMutators, mutator)
}
func newIotDomainDefaultRuntimeHooks(sdkClient iotsdk.IotClient) IotDomainRuntimeHooks {
	return IotDomainRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*iotv1beta1.IotDomain]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*iotv1beta1.IotDomain]{},
		StatusHooks:     generatedruntime.StatusHooks[*iotv1beta1.IotDomain]{},
		ParityHooks:     generatedruntime.ParityHooks[*iotv1beta1.IotDomain]{},
		Async:           generatedruntime.AsyncHooks[*iotv1beta1.IotDomain]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*iotv1beta1.IotDomain]{},
		Create: runtimeOperationHooks[iotsdk.CreateIotDomainRequest, iotsdk.CreateIotDomainResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateIotDomainDetails", RequestName: "CreateIotDomainDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request iotsdk.CreateIotDomainRequest) (iotsdk.CreateIotDomainResponse, error) {
				return sdkClient.CreateIotDomain(ctx, request)
			},
		},
		Get: runtimeOperationHooks[iotsdk.GetIotDomainRequest, iotsdk.GetIotDomainResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "IotDomainId", RequestName: "iotDomainId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request iotsdk.GetIotDomainRequest) (iotsdk.GetIotDomainResponse, error) {
				return sdkClient.GetIotDomain(ctx, request)
			},
		},
		List: runtimeOperationHooks[iotsdk.ListIotDomainsRequest, iotsdk.ListIotDomainsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "IotDomainGroupId", RequestName: "iotDomainGroupId", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request iotsdk.ListIotDomainsRequest) (iotsdk.ListIotDomainsResponse, error) {
				return sdkClient.ListIotDomains(ctx, request)
			},
		},
		Update: runtimeOperationHooks[iotsdk.UpdateIotDomainRequest, iotsdk.UpdateIotDomainResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "IotDomainId", RequestName: "iotDomainId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateIotDomainDetails", RequestName: "UpdateIotDomainDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request iotsdk.UpdateIotDomainRequest) (iotsdk.UpdateIotDomainResponse, error) {
				return sdkClient.UpdateIotDomain(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[iotsdk.DeleteIotDomainRequest, iotsdk.DeleteIotDomainResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "IotDomainId", RequestName: "iotDomainId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request iotsdk.DeleteIotDomainRequest) (iotsdk.DeleteIotDomainResponse, error) {
				return sdkClient.DeleteIotDomain(ctx, request)
			},
		},
		WrapGeneratedClient: []func(IotDomainServiceClient) IotDomainServiceClient{},
	}
}

func newIotDomainRuntimeHooks(manager *IotDomainServiceManager, sdkClient iotsdk.IotClient) IotDomainRuntimeHooks {
	hooks := newIotDomainDefaultRuntimeHooks(sdkClient)
	for _, mutator := range iotdomainRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildIotDomainGeneratedRuntimeConfig(
	manager *IotDomainServiceManager,
	hooks IotDomainRuntimeHooks,
) generatedruntime.Config[*iotv1beta1.IotDomain] {
	return generatedruntime.Config[*iotv1beta1.IotDomain]{
		Kind:            "IotDomain",
		SDKName:         "IotDomain",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &iotsdk.CreateIotDomainRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*iotsdk.CreateIotDomainRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &iotsdk.GetIotDomainRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*iotsdk.GetIotDomainRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &iotsdk.ListIotDomainsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*iotsdk.ListIotDomainsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &iotsdk.UpdateIotDomainRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*iotsdk.UpdateIotDomainRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &iotsdk.DeleteIotDomainRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*iotsdk.DeleteIotDomainRequest))
			},
		},
	}
}

func wrapIotDomainGeneratedClient(
	hooks IotDomainRuntimeHooks,
	delegate IotDomainServiceClient,
) IotDomainServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
