/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package privateapplication

import (
	"context"
	"fmt"

	servicecatalogsdk "github.com/oracle/oci-go-sdk/v65/servicecatalog"
	servicecatalogv1beta1 "github.com/oracle/oci-service-operator/api/servicecatalog/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// PrivateApplicationServiceClient is the handwritten extension seam for PrivateApplication runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*PrivateApplicationServiceManager).WithClient.
type PrivateApplicationServiceClient interface {
	CreateOrUpdate(context.Context, *servicecatalogv1beta1.PrivateApplication, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *servicecatalogv1beta1.PrivateApplication) (bool, error)
}

type defaultPrivateApplicationServiceClient struct {
	generatedruntime.ServiceClient[*servicecatalogv1beta1.PrivateApplication]
}

var _ PrivateApplicationServiceClient = defaultPrivateApplicationServiceClient{}

var newPrivateApplicationServiceClient = func(manager *PrivateApplicationServiceManager) PrivateApplicationServiceClient {
	sdkClient, err := servicecatalogsdk.NewServiceCatalogClientWithConfigurationProvider(manager.Provider)
	hooks := newPrivateApplicationRuntimeHooks(manager, sdkClient)
	config := buildPrivateApplicationGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize PrivateApplication OCI client: %w", err)
	}
	delegate := defaultPrivateApplicationServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*servicecatalogv1beta1.PrivateApplication](config),
	}
	return wrapPrivateApplicationGeneratedClient(hooks, delegate)
}
