/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package trigger

import (
	"context"
	"fmt"

	devopssdk "github.com/oracle/oci-go-sdk/v65/devops"
	devopsv1beta1 "github.com/oracle/oci-service-operator/api/devops/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// TriggerServiceClient is the handwritten extension seam for Trigger runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*TriggerServiceManager).WithClient.
type TriggerServiceClient interface {
	CreateOrUpdate(context.Context, *devopsv1beta1.Trigger, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *devopsv1beta1.Trigger) (bool, error)
}

type defaultTriggerServiceClient struct {
	generatedruntime.ServiceClient[*devopsv1beta1.Trigger]
}

var _ TriggerServiceClient = defaultTriggerServiceClient{}

var newTriggerServiceClient = func(manager *TriggerServiceManager) TriggerServiceClient {
	sdkClient, err := devopssdk.NewDevopsClientWithConfigurationProvider(manager.Provider)
	hooks := newTriggerRuntimeHooks(manager, sdkClient)
	config := buildTriggerGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Trigger OCI client: %w", err)
	}
	delegate := defaultTriggerServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*devopsv1beta1.Trigger](config),
	}
	return wrapTriggerGeneratedClient(hooks, delegate)
}
