/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IdpGroupMappingSpec defines the desired state of IdpGroupMapping.
type IdpGroupMappingSpec struct {
	Id             shared.OCID `json:"id,omitempty"`
	CompartmentId  shared.OCID `json:"compartmentId,omitempty"`
	IdpGroupName   string      `json:"idpGroupName,omitempty"`
	GroupId        string      `json:"groupId,omitempty"`
	IdpId          string      `json:"idpId,omitempty"`
	TimeCreated    string      `json:"timeCreated,omitempty"`
	LifecycleState string      `json:"lifecycleState,omitempty"`
	InactiveStatus int64       `json:"inactiveStatus,omitempty"`
}

// IdpGroupMappingStatus defines the observed state of IdpGroupMapping.
type IdpGroupMappingStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the IdpGroupMapping",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the IdpGroupMapping",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// IdpGroupMapping is the Schema for the idpgroupmappings API.
type IdpGroupMapping struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   IdpGroupMappingSpec   `json:"spec,omitempty"`
	Status IdpGroupMappingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// IdpGroupMappingList contains a list of IdpGroupMapping.
type IdpGroupMappingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IdpGroupMapping `json:"items"`
}

func init() {
	SchemeBuilder.Register(&IdpGroupMapping{}, &IdpGroupMappingList{})
}
