/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RegionSubscriptionSpec defines the desired state of RegionSubscription.
type RegionSubscriptionSpec struct {
	Id            shared.OCID `json:"id,omitempty"`
	CompartmentId shared.OCID `json:"compartmentId,omitempty"`
	RegionKey     string      `json:"regionKey,omitempty"`
	RegionName    string      `json:"regionName,omitempty"`
	Status        string      `json:"status,omitempty"`
	IsHomeRegion  bool        `json:"isHomeRegion,omitempty"`
}

// RegionSubscriptionStatus defines the observed state of RegionSubscription.
type RegionSubscriptionStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the RegionSubscription",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the RegionSubscription",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// RegionSubscription is the Schema for the regionsubscriptions API.
type RegionSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RegionSubscriptionSpec   `json:"spec,omitempty"`
	Status RegionSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// RegionSubscriptionList contains a list of RegionSubscription.
type RegionSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegionSubscription `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RegionSubscription{}, &RegionSubscriptionList{})
}
