/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RegionSubscriptionSpec defines the desired state of RegionSubscription.
type RegionSubscriptionSpec struct {
	// The regions's key. See Regions and Availability Domains (https://docs.cloud.oracle.com/Content/General/Concepts/regions.htm) for
	// the full list of supported 3-letter region codes.
	// Example: `PHX`
	// +kubebuilder:validation:Required
	RegionKey string `json:"regionKey"`
}

// RegionSubscriptionStatus defines the observed state of RegionSubscription.
type RegionSubscriptionStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The region's key. See Regions and Availability Domains (https://docs.cloud.oracle.com/Content/General/Concepts/regions.htm)
	// for the full list of supported 3-letter region codes.
	// Example: `PHX`
	RegionKey string `json:"regionKey,omitempty"`
	// The region's name. See Regions and Availability Domains (https://docs.cloud.oracle.com/Content/General/Concepts/regions.htm)
	// for the full list of supported region names.
	// Example: `us-phoenix-1`
	RegionName string `json:"regionName,omitempty"`
	// The region subscription status.
	// This uses a distinct JSON name so it can coexist with the OSOK status envelope.
	Status string `json:"sdkStatus,omitempty"`
	// Indicates if the region is the home region or not.
	IsHomeRegion bool `json:"isHomeRegion,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the RegionSubscription",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the RegionSubscription",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// RegionSubscription is the Schema for the regionsubscriptions API.
type RegionSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RegionSubscriptionSpec   `json:"spec,omitempty"`
	Status RegionSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// RegionSubscriptionList contains a list of RegionSubscription.
type RegionSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegionSubscription `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RegionSubscription{}, &RegionSubscriptionList{})
}
