/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TaggingWorkRequestLogSpec defines the desired state of TaggingWorkRequestLog.
type TaggingWorkRequestLogSpec struct {
}

// TaggingWorkRequestLogStatus defines the observed state of TaggingWorkRequestLog.
type TaggingWorkRequestLogStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// A human-readable error string.
	Message string `json:"message,omitempty"`
	// Date and time the log was written, in the format defined by RFC3339.
	// Example: `2016-08-25T21:10:29.600Z`
	Timestamp string `json:"timestamp,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the TaggingWorkRequestLog",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the TaggingWorkRequestLog",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// TaggingWorkRequestLog is the Schema for the taggingworkrequestlogs API.
type TaggingWorkRequestLog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TaggingWorkRequestLogSpec   `json:"spec,omitempty"`
	Status TaggingWorkRequestLogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// TaggingWorkRequestLogList contains a list of TaggingWorkRequestLog.
type TaggingWorkRequestLogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TaggingWorkRequestLog `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TaggingWorkRequestLog{}, &TaggingWorkRequestLogList{})
}
