/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CustomTableSpec defines the desired state of CustomTable.
type CustomTableSpec struct {
	// The compartment OCID.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The associated saved report OCID.
	// +kubebuilder:validation:Required
	SavedReportId string `json:"savedReportId"`
	// +kubebuilder:validation:Required
	SavedCustomTable CustomTableSavedCustomTable `json:"savedCustomTable"`
}

// CustomTableSavedCustomTableGroupByTag defines nested fields for CustomTable.SavedCustomTable.GroupByTag.
type CustomTableSavedCustomTableGroupByTag struct {
	// The tag namespace.
	// +kubebuilder:validation:Optional
	Namespace string `json:"namespace,omitempty"`
	// The tag key.
	// +kubebuilder:validation:Optional
	Key string `json:"key,omitempty"`
	// The tag value.
	// +kubebuilder:validation:Optional
	Value string `json:"value,omitempty"`
}

// CustomTableSavedCustomTable defines nested fields for CustomTable.SavedCustomTable.
type CustomTableSavedCustomTable struct {
	// The name of the custom table.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// The row groupBy key list.
	// example:
	//   `["tagNamespace", "tagKey", "tagValue", "service", "skuName", "skuPartNumber", "unit",
	//     "compartmentName", "compartmentPath", "compartmentId", "platform", "region", "logicalAd",
	//     "resourceId", "tenantId", "tenantName"]`
	// +kubebuilder:validation:Optional
	RowGroupBy []string `json:"rowGroupBy,omitempty"`
	// The column groupBy key list.
	// example:
	//   `["tagNamespace", "tagKey", "tagValue", "service", "skuName", "skuPartNumber", "unit",
	//     "compartmentName", "compartmentPath", "compartmentId", "platform", "region", "logicalAd",
	//     "resourceId", "tenantId", "tenantName"]`
	// +kubebuilder:validation:Optional
	ColumnGroupBy []string `json:"columnGroupBy,omitempty"`
	// GroupBy a specific tagKey. Provide the tagNamespace and tagKey in the tag object. Only one tag in the list is supported.
	// For example:
	//   `[{"namespace":"oracle", "key":"createdBy"]`
	// +kubebuilder:validation:Optional
	GroupByTag []CustomTableSavedCustomTableGroupByTag `json:"groupByTag,omitempty"`
	// The compartment depth level.
	// +kubebuilder:validation:Optional
	CompartmentDepth float32 `json:"compartmentDepth,omitempty"`
	// The version of the custom table.
	// +kubebuilder:validation:Optional
	Version float32 `json:"version,omitempty"`
}

// CustomTableStatus defines the observed state of CustomTable.
type CustomTableStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The custom table OCID.
	Id string `json:"id,omitempty"`
	// The custom table associated saved report OCID.
	SavedReportId string `json:"savedReportId,omitempty"`
	// The custom table compartment OCID.
	CompartmentId    string                      `json:"compartmentId,omitempty"`
	SavedCustomTable CustomTableSavedCustomTable `json:"savedCustomTable,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the CustomTable",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the CustomTable",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// CustomTable is the Schema for the customtables API.
type CustomTable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CustomTableSpec   `json:"spec,omitempty"`
	Status CustomTableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// CustomTableList contains a list of CustomTable.
type CustomTableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomTable `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CustomTable{}, &CustomTableList{})
}
