/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IngestTimeRuleSpec defines the desired state of IngestTimeRule.
type IngestTimeRuleSpec struct {
	// Compartment Identifier OCID  (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The ingest time rule display name.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// +kubebuilder:validation:Required
	Conditions IngestTimeRuleConditions `json:"conditions"`
	// The action(s) to be performed if the ingest time rule condition(s) are satisfied.
	// +kubebuilder:validation:Required
	Actions []IngestTimeRuleAction `json:"actions"`
	// Description for this resource.
	// +kubebuilder:validation:Optional
	Description string `json:"description,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The log analytics entity OCID. This ID is a reference used by log analytics features and it represents
	// a resource that is provisioned and managed by the customer on their premises or on the cloud.
	// +kubebuilder:validation:Required
	Id string `json:"id"`
	// The date and time the resource was created, in the format defined by RFC3339.
	// +kubebuilder:validation:Optional
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the resource was last updated, in the format defined by RFC3339.
	// +kubebuilder:validation:Optional
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The current state of the ingest time rule.
	// +kubebuilder:validation:Optional
	LifecycleState string `json:"lifecycleState,omitempty"`
	// A flag indicating whether or not the ingest time rule is enabled.
	// +kubebuilder:validation:Optional
	IsEnabled bool `json:"isEnabled,omitempty"`
}

// IngestTimeRuleConditionsAdditionalCondition defines nested fields for IngestTimeRule.Conditions.AdditionalCondition.
type IngestTimeRuleConditionsAdditionalCondition struct {
	// The additional field name to be evaluated.
	// +kubebuilder:validation:Required
	ConditionField string `json:"conditionField"`
	// The operator to be used for evaluating the additional field.
	// +kubebuilder:validation:Required
	ConditionOperator string `json:"conditionOperator"`
	// The additional field value to be evaluated.
	// +kubebuilder:validation:Required
	ConditionValue string `json:"conditionValue"`
}

// IngestTimeRuleConditions defines nested fields for IngestTimeRule.Conditions.
type IngestTimeRuleConditions struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	Kind string `json:"kind,omitempty"`
	// The field name to be evaluated.
	// +kubebuilder:validation:Optional
	FieldName string `json:"fieldName,omitempty"`
	// The field value to be evaluated.
	// +kubebuilder:validation:Optional
	FieldValue string `json:"fieldValue,omitempty"`
	// Optional additional condition(s) to be evaluated.
	// +kubebuilder:validation:Optional
	AdditionalConditions []IngestTimeRuleConditionsAdditionalCondition `json:"additionalConditions,omitempty"`
	// The operator to be used for evaluating the field.
	// +kubebuilder:validation:Optional
	FieldOperator string `json:"fieldOperator,omitempty"`
}

// IngestTimeRuleAction defines nested fields for IngestTimeRule.Action.
type IngestTimeRuleAction struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	Type string `json:"type,omitempty"`
	// The compartment OCID (/iaas/Content/General/Concepts/identifiers.htm) of the extracted metric.
	// +kubebuilder:validation:Optional
	CompartmentId string `json:"compartmentId,omitempty"`
	// The namespace of the extracted metric.
	// A valid value starts with an alphabetical character and includes only
	// alphanumeric characters and underscores (_).
	// +kubebuilder:validation:Optional
	Namespace string `json:"namespace,omitempty"`
	// The metric name of the extracted metric.
	// A valid value starts with an alphabetical character and includes only
	// alphanumeric characters, periods (.), underscores (_), hyphens (-), and dollar signs ($).
	// +kubebuilder:validation:Optional
	MetricName string `json:"metricName,omitempty"`
	// The resourceGroup of the extracted metric.
	// A valid value starts with an alphabetical character and includes only
	// alphanumeric characters, periods (.), underscores (_), hyphens (-), and dollar signs ($).
	// +kubebuilder:validation:Optional
	ResourceGroup string `json:"resourceGroup,omitempty"`
	// Additional dimensions to publish for the extracted metric.
	// A valid list contains the source field names whose values are to be published as dimensions.
	// The source name itself is specified using a special macro SOURCE_NAME
	// +kubebuilder:validation:Optional
	Dimensions []string `json:"dimensions,omitempty"`
}

// IngestTimeRuleStatus defines the observed state of IngestTimeRule.
type IngestTimeRuleStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The log analytics entity OCID. This ID is a reference used by log analytics features and it represents
	// a resource that is provisioned and managed by the customer on their premises or on the cloud.
	Id string `json:"id,omitempty"`
	// Compartment Identifier OCID  (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	CompartmentId string `json:"compartmentId,omitempty"`
	// The ingest time rule display name.
	DisplayName string `json:"displayName,omitempty"`
	// Description for this resource.
	Description string `json:"description,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The date and time the resource was created, in the format defined by RFC3339.
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the resource was last updated, in the format defined by RFC3339.
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The current state of the ingest time rule.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// A flag indicating whether or not the ingest time rule is enabled.
	IsEnabled  bool                     `json:"isEnabled,omitempty"`
	Conditions IngestTimeRuleConditions `json:"conditions,omitempty"`
	// The action(s) to be performed if the ingest time rule condition(s) are satisfied.
	Actions []IngestTimeRuleAction `json:"actions,omitempty"`
	// The ingest time rule condition kind.
	ConditionKind string `json:"conditionKind,omitempty"`
	// The ingest time rule condition field name.
	FieldName string `json:"fieldName,omitempty"`
	// The ingest time rule condition field value.
	FieldValue string `json:"fieldValue,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the IngestTimeRule",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the IngestTimeRule",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// IngestTimeRule is the Schema for the ingesttimerules API.
type IngestTimeRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   IngestTimeRuleSpec   `json:"spec,omitempty"`
	Status IngestTimeRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// IngestTimeRuleList contains a list of IngestTimeRule.
type IngestTimeRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IngestTimeRule `json:"items"`
}

func init() {
	SchemeBuilder.Register(&IngestTimeRule{}, &IngestTimeRuleList{})
}
