/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package disapplicationdetaileddescription

import (
	"context"
	"fmt"

	dataintegrationsdk "github.com/oracle/oci-go-sdk/v65/dataintegration"
	dataintegrationv1beta1 "github.com/oracle/oci-service-operator/api/dataintegration/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DisApplicationDetailedDescriptionServiceClient is the handwritten extension seam for DisApplicationDetailedDescription runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DisApplicationDetailedDescriptionServiceManager).WithClient.
type DisApplicationDetailedDescriptionServiceClient interface {
	CreateOrUpdate(context.Context, *dataintegrationv1beta1.DisApplicationDetailedDescription, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *dataintegrationv1beta1.DisApplicationDetailedDescription) (bool, error)
}

type defaultDisApplicationDetailedDescriptionServiceClient struct {
	generatedruntime.ServiceClient[*dataintegrationv1beta1.DisApplicationDetailedDescription]
}

var _ DisApplicationDetailedDescriptionServiceClient = defaultDisApplicationDetailedDescriptionServiceClient{}

var newDisApplicationDetailedDescriptionServiceClient = func(manager *DisApplicationDetailedDescriptionServiceManager) DisApplicationDetailedDescriptionServiceClient {
	sdkClient, err := dataintegrationsdk.NewDataIntegrationClientWithConfigurationProvider(manager.Provider)
	hooks := newDisApplicationDetailedDescriptionRuntimeHooks(manager, sdkClient)
	config := buildDisApplicationDetailedDescriptionGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DisApplicationDetailedDescription OCI client: %w", err)
	}
	delegate := defaultDisApplicationDetailedDescriptionServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*dataintegrationv1beta1.DisApplicationDetailedDescription](config),
	}
	return wrapDisApplicationDetailedDescriptionGeneratedClient(hooks, delegate)
}
