/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package domainrecord

import (
	"context"
	"fmt"

	dnssdk "github.com/oracle/oci-go-sdk/v65/dns"
	dnsv1beta1 "github.com/oracle/oci-service-operator/api/dns/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DomainRecordServiceClient is the handwritten extension seam for DomainRecord runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*DomainRecordServiceManager).WithClient.
type DomainRecordServiceClient interface {
	CreateOrUpdate(context.Context, *dnsv1beta1.DomainRecord, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *dnsv1beta1.DomainRecord) (bool, error)
}

type defaultDomainRecordServiceClient struct {
	generatedruntime.ServiceClient[*dnsv1beta1.DomainRecord]
}

var _ DomainRecordServiceClient = defaultDomainRecordServiceClient{}

var newDomainRecordServiceClient = func(manager *DomainRecordServiceManager) DomainRecordServiceClient {
	sdkClient, err := dnssdk.NewDnsClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*dnsv1beta1.DomainRecord]{
		Kind:    "DomainRecord",
		SDKName: "DomainRecord",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &dnssdk.GetDomainRecordsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetDomainRecords(ctx, *request.(*dnssdk.GetDomainRecordsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &dnssdk.UpdateDomainRecordsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateDomainRecords(ctx, *request.(*dnssdk.UpdateDomainRecordsRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &dnssdk.DeleteDomainRecordsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteDomainRecords(ctx, *request.(*dnssdk.DeleteDomainRecordsRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize DomainRecord OCI client: %w", err)
	}
	return defaultDomainRecordServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*dnsv1beta1.DomainRecord](config),
	}
}
