#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: demandsignal.oracle.com/v1beta1
kind: OccDemandSignal
metadata:
  name: occdemandsignal-sample
spec: {}
