#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

## Append samples you want in your CSV to this file as resources ##
resources:
- database_v1beta1_autonomousdatabases.yaml
- streaming_v1beta1_stream.yaml
- mysql_v1beta1_mysqldbsystem.yaml
- artifacts_v1beta1_containerconfiguration.yaml
- artifacts_v1beta1_containerimage.yaml
- artifacts_v1beta1_containerimagesignature.yaml
- artifacts_v1beta1_containerrepository.yaml
- artifacts_v1beta1_genericartifact.yaml
- artifacts_v1beta1_genericartifactbypath.yaml
- artifacts_v1beta1_repository.yaml
- nosql_v1beta1_index.yaml
- nosql_v1beta1_replica.yaml
- nosql_v1beta1_row.yaml
- nosql_v1beta1_table.yaml
- nosql_v1beta1_tableusage.yaml
- nosql_v1beta1_workrequest.yaml
- nosql_v1beta1_workrequesterror.yaml
- nosql_v1beta1_workrequestlog.yaml
- objectstorage_v1beta1_bucket.yaml
- objectstorage_v1beta1_multipartupload.yaml
- objectstorage_v1beta1_multipartuploadpart.yaml
- objectstorage_v1beta1_namespace.yaml
- objectstorage_v1beta1_namespacemetadata.yaml
- objectstorage_v1beta1_object.yaml
- objectstorage_v1beta1_objectlifecyclepolicy.yaml
- objectstorage_v1beta1_objectstoragetier.yaml
- objectstorage_v1beta1_objectversion.yaml
- objectstorage_v1beta1_preauthenticatedrequest.yaml
- objectstorage_v1beta1_replicationpolicy.yaml
- objectstorage_v1beta1_replicationsource.yaml
- objectstorage_v1beta1_retentionrule.yaml
- objectstorage_v1beta1_workrequest.yaml
- objectstorage_v1beta1_workrequesterror.yaml
- objectstorage_v1beta1_workrequestlog.yaml
- psql_v1beta1_backup.yaml
- psql_v1beta1_configuration.yaml
- psql_v1beta1_connectiondetail.yaml
- psql_v1beta1_dbsystem.yaml
- psql_v1beta1_dbsystemdbinstance.yaml
- psql_v1beta1_defaultconfiguration.yaml
- psql_v1beta1_primarydbinstance.yaml
- psql_v1beta1_shape.yaml
- psql_v1beta1_workrequest.yaml
- psql_v1beta1_workrequesterror.yaml
- psql_v1beta1_workrequestlog.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
