#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

## Append samples you want in your CSV to this file as resources ##
resources:
- streaming_v1beta1_stream.yaml
- artifacts_v1beta1_containerconfiguration.yaml
- artifacts_v1beta1_containerimage.yaml
- artifacts_v1beta1_containerimagesignature.yaml
- artifacts_v1beta1_containerrepository.yaml
- artifacts_v1beta1_genericartifact.yaml
- artifacts_v1beta1_genericartifactbypath.yaml
- artifacts_v1beta1_repository.yaml
- nosql_v1beta1_index.yaml
- nosql_v1beta1_replica.yaml
- nosql_v1beta1_row.yaml
- nosql_v1beta1_table.yaml
- nosql_v1beta1_tableusage.yaml
- nosql_v1beta1_workrequest.yaml
- nosql_v1beta1_workrequesterror.yaml
- nosql_v1beta1_workrequestlog.yaml
- objectstorage_v1beta1_bucket.yaml
- objectstorage_v1beta1_multipartupload.yaml
- objectstorage_v1beta1_multipartuploadpart.yaml
- objectstorage_v1beta1_namespace.yaml
- objectstorage_v1beta1_namespacemetadata.yaml
- objectstorage_v1beta1_object.yaml
- objectstorage_v1beta1_objectlifecyclepolicy.yaml
- objectstorage_v1beta1_objectstoragetier.yaml
- objectstorage_v1beta1_objectversion.yaml
- objectstorage_v1beta1_preauthenticatedrequest.yaml
- objectstorage_v1beta1_replicationpolicy.yaml
- objectstorage_v1beta1_replicationsource.yaml
- objectstorage_v1beta1_retentionrule.yaml
- objectstorage_v1beta1_workrequest.yaml
- objectstorage_v1beta1_workrequesterror.yaml
- objectstorage_v1beta1_workrequestlog.yaml
- psql_v1beta1_backup.yaml
- psql_v1beta1_configuration.yaml
- psql_v1beta1_connectiondetail.yaml
- psql_v1beta1_dbsystem.yaml
- psql_v1beta1_dbsystemdbinstance.yaml
- psql_v1beta1_defaultconfiguration.yaml
- psql_v1beta1_primarydbinstance.yaml
- psql_v1beta1_shape.yaml
- psql_v1beta1_workrequest.yaml
- psql_v1beta1_workrequesterror.yaml
- psql_v1beta1_workrequestlog.yaml
- containerengine_v1beta1_addon.yaml
- containerengine_v1beta1_addonoption.yaml
- containerengine_v1beta1_cluster.yaml
- containerengine_v1beta1_clusterendpointconfig.yaml
- containerengine_v1beta1_clustermigratetonativevcnstatus.yaml
- containerengine_v1beta1_clusteroption.yaml
- containerengine_v1beta1_credentialrotationstatus.yaml
- containerengine_v1beta1_kubeconfig.yaml
- containerengine_v1beta1_node.yaml
- containerengine_v1beta1_nodepool.yaml
- containerengine_v1beta1_nodepooloption.yaml
- containerengine_v1beta1_podshape.yaml
- containerengine_v1beta1_virtualnode.yaml
- containerengine_v1beta1_virtualnodepool.yaml
- containerengine_v1beta1_workloadmapping.yaml
- containerengine_v1beta1_workrequest.yaml
- containerengine_v1beta1_workrequesterror.yaml
- containerengine_v1beta1_workrequestlog.yaml
- core_v1beta1_alldrgattachment.yaml
- core_v1beta1_allowedikeipsecparameter.yaml
- core_v1beta1_allowedpeerregionsforremotepeering.yaml
- core_v1beta1_appcataloglisting.yaml
- core_v1beta1_appcataloglistingagreement.yaml
- core_v1beta1_appcataloglistingresourceversion.yaml
- core_v1beta1_appcatalogsubscription.yaml
- core_v1beta1_blockvolumereplica.yaml
- core_v1beta1_bootvolume.yaml
- core_v1beta1_bootvolumeattachment.yaml
- core_v1beta1_bootvolumebackup.yaml
- core_v1beta1_bootvolumekmskey.yaml
- core_v1beta1_bootvolumereplica.yaml
- core_v1beta1_byoipallocatedrange.yaml
- core_v1beta1_byoiprange.yaml
- core_v1beta1_capturefilter.yaml
- core_v1beta1_clusternetwork.yaml
- core_v1beta1_clusternetworkinstance.yaml
- core_v1beta1_computecapacityreport.yaml
- core_v1beta1_computecapacityreservation.yaml
- core_v1beta1_computecapacityreservationinstance.yaml
- core_v1beta1_computecapacityreservationinstanceshape.yaml
- core_v1beta1_computecapacitytopology.yaml
- core_v1beta1_computecapacitytopologycomputebaremetalhost.yaml
- core_v1beta1_computecapacitytopologycomputehpcisland.yaml
- core_v1beta1_computecapacitytopologycomputenetworkblock.yaml
- core_v1beta1_computecluster.yaml
- core_v1beta1_computeglobalimagecapabilityschema.yaml
- core_v1beta1_computeglobalimagecapabilityschemaversion.yaml
- core_v1beta1_computeimagecapabilityschema.yaml
- core_v1beta1_consolehistory.yaml
- core_v1beta1_consolehistorycontent.yaml
- core_v1beta1_cpe.yaml
- core_v1beta1_cpedeviceconfigcontent.yaml
- core_v1beta1_cpedeviceshape.yaml
- core_v1beta1_crossconnect.yaml
- core_v1beta1_crossconnectgroup.yaml
- core_v1beta1_crossconnectletterofauthority.yaml
- core_v1beta1_crossconnectlocation.yaml
- core_v1beta1_crossconnectmapping.yaml
- core_v1beta1_crossconnectportspeedshape.yaml
- core_v1beta1_crossconnectstatus.yaml
- core_v1beta1_dedicatedvmhost.yaml
- core_v1beta1_dedicatedvmhostinstance.yaml
- core_v1beta1_dedicatedvmhostinstanceshape.yaml
- core_v1beta1_dedicatedvmhostshape.yaml
- core_v1beta1_dhcpoption.yaml
- core_v1beta1_drg.yaml
- core_v1beta1_drgattachment.yaml
- core_v1beta1_drgredundancystatus.yaml
- core_v1beta1_drgroutedistribution.yaml
- core_v1beta1_drgroutedistributionstatement.yaml
- core_v1beta1_drgrouterule.yaml
- core_v1beta1_drgroutetable.yaml
- core_v1beta1_fastconnectproviderservice.yaml
- core_v1beta1_fastconnectproviderservicekey.yaml
- core_v1beta1_fastconnectprovidervirtualcircuitbandwidthshape.yaml
- core_v1beta1_image.yaml
- core_v1beta1_imageshapecompatibilityentry.yaml
- core_v1beta1_instance.yaml
- core_v1beta1_instanceconfiguration.yaml
- core_v1beta1_instanceconsoleconnection.yaml
- core_v1beta1_instancedevice.yaml
- core_v1beta1_instancemaintenancereboot.yaml
- core_v1beta1_instancepool.yaml
- core_v1beta1_instancepoolinstance.yaml
- core_v1beta1_instancepoolloadbalancerattachment.yaml
- core_v1beta1_internetgateway.yaml
- core_v1beta1_ipsecconnection.yaml
- core_v1beta1_ipsecconnectiondeviceconfig.yaml
- core_v1beta1_ipsecconnectiondevicestatus.yaml
- core_v1beta1_ipsecconnectiontunnel.yaml
- core_v1beta1_ipsecconnectiontunnelerror.yaml
- core_v1beta1_ipsecconnectiontunnelroute.yaml
- core_v1beta1_ipsecconnectiontunnelsecurityassociation.yaml
- core_v1beta1_ipsecconnectiontunnelsharedsecret.yaml
- core_v1beta1_ipseccpedeviceconfigcontent.yaml
- core_v1beta1_ipv6.yaml
- core_v1beta1_localpeeringgateway.yaml
- core_v1beta1_measuredbootreport.yaml
- core_v1beta1_natgateway.yaml
- core_v1beta1_networkingtopology.yaml
- core_v1beta1_networksecuritygroup.yaml
- core_v1beta1_networksecuritygroupsecurityrule.yaml
- core_v1beta1_networksecuritygroupvnic.yaml
- core_v1beta1_privateip.yaml
- core_v1beta1_publicip.yaml
- core_v1beta1_publicipbyipaddress.yaml
- core_v1beta1_publicipbyprivateipid.yaml
- core_v1beta1_publicippool.yaml
- core_v1beta1_remotepeeringconnection.yaml
- core_v1beta1_routetable.yaml
- core_v1beta1_securitylist.yaml
- core_v1beta1_service.yaml
- core_v1beta1_servicegateway.yaml
- core_v1beta1_shape.yaml
- core_v1beta1_subnet.yaml
- core_v1beta1_subnettopology.yaml
- core_v1beta1_tunnelcpedeviceconfig.yaml
- core_v1beta1_tunnelcpedeviceconfigcontent.yaml
- core_v1beta1_upgradestatus.yaml
- core_v1beta1_vcn.yaml
- core_v1beta1_vcndnsresolverassociation.yaml
- core_v1beta1_vcntopology.yaml
- core_v1beta1_virtualcircuit.yaml
- core_v1beta1_virtualcircuitassociatedtunnel.yaml
- core_v1beta1_virtualcircuitbandwidthshape.yaml
- core_v1beta1_virtualcircuitpublicprefix.yaml
- core_v1beta1_vlan.yaml
- core_v1beta1_vnic.yaml
- core_v1beta1_vnicattachment.yaml
- core_v1beta1_volume.yaml
- core_v1beta1_volumeattachment.yaml
- core_v1beta1_volumebackup.yaml
- core_v1beta1_volumebackuppolicy.yaml
- core_v1beta1_volumebackuppolicyassetassignment.yaml
- core_v1beta1_volumebackuppolicyassignment.yaml
- core_v1beta1_volumegroup.yaml
- core_v1beta1_volumegroupbackup.yaml
- core_v1beta1_volumegroupreplica.yaml
- core_v1beta1_volumekmskey.yaml
- core_v1beta1_vtap.yaml
- core_v1beta1_windowsinstanceinitialcredential.yaml
- dns_v1beta1_domainrecord.yaml
- dns_v1beta1_resolver.yaml
- dns_v1beta1_resolverendpoint.yaml
- dns_v1beta1_rrset.yaml
- dns_v1beta1_steeringpolicy.yaml
- dns_v1beta1_steeringpolicyattachment.yaml
- dns_v1beta1_tsigkey.yaml
- dns_v1beta1_view.yaml
- dns_v1beta1_zone.yaml
- dns_v1beta1_zonecontent.yaml
- dns_v1beta1_zonefromzonefile.yaml
- dns_v1beta1_zonerecord.yaml
- dns_v1beta1_zonetransferserver.yaml
- loadbalancer_v1beta1_backend.yaml
- loadbalancer_v1beta1_backendhealth.yaml
- loadbalancer_v1beta1_backendset.yaml
- loadbalancer_v1beta1_backendsethealth.yaml
- loadbalancer_v1beta1_certificate.yaml
- loadbalancer_v1beta1_healthchecker.yaml
- loadbalancer_v1beta1_hostname.yaml
- loadbalancer_v1beta1_listener.yaml
- loadbalancer_v1beta1_listenerrule.yaml
- loadbalancer_v1beta1_loadbalancer.yaml
- loadbalancer_v1beta1_loadbalancerhealth.yaml
- loadbalancer_v1beta1_loadbalancershape.yaml
- loadbalancer_v1beta1_networksecuritygroup.yaml
- loadbalancer_v1beta1_pathrouteset.yaml
- loadbalancer_v1beta1_policy.yaml
- loadbalancer_v1beta1_protocol.yaml
- loadbalancer_v1beta1_routingpolicy.yaml
- loadbalancer_v1beta1_ruleset.yaml
- loadbalancer_v1beta1_shape.yaml
- loadbalancer_v1beta1_sslciphersuite.yaml
- loadbalancer_v1beta1_workrequest.yaml
- networkloadbalancer_v1beta1_backend.yaml
- networkloadbalancer_v1beta1_backendhealth.yaml
- networkloadbalancer_v1beta1_backendset.yaml
- networkloadbalancer_v1beta1_backendsethealth.yaml
- networkloadbalancer_v1beta1_healthchecker.yaml
- networkloadbalancer_v1beta1_listener.yaml
- networkloadbalancer_v1beta1_networkloadbalancer.yaml
- networkloadbalancer_v1beta1_networkloadbalancerhealth.yaml
- networkloadbalancer_v1beta1_networkloadbalancerspolicy.yaml
- networkloadbalancer_v1beta1_networkloadbalancersprotocol.yaml
- networkloadbalancer_v1beta1_networksecuritygroup.yaml
- networkloadbalancer_v1beta1_workrequest.yaml
- networkloadbalancer_v1beta1_workrequesterror.yaml
- networkloadbalancer_v1beta1_workrequestlog.yaml
- workrequests_v1beta1_workrequest.yaml
- workrequests_v1beta1_workrequesterror.yaml
- workrequests_v1beta1_workrequestlog.yaml
- certificates_v1beta1_cabundle.yaml
- certificates_v1beta1_certificateauthoritybundle.yaml
- certificates_v1beta1_certificateauthoritybundleversion.yaml
- certificates_v1beta1_certificatebundle.yaml
- certificates_v1beta1_certificatebundleversion.yaml
- certificatesmanagement_v1beta1_association.yaml
- certificatesmanagement_v1beta1_cabundle.yaml
- certificatesmanagement_v1beta1_certificate.yaml
- certificatesmanagement_v1beta1_certificateauthority.yaml
- certificatesmanagement_v1beta1_certificateauthorityversion.yaml
- certificatesmanagement_v1beta1_certificateversion.yaml
- identity_v1beta1_alloweddomainlicensetype.yaml
- identity_v1beta1_apikey.yaml
- identity_v1beta1_authenticationpolicy.yaml
- identity_v1beta1_authtoken.yaml
- identity_v1beta1_availabilitydomain.yaml
- identity_v1beta1_bulkactionresourcetype.yaml
- identity_v1beta1_bulkedittagsresourcetype.yaml
- identity_v1beta1_compartment.yaml
- identity_v1beta1_costtrackingtag.yaml
- identity_v1beta1_customersecretkey.yaml
- identity_v1beta1_dbcredential.yaml
- identity_v1beta1_domain.yaml
- identity_v1beta1_dynamicgroup.yaml
- identity_v1beta1_faultdomain.yaml
- identity_v1beta1_group.yaml
- identity_v1beta1_iamworkrequest.yaml
- identity_v1beta1_iamworkrequesterror.yaml
- identity_v1beta1_iamworkrequestlog.yaml
- identity_v1beta1_identityprovider.yaml
- identity_v1beta1_identityprovidergroup.yaml
- identity_v1beta1_idpgroupmapping.yaml
- identity_v1beta1_mfatotpdevice.yaml
- identity_v1beta1_networksource.yaml
- identity_v1beta1_oauthclientcredential.yaml
- identity_v1beta1_orresetuipassword.yaml
- identity_v1beta1_policy.yaml
- identity_v1beta1_region.yaml
- identity_v1beta1_regionsubscription.yaml
- identity_v1beta1_smtpcredential.yaml
- identity_v1beta1_standardtagnamespace.yaml
- identity_v1beta1_standardtagtemplate.yaml
- identity_v1beta1_swiftpassword.yaml
- identity_v1beta1_tag.yaml
- identity_v1beta1_tagdefault.yaml
- identity_v1beta1_taggingworkrequest.yaml
- identity_v1beta1_taggingworkrequesterror.yaml
- identity_v1beta1_taggingworkrequestlog.yaml
- identity_v1beta1_tagnamespace.yaml
- identity_v1beta1_tenancy.yaml
- identity_v1beta1_user.yaml
- identity_v1beta1_usercapability.yaml
- identity_v1beta1_usergroupmembership.yaml
- identity_v1beta1_userstate.yaml
- identity_v1beta1_useruipasswordinformation.yaml
- identity_v1beta1_workrequest.yaml
- keymanagement_v1beta1_ekmsprivateendpoint.yaml
- keymanagement_v1beta1_hsmcluster.yaml
- keymanagement_v1beta1_hsmpartition.yaml
- keymanagement_v1beta1_key.yaml
- keymanagement_v1beta1_keyversion.yaml
- keymanagement_v1beta1_precousercredential.yaml
- keymanagement_v1beta1_replicationstatus.yaml
- keymanagement_v1beta1_vault.yaml
- keymanagement_v1beta1_vaultreplica.yaml
- keymanagement_v1beta1_vaultusage.yaml
- keymanagement_v1beta1_wrappingkey.yaml
- secrets_v1beta1_secretbundle.yaml
- secrets_v1beta1_secretbundlebyname.yaml
- secrets_v1beta1_secretbundleversion.yaml
- vault_v1beta1_secret.yaml
- vault_v1beta1_secretversion.yaml
- events_v1beta1_rule.yaml
- functions_v1beta1_application.yaml
- functions_v1beta1_function.yaml
- functions_v1beta1_pbflisting.yaml
- functions_v1beta1_pbflistingversion.yaml
- functions_v1beta1_trigger.yaml
- limits_v1beta1_limitdefinition.yaml
- limits_v1beta1_limitvalue.yaml
- limits_v1beta1_quota.yaml
- limits_v1beta1_resourceavailability.yaml
- limits_v1beta1_service.yaml
- logging_v1beta1_log.yaml
- logging_v1beta1_loggroup.yaml
- logging_v1beta1_logsavedsearch.yaml
- logging_v1beta1_service.yaml
- logging_v1beta1_unifiedagentconfiguration.yaml
- logging_v1beta1_workrequest.yaml
- logging_v1beta1_workrequesterror.yaml
- logging_v1beta1_workrequestlog.yaml
- monitoring_v1beta1_alarm.yaml
- monitoring_v1beta1_alarmhistory.yaml
- monitoring_v1beta1_alarmstatus.yaml
- monitoring_v1beta1_alarmsuppression.yaml
- monitoring_v1beta1_metric.yaml
- ons_v1beta1_confirmsubscription.yaml
- ons_v1beta1_subscription.yaml
- ons_v1beta1_topic.yaml
- ons_v1beta1_unsubscription.yaml
- queue_v1beta1_channel.yaml
- queue_v1beta1_message.yaml
- queue_v1beta1_queue.yaml
- queue_v1beta1_stats.yaml
- queue_v1beta1_workrequest.yaml
- queue_v1beta1_workrequesterror.yaml
- queue_v1beta1_workrequestlog.yaml
- database_v1beta1_applicationvip.yaml
- database_v1beta1_autonomouscontainerdatabase.yaml
- database_v1beta1_autonomouscontainerdatabasedataguardassociation.yaml
- database_v1beta1_autonomouscontainerdatabaseresourceusage.yaml
- database_v1beta1_autonomouscontainerdatabaseversion.yaml
- database_v1beta1_autonomousdatabasebackup.yaml
- database_v1beta1_autonomousdatabasecharacterset.yaml
- database_v1beta1_autonomousdatabaseclone.yaml
- database_v1beta1_autonomousdatabasedataguardassociation.yaml
- database_v1beta1_autonomousdatabaserefreshableclone.yaml
- database_v1beta1_autonomousdatabaseregionalwallet.yaml
- database_v1beta1_autonomousdatabasewallet.yaml
- database_v1beta1_autonomousdbpreviewversion.yaml
- database_v1beta1_autonomousdbversion.yaml
- database_v1beta1_autonomousexadatainfrastructure.yaml
- database_v1beta1_autonomousexadatainfrastructureshape.yaml
- database_v1beta1_autonomouspatch.yaml
- database_v1beta1_autonomousvirtualmachine.yaml
- database_v1beta1_autonomousvmcluster.yaml
- database_v1beta1_autonomousvmclusteracdresourceusage.yaml
- database_v1beta1_autonomousvmclusterresourceusage.yaml
- database_v1beta1_backup.yaml
- database_v1beta1_backupdestination.yaml
- database_v1beta1_cloudautonomousvmcluster.yaml
- database_v1beta1_cloudautonomousvmclusteracdresourceusage.yaml
- database_v1beta1_cloudautonomousvmclusterresourceusage.yaml
- database_v1beta1_cloudexadatainfrastructure.yaml
- database_v1beta1_cloudexadatainfrastructureunallocatedresource.yaml
- database_v1beta1_cloudvmcluster.yaml
- database_v1beta1_cloudvmclusteriormconfig.yaml
- database_v1beta1_cloudvmclusterupdate.yaml
- database_v1beta1_cloudvmclusterupdatehistoryentry.yaml
- database_v1beta1_consoleconnection.yaml
- database_v1beta1_consolehistory.yaml
- database_v1beta1_consolehistorycontent.yaml
- database_v1beta1_containerdatabasepatch.yaml
- database_v1beta1_databasesoftwareimage.yaml
- database_v1beta1_databaseupgradehistoryentry.yaml
- database_v1beta1_dataguardassociation.yaml
- database_v1beta1_dbhome.yaml
- database_v1beta1_dbhomepatch.yaml
- database_v1beta1_dbhomepatchhistoryentry.yaml
- database_v1beta1_dbnode.yaml
- database_v1beta1_dbserver.yaml
- database_v1beta1_dbsystem.yaml
- database_v1beta1_dbsystemcomputeperformance.yaml
- database_v1beta1_dbsystempatch.yaml
- database_v1beta1_dbsystempatchhistoryentry.yaml
- database_v1beta1_dbsystemshape.yaml
- database_v1beta1_dbsystemstorageperformance.yaml
- database_v1beta1_dbsystemupgradehistoryentry.yaml
- database_v1beta1_dbversion.yaml
- database_v1beta1_exadatainfrastructure.yaml
- database_v1beta1_exadatainfrastructureocpu.yaml
- database_v1beta1_exadatainfrastructureunallocatedresource.yaml
- database_v1beta1_exadataiormconfig.yaml
- database_v1beta1_externalbackupjob.yaml
- database_v1beta1_externalcontainerdatabase.yaml
- database_v1beta1_externaldatabaseconnector.yaml
- database_v1beta1_externalnoncontainerdatabase.yaml
- database_v1beta1_externalpluggabledatabase.yaml
- database_v1beta1_flexcomponent.yaml
- database_v1beta1_giversion.yaml
- database_v1beta1_infrastructuretargetversion.yaml
- database_v1beta1_keystore.yaml
- database_v1beta1_maintenancerun.yaml
- database_v1beta1_maintenancerunhistory.yaml
- database_v1beta1_oneoffpatch.yaml
- database_v1beta1_pdbconversionhistoryentry.yaml
- database_v1beta1_pluggabledatabase.yaml
- database_v1beta1_systemversion.yaml
- database_v1beta1_vmcluster.yaml
- database_v1beta1_vmclusternetwork.yaml
- database_v1beta1_vmclusterpatch.yaml
- database_v1beta1_vmclusterpatchhistoryentry.yaml
- database_v1beta1_vmclusterupdate.yaml
- database_v1beta1_vmclusterupdatehistoryentry.yaml
- streaming_v1beta1_connectharness.yaml
- streaming_v1beta1_cursor.yaml
- streaming_v1beta1_group.yaml
- streaming_v1beta1_groupcursor.yaml
- streaming_v1beta1_message.yaml
- streaming_v1beta1_streampool.yaml
- mysql_v1beta1_backup.yaml
- mysql_v1beta1_channel.yaml
- mysql_v1beta1_configuration.yaml
- mysql_v1beta1_heatwavecluster.yaml
- mysql_v1beta1_heatwaveclustermemoryestimate.yaml
- mysql_v1beta1_replica.yaml
- mysql_v1beta1_shape.yaml
- mysql_v1beta1_version.yaml
- mysql_v1beta1_workrequest.yaml
- mysql_v1beta1_workrequesterror.yaml
- mysql_v1beta1_workrequestlog.yaml
- database_v1beta1_database.yaml
- database_v1beta1_autonomousdatabase.yaml
- mysql_v1beta1_dbsystem.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
