#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: loadbalancer.oracle.com/v1beta1
kind: Backend
metadata:
  name: backend-sample
spec:
  loadBalancerId: ocid1.loadbalancer.oc1..<unique_ID>
  backendSetName: example_backend_set
  ipAddress: "10.0.0.3"
  port: 8080
  weight: 1
  backup: false
  drain: false
  offline: false
