#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

#
# Replace the OCIDs below before running e2e.
#
apiVersion: visualbuilder.oracle.com/v1beta1
kind: VbInstance
metadata:
  name: vbinstance-sample
spec:
  compartmentId: ocid1.compartment.oc1..exampleuniqueID
  displayName: vbinstance-sample
  nodeCount: 1
  isVisualBuilderEnabled: true
  networkEndpointDetails:
    networkEndpointType: PRIVATE
    subnetId: ocid1.subnet.oc1..exampleuniqueID
    networkSecurityGroupIds:
      - ocid1.nsg.oc1..exampleuniqueID
