/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package stack

import (
	"context"
	"fmt"

	resourcemanagersdk "github.com/oracle/oci-go-sdk/v65/resourcemanager"
	resourcemanagerv1beta1 "github.com/oracle/oci-service-operator/api/resourcemanager/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// StackServiceClient is the handwritten extension seam for Stack runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*StackServiceManager).WithClient.
type StackServiceClient interface {
	CreateOrUpdate(context.Context, *resourcemanagerv1beta1.Stack, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *resourcemanagerv1beta1.Stack) (bool, error)
}

type defaultStackServiceClient struct {
	generatedruntime.ServiceClient[*resourcemanagerv1beta1.Stack]
}

var _ StackServiceClient = defaultStackServiceClient{}

var newStackServiceClient = func(manager *StackServiceManager) StackServiceClient {
	sdkClient, err := resourcemanagersdk.NewResourceManagerClientWithConfigurationProvider(manager.Provider)
	hooks := newStackRuntimeHooks(manager, sdkClient)
	config := buildStackGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Stack OCI client: %w", err)
	}
	delegate := defaultStackServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*resourcemanagerv1beta1.Stack](config),
	}
	return wrapStackGeneratedClient(hooks, delegate)
}
