/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package mappedsecret

import (
	"context"
	"fmt"

	networkfirewallsdk "github.com/oracle/oci-go-sdk/v65/networkfirewall"
	networkfirewallv1beta1 "github.com/oracle/oci-service-operator/api/networkfirewall/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MappedSecretServiceClient is the handwritten extension seam for MappedSecret runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*MappedSecretServiceManager).WithClient.
type MappedSecretServiceClient interface {
	CreateOrUpdate(context.Context, *networkfirewallv1beta1.MappedSecret, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *networkfirewallv1beta1.MappedSecret) (bool, error)
}

type defaultMappedSecretServiceClient struct {
	generatedruntime.ServiceClient[*networkfirewallv1beta1.MappedSecret]
}

var _ MappedSecretServiceClient = defaultMappedSecretServiceClient{}

var newMappedSecretServiceClient = func(manager *MappedSecretServiceManager) MappedSecretServiceClient {
	sdkClient, err := networkfirewallsdk.NewNetworkFirewallClientWithConfigurationProvider(manager.Provider)
	hooks := newMappedSecretRuntimeHooks(manager, sdkClient)
	config := buildMappedSecretGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize MappedSecret OCI client: %w", err)
	}
	delegate := defaultMappedSecretServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*networkfirewallv1beta1.MappedSecret](config),
	}
	return wrapMappedSecretGeneratedClient(hooks, delegate)
}
