/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package recovery

import (
	"context"

	recoveryv1beta1 "github.com/oracle/oci-service-operator/api/recovery/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ProtectionPolicyReconciler reconciles a ProtectionPolicy object.
type ProtectionPolicyReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=recovery.oracle.com,resources=protectionpolicies,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=recovery.oracle.com,resources=protectionpolicies/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=recovery.oracle.com,resources=protectionpolicies/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *ProtectionPolicyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	protectionPolicy := &recoveryv1beta1.ProtectionPolicy{}
	return r.Reconciler.Reconcile(ctx, req, protectionPolicy)
}

// SetupWithManager sets up the controller with the Manager.
func (r *ProtectionPolicyReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&recoveryv1beta1.ProtectionPolicy{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
