/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package networkaddresslist

import (
	"context"
	"fmt"

	wafsdk "github.com/oracle/oci-go-sdk/v65/waf"
	wafv1beta1 "github.com/oracle/oci-service-operator/api/waf/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// NetworkAddressListServiceClient is the handwritten extension seam for NetworkAddressList runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*NetworkAddressListServiceManager).WithClient.
type NetworkAddressListServiceClient interface {
	CreateOrUpdate(context.Context, *wafv1beta1.NetworkAddressList, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *wafv1beta1.NetworkAddressList) (bool, error)
}

type defaultNetworkAddressListServiceClient struct {
	generatedruntime.ServiceClient[*wafv1beta1.NetworkAddressList]
}

var _ NetworkAddressListServiceClient = defaultNetworkAddressListServiceClient{}

var newNetworkAddressListServiceClient = func(manager *NetworkAddressListServiceManager) NetworkAddressListServiceClient {
	sdkClient, err := wafsdk.NewWafClientWithConfigurationProvider(manager.Provider)
	hooks := newNetworkAddressListRuntimeHooks(manager, sdkClient)
	config := buildNetworkAddressListGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize NetworkAddressList OCI client: %w", err)
	}
	delegate := defaultNetworkAddressListServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*wafv1beta1.NetworkAddressList](config),
	}
	return wrapNetworkAddressListGeneratedClient(hooks, delegate)
}
