/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HostnameSpec defines the desired state of Hostname.
type HostnameSpec struct {
	Id            shared.OCID `json:"id,omitempty"`
	CompartmentId shared.OCID `json:"compartmentId,omitempty"`
	Name          string      `json:"name,omitempty"`
	Hostname      string      `json:"hostname,omitempty"`
}

// HostnameStatus defines the observed state of Hostname.
type HostnameStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Name",type="string",JSONPath=".spec.name",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the Hostname",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the Hostname",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// Hostname is the Schema for the hostnames API.
type Hostname struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   HostnameSpec   `json:"spec,omitempty"`
	Status HostnameStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// HostnameList contains a list of Hostname.
type HostnameList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Hostname `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Hostname{}, &HostnameList{})
}
