---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - applicationvips
  - autonomouscontainerdatabasedataguardassociations
  - autonomouscontainerdatabaseresourceusages
  - autonomouscontainerdatabases
  - autonomouscontainerdatabaseversions
  - autonomousdatabasebackups
  - autonomousdatabasecharactersets
  - autonomousdatabaseclones
  - autonomousdatabasedataguardassociations
  - autonomousdatabaserefreshableclones
  - autonomousdatabaseregionalwallets
  - autonomousdatabases
  - autonomousdatabasewallets
  - autonomousdbpreviewversions
  - autonomousdbversions
  - autonomousexadatainfrastructures
  - autonomousexadatainfrastructureshapes
  - autonomouspatches
  - autonomousvirtualmachines
  - autonomousvmclusteracdresourceusages
  - autonomousvmclusterresourceusages
  - autonomousvmclusters
  - backupdestinations
  - backups
  - cloudautonomousvmclusteracdresourceusages
  - cloudautonomousvmclusterresourceusages
  - cloudautonomousvmclusters
  - cloudexadatainfrastructures
  - cloudexadatainfrastructureunallocatedresources
  - cloudvmclusteriormconfigs
  - cloudvmclusters
  - cloudvmclusterupdatehistoryentries
  - cloudvmclusterupdates
  - consoleconnections
  - consolehistories
  - consolehistorycontents
  - containerdatabasepatches
  - databases
  - databasesoftwareimages
  - databaseupgradehistoryentries
  - dataguardassociations
  - dbhomepatches
  - dbhomepatchhistoryentries
  - dbhomes
  - dbnodes
  - dbservers
  - dbsystemcomputeperformances
  - dbsystempatches
  - dbsystempatchhistoryentries
  - dbsystems
  - dbsystemshapes
  - dbsystemstorageperformances
  - dbsystemupgradehistoryentries
  - dbversions
  - exadatainfrastructureocpus
  - exadatainfrastructures
  - exadatainfrastructureunallocatedresources
  - exadataiormconfigs
  - externalbackupjobs
  - externalcontainerdatabases
  - externaldatabaseconnectors
  - externalnoncontainerdatabases
  - externalpluggabledatabases
  - flexcomponents
  - giversions
  - infrastructuretargetversions
  - keystores
  - maintenancerunhistories
  - maintenanceruns
  - oneoffpatches
  - pdbconversionhistoryentries
  - pluggabledatabases
  - systemversions
  - vmclusternetworks
  - vmclusterpatches
  - vmclusterpatchhistoryentries
  - vmclusters
  - vmclusterupdatehistoryentries
  - vmclusterupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - applicationvips/finalizers
  - autonomouscontainerdatabasedataguardassociations/finalizers
  - autonomouscontainerdatabaseresourceusages/finalizers
  - autonomouscontainerdatabases/finalizers
  - autonomouscontainerdatabaseversions/finalizers
  - autonomousdatabasebackups/finalizers
  - autonomousdatabasecharactersets/finalizers
  - autonomousdatabaseclones/finalizers
  - autonomousdatabasedataguardassociations/finalizers
  - autonomousdatabaserefreshableclones/finalizers
  - autonomousdatabaseregionalwallets/finalizers
  - autonomousdatabases/finalizers
  - autonomousdatabasewallets/finalizers
  - autonomousdbpreviewversions/finalizers
  - autonomousdbversions/finalizers
  - autonomousexadatainfrastructures/finalizers
  - autonomousexadatainfrastructureshapes/finalizers
  - autonomouspatches/finalizers
  - autonomousvirtualmachines/finalizers
  - autonomousvmclusteracdresourceusages/finalizers
  - autonomousvmclusterresourceusages/finalizers
  - autonomousvmclusters/finalizers
  - backupdestinations/finalizers
  - backups/finalizers
  - cloudautonomousvmclusteracdresourceusages/finalizers
  - cloudautonomousvmclusterresourceusages/finalizers
  - cloudautonomousvmclusters/finalizers
  - cloudexadatainfrastructures/finalizers
  - cloudexadatainfrastructureunallocatedresources/finalizers
  - cloudvmclusteriormconfigs/finalizers
  - cloudvmclusters/finalizers
  - cloudvmclusterupdatehistoryentries/finalizers
  - cloudvmclusterupdates/finalizers
  - consoleconnections/finalizers
  - consolehistories/finalizers
  - consolehistorycontents/finalizers
  - containerdatabasepatches/finalizers
  - databases/finalizers
  - databasesoftwareimages/finalizers
  - databaseupgradehistoryentries/finalizers
  - dataguardassociations/finalizers
  - dbhomepatches/finalizers
  - dbhomepatchhistoryentries/finalizers
  - dbhomes/finalizers
  - dbnodes/finalizers
  - dbservers/finalizers
  - dbsystemcomputeperformances/finalizers
  - dbsystempatches/finalizers
  - dbsystempatchhistoryentries/finalizers
  - dbsystems/finalizers
  - dbsystemshapes/finalizers
  - dbsystemstorageperformances/finalizers
  - dbsystemupgradehistoryentries/finalizers
  - dbversions/finalizers
  - exadatainfrastructureocpus/finalizers
  - exadatainfrastructures/finalizers
  - exadatainfrastructureunallocatedresources/finalizers
  - exadataiormconfigs/finalizers
  - externalbackupjobs/finalizers
  - externalcontainerdatabases/finalizers
  - externaldatabaseconnectors/finalizers
  - externalnoncontainerdatabases/finalizers
  - externalpluggabledatabases/finalizers
  - flexcomponents/finalizers
  - giversions/finalizers
  - infrastructuretargetversions/finalizers
  - keystores/finalizers
  - maintenancerunhistories/finalizers
  - maintenanceruns/finalizers
  - oneoffpatches/finalizers
  - pdbconversionhistoryentries/finalizers
  - pluggabledatabases/finalizers
  - systemversions/finalizers
  - vmclusternetworks/finalizers
  - vmclusterpatches/finalizers
  - vmclusterpatchhistoryentries/finalizers
  - vmclusters/finalizers
  - vmclusterupdatehistoryentries/finalizers
  - vmclusterupdates/finalizers
  verbs:
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - applicationvips/status
  - autonomouscontainerdatabasedataguardassociations/status
  - autonomouscontainerdatabaseresourceusages/status
  - autonomouscontainerdatabases/status
  - autonomouscontainerdatabaseversions/status
  - autonomousdatabasebackups/status
  - autonomousdatabasecharactersets/status
  - autonomousdatabaseclones/status
  - autonomousdatabasedataguardassociations/status
  - autonomousdatabaserefreshableclones/status
  - autonomousdatabaseregionalwallets/status
  - autonomousdatabases/status
  - autonomousdatabasewallets/status
  - autonomousdbpreviewversions/status
  - autonomousdbversions/status
  - autonomousexadatainfrastructures/status
  - autonomousexadatainfrastructureshapes/status
  - autonomouspatches/status
  - autonomousvirtualmachines/status
  - autonomousvmclusteracdresourceusages/status
  - autonomousvmclusterresourceusages/status
  - autonomousvmclusters/status
  - backupdestinations/status
  - backups/status
  - cloudautonomousvmclusteracdresourceusages/status
  - cloudautonomousvmclusterresourceusages/status
  - cloudautonomousvmclusters/status
  - cloudexadatainfrastructures/status
  - cloudexadatainfrastructureunallocatedresources/status
  - cloudvmclusteriormconfigs/status
  - cloudvmclusters/status
  - cloudvmclusterupdatehistoryentries/status
  - cloudvmclusterupdates/status
  - consoleconnections/status
  - consolehistories/status
  - consolehistorycontents/status
  - containerdatabasepatches/status
  - databases/status
  - databasesoftwareimages/status
  - databaseupgradehistoryentries/status
  - dataguardassociations/status
  - dbhomepatches/status
  - dbhomepatchhistoryentries/status
  - dbhomes/status
  - dbnodes/status
  - dbservers/status
  - dbsystemcomputeperformances/status
  - dbsystempatches/status
  - dbsystempatchhistoryentries/status
  - dbsystems/status
  - dbsystemshapes/status
  - dbsystemstorageperformances/status
  - dbsystemupgradehistoryentries/status
  - dbversions/status
  - exadatainfrastructureocpus/status
  - exadatainfrastructures/status
  - exadatainfrastructureunallocatedresources/status
  - exadataiormconfigs/status
  - externalbackupjobs/status
  - externalcontainerdatabases/status
  - externaldatabaseconnectors/status
  - externalnoncontainerdatabases/status
  - externalpluggabledatabases/status
  - flexcomponents/status
  - giversions/status
  - infrastructuretargetversions/status
  - keystores/status
  - maintenancerunhistories/status
  - maintenanceruns/status
  - oneoffpatches/status
  - pdbconversionhistoryentries/status
  - pluggabledatabases/status
  - systemversions/status
  - vmclusternetworks/status
  - vmclusterpatches/status
  - vmclusterpatchhistoryentries/status
  - vmclusters/status
  - vmclusterupdatehistoryentries/status
  - vmclusterupdates/status
  verbs:
  - get
  - patch
  - update
