/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package vaultusage

import (
	"context"
	"fmt"

	keymanagementsdk "github.com/oracle/oci-go-sdk/v65/keymanagement"
	keymanagementv1beta1 "github.com/oracle/oci-service-operator/api/keymanagement/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// VaultUsageServiceClient is the handwritten extension seam for VaultUsage runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*VaultUsageServiceManager).WithClient.
type VaultUsageServiceClient interface {
	CreateOrUpdate(context.Context, *keymanagementv1beta1.VaultUsage, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *keymanagementv1beta1.VaultUsage) (bool, error)
}

type defaultVaultUsageServiceClient struct {
	generatedruntime.ServiceClient[*keymanagementv1beta1.VaultUsage]
}

var _ VaultUsageServiceClient = defaultVaultUsageServiceClient{}

var newVaultUsageServiceClient = func(manager *VaultUsageServiceManager) VaultUsageServiceClient {
	sdkClient, err := keymanagementsdk.NewKmsVaultClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*keymanagementv1beta1.VaultUsage]{
		Kind:    "VaultUsage",
		SDKName: "VaultUsage",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &keymanagementsdk.GetVaultUsageRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetVaultUsage(ctx, *request.(*keymanagementsdk.GetVaultUsageRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize VaultUsage OCI client: %w", err)
	}
	return defaultVaultUsageServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*keymanagementv1beta1.VaultUsage](config),
	}
}
