apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/identity.oracle.com_alloweddomainlicensetypes.yaml
- bases/identity.oracle.com_apikeys.yaml
- bases/identity.oracle.com_authenticationpolicies.yaml
- bases/identity.oracle.com_authtokens.yaml
- bases/identity.oracle.com_availabilitydomains.yaml
- bases/identity.oracle.com_bulkactionresourcetypes.yaml
- bases/identity.oracle.com_bulkedittagsresourcetypes.yaml
- bases/identity.oracle.com_compartments.yaml
- bases/identity.oracle.com_costtrackingtags.yaml
- bases/identity.oracle.com_customersecretkeys.yaml
- bases/identity.oracle.com_dbcredentials.yaml
- bases/identity.oracle.com_domains.yaml
- bases/identity.oracle.com_dynamicgroups.yaml
- bases/identity.oracle.com_faultdomains.yaml
- bases/identity.oracle.com_groups.yaml
- bases/identity.oracle.com_iamworkrequesterrors.yaml
- bases/identity.oracle.com_iamworkrequestlogs.yaml
- bases/identity.oracle.com_iamworkrequests.yaml
- bases/identity.oracle.com_identityprovidergroups.yaml
- bases/identity.oracle.com_identityproviders.yaml
- bases/identity.oracle.com_idpgroupmappings.yaml
- bases/identity.oracle.com_mfatotpdevices.yaml
- bases/identity.oracle.com_networksources.yaml
- bases/identity.oracle.com_oauthclientcredentials.yaml
- bases/identity.oracle.com_orresetuipasswords.yaml
- bases/identity.oracle.com_policies.yaml
- bases/identity.oracle.com_regions.yaml
- bases/identity.oracle.com_regionsubscriptions.yaml
- bases/identity.oracle.com_smtpcredentials.yaml
- bases/identity.oracle.com_standardtagnamespaces.yaml
- bases/identity.oracle.com_standardtagtemplates.yaml
- bases/identity.oracle.com_swiftpasswords.yaml
- bases/identity.oracle.com_tagdefaults.yaml
- bases/identity.oracle.com_taggingworkrequesterrors.yaml
- bases/identity.oracle.com_taggingworkrequestlogs.yaml
- bases/identity.oracle.com_taggingworkrequests.yaml
- bases/identity.oracle.com_tagnamespaces.yaml
- bases/identity.oracle.com_tags.yaml
- bases/identity.oracle.com_tenancies.yaml
- bases/identity.oracle.com_usercapabilities.yaml
- bases/identity.oracle.com_usergroupmemberships.yaml
- bases/identity.oracle.com_users.yaml
- bases/identity.oracle.com_userstates.yaml
- bases/identity.oracle.com_useruipasswordinformation.yaml
- bases/identity.oracle.com_workrequests.yaml
