/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package drg

import (
	"context"
	"fmt"

	coresdk "github.com/oracle/oci-go-sdk/v65/core"
	corev1beta1 "github.com/oracle/oci-service-operator/api/core/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DrgServiceClient is the handwritten extension seam for Drg runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DrgServiceManager).WithClient.
type DrgServiceClient interface {
	CreateOrUpdate(context.Context, *corev1beta1.Drg, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *corev1beta1.Drg) (bool, error)
}

type defaultDrgServiceClient struct {
	generatedruntime.ServiceClient[*corev1beta1.Drg]
}

var _ DrgServiceClient = defaultDrgServiceClient{}

var newDrgServiceClient = func(manager *DrgServiceManager) DrgServiceClient {
	sdkClient, err := coresdk.NewVirtualNetworkClientWithConfigurationProvider(manager.Provider)
	hooks := newDrgRuntimeHooks(manager, sdkClient)
	config := buildDrgGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Drg OCI client: %w", err)
	}
	delegate := defaultDrgServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*corev1beta1.Drg](config),
	}
	return wrapDrgGeneratedClient(hooks, delegate)
}
