/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package stackmonitoring

import (
	"context"

	stackmonitoringv1beta1 "github.com/oracle/oci-service-operator/api/stackmonitoring/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MetricExtensionReconciler reconciles a MetricExtension object.
type MetricExtensionReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=stackmonitoring.oracle.com,resources=metricextensions,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=stackmonitoring.oracle.com,resources=metricextensions/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=stackmonitoring.oracle.com,resources=metricextensions/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *MetricExtensionReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	metricExtension := &stackmonitoringv1beta1.MetricExtension{}
	return r.Reconciler.Reconcile(ctx, req, metricExtension)
}

// SetupWithManager sets up the controller with the Manager.
func (r *MetricExtensionReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&stackmonitoringv1beta1.MetricExtension{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
