resources:
  - sourceResource: DbSystem
    kind: DbSystem
    mergeWithDiscovered: true
    specFields:
      - name: AdminUsername
        type: shared.UsernameSource
        tag: 'json:"adminUsername,omitempty"'
        comments:
          - The username for the administrative user sourced from a Kubernetes Secret.
      - name: AdminPassword
        type: shared.PasswordSource
        tag: 'json:"adminPassword,omitempty"'
        comments:
          - The password for the administrative user sourced from a Kubernetes Secret.
    statusFields:
      - name: AdminUsername
        type: shared.UsernameSource
        tag: 'json:"adminUsername,omitempty"'
        comments:
          - The last applied secret reference for the administrative username.
      - name: AdminPassword
        type: shared.PasswordSource
        tag: 'json:"adminPassword,omitempty"'
        comments:
          - The last applied secret reference for the administrative password.
    sample:
      metadataName: dbsystem-sample
      body: |-
        apiVersion: mysql.oracle.com/v1beta1
        kind: DbSystem
        metadata:
          name: dbsystem-sample
        spec:
          compartmentId: ocid1.compartment.oc1..exampleuniqueID
          shapeName: MySQL.VM.Standard.E3.1.8GB
          subnetId: ocid1.subnet.oc1..exampleuniqueID
          adminUsername:
            secret:
              secretName: admin-secret
          adminPassword:
            secret:
              secretName: admin-secret
