apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/logging.oracle.com_loggroups.yaml
- bases/logging.oracle.com_logs.yaml
- bases/logging.oracle.com_logsavedsearches.yaml
- bases/logging.oracle.com_services.yaml
- bases/logging.oracle.com_unifiedagentconfigurations.yaml
- bases/logging.oracle.com_workrequesterrors.yaml
- bases/logging.oracle.com_workrequestlogs.yaml
- bases/logging.oracle.com_workrequests.yaml
