---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secrets.oracle.com
  resources:
  - secretbundlebynames
  - secretbundles
  - secretbundleversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.oracle.com
  resources:
  - secretbundlebynames/finalizers
  - secretbundles/finalizers
  - secretbundleversions/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.oracle.com
  resources:
  - secretbundlebynames/status
  - secretbundles/status
  - secretbundleversions/status
  verbs:
  - get
  - patch
  - update
