---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - identity.oracle.com
  resources:
  - alloweddomainlicensetypes
  - apikeies
  - authenticationpolicies
  - authtokens
  - availabilitydomains
  - bulkactionresourcetypes
  - bulkedittagsresourcetypes
  - compartments
  - costtrackingtags
  - customersecretkeies
  - dbcredentials
  - domains
  - dynamicgroups
  - faultdomains
  - groups
  - iamworkrequesterrors
  - iamworkrequestlogs
  - iamworkrequests
  - identityprovidergroups
  - identityproviders
  - idpgroupmappings
  - mfatotpdevices
  - networksources
  - oauthclientcredentials
  - orresetuipasswords
  - policies
  - regions
  - regionsubscriptions
  - smtpcredentials
  - standardtagnamespaces
  - standardtagtemplates
  - swiftpasswords
  - tagdefaults
  - taggingworkrequesterrors
  - taggingworkrequestlogs
  - taggingworkrequests
  - tagnamespaces
  - tags
  - tenancies
  - usercapabilities
  - usergroupmemberships
  - users
  - userstates
  - useruipasswordinformations
  - workrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.oracle.com
  resources:
  - alloweddomainlicensetypes/finalizers
  - apikeies/finalizers
  - authenticationpolicies/finalizers
  - authtokens/finalizers
  - availabilitydomains/finalizers
  - bulkactionresourcetypes/finalizers
  - bulkedittagsresourcetypes/finalizers
  - compartments/finalizers
  - costtrackingtags/finalizers
  - customersecretkeies/finalizers
  - dbcredentials/finalizers
  - domains/finalizers
  - dynamicgroups/finalizers
  - faultdomains/finalizers
  - groups/finalizers
  - iamworkrequesterrors/finalizers
  - iamworkrequestlogs/finalizers
  - iamworkrequests/finalizers
  - identityprovidergroups/finalizers
  - identityproviders/finalizers
  - idpgroupmappings/finalizers
  - mfatotpdevices/finalizers
  - networksources/finalizers
  - oauthclientcredentials/finalizers
  - orresetuipasswords/finalizers
  - policies/finalizers
  - regions/finalizers
  - regionsubscriptions/finalizers
  - smtpcredentials/finalizers
  - standardtagnamespaces/finalizers
  - standardtagtemplates/finalizers
  - swiftpasswords/finalizers
  - tagdefaults/finalizers
  - taggingworkrequesterrors/finalizers
  - taggingworkrequestlogs/finalizers
  - taggingworkrequests/finalizers
  - tagnamespaces/finalizers
  - tags/finalizers
  - tenancies/finalizers
  - usercapabilities/finalizers
  - usergroupmemberships/finalizers
  - users/finalizers
  - userstates/finalizers
  - useruipasswordinformations/finalizers
  - workrequests/finalizers
  verbs:
  - update
- apiGroups:
  - identity.oracle.com
  resources:
  - alloweddomainlicensetypes/status
  - apikeies/status
  - authenticationpolicies/status
  - authtokens/status
  - availabilitydomains/status
  - bulkactionresourcetypes/status
  - bulkedittagsresourcetypes/status
  - compartments/status
  - costtrackingtags/status
  - customersecretkeies/status
  - dbcredentials/status
  - domains/status
  - dynamicgroups/status
  - faultdomains/status
  - groups/status
  - iamworkrequesterrors/status
  - iamworkrequestlogs/status
  - iamworkrequests/status
  - identityprovidergroups/status
  - identityproviders/status
  - idpgroupmappings/status
  - mfatotpdevices/status
  - networksources/status
  - oauthclientcredentials/status
  - orresetuipasswords/status
  - policies/status
  - regions/status
  - regionsubscriptions/status
  - smtpcredentials/status
  - standardtagnamespaces/status
  - standardtagtemplates/status
  - swiftpasswords/status
  - tagdefaults/status
  - taggingworkrequesterrors/status
  - taggingworkrequestlogs/status
  - taggingworkrequests/status
  - tagnamespaces/status
  - tags/status
  - tenancies/status
  - usercapabilities/status
  - usergroupmemberships/status
  - users/status
  - userstates/status
  - useruipasswordinformations/status
  - workrequests/status
  verbs:
  - get
  - patch
  - update
