//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/oracle/oci-service-operator/pkg/shared"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stack) DeepCopyInto(out *Stack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stack.
func (in *Stack) DeepCopy() *Stack {
	if in == nil {
		return nil
	}
	out := new(Stack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Stack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackAdb) DeepCopyInto(out *StackAdb) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackAdb.
func (in *StackAdb) DeepCopy() *StackAdb {
	if in == nil {
		return nil
	}
	out := new(StackAdb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackAidataplatform) DeepCopyInto(out *StackAidataplatform) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackAidataplatform.
func (in *StackAidataplatform) DeepCopy() *StackAidataplatform {
	if in == nil {
		return nil
	}
	out := new(StackAidataplatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDataflow) DeepCopyInto(out *StackDataflow) {
	*out = *in
	out.DriverShapeConfig = in.DriverShapeConfig
	out.ExecutorShapeConfig = in.ExecutorShapeConfig
	in.Connections.DeepCopyInto(&out.Connections)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDataflow.
func (in *StackDataflow) DeepCopy() *StackDataflow {
	if in == nil {
		return nil
	}
	out := new(StackDataflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDataflowConnections) DeepCopyInto(out *StackDataflowConnections) {
	*out = *in
	in.ConnectionDetails.DeepCopyInto(&out.ConnectionDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDataflowConnections.
func (in *StackDataflowConnections) DeepCopy() *StackDataflowConnections {
	if in == nil {
		return nil
	}
	out := new(StackDataflowConnections)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDataflowConnectionsConnectionDetails) DeepCopyInto(out *StackDataflowConnectionsConnectionDetails) {
	*out = *in
	if in.DifDependencies != nil {
		in, out := &in.DifDependencies, &out.DifDependencies
		*out = make([]StackDataflowConnectionsConnectionDetailsDifDependency, len(*in))
		copy(*out, *in)
	}
	if in.DomainNames != nil {
		in, out := &in.DomainNames, &out.DomainNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDataflowConnectionsConnectionDetails.
func (in *StackDataflowConnectionsConnectionDetails) DeepCopy() *StackDataflowConnectionsConnectionDetails {
	if in == nil {
		return nil
	}
	out := new(StackDataflowConnectionsConnectionDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDataflowConnectionsConnectionDetailsDifDependency) DeepCopyInto(out *StackDataflowConnectionsConnectionDetailsDifDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDataflowConnectionsConnectionDetailsDifDependency.
func (in *StackDataflowConnectionsConnectionDetailsDifDependency) DeepCopy() *StackDataflowConnectionsConnectionDetailsDifDependency {
	if in == nil {
		return nil
	}
	out := new(StackDataflowConnectionsConnectionDetailsDifDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDataflowDriverShapeConfig) DeepCopyInto(out *StackDataflowDriverShapeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDataflowDriverShapeConfig.
func (in *StackDataflowDriverShapeConfig) DeepCopy() *StackDataflowDriverShapeConfig {
	if in == nil {
		return nil
	}
	out := new(StackDataflowDriverShapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDataflowExecutorShapeConfig) DeepCopyInto(out *StackDataflowExecutorShapeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDataflowExecutorShapeConfig.
func (in *StackDataflowExecutorShapeConfig) DeepCopy() *StackDataflowExecutorShapeConfig {
	if in == nil {
		return nil
	}
	out := new(StackDataflowExecutorShapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackGenai) DeepCopyInto(out *StackGenai) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]StackGenaiEndpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackGenai.
func (in *StackGenai) DeepCopy() *StackGenai {
	if in == nil {
		return nil
	}
	out := new(StackGenai)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackGenaiEndpoint) DeepCopyInto(out *StackGenaiEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackGenaiEndpoint.
func (in *StackGenaiEndpoint) DeepCopy() *StackGenaiEndpoint {
	if in == nil {
		return nil
	}
	out := new(StackGenaiEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackGgc) DeepCopyInto(out *StackGgc) {
	*out = *in
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]StackGgcConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackGgc.
func (in *StackGgc) DeepCopy() *StackGgc {
	if in == nil {
		return nil
	}
	out := new(StackGgc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackGgcConnection) DeepCopyInto(out *StackGgcConnection) {
	*out = *in
	if in.DifDependencies != nil {
		in, out := &in.DifDependencies, &out.DifDependencies
		*out = make([]StackGgcConnectionDifDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackGgcConnection.
func (in *StackGgcConnection) DeepCopy() *StackGgcConnection {
	if in == nil {
		return nil
	}
	out := new(StackGgcConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackGgcConnectionDifDependency) DeepCopyInto(out *StackGgcConnectionDifDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackGgcConnectionDifDependency.
func (in *StackGgcConnectionDifDependency) DeepCopy() *StackGgcConnectionDifDependency {
	if in == nil {
		return nil
	}
	out := new(StackGgcConnectionDifDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackList) DeepCopyInto(out *StackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Stack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackList.
func (in *StackList) DeepCopy() *StackList {
	if in == nil {
		return nil
	}
	out := new(StackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackObjectstorage) DeepCopyInto(out *StackObjectstorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackObjectstorage.
func (in *StackObjectstorage) DeepCopy() *StackObjectstorage {
	if in == nil {
		return nil
	}
	out := new(StackObjectstorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackOke) DeepCopyInto(out *StackOke) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackOke.
func (in *StackOke) DeepCopy() *StackOke {
	if in == nil {
		return nil
	}
	out := new(StackOke)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackOmk) DeepCopyInto(out *StackOmk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackOmk.
func (in *StackOmk) DeepCopy() *StackOmk {
	if in == nil {
		return nil
	}
	out := new(StackOmk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackServiceDetail) DeepCopyInto(out *StackServiceDetail) {
	*out = *in
	in.AdditionalDetails.DeepCopyInto(&out.AdditionalDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackServiceDetail.
func (in *StackServiceDetail) DeepCopy() *StackServiceDetail {
	if in == nil {
		return nil
	}
	out := new(StackServiceDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackServiceDetailAdditionalDetails) DeepCopyInto(out *StackServiceDetailAdditionalDetails) {
	*out = *in
	if in.AssignedConnections != nil {
		in, out := &in.AssignedConnections, &out.AssignedConnections
		*out = make([]StackServiceDetailAdditionalDetailsAssignedConnection, len(*in))
		copy(*out, *in)
	}
	if in.EndpointDetails != nil {
		in, out := &in.EndpointDetails, &out.EndpointDetails
		*out = make([]StackServiceDetailAdditionalDetailsEndpointDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackServiceDetailAdditionalDetails.
func (in *StackServiceDetailAdditionalDetails) DeepCopy() *StackServiceDetailAdditionalDetails {
	if in == nil {
		return nil
	}
	out := new(StackServiceDetailAdditionalDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackServiceDetailAdditionalDetailsAssignedConnection) DeepCopyInto(out *StackServiceDetailAdditionalDetailsAssignedConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackServiceDetailAdditionalDetailsAssignedConnection.
func (in *StackServiceDetailAdditionalDetailsAssignedConnection) DeepCopy() *StackServiceDetailAdditionalDetailsAssignedConnection {
	if in == nil {
		return nil
	}
	out := new(StackServiceDetailAdditionalDetailsAssignedConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackServiceDetailAdditionalDetailsEndpointDetail) DeepCopyInto(out *StackServiceDetailAdditionalDetailsEndpointDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackServiceDetailAdditionalDetailsEndpointDetail.
func (in *StackServiceDetailAdditionalDetailsEndpointDetail) DeepCopy() *StackServiceDetailAdditionalDetailsEndpointDetail {
	if in == nil {
		return nil
	}
	out := new(StackServiceDetailAdditionalDetailsEndpointDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackSpec) DeepCopyInto(out *StackSpec) {
	*out = *in
	if in.StackTemplates != nil {
		in, out := &in.StackTemplates, &out.StackTemplates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Adb != nil {
		in, out := &in.Adb, &out.Adb
		*out = make([]StackAdb, len(*in))
		copy(*out, *in)
	}
	if in.Ggcs != nil {
		in, out := &in.Ggcs, &out.Ggcs
		*out = make([]StackGgc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dataflow != nil {
		in, out := &in.Dataflow, &out.Dataflow
		*out = make([]StackDataflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Objectstorage != nil {
		in, out := &in.Objectstorage, &out.Objectstorage
		*out = make([]StackObjectstorage, len(*in))
		copy(*out, *in)
	}
	if in.Genai != nil {
		in, out := &in.Genai, &out.Genai
		*out = make([]StackGenai, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Aidataplatform != nil {
		in, out := &in.Aidataplatform, &out.Aidataplatform
		*out = make([]StackAidataplatform, len(*in))
		copy(*out, *in)
	}
	if in.Omk != nil {
		in, out := &in.Omk, &out.Omk
		*out = make([]StackOmk, len(*in))
		copy(*out, *in)
	}
	if in.Oke != nil {
		in, out := &in.Oke, &out.Oke
		*out = make([]StackOke, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackSpec.
func (in *StackSpec) DeepCopy() *StackSpec {
	if in == nil {
		return nil
	}
	out := new(StackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackStatus) DeepCopyInto(out *StackStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.StackTemplates != nil {
		in, out := &in.StackTemplates, &out.StackTemplates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Adb != nil {
		in, out := &in.Adb, &out.Adb
		*out = make([]StackAdb, len(*in))
		copy(*out, *in)
	}
	if in.Ggcs != nil {
		in, out := &in.Ggcs, &out.Ggcs
		*out = make([]StackGgc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dataflow != nil {
		in, out := &in.Dataflow, &out.Dataflow
		*out = make([]StackDataflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Objectstorage != nil {
		in, out := &in.Objectstorage, &out.Objectstorage
		*out = make([]StackObjectstorage, len(*in))
		copy(*out, *in)
	}
	if in.Genai != nil {
		in, out := &in.Genai, &out.Genai
		*out = make([]StackGenai, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Aidataplatform != nil {
		in, out := &in.Aidataplatform, &out.Aidataplatform
		*out = make([]StackAidataplatform, len(*in))
		copy(*out, *in)
	}
	if in.Omk != nil {
		in, out := &in.Omk, &out.Omk
		*out = make([]StackOmk, len(*in))
		copy(*out, *in)
	}
	if in.Oke != nil {
		in, out := &in.Oke, &out.Oke
		*out = make([]StackOke, len(*in))
		copy(*out, *in)
	}
	if in.ServiceDetails != nil {
		in, out := &in.ServiceDetails, &out.ServiceDetails
		*out = make([]StackServiceDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackStatus.
func (in *StackStatus) DeepCopy() *StackStatus {
	if in == nil {
		return nil
	}
	out := new(StackStatus)
	in.DeepCopyInto(out)
	return out
}
