apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/core.oracle.com_drgs.yaml
- bases/core.oracle.com_instances.yaml
- bases/core.oracle.com_internetgateways.yaml
- bases/core.oracle.com_natgateways.yaml
- bases/core.oracle.com_networksecuritygroups.yaml
- bases/core.oracle.com_routetables.yaml
- bases/core.oracle.com_securitylists.yaml
- bases/core.oracle.com_servicegateways.yaml
- bases/core.oracle.com_subnets.yaml
- bases/core.oracle.com_vcns.yaml
