apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/core.oracle.com_alldrgattachments.yaml
- bases/core.oracle.com_allowedikeipsecparameters.yaml
- bases/core.oracle.com_allowedpeerregionsforremotepeerings.yaml
- bases/core.oracle.com_appcataloglistingagreements.yaml
- bases/core.oracle.com_appcataloglistingresourceversions.yaml
- bases/core.oracle.com_appcataloglistings.yaml
- bases/core.oracle.com_appcatalogsubscriptions.yaml
- bases/core.oracle.com_blockvolumereplicas.yaml
- bases/core.oracle.com_bootvolumeattachments.yaml
- bases/core.oracle.com_bootvolumebackups.yaml
- bases/core.oracle.com_bootvolumekmskeys.yaml
- bases/core.oracle.com_bootvolumereplicas.yaml
- bases/core.oracle.com_bootvolumes.yaml
- bases/core.oracle.com_byoipallocatedranges.yaml
- bases/core.oracle.com_byoipranges.yaml
- bases/core.oracle.com_capturefilters.yaml
- bases/core.oracle.com_clusternetworkinstances.yaml
- bases/core.oracle.com_clusternetworks.yaml
- bases/core.oracle.com_computecapacityreports.yaml
- bases/core.oracle.com_computecapacityreservationinstances.yaml
- bases/core.oracle.com_computecapacityreservationinstanceshapes.yaml
- bases/core.oracle.com_computecapacityreservations.yaml
- bases/core.oracle.com_computecapacitytopologies.yaml
- bases/core.oracle.com_computecapacitytopologycomputebaremetalhosts.yaml
- bases/core.oracle.com_computecapacitytopologycomputehpcislands.yaml
- bases/core.oracle.com_computecapacitytopologycomputenetworkblocks.yaml
- bases/core.oracle.com_computeclusters.yaml
- bases/core.oracle.com_computeglobalimagecapabilityschemas.yaml
- bases/core.oracle.com_computeglobalimagecapabilityschemaversions.yaml
- bases/core.oracle.com_computeimagecapabilityschemas.yaml
- bases/core.oracle.com_consolehistories.yaml
- bases/core.oracle.com_consolehistorycontents.yaml
- bases/core.oracle.com_cpedeviceconfigcontents.yaml
- bases/core.oracle.com_cpedeviceshapes.yaml
- bases/core.oracle.com_cpes.yaml
- bases/core.oracle.com_crossconnectgroups.yaml
- bases/core.oracle.com_crossconnectletterofauthorities.yaml
- bases/core.oracle.com_crossconnectlocations.yaml
- bases/core.oracle.com_crossconnectmappings.yaml
- bases/core.oracle.com_crossconnectportspeedshapes.yaml
- bases/core.oracle.com_crossconnects.yaml
- bases/core.oracle.com_crossconnectstatuses.yaml
- bases/core.oracle.com_dedicatedvmhostinstances.yaml
- bases/core.oracle.com_dedicatedvmhostinstanceshapes.yaml
- bases/core.oracle.com_dedicatedvmhosts.yaml
- bases/core.oracle.com_dedicatedvmhostshapes.yaml
- bases/core.oracle.com_dhcpoptions.yaml
- bases/core.oracle.com_drgattachments.yaml
- bases/core.oracle.com_drgredundancystatuses.yaml
- bases/core.oracle.com_drgroutedistributions.yaml
- bases/core.oracle.com_drgroutedistributionstatements.yaml
- bases/core.oracle.com_drgrouterules.yaml
- bases/core.oracle.com_drgroutetables.yaml
- bases/core.oracle.com_drgs.yaml
- bases/core.oracle.com_fastconnectproviderservicekeys.yaml
- bases/core.oracle.com_fastconnectproviderservices.yaml
- bases/core.oracle.com_fastconnectprovidervirtualcircuitbandwidthshapes.yaml
- bases/core.oracle.com_images.yaml
- bases/core.oracle.com_imageshapecompatibilityentries.yaml
- bases/core.oracle.com_instanceconfigurations.yaml
- bases/core.oracle.com_instanceconsoleconnections.yaml
- bases/core.oracle.com_instancedevices.yaml
- bases/core.oracle.com_instancemaintenancereboots.yaml
- bases/core.oracle.com_instancepoolinstances.yaml
- bases/core.oracle.com_instancepoolloadbalancerattachments.yaml
- bases/core.oracle.com_instancepools.yaml
- bases/core.oracle.com_instances.yaml
- bases/core.oracle.com_internetgateways.yaml
- bases/core.oracle.com_ipsecconnectiondeviceconfigs.yaml
- bases/core.oracle.com_ipsecconnectiondevicestatuses.yaml
- bases/core.oracle.com_ipsecconnections.yaml
- bases/core.oracle.com_ipsecconnectiontunnelerrors.yaml
- bases/core.oracle.com_ipsecconnectiontunnelroutes.yaml
- bases/core.oracle.com_ipsecconnectiontunnels.yaml
- bases/core.oracle.com_ipsecconnectiontunnelsecurityassociations.yaml
- bases/core.oracle.com_ipsecconnectiontunnelsharedsecrets.yaml
- bases/core.oracle.com_ipseccpedeviceconfigcontents.yaml
- bases/core.oracle.com_ipv6s.yaml
- bases/core.oracle.com_localpeeringgateways.yaml
- bases/core.oracle.com_measuredbootreports.yaml
- bases/core.oracle.com_natgateways.yaml
- bases/core.oracle.com_networkingtopologies.yaml
- bases/core.oracle.com_networksecuritygroups.yaml
- bases/core.oracle.com_networksecuritygroupsecurityrules.yaml
- bases/core.oracle.com_networksecuritygroupvnics.yaml
- bases/core.oracle.com_privateips.yaml
- bases/core.oracle.com_publicipbyipaddresses.yaml
- bases/core.oracle.com_publicipbyprivateipids.yaml
- bases/core.oracle.com_publicippools.yaml
- bases/core.oracle.com_publicips.yaml
- bases/core.oracle.com_remotepeeringconnections.yaml
- bases/core.oracle.com_routetables.yaml
- bases/core.oracle.com_securitylists.yaml
- bases/core.oracle.com_servicegateways.yaml
- bases/core.oracle.com_services.yaml
- bases/core.oracle.com_shapes.yaml
- bases/core.oracle.com_subnets.yaml
- bases/core.oracle.com_subnettopologies.yaml
- bases/core.oracle.com_tunnelcpedeviceconfigcontents.yaml
- bases/core.oracle.com_tunnelcpedeviceconfigs.yaml
- bases/core.oracle.com_upgradestatuses.yaml
- bases/core.oracle.com_vcndnsresolverassociations.yaml
- bases/core.oracle.com_vcns.yaml
- bases/core.oracle.com_vcntopologies.yaml
- bases/core.oracle.com_virtualcircuitassociatedtunnels.yaml
- bases/core.oracle.com_virtualcircuitbandwidthshapes.yaml
- bases/core.oracle.com_virtualcircuitpublicprefixes.yaml
- bases/core.oracle.com_virtualcircuits.yaml
- bases/core.oracle.com_vlans.yaml
- bases/core.oracle.com_vnicattachments.yaml
- bases/core.oracle.com_vnics.yaml
- bases/core.oracle.com_volumeattachments.yaml
- bases/core.oracle.com_volumebackuppolicies.yaml
- bases/core.oracle.com_volumebackuppolicyassetassignments.yaml
- bases/core.oracle.com_volumebackuppolicyassignments.yaml
- bases/core.oracle.com_volumebackups.yaml
- bases/core.oracle.com_volumegroupbackups.yaml
- bases/core.oracle.com_volumegroupreplicas.yaml
- bases/core.oracle.com_volumegroups.yaml
- bases/core.oracle.com_volumekmskeys.yaml
- bases/core.oracle.com_volumes.yaml
- bases/core.oracle.com_vtaps.yaml
- bases/core.oracle.com_windowsinstanceinitialcredentials.yaml
