/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package cloudmigrations

import (
	"context"

	cloudmigrationsv1beta1 "github.com/oracle/oci-service-operator/api/cloudmigrations/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ReplicationScheduleReconciler reconciles a ReplicationSchedule object.
type ReplicationScheduleReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=cloudmigrations.oracle.com,resources=replicationschedules,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=cloudmigrations.oracle.com,resources=replicationschedules/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=cloudmigrations.oracle.com,resources=replicationschedules/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *ReplicationScheduleReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	replicationSchedule := &cloudmigrationsv1beta1.ReplicationSchedule{}
	return r.Reconciler.Reconcile(ctx, req, replicationSchedule)
}

// SetupWithManager sets up the controller with the Manager.
func (r *ReplicationScheduleReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&cloudmigrationsv1beta1.ReplicationSchedule{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
