/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package jobdefinition

import (
	"context"
	"fmt"

	datacatalogsdk "github.com/oracle/oci-go-sdk/v65/datacatalog"
	datacatalogv1beta1 "github.com/oracle/oci-service-operator/api/datacatalog/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// JobDefinitionServiceClient is the handwritten extension seam for JobDefinition runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*JobDefinitionServiceManager).WithClient.
type JobDefinitionServiceClient interface {
	CreateOrUpdate(context.Context, *datacatalogv1beta1.JobDefinition, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *datacatalogv1beta1.JobDefinition) (bool, error)
}

type defaultJobDefinitionServiceClient struct {
	generatedruntime.ServiceClient[*datacatalogv1beta1.JobDefinition]
}

var _ JobDefinitionServiceClient = defaultJobDefinitionServiceClient{}

var newJobDefinitionServiceClient = func(manager *JobDefinitionServiceManager) JobDefinitionServiceClient {
	sdkClient, err := datacatalogsdk.NewDataCatalogClientWithConfigurationProvider(manager.Provider)
	hooks := newJobDefinitionRuntimeHooks(manager, sdkClient)
	config := buildJobDefinitionGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize JobDefinition OCI client: %w", err)
	}
	delegate := defaultJobDefinitionServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*datacatalogv1beta1.JobDefinition](config),
	}
	return wrapJobDefinitionGeneratedClient(hooks, delegate)
}
