/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package dynamicgroup

import (
	"context"
	"fmt"

	identitysdk "github.com/oracle/oci-go-sdk/v65/identity"
	identityv1beta1 "github.com/oracle/oci-service-operator/api/identity/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DynamicGroupServiceClient is the handwritten extension seam for DynamicGroup runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*DynamicGroupServiceManager).WithClient.
type DynamicGroupServiceClient interface {
	CreateOrUpdate(context.Context, *identityv1beta1.DynamicGroup, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *identityv1beta1.DynamicGroup) (bool, error)
}

type defaultDynamicGroupServiceClient struct {
	generatedruntime.ServiceClient[*identityv1beta1.DynamicGroup]
}

var _ DynamicGroupServiceClient = defaultDynamicGroupServiceClient{}

var newDynamicGroupServiceClient = func(manager *DynamicGroupServiceManager) DynamicGroupServiceClient {
	sdkClient, err := identitysdk.NewIdentityClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*identityv1beta1.DynamicGroup]{
		Kind:    "DynamicGroup",
		SDKName: "DynamicGroup",
		Log:     manager.Log,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.CreateDynamicGroupRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.CreateDynamicGroup(ctx, *request.(*identitysdk.CreateDynamicGroupRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.GetDynamicGroupRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetDynamicGroup(ctx, *request.(*identitysdk.GetDynamicGroupRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.ListDynamicGroupsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListDynamicGroups(ctx, *request.(*identitysdk.ListDynamicGroupsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.UpdateDynamicGroupRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateDynamicGroup(ctx, *request.(*identitysdk.UpdateDynamicGroupRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.DeleteDynamicGroupRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteDynamicGroup(ctx, *request.(*identitysdk.DeleteDynamicGroupRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize DynamicGroup OCI client: %w", err)
	}
	return defaultDynamicGroupServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*identityv1beta1.DynamicGroup](config),
	}
}
