apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oci-service-operator-batch-system
namePrefix: oci-service-operator-batch-

resources:
- generated/crd
- generated/rbac
- ../../../config/manager/batch
- ../../../config/rbac/role_binding.yaml
- ../../../config/rbac/leader_election_role.yaml
- ../../../config/rbac/leader_election_role_binding.yaml

patches:
- path: ../../../config/default/manager_config_patch.yaml
  target:
    kind: Deployment
