/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EntityTagSpec defines the desired state of EntityTag.
type EntityTagSpec struct {
	// The name of the tag in the case of a free form tag.
	// When linking to a glossary term, this field is not specified.
	// +kubebuilder:validation:Optional
	Name string `json:"name,omitempty"`
	// Unique key of the related term or null in the case of a free form tag.
	// +kubebuilder:validation:Optional
	TermKey string `json:"termKey,omitempty"`
}

// EntityTagStatus defines the observed state of EntityTag.
type EntityTagStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Unique tag key that is immutable.
	Key string `json:"key,omitempty"`
	// Name of the tag which matches the term name.
	Name string `json:"name,omitempty"`
	// Unique key of the related term.
	TermKey string `json:"termKey,omitempty"`
	// Path of the related term.
	TermPath string `json:"termPath,omitempty"`
	// Description of the related term.
	TermDescription string `json:"termDescription,omitempty"`
	// The current state of the tag.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The date and time the tag was created, in the format defined by RFC3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2019-03-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// OCID of the user who created the tag.
	CreatedById string `json:"createdById,omitempty"`
	// URI to the tag instance in the API.
	Uri string `json:"uri,omitempty"`
	// The unique key of the parent entity.
	EntityKey string `json:"entityKey,omitempty"`
	// Unique id of the parent glossary of the term.
	GlossaryKey string `json:"glossaryKey,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Name",type="string",JSONPath=".spec.name",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the EntityTag",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the EntityTag",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// EntityTag is the Schema for the entitytags API.
type EntityTag struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   EntityTagSpec   `json:"spec,omitempty"`
	Status EntityTagStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// EntityTagList contains a list of EntityTag.
type EntityTagList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EntityTag `json:"items"`
}

func init() {
	SchemeBuilder.Register(&EntityTag{}, &EntityTagList{})
}
