apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/batch.oracle.com_batchcontexts.yaml
- bases/batch.oracle.com_batchjobpools.yaml
- bases/batch.oracle.com_batchtaskenvironments.yaml
- bases/batch.oracle.com_batchtaskprofiles.yaml
