/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package smtpcredential

import (
	"context"
	"fmt"

	identitysdk "github.com/oracle/oci-go-sdk/v65/identity"
	identityv1beta1 "github.com/oracle/oci-service-operator/api/identity/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// SmtpCredentialServiceClient is the handwritten extension seam for SmtpCredential runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*SmtpCredentialServiceManager).WithClient.
type SmtpCredentialServiceClient interface {
	CreateOrUpdate(context.Context, *identityv1beta1.SmtpCredential, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *identityv1beta1.SmtpCredential) (bool, error)
}

type defaultSmtpCredentialServiceClient struct {
	generatedruntime.ServiceClient[*identityv1beta1.SmtpCredential]
}

var _ SmtpCredentialServiceClient = defaultSmtpCredentialServiceClient{}

var newSmtpCredentialServiceClient = func(manager *SmtpCredentialServiceManager) SmtpCredentialServiceClient {
	sdkClient, err := identitysdk.NewIdentityClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*identityv1beta1.SmtpCredential]{
		Kind:    "SmtpCredential",
		SDKName: "SmtpCredential",
		Log:     manager.Log,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.CreateSmtpCredentialRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.CreateSmtpCredential(ctx, *request.(*identitysdk.CreateSmtpCredentialRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.ListSmtpCredentialsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListSmtpCredentials(ctx, *request.(*identitysdk.ListSmtpCredentialsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.UpdateSmtpCredentialRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateSmtpCredential(ctx, *request.(*identitysdk.UpdateSmtpCredentialRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.DeleteSmtpCredentialRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteSmtpCredential(ctx, *request.(*identitysdk.DeleteSmtpCredentialRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize SmtpCredential OCI client: %w", err)
	}
	return defaultSmtpCredentialServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*identityv1beta1.SmtpCredential](config),
	}
}
