/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package database

import (
	"context"

	databasev1beta1 "github.com/oracle/oci-service-operator/api/database/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// DatabaseSoftwareImageReconciler reconciles a DatabaseSoftwareImage object.
type DatabaseSoftwareImageReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=database.oracle.com,resources=databasesoftwareimages,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=database.oracle.com,resources=databasesoftwareimages/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=database.oracle.com,resources=databasesoftwareimages/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *DatabaseSoftwareImageReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	databaseSoftwareImage := &databasev1beta1.DatabaseSoftwareImage{}
	return r.Reconciler.Reconcile(ctx, req, databaseSoftwareImage)
}

// SetupWithManager sets up the controller with the Manager.
func (r *DatabaseSoftwareImageReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&databasev1beta1.DatabaseSoftwareImage{})
	return builder.
		WithEventFilter(predicate.GenerationChangedPredicate{}).
		Complete(r)
}
