/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package alertpolicy

import (
	"context"
	"fmt"

	datasafesdk "github.com/oracle/oci-go-sdk/v65/datasafe"
	datasafev1beta1 "github.com/oracle/oci-service-operator/api/datasafe/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AlertPolicyServiceClient is the handwritten extension seam for AlertPolicy runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*AlertPolicyServiceManager).WithClient.
type AlertPolicyServiceClient interface {
	CreateOrUpdate(context.Context, *datasafev1beta1.AlertPolicy, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *datasafev1beta1.AlertPolicy) (bool, error)
}

type defaultAlertPolicyServiceClient struct {
	generatedruntime.ServiceClient[*datasafev1beta1.AlertPolicy]
}

var _ AlertPolicyServiceClient = defaultAlertPolicyServiceClient{}

var newAlertPolicyServiceClient = func(manager *AlertPolicyServiceManager) AlertPolicyServiceClient {
	sdkClient, err := datasafesdk.NewDataSafeClientWithConfigurationProvider(manager.Provider)
	hooks := newAlertPolicyRuntimeHooks(manager, sdkClient)
	config := buildAlertPolicyGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize AlertPolicy OCI client: %w", err)
	}
	delegate := defaultAlertPolicyServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*datasafev1beta1.AlertPolicy](config),
	}
	return wrapAlertPolicyGeneratedClient(hooks, delegate)
}
