package sdk

import (
	"path"
	"reflect"

	"github.com/oracle/oci-go-sdk/v65/containerengine"
	"github.com/oracle/oci-go-sdk/v65/database"
	"github.com/oracle/oci-go-sdk/v65/mysql"
	"github.com/oracle/oci-go-sdk/v65/nosql"
	"github.com/oracle/oci-go-sdk/v65/psql"
	"github.com/oracle/oci-go-sdk/v65/streaming"
)

const (
	modulePath    = "github.com/oracle/oci-go-sdk/v65"
	moduleVersion = "v65.61.1"
)

var seedTargets = []Target{
	// Autonomous Database CRD support
	newTarget("database", "CreateApplicationVipDetails", reflect.TypeOf(database.CreateApplicationVipDetails{})),
	newTarget("database", "CreateAutonomousContainerDatabaseDataguardAssociationDetails", reflect.TypeOf(database.CreateAutonomousContainerDatabaseDataguardAssociationDetails{})),
	newTarget("database", "CreateAutonomousContainerDatabaseDetails", reflect.TypeOf(database.CreateAutonomousContainerDatabaseDetails{})),
	newTarget("database", "CreateAutonomousDatabaseBackupDetails", reflect.TypeOf(database.CreateAutonomousDatabaseBackupDetails{})),
	newTarget("database", "CreateAutonomousDatabaseCloneDetails", reflect.TypeOf(database.CreateAutonomousDatabaseCloneDetails{})),
	newTarget("database", "CreateAutonomousDatabaseDetails", reflect.TypeOf(database.CreateAutonomousDatabaseDetails{})),
	newTarget("database", "CreateAutonomousVmClusterDetails", reflect.TypeOf(database.CreateAutonomousVmClusterDetails{})),
	newTarget("database", "CreateBackupDetails", reflect.TypeOf(database.CreateBackupDetails{})),
	newTarget("database", "CreateCloudAutonomousVmClusterDetails", reflect.TypeOf(database.CreateCloudAutonomousVmClusterDetails{})),
	newTarget("database", "CreateCloudExadataInfrastructureDetails", reflect.TypeOf(database.CreateCloudExadataInfrastructureDetails{})),
	newTarget("database", "CreateCloudVmClusterDetails", reflect.TypeOf(database.CreateCloudVmClusterDetails{})),
	newTarget("database", "CreateConsoleConnectionDetails", reflect.TypeOf(database.CreateConsoleConnectionDetails{})),
	newTarget("database", "CreateConsoleHistoryDetails", reflect.TypeOf(database.CreateConsoleHistoryDetails{})),
	newTarget("database", "CreateDataGuardAssociationToExistingDbSystemDetails", reflect.TypeOf(database.CreateDataGuardAssociationToExistingDbSystemDetails{})),
	newTarget("database", "CreateDataGuardAssociationToExistingVmClusterDetails", reflect.TypeOf(database.CreateDataGuardAssociationToExistingVmClusterDetails{})),
	newTarget("database", "CreateDataGuardAssociationWithNewDbSystemDetails", reflect.TypeOf(database.CreateDataGuardAssociationWithNewDbSystemDetails{})),
	newTarget("database", "CreateDatabaseDetails", reflect.TypeOf(database.CreateDatabaseDetails{})),
	newTarget("database", "CreateDatabaseSoftwareImageDetails", reflect.TypeOf(database.CreateDatabaseSoftwareImageDetails{})),
	newTarget("database", "CreateDbHomeDetails", reflect.TypeOf(database.CreateDbHomeDetails{})),
	newTarget("database", "CreateExadataInfrastructureDetails", reflect.TypeOf(database.CreateExadataInfrastructureDetails{})),
	newTarget("database", "CreateExternalBackupJobDetails", reflect.TypeOf(database.CreateExternalBackupJobDetails{})),
	newTarget("database", "CreateExternalContainerDatabaseDetails", reflect.TypeOf(database.CreateExternalContainerDatabaseDetails{})),
	newTarget("database", "CreateExternalMacsConnectorDetails", reflect.TypeOf(database.CreateExternalMacsConnectorDetails{})),
	newTarget("database", "CreateExternalNonContainerDatabaseDetails", reflect.TypeOf(database.CreateExternalNonContainerDatabaseDetails{})),
	newTarget("database", "CreateExternalPluggableDatabaseDetails", reflect.TypeOf(database.CreateExternalPluggableDatabaseDetails{})),
	newTarget("database", "CreateKeyStoreDetails", reflect.TypeOf(database.CreateKeyStoreDetails{})),
	newTarget("database", "CreateMaintenanceRunDetails", reflect.TypeOf(database.CreateMaintenanceRunDetails{})),
	newTarget("database", "CreateNfsBackupDestinationDetails", reflect.TypeOf(database.CreateNfsBackupDestinationDetails{})),
	newTarget("database", "CreateOneoffPatchDetails", reflect.TypeOf(database.CreateOneoffPatchDetails{})),
	newTarget("database", "CreatePluggableDatabaseDetails", reflect.TypeOf(database.CreatePluggableDatabaseDetails{})),
	newTarget("database", "CreateRecoveryApplianceBackupDestinationDetails", reflect.TypeOf(database.CreateRecoveryApplianceBackupDestinationDetails{})),
	newTarget("database", "CreateVmClusterDetails", reflect.TypeOf(database.CreateVmClusterDetails{})),
	newTarget("database", "UpdateAutonomousContainerDatabaseDetails", reflect.TypeOf(database.UpdateAutonomousContainerDatabaseDetails{})),
	newTarget("database", "UpdateAutonomousDatabaseBackupDetails", reflect.TypeOf(database.UpdateAutonomousDatabaseBackupDetails{})),
	newTarget("database", "UpdateAutonomousDatabaseDetails", reflect.TypeOf(database.UpdateAutonomousDatabaseDetails{})),
	newTarget("database", "UpdateAutonomousDatabaseWalletDetails", reflect.TypeOf(database.UpdateAutonomousDatabaseWalletDetails{})),
	newTarget("database", "UpdateAutonomousExadataInfrastructureDetails", reflect.TypeOf(database.UpdateAutonomousExadataInfrastructureDetails{})),
	newTarget("database", "UpdateAutonomousVmClusterDetails", reflect.TypeOf(database.UpdateAutonomousVmClusterDetails{})),
	newTarget("database", "UpdateBackupDestinationDetails", reflect.TypeOf(database.UpdateBackupDestinationDetails{})),
	newTarget("database", "UpdateCloudAutonomousVmClusterDetails", reflect.TypeOf(database.UpdateCloudAutonomousVmClusterDetails{})),
	newTarget("database", "UpdateCloudExadataInfrastructureDetails", reflect.TypeOf(database.UpdateCloudExadataInfrastructureDetails{})),
	newTarget("database", "UpdateCloudVmClusterDetails", reflect.TypeOf(database.UpdateCloudVmClusterDetails{})),
	newTarget("database", "UpdateConsoleConnectionDetails", reflect.TypeOf(database.UpdateConsoleConnectionDetails{})),
	newTarget("database", "UpdateConsoleHistoryDetails", reflect.TypeOf(database.UpdateConsoleHistoryDetails{})),
	newTarget("database", "UpdateDataGuardAssociationDetails", reflect.TypeOf(database.UpdateDataGuardAssociationDetails{})),
	newTarget("database", "UpdateDatabaseDetails", reflect.TypeOf(database.UpdateDatabaseDetails{})),
	newTarget("database", "UpdateDatabaseSoftwareImageDetails", reflect.TypeOf(database.UpdateDatabaseSoftwareImageDetails{})),
	newTarget("database", "UpdateDbHomeDetails", reflect.TypeOf(database.UpdateDbHomeDetails{})),
	newTarget("database", "UpdateDbNodeDetails", reflect.TypeOf(database.UpdateDbNodeDetails{})),
	newTarget("database", "UpdateDbSystemDetails", reflect.TypeOf(database.UpdateDbSystemDetails{})),
	newTarget("database", "UpdateExadataInfrastructureDetails", reflect.TypeOf(database.UpdateExadataInfrastructureDetails{})),
	newTarget("database", "UpdateExternalContainerDatabaseDetails", reflect.TypeOf(database.UpdateExternalContainerDatabaseDetails{})),
	newTarget("database", "UpdateExternalMacsConnectorDetails", reflect.TypeOf(database.UpdateExternalMacsConnectorDetails{})),
	newTarget("database", "UpdateExternalNonContainerDatabaseDetails", reflect.TypeOf(database.UpdateExternalNonContainerDatabaseDetails{})),
	newTarget("database", "UpdateExternalPluggableDatabaseDetails", reflect.TypeOf(database.UpdateExternalPluggableDatabaseDetails{})),
	newTarget("database", "UpdateKeyStoreDetails", reflect.TypeOf(database.UpdateKeyStoreDetails{})),
	newTarget("database", "UpdateMaintenanceRunDetails", reflect.TypeOf(database.UpdateMaintenanceRunDetails{})),
	newTarget("database", "UpdateOneoffPatchDetails", reflect.TypeOf(database.UpdateOneoffPatchDetails{})),
	newTarget("database", "UpdatePluggableDatabaseDetails", reflect.TypeOf(database.UpdatePluggableDatabaseDetails{})),
	newTarget("database", "UpdateVmClusterDetails", reflect.TypeOf(database.UpdateVmClusterDetails{})),
	newTarget("database", "UpdateVmClusterNetworkDetails", reflect.TypeOf(database.UpdateVmClusterNetworkDetails{})),
	newTarget("database", "BackupDestinationDetails", reflect.TypeOf(database.BackupDestinationDetails{})),
	newTarget("database", "DbServerDetails", reflect.TypeOf(database.DbServerDetails{})),
	newTarget("database", "ExadataIormConfigUpdateDetails", reflect.TypeOf(database.ExadataIormConfigUpdateDetails{})),
	newTarget("database", "GenerateAutonomousDatabaseWalletDetails", reflect.TypeOf(database.GenerateAutonomousDatabaseWalletDetails{})),
	newTarget("database", "VmClusterNetworkDetails", reflect.TypeOf(database.VmClusterNetworkDetails{})),
	newTarget("database", "VmClusterUpdateDetails", reflect.TypeOf(database.VmClusterUpdateDetails{})),
	newTarget("database", "ApplicationVip", reflect.TypeOf(database.ApplicationVip{})),
	newTarget("database", "AutonomousContainerDatabase", reflect.TypeOf(database.AutonomousContainerDatabase{})),
	newTarget("database", "AutonomousContainerDatabaseDataguardAssociation", reflect.TypeOf(database.AutonomousContainerDatabaseDataguardAssociation{})),
	newTarget("database", "AutonomousContainerDatabaseResourceUsage", reflect.TypeOf(database.AutonomousContainerDatabaseResourceUsage{})),
	newTarget("database", "AutonomousDatabase", reflect.TypeOf(database.AutonomousDatabase{})),
	newTarget("database", "AutonomousDatabaseBackup", reflect.TypeOf(database.AutonomousDatabaseBackup{})),
	newTarget("database", "AutonomousDatabaseCharacterSets", reflect.TypeOf(database.AutonomousDatabaseCharacterSets{})),
	newTarget("database", "AutonomousDatabaseDataguardAssociation", reflect.TypeOf(database.AutonomousDatabaseDataguardAssociation{})),
	newTarget("database", "AutonomousDatabaseWallet", reflect.TypeOf(database.AutonomousDatabaseWallet{})),
	newTarget("database", "AutonomousExadataInfrastructure", reflect.TypeOf(database.AutonomousExadataInfrastructure{})),
	newTarget("database", "AutonomousPatch", reflect.TypeOf(database.AutonomousPatch{})),
	newTarget("database", "AutonomousVirtualMachine", reflect.TypeOf(database.AutonomousVirtualMachine{})),
	newTarget("database", "AutonomousVmCluster", reflect.TypeOf(database.AutonomousVmCluster{})),
	newTarget("database", "AutonomousVmClusterResourceUsage", reflect.TypeOf(database.AutonomousVmClusterResourceUsage{})),
	newTarget("database", "Backup", reflect.TypeOf(database.Backup{})),
	newTarget("database", "BackupDestination", reflect.TypeOf(database.BackupDestination{})),
	newTarget("database", "CloudAutonomousVmCluster", reflect.TypeOf(database.CloudAutonomousVmCluster{})),
	newTarget("database", "CloudAutonomousVmClusterResourceUsage", reflect.TypeOf(database.CloudAutonomousVmClusterResourceUsage{})),
	newTarget("database", "CloudExadataInfrastructure", reflect.TypeOf(database.CloudExadataInfrastructure{})),
	newTarget("database", "CloudExadataInfrastructureUnallocatedResources", reflect.TypeOf(database.CloudExadataInfrastructureUnallocatedResources{})),
	newTarget("database", "CloudVmCluster", reflect.TypeOf(database.CloudVmCluster{})),
	newTarget("database", "ConsoleConnection", reflect.TypeOf(database.ConsoleConnection{})),
	newTarget("database", "ConsoleHistory", reflect.TypeOf(database.ConsoleHistory{})),
	newTarget("database", "ConsoleHistoryCollection", reflect.TypeOf(database.ConsoleHistoryCollection{})),
	newTarget("database", "DataGuardAssociation", reflect.TypeOf(database.DataGuardAssociation{})),
	newTarget("database", "Database", reflect.TypeOf(database.Database{})),
	newTarget("database", "DatabaseSoftwareImage", reflect.TypeOf(database.DatabaseSoftwareImage{})),
	newTarget("database", "DatabaseUpgradeHistoryEntry", reflect.TypeOf(database.DatabaseUpgradeHistoryEntry{})),
	newTarget("database", "DbHome", reflect.TypeOf(database.DbHome{})),
	newTarget("database", "DbNode", reflect.TypeOf(database.DbNode{})),
	newTarget("database", "DbServer", reflect.TypeOf(database.DbServer{})),
	newTarget("database", "DbSystem", reflect.TypeOf(database.DbSystem{})),
	newTarget("database", "DbSystemUpgradeHistoryEntry", reflect.TypeOf(database.DbSystemUpgradeHistoryEntry{})),
	newTarget("database", "ExadataInfrastructure", reflect.TypeOf(database.ExadataInfrastructure{})),
	newTarget("database", "ExadataInfrastructureUnAllocatedResources", reflect.TypeOf(database.ExadataInfrastructureUnAllocatedResources{})),
	newTarget("database", "ExadataIormConfig", reflect.TypeOf(database.ExadataIormConfig{})),
	newTarget("database", "ExternalBackupJob", reflect.TypeOf(database.ExternalBackupJob{})),
	newTarget("database", "ExternalContainerDatabase", reflect.TypeOf(database.ExternalContainerDatabase{})),
	newTarget("database", "ExternalMacsConnector", reflect.TypeOf(database.ExternalMacsConnector{})),
	newTarget("database", "ExternalNonContainerDatabase", reflect.TypeOf(database.ExternalNonContainerDatabase{})),
	newTarget("database", "ExternalPluggableDatabase", reflect.TypeOf(database.ExternalPluggableDatabase{})),
	newTarget("database", "FlexComponentCollection", reflect.TypeOf(database.FlexComponentCollection{})),
	newTarget("database", "InfrastructureTargetVersion", reflect.TypeOf(database.InfrastructureTargetVersion{})),
	newTarget("database", "KeyStore", reflect.TypeOf(database.KeyStore{})),
	newTarget("database", "MaintenanceRun", reflect.TypeOf(database.MaintenanceRun{})),
	newTarget("database", "MaintenanceRunHistory", reflect.TypeOf(database.MaintenanceRunHistory{})),
	newTarget("database", "OcpUs", reflect.TypeOf(database.OcpUs{})),
	newTarget("database", "OneoffPatch", reflect.TypeOf(database.OneoffPatch{})),
	newTarget("database", "Patch", reflect.TypeOf(database.Patch{})),
	newTarget("database", "PatchHistoryEntry", reflect.TypeOf(database.PatchHistoryEntry{})),
	newTarget("database", "PdbConversionHistoryEntry", reflect.TypeOf(database.PdbConversionHistoryEntry{})),
	newTarget("database", "PluggableDatabase", reflect.TypeOf(database.PluggableDatabase{})),
	newTarget("database", "SystemVersionCollection", reflect.TypeOf(database.SystemVersionCollection{})),
	newTarget("database", "Update", reflect.TypeOf(database.Update{})),
	newTarget("database", "UpdateHistoryEntry", reflect.TypeOf(database.UpdateHistoryEntry{})),
	newTarget("database", "VmCluster", reflect.TypeOf(database.VmCluster{})),
	newTarget("database", "VmClusterNetwork", reflect.TypeOf(database.VmClusterNetwork{})),
	newTarget("database", "VmClusterUpdate", reflect.TypeOf(database.VmClusterUpdate{})),
	newTarget("database", "VmClusterUpdateHistoryEntry", reflect.TypeOf(database.VmClusterUpdateHistoryEntry{})),
	newTarget("database", "AutonomousContainerDatabaseVersionSummary", reflect.TypeOf(database.AutonomousContainerDatabaseVersionSummary{})),
	newTarget("database", "AutonomousDbPreviewVersionSummary", reflect.TypeOf(database.AutonomousDbPreviewVersionSummary{})),
	newTarget("database", "AutonomousDbVersionSummary", reflect.TypeOf(database.AutonomousDbVersionSummary{})),
	newTarget("database", "DbVersionSummary", reflect.TypeOf(database.DbVersionSummary{})),
	newTarget("database", "GiVersionSummary", reflect.TypeOf(database.GiVersionSummary{})),
	newTarget("database", "InfrastructureTargetVersionSummary", reflect.TypeOf(database.InfrastructureTargetVersionSummary{})),
	newTarget("database", "SystemVersionSummary", reflect.TypeOf(database.SystemVersionSummary{})),
	newTarget("database", "ApplicationVipSummary", reflect.TypeOf(database.ApplicationVipSummary{})),
	newTarget("database", "AutonomousContainerDatabaseSummary", reflect.TypeOf(database.AutonomousContainerDatabaseSummary{})),
	newTarget("database", "AutonomousDatabaseBackupSummary", reflect.TypeOf(database.AutonomousDatabaseBackupSummary{})),
	newTarget("database", "AutonomousDatabaseSummary", reflect.TypeOf(database.AutonomousDatabaseSummary{})),
	newTarget("database", "AutonomousExadataInfrastructureShapeSummary", reflect.TypeOf(database.AutonomousExadataInfrastructureShapeSummary{})),
	newTarget("database", "AutonomousExadataInfrastructureSummary", reflect.TypeOf(database.AutonomousExadataInfrastructureSummary{})),
	newTarget("database", "AutonomousPatchSummary", reflect.TypeOf(database.AutonomousPatchSummary{})),
	newTarget("database", "AutonomousVirtualMachineSummary", reflect.TypeOf(database.AutonomousVirtualMachineSummary{})),
	newTarget("database", "AutonomousVmClusterSummary", reflect.TypeOf(database.AutonomousVmClusterSummary{})),
	newTarget("database", "BackupDestinationSummary", reflect.TypeOf(database.BackupDestinationSummary{})),
	newTarget("database", "BackupSummary", reflect.TypeOf(database.BackupSummary{})),
	newTarget("database", "CloudAutonomousVmClusterSummary", reflect.TypeOf(database.CloudAutonomousVmClusterSummary{})),
	newTarget("database", "CloudExadataInfrastructureSummary", reflect.TypeOf(database.CloudExadataInfrastructureSummary{})),
	newTarget("database", "CloudVmClusterSummary", reflect.TypeOf(database.CloudVmClusterSummary{})),
	newTarget("database", "ConsoleConnectionSummary", reflect.TypeOf(database.ConsoleConnectionSummary{})),
	newTarget("database", "ConsoleHistorySummary", reflect.TypeOf(database.ConsoleHistorySummary{})),
	newTarget("database", "DataGuardAssociationSummary", reflect.TypeOf(database.DataGuardAssociationSummary{})),
	newTarget("database", "DatabaseSoftwareImageSummary", reflect.TypeOf(database.DatabaseSoftwareImageSummary{})),
	newTarget("database", "DatabaseSummary", reflect.TypeOf(database.DatabaseSummary{})),
	newTarget("database", "DatabaseUpgradeHistoryEntrySummary", reflect.TypeOf(database.DatabaseUpgradeHistoryEntrySummary{})),
	newTarget("database", "DbHomeSummary", reflect.TypeOf(database.DbHomeSummary{})),
	newTarget("database", "DbNodeSummary", reflect.TypeOf(database.DbNodeSummary{})),
	newTarget("database", "DbServerSummary", reflect.TypeOf(database.DbServerSummary{})),
	newTarget("database", "DbSystemComputePerformanceSummary", reflect.TypeOf(database.DbSystemComputePerformanceSummary{})),
	newTarget("database", "DbSystemShapeSummary", reflect.TypeOf(database.DbSystemShapeSummary{})),
	newTarget("database", "DbSystemStoragePerformanceSummary", reflect.TypeOf(database.DbSystemStoragePerformanceSummary{})),
	newTarget("database", "DbSystemSummary", reflect.TypeOf(database.DbSystemSummary{})),
	newTarget("database", "DbSystemUpgradeHistoryEntrySummary", reflect.TypeOf(database.DbSystemUpgradeHistoryEntrySummary{})),
	newTarget("database", "ExadataInfrastructureSummary", reflect.TypeOf(database.ExadataInfrastructureSummary{})),
	newTarget("database", "ExternalContainerDatabaseSummary", reflect.TypeOf(database.ExternalContainerDatabaseSummary{})),
	newTarget("database", "ExternalMacsConnectorSummary", reflect.TypeOf(database.ExternalMacsConnectorSummary{})),
	newTarget("database", "ExternalNonContainerDatabaseSummary", reflect.TypeOf(database.ExternalNonContainerDatabaseSummary{})),
	newTarget("database", "ExternalPluggableDatabaseSummary", reflect.TypeOf(database.ExternalPluggableDatabaseSummary{})),
	newTarget("database", "FlexComponentSummary", reflect.TypeOf(database.FlexComponentSummary{})),
	newTarget("database", "KeyStoreSummary", reflect.TypeOf(database.KeyStoreSummary{})),
	newTarget("database", "MaintenanceRunHistorySummary", reflect.TypeOf(database.MaintenanceRunHistorySummary{})),
	newTarget("database", "MaintenanceRunSummary", reflect.TypeOf(database.MaintenanceRunSummary{})),
	newTarget("database", "OneoffPatchSummary", reflect.TypeOf(database.OneoffPatchSummary{})),
	newTarget("database", "PatchHistoryEntrySummary", reflect.TypeOf(database.PatchHistoryEntrySummary{})),
	newTarget("database", "PatchSummary", reflect.TypeOf(database.PatchSummary{})),
	newTarget("database", "PdbConversionHistoryEntrySummary", reflect.TypeOf(database.PdbConversionHistoryEntrySummary{})),
	newTarget("database", "PluggableDatabaseSummary", reflect.TypeOf(database.PluggableDatabaseSummary{})),
	newTarget("database", "RefreshableCloneSummary", reflect.TypeOf(database.RefreshableCloneSummary{})),
	newTarget("database", "UpdateHistoryEntrySummary", reflect.TypeOf(database.UpdateHistoryEntrySummary{})),
	newTarget("database", "UpdateSummary", reflect.TypeOf(database.UpdateSummary{})),
	newTarget("database", "VmClusterNetworkSummary", reflect.TypeOf(database.VmClusterNetworkSummary{})),
	newTarget("database", "VmClusterSummary", reflect.TypeOf(database.VmClusterSummary{})),
	newTarget("database", "VmClusterUpdateHistoryEntrySummary", reflect.TypeOf(database.VmClusterUpdateHistoryEntrySummary{})),
	newTarget("database", "VmClusterUpdateSummary", reflect.TypeOf(database.VmClusterUpdateSummary{})),

	// MySQL DB System CRD support
	newTarget("mysql", "CreateBackupDetails", reflect.TypeOf(mysql.CreateBackupDetails{})),
	newTarget("mysql", "CreateChannelDetails", reflect.TypeOf(mysql.CreateChannelDetails{})),
	newTarget("mysql", "CreateConfigurationDetails", reflect.TypeOf(mysql.CreateConfigurationDetails{})),
	newTarget("mysql", "CreateDbSystemDetails", reflect.TypeOf(mysql.CreateDbSystemDetails{})),
	newTarget("mysql", "CreateReplicaDetails", reflect.TypeOf(mysql.CreateReplicaDetails{})),
	newTarget("mysql", "UpdateBackupDetails", reflect.TypeOf(mysql.UpdateBackupDetails{})),
	newTarget("mysql", "UpdateChannelDetails", reflect.TypeOf(mysql.UpdateChannelDetails{})),
	newTarget("mysql", "UpdateConfigurationDetails", reflect.TypeOf(mysql.UpdateConfigurationDetails{})),
	newTarget("mysql", "UpdateDbSystemDetails", reflect.TypeOf(mysql.UpdateDbSystemDetails{})),
	newTarget("mysql", "UpdateHeatWaveClusterDetails", reflect.TypeOf(mysql.UpdateHeatWaveClusterDetails{})),
	newTarget("mysql", "UpdateReplicaDetails", reflect.TypeOf(mysql.UpdateReplicaDetails{})),
	newTarget("mysql", "Backup", reflect.TypeOf(mysql.Backup{})),
	newTarget("mysql", "Channel", reflect.TypeOf(mysql.Channel{})),
	newTarget("mysql", "Configuration", reflect.TypeOf(mysql.Configuration{})),
	newTarget("mysql", "DbSystem", reflect.TypeOf(mysql.DbSystem{})),
	newTarget("mysql", "HeatWaveCluster", reflect.TypeOf(mysql.HeatWaveCluster{})),
	newTarget("mysql", "HeatWaveClusterMemoryEstimate", reflect.TypeOf(mysql.HeatWaveClusterMemoryEstimate{})),
	newTarget("mysql", "Replica", reflect.TypeOf(mysql.Replica{})),
	newTarget("mysql", "Version", reflect.TypeOf(mysql.Version{})),
	newTarget("mysql", "WorkRequest", reflect.TypeOf(mysql.WorkRequest{})),
	newTarget("mysql", "WorkRequestError", reflect.TypeOf(mysql.WorkRequestError{})),
	newTarget("mysql", "WorkRequestLogEntry", reflect.TypeOf(mysql.WorkRequestLogEntry{})),
	newTarget("mysql", "VersionSummary", reflect.TypeOf(mysql.VersionSummary{})),
	newTarget("mysql", "BackupSummary", reflect.TypeOf(mysql.BackupSummary{})),
	newTarget("mysql", "ChannelSummary", reflect.TypeOf(mysql.ChannelSummary{})),
	newTarget("mysql", "ConfigurationSummary", reflect.TypeOf(mysql.ConfigurationSummary{})),
	newTarget("mysql", "DbSystemSummary", reflect.TypeOf(mysql.DbSystemSummary{})),
	newTarget("mysql", "HeatWaveClusterSummary", reflect.TypeOf(mysql.HeatWaveClusterSummary{})),
	newTarget("mysql", "ReplicaSummary", reflect.TypeOf(mysql.ReplicaSummary{})),
	newTarget("mysql", "ShapeSummary", reflect.TypeOf(mysql.ShapeSummary{})),
	newTarget("mysql", "WorkRequestSummary", reflect.TypeOf(mysql.WorkRequestSummary{})),

	// Streaming CRD support
	newTarget("streaming", "CreateConnectHarnessDetails", reflect.TypeOf(streaming.CreateConnectHarnessDetails{})),
	newTarget("streaming", "CreateCursorDetails", reflect.TypeOf(streaming.CreateCursorDetails{})),
	newTarget("streaming", "CreateGroupCursorDetails", reflect.TypeOf(streaming.CreateGroupCursorDetails{})),
	newTarget("streaming", "CreateStreamDetails", reflect.TypeOf(streaming.CreateStreamDetails{})),
	newTarget("streaming", "CreateStreamPoolDetails", reflect.TypeOf(streaming.CreateStreamPoolDetails{})),
	newTarget("streaming", "UpdateConnectHarnessDetails", reflect.TypeOf(streaming.UpdateConnectHarnessDetails{})),
	newTarget("streaming", "UpdateGroupDetails", reflect.TypeOf(streaming.UpdateGroupDetails{})),
	newTarget("streaming", "UpdateStreamDetails", reflect.TypeOf(streaming.UpdateStreamDetails{})),
	newTarget("streaming", "UpdateStreamPoolDetails", reflect.TypeOf(streaming.UpdateStreamPoolDetails{})),
	newTarget("streaming", "ConnectHarness", reflect.TypeOf(streaming.ConnectHarness{})),
	newTarget("streaming", "Cursor", reflect.TypeOf(streaming.Cursor{})),
	newTarget("streaming", "Group", reflect.TypeOf(streaming.Group{})),
	newTarget("streaming", "Message", reflect.TypeOf(streaming.Message{})),
	newTarget("streaming", "Stream", reflect.TypeOf(streaming.Stream{})),
	newTarget("streaming", "StreamPool", reflect.TypeOf(streaming.StreamPool{})),
	newTarget("streaming", "ConnectHarnessSummary", reflect.TypeOf(streaming.ConnectHarnessSummary{})),
	newTarget("streaming", "StreamPoolSummary", reflect.TypeOf(streaming.StreamPoolSummary{})),
	newTarget("streaming", "StreamSummary", reflect.TypeOf(streaming.StreamSummary{})),

	// NoSQL CRD support
	newTarget("nosql", "CreateIndexDetails", reflect.TypeOf(nosql.CreateIndexDetails{})),
	newTarget("nosql", "CreateReplicaDetails", reflect.TypeOf(nosql.CreateReplicaDetails{})),
	newTarget("nosql", "CreateTableDetails", reflect.TypeOf(nosql.CreateTableDetails{})),
	newTarget("nosql", "UpdateRowDetails", reflect.TypeOf(nosql.UpdateRowDetails{})),
	newTarget("nosql", "UpdateTableDetails", reflect.TypeOf(nosql.UpdateTableDetails{})),
	newTarget("nosql", "Index", reflect.TypeOf(nosql.Index{})),
	newTarget("nosql", "IndexCollection", reflect.TypeOf(nosql.IndexCollection{})),
	newTarget("nosql", "Replica", reflect.TypeOf(nosql.Replica{})),
	newTarget("nosql", "Row", reflect.TypeOf(nosql.Row{})),
	newTarget("nosql", "Table", reflect.TypeOf(nosql.Table{})),
	newTarget("nosql", "TableCollection", reflect.TypeOf(nosql.TableCollection{})),
	newTarget("nosql", "TableUsageCollection", reflect.TypeOf(nosql.TableUsageCollection{})),
	newTarget("nosql", "WorkRequest", reflect.TypeOf(nosql.WorkRequest{})),
	newTarget("nosql", "WorkRequestCollection", reflect.TypeOf(nosql.WorkRequestCollection{})),
	newTarget("nosql", "WorkRequestError", reflect.TypeOf(nosql.WorkRequestError{})),
	newTarget("nosql", "WorkRequestErrorCollection", reflect.TypeOf(nosql.WorkRequestErrorCollection{})),
	newTarget("nosql", "WorkRequestLogEntry", reflect.TypeOf(nosql.WorkRequestLogEntry{})),
	newTarget("nosql", "WorkRequestLogEntryCollection", reflect.TypeOf(nosql.WorkRequestLogEntryCollection{})),
	newTarget("nosql", "IndexSummary", reflect.TypeOf(nosql.IndexSummary{})),
	newTarget("nosql", "TableSummary", reflect.TypeOf(nosql.TableSummary{})),
	newTarget("nosql", "TableUsageSummary", reflect.TypeOf(nosql.TableUsageSummary{})),
	newTarget("nosql", "WorkRequestSummary", reflect.TypeOf(nosql.WorkRequestSummary{})),

	// PostgreSQL CRD support
	newTarget("psql", "CreateBackupDetails", reflect.TypeOf(psql.CreateBackupDetails{})),
	newTarget("psql", "CreateConfigurationDetails", reflect.TypeOf(psql.CreateConfigurationDetails{})),
	newTarget("psql", "CreateDbSystemDetails", reflect.TypeOf(psql.CreateDbSystemDetails{})),
	newTarget("psql", "UpdateBackupDetails", reflect.TypeOf(psql.UpdateBackupDetails{})),
	newTarget("psql", "UpdateConfigurationDetails", reflect.TypeOf(psql.UpdateConfigurationDetails{})),
	newTarget("psql", "UpdateDbSystemDbInstanceDetails", reflect.TypeOf(psql.UpdateDbSystemDbInstanceDetails{})),
	newTarget("psql", "UpdateDbSystemDetails", reflect.TypeOf(psql.UpdateDbSystemDetails{})),
	newTarget("psql", "ConfigurationDetails", reflect.TypeOf(psql.ConfigurationDetails{})),
	newTarget("psql", "ConnectionDetails", reflect.TypeOf(psql.ConnectionDetails{})),
	newTarget("psql", "DbSystemDetails", reflect.TypeOf(psql.DbSystemDetails{})),
	newTarget("psql", "DefaultConfigurationDetails", reflect.TypeOf(psql.DefaultConfigurationDetails{})),
	newTarget("psql", "PrimaryDbInstanceDetails", reflect.TypeOf(psql.PrimaryDbInstanceDetails{})),
	newTarget("psql", "Backup", reflect.TypeOf(psql.Backup{})),
	newTarget("psql", "BackupCollection", reflect.TypeOf(psql.BackupCollection{})),
	newTarget("psql", "Configuration", reflect.TypeOf(psql.Configuration{})),
	newTarget("psql", "ConfigurationCollection", reflect.TypeOf(psql.ConfigurationCollection{})),
	newTarget("psql", "DbSystem", reflect.TypeOf(psql.DbSystem{})),
	newTarget("psql", "DbSystemCollection", reflect.TypeOf(psql.DbSystemCollection{})),
	newTarget("psql", "DefaultConfiguration", reflect.TypeOf(psql.DefaultConfiguration{})),
	newTarget("psql", "DefaultConfigurationCollection", reflect.TypeOf(psql.DefaultConfigurationCollection{})),
	newTarget("psql", "ShapeCollection", reflect.TypeOf(psql.ShapeCollection{})),
	newTarget("psql", "WorkRequest", reflect.TypeOf(psql.WorkRequest{})),
	newTarget("psql", "WorkRequestError", reflect.TypeOf(psql.WorkRequestError{})),
	newTarget("psql", "WorkRequestErrorCollection", reflect.TypeOf(psql.WorkRequestErrorCollection{})),
	newTarget("psql", "WorkRequestLogEntry", reflect.TypeOf(psql.WorkRequestLogEntry{})),
	newTarget("psql", "WorkRequestLogEntryCollection", reflect.TypeOf(psql.WorkRequestLogEntryCollection{})),
	newTarget("psql", "BackupSummary", reflect.TypeOf(psql.BackupSummary{})),
	newTarget("psql", "ConfigurationSummary", reflect.TypeOf(psql.ConfigurationSummary{})),
	newTarget("psql", "DbSystemSummary", reflect.TypeOf(psql.DbSystemSummary{})),
	newTarget("psql", "DefaultConfigurationSummary", reflect.TypeOf(psql.DefaultConfigurationSummary{})),
	newTarget("psql", "ShapeSummary", reflect.TypeOf(psql.ShapeSummary{})),
	newTarget("psql", "WorkRequestSummary", reflect.TypeOf(psql.WorkRequestSummary{})),

	// Container Engine CRD support
	newTarget("containerengine", "CreateClusterDetails", reflect.TypeOf(containerengine.CreateClusterDetails{})),
	newTarget("containerengine", "CreateClusterEndpointConfigDetails", reflect.TypeOf(containerengine.CreateClusterEndpointConfigDetails{})),
	newTarget("containerengine", "CreateClusterKubeconfigContentDetails", reflect.TypeOf(containerengine.CreateClusterKubeconfigContentDetails{})),
	newTarget("containerengine", "CreateNodePoolDetails", reflect.TypeOf(containerengine.CreateNodePoolDetails{})),
	newTarget("containerengine", "CreateVirtualNodePoolDetails", reflect.TypeOf(containerengine.CreateVirtualNodePoolDetails{})),
	newTarget("containerengine", "CreateWorkloadMappingDetails", reflect.TypeOf(containerengine.CreateWorkloadMappingDetails{})),
	newTarget("containerengine", "UpdateAddonDetails", reflect.TypeOf(containerengine.UpdateAddonDetails{})),
	newTarget("containerengine", "UpdateClusterDetails", reflect.TypeOf(containerengine.UpdateClusterDetails{})),
	newTarget("containerengine", "UpdateClusterEndpointConfigDetails", reflect.TypeOf(containerengine.UpdateClusterEndpointConfigDetails{})),
	newTarget("containerengine", "UpdateNodePoolDetails", reflect.TypeOf(containerengine.UpdateNodePoolDetails{})),
	newTarget("containerengine", "UpdateVirtualNodePoolDetails", reflect.TypeOf(containerengine.UpdateVirtualNodePoolDetails{})),
	newTarget("containerengine", "UpdateWorkloadMappingDetails", reflect.TypeOf(containerengine.UpdateWorkloadMappingDetails{})),
	newTarget("containerengine", "Addon", reflect.TypeOf(containerengine.Addon{})),
	newTarget("containerengine", "Cluster", reflect.TypeOf(containerengine.Cluster{})),
	newTarget("containerengine", "ClusterEndpointConfig", reflect.TypeOf(containerengine.ClusterEndpointConfig{})),
	newTarget("containerengine", "ClusterMigrateToNativeVcnStatus", reflect.TypeOf(containerengine.ClusterMigrateToNativeVcnStatus{})),
	newTarget("containerengine", "ClusterOptions", reflect.TypeOf(containerengine.ClusterOptions{})),
	newTarget("containerengine", "CredentialRotationStatus", reflect.TypeOf(containerengine.CredentialRotationStatus{})),
	newTarget("containerengine", "Node", reflect.TypeOf(containerengine.Node{})),
	newTarget("containerengine", "NodePool", reflect.TypeOf(containerengine.NodePool{})),
	newTarget("containerengine", "NodePoolOptions", reflect.TypeOf(containerengine.NodePoolOptions{})),
	newTarget("containerengine", "PodShape", reflect.TypeOf(containerengine.PodShape{})),
	newTarget("containerengine", "VirtualNode", reflect.TypeOf(containerengine.VirtualNode{})),
	newTarget("containerengine", "VirtualNodePool", reflect.TypeOf(containerengine.VirtualNodePool{})),
	newTarget("containerengine", "WorkRequest", reflect.TypeOf(containerengine.WorkRequest{})),
	newTarget("containerengine", "WorkRequestError", reflect.TypeOf(containerengine.WorkRequestError{})),
	newTarget("containerengine", "WorkRequestLogEntry", reflect.TypeOf(containerengine.WorkRequestLogEntry{})),
	newTarget("containerengine", "WorkloadMapping", reflect.TypeOf(containerengine.WorkloadMapping{})),
	newTarget("containerengine", "AddonOptionSummary", reflect.TypeOf(containerengine.AddonOptionSummary{})),
	newTarget("containerengine", "AddonSummary", reflect.TypeOf(containerengine.AddonSummary{})),
	newTarget("containerengine", "ClusterSummary", reflect.TypeOf(containerengine.ClusterSummary{})),
	newTarget("containerengine", "NodePoolSummary", reflect.TypeOf(containerengine.NodePoolSummary{})),
	newTarget("containerengine", "PodShapeSummary", reflect.TypeOf(containerengine.PodShapeSummary{})),
	newTarget("containerengine", "VirtualNodePoolSummary", reflect.TypeOf(containerengine.VirtualNodePoolSummary{})),
	newTarget("containerengine", "VirtualNodeSummary", reflect.TypeOf(containerengine.VirtualNodeSummary{})),
	newTarget("containerengine", "WorkRequestSummary", reflect.TypeOf(containerengine.WorkRequestSummary{})),
	newTarget("containerengine", "WorkloadMappingSummary", reflect.TypeOf(containerengine.WorkloadMappingSummary{})),
}

var interfaceImplementations = map[string][]reflect.Type{
	qualifiedTypeName(reflect.TypeOf((*mysql.CreateDbSystemSourceDetails)(nil)).Elem()): {
		reflect.TypeOf(mysql.CreateDbSystemSourceFromBackupDetails{}),
		reflect.TypeOf(mysql.CreateDbSystemSourceFromNoneDetails{}),
		reflect.TypeOf(mysql.CreateDbSystemSourceFromPitrDetails{}),
		reflect.TypeOf(mysql.CreateDbSystemSourceImportFromUrlDetails{}),
	},
}

func SeedTargets() []Target {
	result := make([]Target, len(seedTargets))
	copy(result, seedTargets)
	return result
}

func TargetByName(qualifiedName string) (Target, bool) {
	for _, target := range seedTargets {
		if target.QualifiedName == qualifiedName {
			return target, true
		}
	}
	return Target{}, false
}

func knownInterfaceImplementations(interfaceType reflect.Type) []reflect.Type {
	known := interfaceImplementations[qualifiedTypeName(interfaceType)]
	result := make([]reflect.Type, len(known))
	copy(result, known)
	return result
}

func newTarget(packageName string, typeName string, typeRef reflect.Type) Target {
	return Target{
		QualifiedName: packageName + "." + typeName,
		PackageName:   packageName,
		TypeName:      typeName,
		ImportPath:    typeRef.PkgPath(),
		ReflectType:   typeRef,
	}
}

func qualifiedTypeName(typeRef reflect.Type) string {
	return path.Base(typeRef.PkgPath()) + "." + typeRef.Name()
}
