package sdk

import (
	"path"
	"reflect"

	"github.com/oracle/oci-go-sdk/v65/containerengine"
	"github.com/oracle/oci-go-sdk/v65/containerinstances"
	"github.com/oracle/oci-go-sdk/v65/core"
	"github.com/oracle/oci-go-sdk/v65/database"
	"github.com/oracle/oci-go-sdk/v65/dataflow"
	"github.com/oracle/oci-go-sdk/v65/functions"
	"github.com/oracle/oci-go-sdk/v65/identity"
	"github.com/oracle/oci-go-sdk/v65/mysql"
	"github.com/oracle/oci-go-sdk/v65/nosql"
	"github.com/oracle/oci-go-sdk/v65/objectstorage"
	"github.com/oracle/oci-go-sdk/v65/opensearch"
	"github.com/oracle/oci-go-sdk/v65/psql"
	"github.com/oracle/oci-go-sdk/v65/queue"
	"github.com/oracle/oci-go-sdk/v65/redis"
	"github.com/oracle/oci-go-sdk/v65/streaming"
	"github.com/oracle/oci-go-sdk/v65/vault"
)

const (
	modulePath    = "github.com/oracle/oci-go-sdk/v65"
	moduleVersion = "v65.61.1"
)

var seedTargets = []Target{
	// Autonomous Database CRD support
	newTarget("database", "CreateAutonomousDatabaseDetails", reflect.TypeOf(database.CreateAutonomousDatabaseDetails{})),
	newTarget("database", "UpdateAutonomousDatabaseDetails", reflect.TypeOf(database.UpdateAutonomousDatabaseDetails{})),
	newTarget("database", "AutonomousDatabase", reflect.TypeOf(database.AutonomousDatabase{})),
	newTarget("database", "AutonomousDatabaseSummary", reflect.TypeOf(database.AutonomousDatabaseSummary{})),

	// MySQL DB System CRD support
	newTarget("mysql", "CreateBackupDetails", reflect.TypeOf(mysql.CreateBackupDetails{})),
	newTarget("mysql", "CreateChannelDetails", reflect.TypeOf(mysql.CreateChannelDetails{})),
	newTarget("mysql", "CreateConfigurationDetails", reflect.TypeOf(mysql.CreateConfigurationDetails{})),
	newTarget("mysql", "CreateDbSystemDetails", reflect.TypeOf(mysql.CreateDbSystemDetails{})),
	newTarget("mysql", "CreateReplicaDetails", reflect.TypeOf(mysql.CreateReplicaDetails{})),
	newTarget("mysql", "UpdateBackupDetails", reflect.TypeOf(mysql.UpdateBackupDetails{})),
	newTarget("mysql", "UpdateChannelDetails", reflect.TypeOf(mysql.UpdateChannelDetails{})),
	newTarget("mysql", "UpdateConfigurationDetails", reflect.TypeOf(mysql.UpdateConfigurationDetails{})),
	newTarget("mysql", "UpdateDbSystemDetails", reflect.TypeOf(mysql.UpdateDbSystemDetails{})),
	newTarget("mysql", "UpdateHeatWaveClusterDetails", reflect.TypeOf(mysql.UpdateHeatWaveClusterDetails{})),
	newTarget("mysql", "UpdateReplicaDetails", reflect.TypeOf(mysql.UpdateReplicaDetails{})),
	newTarget("mysql", "Backup", reflect.TypeOf(mysql.Backup{})),
	newTarget("mysql", "Channel", reflect.TypeOf(mysql.Channel{})),
	newTarget("mysql", "Configuration", reflect.TypeOf(mysql.Configuration{})),
	newTarget("mysql", "DbSystem", reflect.TypeOf(mysql.DbSystem{})),
	newTarget("mysql", "HeatWaveCluster", reflect.TypeOf(mysql.HeatWaveCluster{})),
	newTarget("mysql", "HeatWaveClusterMemoryEstimate", reflect.TypeOf(mysql.HeatWaveClusterMemoryEstimate{})),
	newTarget("mysql", "Replica", reflect.TypeOf(mysql.Replica{})),
	newTarget("mysql", "Version", reflect.TypeOf(mysql.Version{})),
	newTarget("mysql", "WorkRequest", reflect.TypeOf(mysql.WorkRequest{})),
	newTarget("mysql", "WorkRequestError", reflect.TypeOf(mysql.WorkRequestError{})),
	newTarget("mysql", "WorkRequestLogEntry", reflect.TypeOf(mysql.WorkRequestLogEntry{})),
	newTarget("mysql", "VersionSummary", reflect.TypeOf(mysql.VersionSummary{})),
	newTarget("mysql", "BackupSummary", reflect.TypeOf(mysql.BackupSummary{})),
	newTarget("mysql", "ChannelSummary", reflect.TypeOf(mysql.ChannelSummary{})),
	newTarget("mysql", "ConfigurationSummary", reflect.TypeOf(mysql.ConfigurationSummary{})),
	newTarget("mysql", "DbSystemSummary", reflect.TypeOf(mysql.DbSystemSummary{})),
	newTarget("mysql", "HeatWaveClusterSummary", reflect.TypeOf(mysql.HeatWaveClusterSummary{})),
	newTarget("mysql", "ReplicaSummary", reflect.TypeOf(mysql.ReplicaSummary{})),
	newTarget("mysql", "ShapeSummary", reflect.TypeOf(mysql.ShapeSummary{})),
	newTarget("mysql", "WorkRequestSummary", reflect.TypeOf(mysql.WorkRequestSummary{})),

	// Streaming CRD support
	newTarget("streaming", "CreateStreamDetails", reflect.TypeOf(streaming.CreateStreamDetails{})),
	newTarget("streaming", "UpdateStreamDetails", reflect.TypeOf(streaming.UpdateStreamDetails{})),
	newTarget("streaming", "Stream", reflect.TypeOf(streaming.Stream{})),
	newTarget("streaming", "StreamSummary", reflect.TypeOf(streaming.StreamSummary{})),

	// Queue CRD support
	newTarget("queue", "CreateQueueDetails", reflect.TypeOf(queue.CreateQueueDetails{})),
	newTarget("queue", "UpdateMessageDetails", reflect.TypeOf(queue.UpdateMessageDetails{})),
	newTarget("queue", "UpdateQueueDetails", reflect.TypeOf(queue.UpdateQueueDetails{})),
	newTarget("queue", "ChannelCollection", reflect.TypeOf(queue.ChannelCollection{})),
	newTarget("queue", "Queue", reflect.TypeOf(queue.Queue{})),
	newTarget("queue", "QueueCollection", reflect.TypeOf(queue.QueueCollection{})),
	newTarget("queue", "Stats", reflect.TypeOf(queue.Stats{})),
	newTarget("queue", "WorkRequest", reflect.TypeOf(queue.WorkRequest{})),
	newTarget("queue", "WorkRequestError", reflect.TypeOf(queue.WorkRequestError{})),
	newTarget("queue", "WorkRequestErrorCollection", reflect.TypeOf(queue.WorkRequestErrorCollection{})),
	newTarget("queue", "WorkRequestLogEntry", reflect.TypeOf(queue.WorkRequestLogEntry{})),
	newTarget("queue", "WorkRequestLogEntryCollection", reflect.TypeOf(queue.WorkRequestLogEntryCollection{})),
	newTarget("queue", "QueueSummary", reflect.TypeOf(queue.QueueSummary{})),
	newTarget("queue", "WorkRequestSummary", reflect.TypeOf(queue.WorkRequestSummary{})),

	// Functions CRD support
	newTarget("functions", "CreateApplicationDetails", reflect.TypeOf(functions.CreateApplicationDetails{})),
	newTarget("functions", "CreateFunctionDetails", reflect.TypeOf(functions.CreateFunctionDetails{})),
	newTarget("functions", "UpdateApplicationDetails", reflect.TypeOf(functions.UpdateApplicationDetails{})),
	newTarget("functions", "UpdateFunctionDetails", reflect.TypeOf(functions.UpdateFunctionDetails{})),
	newTarget("functions", "Application", reflect.TypeOf(functions.Application{})),
	newTarget("functions", "Function", reflect.TypeOf(functions.Function{})),
	newTarget("functions", "PbfListing", reflect.TypeOf(functions.PbfListing{})),
	newTarget("functions", "PbfListingVersion", reflect.TypeOf(functions.PbfListingVersion{})),
	newTarget("functions", "Trigger", reflect.TypeOf(functions.Trigger{})),
	newTarget("functions", "PbfListingVersionSummary", reflect.TypeOf(functions.PbfListingVersionSummary{})),
	newTarget("functions", "ApplicationSummary", reflect.TypeOf(functions.ApplicationSummary{})),
	newTarget("functions", "FunctionSummary", reflect.TypeOf(functions.FunctionSummary{})),
	newTarget("functions", "PbfListingSummary", reflect.TypeOf(functions.PbfListingSummary{})),
	newTarget("functions", "TriggerSummary", reflect.TypeOf(functions.TriggerSummary{})),

	// NoSQL CRD support
	newTarget("nosql", "CreateIndexDetails", reflect.TypeOf(nosql.CreateIndexDetails{})),
	newTarget("nosql", "CreateReplicaDetails", reflect.TypeOf(nosql.CreateReplicaDetails{})),
	newTarget("nosql", "CreateTableDetails", reflect.TypeOf(nosql.CreateTableDetails{})),
	newTarget("nosql", "UpdateRowDetails", reflect.TypeOf(nosql.UpdateRowDetails{})),
	newTarget("nosql", "UpdateTableDetails", reflect.TypeOf(nosql.UpdateTableDetails{})),
	newTarget("nosql", "Index", reflect.TypeOf(nosql.Index{})),
	newTarget("nosql", "IndexCollection", reflect.TypeOf(nosql.IndexCollection{})),
	newTarget("nosql", "Replica", reflect.TypeOf(nosql.Replica{})),
	newTarget("nosql", "Row", reflect.TypeOf(nosql.Row{})),
	newTarget("nosql", "Table", reflect.TypeOf(nosql.Table{})),
	newTarget("nosql", "TableCollection", reflect.TypeOf(nosql.TableCollection{})),
	newTarget("nosql", "TableUsageCollection", reflect.TypeOf(nosql.TableUsageCollection{})),
	newTarget("nosql", "WorkRequest", reflect.TypeOf(nosql.WorkRequest{})),
	newTarget("nosql", "WorkRequestCollection", reflect.TypeOf(nosql.WorkRequestCollection{})),
	newTarget("nosql", "WorkRequestError", reflect.TypeOf(nosql.WorkRequestError{})),
	newTarget("nosql", "WorkRequestErrorCollection", reflect.TypeOf(nosql.WorkRequestErrorCollection{})),
	newTarget("nosql", "WorkRequestLogEntry", reflect.TypeOf(nosql.WorkRequestLogEntry{})),
	newTarget("nosql", "WorkRequestLogEntryCollection", reflect.TypeOf(nosql.WorkRequestLogEntryCollection{})),
	newTarget("nosql", "IndexSummary", reflect.TypeOf(nosql.IndexSummary{})),
	newTarget("nosql", "TableSummary", reflect.TypeOf(nosql.TableSummary{})),
	newTarget("nosql", "TableUsageSummary", reflect.TypeOf(nosql.TableUsageSummary{})),
	newTarget("nosql", "WorkRequestSummary", reflect.TypeOf(nosql.WorkRequestSummary{})),

	// Object Storage CRD support
	newTarget("objectstorage", "CreateBucketDetails", reflect.TypeOf(objectstorage.CreateBucketDetails{})),
	newTarget("objectstorage", "UpdateBucketDetails", reflect.TypeOf(objectstorage.UpdateBucketDetails{})),
	newTarget("objectstorage", "Bucket", reflect.TypeOf(objectstorage.Bucket{})),
	newTarget("objectstorage", "BucketSummary", reflect.TypeOf(objectstorage.BucketSummary{})),

	// PostgreSQL CRD support
	newTarget("psql", "CreateBackupDetails", reflect.TypeOf(psql.CreateBackupDetails{})),
	newTarget("psql", "CreateConfigurationDetails", reflect.TypeOf(psql.CreateConfigurationDetails{})),
	newTarget("psql", "CreateDbSystemDetails", reflect.TypeOf(psql.CreateDbSystemDetails{})),
	newTarget("psql", "UpdateBackupDetails", reflect.TypeOf(psql.UpdateBackupDetails{})),
	newTarget("psql", "UpdateConfigurationDetails", reflect.TypeOf(psql.UpdateConfigurationDetails{})),
	newTarget("psql", "UpdateDbSystemDbInstanceDetails", reflect.TypeOf(psql.UpdateDbSystemDbInstanceDetails{})),
	newTarget("psql", "UpdateDbSystemDetails", reflect.TypeOf(psql.UpdateDbSystemDetails{})),
	newTarget("psql", "ConfigurationDetails", reflect.TypeOf(psql.ConfigurationDetails{})),
	newTarget("psql", "ConnectionDetails", reflect.TypeOf(psql.ConnectionDetails{})),
	newTarget("psql", "DbSystemDetails", reflect.TypeOf(psql.DbSystemDetails{})),
	newTarget("psql", "DefaultConfigurationDetails", reflect.TypeOf(psql.DefaultConfigurationDetails{})),
	newTarget("psql", "PrimaryDbInstanceDetails", reflect.TypeOf(psql.PrimaryDbInstanceDetails{})),
	newTarget("psql", "Backup", reflect.TypeOf(psql.Backup{})),
	newTarget("psql", "BackupCollection", reflect.TypeOf(psql.BackupCollection{})),
	newTarget("psql", "Configuration", reflect.TypeOf(psql.Configuration{})),
	newTarget("psql", "ConfigurationCollection", reflect.TypeOf(psql.ConfigurationCollection{})),
	newTarget("psql", "DbSystem", reflect.TypeOf(psql.DbSystem{})),
	newTarget("psql", "DbSystemCollection", reflect.TypeOf(psql.DbSystemCollection{})),
	newTarget("psql", "DefaultConfiguration", reflect.TypeOf(psql.DefaultConfiguration{})),
	newTarget("psql", "DefaultConfigurationCollection", reflect.TypeOf(psql.DefaultConfigurationCollection{})),
	newTarget("psql", "ShapeCollection", reflect.TypeOf(psql.ShapeCollection{})),
	newTarget("psql", "WorkRequest", reflect.TypeOf(psql.WorkRequest{})),
	newTarget("psql", "WorkRequestError", reflect.TypeOf(psql.WorkRequestError{})),
	newTarget("psql", "WorkRequestErrorCollection", reflect.TypeOf(psql.WorkRequestErrorCollection{})),
	newTarget("psql", "WorkRequestLogEntry", reflect.TypeOf(psql.WorkRequestLogEntry{})),
	newTarget("psql", "WorkRequestLogEntryCollection", reflect.TypeOf(psql.WorkRequestLogEntryCollection{})),
	newTarget("psql", "BackupSummary", reflect.TypeOf(psql.BackupSummary{})),
	newTarget("psql", "ConfigurationSummary", reflect.TypeOf(psql.ConfigurationSummary{})),
	newTarget("psql", "DbSystemSummary", reflect.TypeOf(psql.DbSystemSummary{})),
	newTarget("psql", "DefaultConfigurationSummary", reflect.TypeOf(psql.DefaultConfigurationSummary{})),
	newTarget("psql", "ShapeSummary", reflect.TypeOf(psql.ShapeSummary{})),
	newTarget("psql", "WorkRequestSummary", reflect.TypeOf(psql.WorkRequestSummary{})),

	// Container Engine CRD support
	newTarget("containerengine", "CreateClusterDetails", reflect.TypeOf(containerengine.CreateClusterDetails{})),
	newTarget("containerengine", "CreateClusterEndpointConfigDetails", reflect.TypeOf(containerengine.CreateClusterEndpointConfigDetails{})),
	newTarget("containerengine", "CreateClusterKubeconfigContentDetails", reflect.TypeOf(containerengine.CreateClusterKubeconfigContentDetails{})),
	newTarget("containerengine", "CreateNodePoolDetails", reflect.TypeOf(containerengine.CreateNodePoolDetails{})),
	newTarget("containerengine", "CreateVirtualNodePoolDetails", reflect.TypeOf(containerengine.CreateVirtualNodePoolDetails{})),
	newTarget("containerengine", "CreateWorkloadMappingDetails", reflect.TypeOf(containerengine.CreateWorkloadMappingDetails{})),
	newTarget("containerengine", "UpdateAddonDetails", reflect.TypeOf(containerengine.UpdateAddonDetails{})),
	newTarget("containerengine", "UpdateClusterDetails", reflect.TypeOf(containerengine.UpdateClusterDetails{})),
	newTarget("containerengine", "UpdateClusterEndpointConfigDetails", reflect.TypeOf(containerengine.UpdateClusterEndpointConfigDetails{})),
	newTarget("containerengine", "UpdateNodePoolDetails", reflect.TypeOf(containerengine.UpdateNodePoolDetails{})),
	newTarget("containerengine", "UpdateVirtualNodePoolDetails", reflect.TypeOf(containerengine.UpdateVirtualNodePoolDetails{})),
	newTarget("containerengine", "UpdateWorkloadMappingDetails", reflect.TypeOf(containerengine.UpdateWorkloadMappingDetails{})),
	newTarget("containerengine", "Addon", reflect.TypeOf(containerengine.Addon{})),
	newTarget("containerengine", "Cluster", reflect.TypeOf(containerengine.Cluster{})),
	newTarget("containerengine", "ClusterEndpointConfig", reflect.TypeOf(containerengine.ClusterEndpointConfig{})),
	newTarget("containerengine", "ClusterMigrateToNativeVcnStatus", reflect.TypeOf(containerengine.ClusterMigrateToNativeVcnStatus{})),
	newTarget("containerengine", "ClusterOptions", reflect.TypeOf(containerengine.ClusterOptions{})),
	newTarget("containerengine", "CredentialRotationStatus", reflect.TypeOf(containerengine.CredentialRotationStatus{})),
	newTarget("containerengine", "Node", reflect.TypeOf(containerengine.Node{})),
	newTarget("containerengine", "NodePool", reflect.TypeOf(containerengine.NodePool{})),
	newTarget("containerengine", "NodePoolOptions", reflect.TypeOf(containerengine.NodePoolOptions{})),
	newTarget("containerengine", "PodShape", reflect.TypeOf(containerengine.PodShape{})),
	newTarget("containerengine", "VirtualNode", reflect.TypeOf(containerengine.VirtualNode{})),
	newTarget("containerengine", "VirtualNodePool", reflect.TypeOf(containerengine.VirtualNodePool{})),
	newTarget("containerengine", "WorkRequest", reflect.TypeOf(containerengine.WorkRequest{})),
	newTarget("containerengine", "WorkRequestError", reflect.TypeOf(containerengine.WorkRequestError{})),
	newTarget("containerengine", "WorkRequestLogEntry", reflect.TypeOf(containerengine.WorkRequestLogEntry{})),
	newTarget("containerengine", "WorkloadMapping", reflect.TypeOf(containerengine.WorkloadMapping{})),
	newTarget("containerengine", "AddonOptionSummary", reflect.TypeOf(containerengine.AddonOptionSummary{})),
	newTarget("containerengine", "AddonSummary", reflect.TypeOf(containerengine.AddonSummary{})),
	newTarget("containerengine", "ClusterSummary", reflect.TypeOf(containerengine.ClusterSummary{})),
	newTarget("containerengine", "NodePoolSummary", reflect.TypeOf(containerengine.NodePoolSummary{})),
	newTarget("containerengine", "PodShapeSummary", reflect.TypeOf(containerengine.PodShapeSummary{})),
	newTarget("containerengine", "VirtualNodePoolSummary", reflect.TypeOf(containerengine.VirtualNodePoolSummary{})),
	newTarget("containerengine", "VirtualNodeSummary", reflect.TypeOf(containerengine.VirtualNodeSummary{})),
	newTarget("containerengine", "WorkRequestSummary", reflect.TypeOf(containerengine.WorkRequestSummary{})),
	newTarget("containerengine", "WorkloadMappingSummary", reflect.TypeOf(containerengine.WorkloadMappingSummary{})),

	// Identity CRD support
	newTarget("identity", "CreateCompartmentDetails", reflect.TypeOf(identity.CreateCompartmentDetails{})),
	newTarget("identity", "UpdateCompartmentDetails", reflect.TypeOf(identity.UpdateCompartmentDetails{})),
	newTarget("identity", "Compartment", reflect.TypeOf(identity.Compartment{})),

	// Vault CRD support
	newTarget("vault", "CreateSecretDetails", reflect.TypeOf(vault.CreateSecretDetails{})),
	newTarget("vault", "UpdateSecretDetails", reflect.TypeOf(vault.UpdateSecretDetails{})),
	newTarget("vault", "Secret", reflect.TypeOf(vault.Secret{})),
	newTarget("vault", "SecretVersion", reflect.TypeOf(vault.SecretVersion{})),
	newTarget("vault", "SecretVersionSummary", reflect.TypeOf(vault.SecretVersionSummary{})),
	newTarget("vault", "SecretSummary", reflect.TypeOf(vault.SecretSummary{})),

	// Core VCN CRD support
	newTarget("core", "CreateAppCatalogSubscriptionDetails", reflect.TypeOf(core.CreateAppCatalogSubscriptionDetails{})),
	newTarget("core", "CreateBootVolumeBackupDetails", reflect.TypeOf(core.CreateBootVolumeBackupDetails{})),
	newTarget("core", "CreateBootVolumeDetails", reflect.TypeOf(core.CreateBootVolumeDetails{})),
	newTarget("core", "CreateByoipRangeDetails", reflect.TypeOf(core.CreateByoipRangeDetails{})),
	newTarget("core", "CreateCaptureFilterDetails", reflect.TypeOf(core.CreateCaptureFilterDetails{})),
	newTarget("core", "CreateClusterNetworkDetails", reflect.TypeOf(core.CreateClusterNetworkDetails{})),
	newTarget("core", "CreateComputeCapacityReportDetails", reflect.TypeOf(core.CreateComputeCapacityReportDetails{})),
	newTarget("core", "CreateComputeCapacityReservationDetails", reflect.TypeOf(core.CreateComputeCapacityReservationDetails{})),
	newTarget("core", "CreateComputeCapacityTopologyDetails", reflect.TypeOf(core.CreateComputeCapacityTopologyDetails{})),
	newTarget("core", "CreateComputeClusterDetails", reflect.TypeOf(core.CreateComputeClusterDetails{})),
	newTarget("core", "CreateComputeImageCapabilitySchemaDetails", reflect.TypeOf(core.CreateComputeImageCapabilitySchemaDetails{})),
	newTarget("core", "CreateCpeDetails", reflect.TypeOf(core.CreateCpeDetails{})),
	newTarget("core", "CreateCrossConnectDetails", reflect.TypeOf(core.CreateCrossConnectDetails{})),
	newTarget("core", "CreateCrossConnectGroupDetails", reflect.TypeOf(core.CreateCrossConnectGroupDetails{})),
	newTarget("core", "CreateDedicatedVmHostDetails", reflect.TypeOf(core.CreateDedicatedVmHostDetails{})),
	newTarget("core", "CreateDrgAttachmentDetails", reflect.TypeOf(core.CreateDrgAttachmentDetails{})),
	newTarget("core", "CreateDrgDetails", reflect.TypeOf(core.CreateDrgDetails{})),
	newTarget("core", "CreateDrgRouteDistributionDetails", reflect.TypeOf(core.CreateDrgRouteDistributionDetails{})),
	newTarget("core", "CreateDrgRouteTableDetails", reflect.TypeOf(core.CreateDrgRouteTableDetails{})),
	newTarget("core", "CreateImageDetails", reflect.TypeOf(core.CreateImageDetails{})),
	newTarget("core", "CreateInstanceConfigurationDetails", reflect.TypeOf(core.CreateInstanceConfigurationDetails{})),
	newTarget("core", "CreateInstanceConsoleConnectionDetails", reflect.TypeOf(core.CreateInstanceConsoleConnectionDetails{})),
	newTarget("core", "CreateInstancePoolDetails", reflect.TypeOf(core.CreateInstancePoolDetails{})),
	newTarget("core", "CreateInternetGatewayDetails", reflect.TypeOf(core.CreateInternetGatewayDetails{})),
	newTarget("core", "CreateIpSecConnectionDetails", reflect.TypeOf(core.CreateIpSecConnectionDetails{})),
	newTarget("core", "CreateIpSecConnectionTunnelDetails", reflect.TypeOf(core.CreateIpSecConnectionTunnelDetails{})),
	newTarget("core", "CreateIpv6Details", reflect.TypeOf(core.CreateIpv6Details{})),
	newTarget("core", "CreateLocalPeeringGatewayDetails", reflect.TypeOf(core.CreateLocalPeeringGatewayDetails{})),
	newTarget("core", "CreateNatGatewayDetails", reflect.TypeOf(core.CreateNatGatewayDetails{})),
	newTarget("core", "CreateNetworkSecurityGroupDetails", reflect.TypeOf(core.CreateNetworkSecurityGroupDetails{})),
	newTarget("core", "CreatePrivateIpDetails", reflect.TypeOf(core.CreatePrivateIpDetails{})),
	newTarget("core", "CreatePublicIpDetails", reflect.TypeOf(core.CreatePublicIpDetails{})),
	newTarget("core", "CreatePublicIpPoolDetails", reflect.TypeOf(core.CreatePublicIpPoolDetails{})),
	newTarget("core", "CreateRemotePeeringConnectionDetails", reflect.TypeOf(core.CreateRemotePeeringConnectionDetails{})),
	newTarget("core", "CreateRouteTableDetails", reflect.TypeOf(core.CreateRouteTableDetails{})),
	newTarget("core", "CreateSecurityListDetails", reflect.TypeOf(core.CreateSecurityListDetails{})),
	newTarget("core", "CreateServiceGatewayDetails", reflect.TypeOf(core.CreateServiceGatewayDetails{})),
	newTarget("core", "CreateSubnetDetails", reflect.TypeOf(core.CreateSubnetDetails{})),
	newTarget("core", "CreateVcnDetails", reflect.TypeOf(core.CreateVcnDetails{})),
	newTarget("core", "CreateVirtualCircuitDetails", reflect.TypeOf(core.CreateVirtualCircuitDetails{})),
	newTarget("core", "CreateVirtualCircuitPublicPrefixDetails", reflect.TypeOf(core.CreateVirtualCircuitPublicPrefixDetails{})),
	newTarget("core", "CreateVlanDetails", reflect.TypeOf(core.CreateVlanDetails{})),
	newTarget("core", "CreateVnicDetails", reflect.TypeOf(core.CreateVnicDetails{})),
	newTarget("core", "CreateVolumeBackupDetails", reflect.TypeOf(core.CreateVolumeBackupDetails{})),
	newTarget("core", "CreateVolumeBackupPolicyAssignmentDetails", reflect.TypeOf(core.CreateVolumeBackupPolicyAssignmentDetails{})),
	newTarget("core", "CreateVolumeBackupPolicyDetails", reflect.TypeOf(core.CreateVolumeBackupPolicyDetails{})),
	newTarget("core", "CreateVolumeDetails", reflect.TypeOf(core.CreateVolumeDetails{})),
	newTarget("core", "CreateVolumeGroupBackupDetails", reflect.TypeOf(core.CreateVolumeGroupBackupDetails{})),
	newTarget("core", "CreateVolumeGroupDetails", reflect.TypeOf(core.CreateVolumeGroupDetails{})),
	newTarget("core", "CreateVtapDetails", reflect.TypeOf(core.CreateVtapDetails{})),
	newTarget("core", "UpdateBootVolumeBackupDetails", reflect.TypeOf(core.UpdateBootVolumeBackupDetails{})),
	newTarget("core", "UpdateBootVolumeDetails", reflect.TypeOf(core.UpdateBootVolumeDetails{})),
	newTarget("core", "UpdateBootVolumeKmsKeyDetails", reflect.TypeOf(core.UpdateBootVolumeKmsKeyDetails{})),
	newTarget("core", "UpdateByoipRangeDetails", reflect.TypeOf(core.UpdateByoipRangeDetails{})),
	newTarget("core", "UpdateCaptureFilterDetails", reflect.TypeOf(core.UpdateCaptureFilterDetails{})),
	newTarget("core", "UpdateClusterNetworkDetails", reflect.TypeOf(core.UpdateClusterNetworkDetails{})),
	newTarget("core", "UpdateComputeCapacityReservationDetails", reflect.TypeOf(core.UpdateComputeCapacityReservationDetails{})),
	newTarget("core", "UpdateComputeCapacityTopologyDetails", reflect.TypeOf(core.UpdateComputeCapacityTopologyDetails{})),
	newTarget("core", "UpdateComputeClusterDetails", reflect.TypeOf(core.UpdateComputeClusterDetails{})),
	newTarget("core", "UpdateComputeImageCapabilitySchemaDetails", reflect.TypeOf(core.UpdateComputeImageCapabilitySchemaDetails{})),
	newTarget("core", "UpdateConsoleHistoryDetails", reflect.TypeOf(core.UpdateConsoleHistoryDetails{})),
	newTarget("core", "UpdateCpeDetails", reflect.TypeOf(core.UpdateCpeDetails{})),
	newTarget("core", "UpdateCrossConnectDetails", reflect.TypeOf(core.UpdateCrossConnectDetails{})),
	newTarget("core", "UpdateCrossConnectGroupDetails", reflect.TypeOf(core.UpdateCrossConnectGroupDetails{})),
	newTarget("core", "UpdateDedicatedVmHostDetails", reflect.TypeOf(core.UpdateDedicatedVmHostDetails{})),
	newTarget("core", "UpdateDrgAttachmentDetails", reflect.TypeOf(core.UpdateDrgAttachmentDetails{})),
	newTarget("core", "UpdateDrgDetails", reflect.TypeOf(core.UpdateDrgDetails{})),
	newTarget("core", "UpdateDrgRouteDistributionDetails", reflect.TypeOf(core.UpdateDrgRouteDistributionDetails{})),
	newTarget("core", "UpdateDrgRouteDistributionStatementDetails", reflect.TypeOf(core.UpdateDrgRouteDistributionStatementDetails{})),
	newTarget("core", "UpdateDrgRouteRuleDetails", reflect.TypeOf(core.UpdateDrgRouteRuleDetails{})),
	newTarget("core", "UpdateDrgRouteTableDetails", reflect.TypeOf(core.UpdateDrgRouteTableDetails{})),
	newTarget("core", "UpdateImageDetails", reflect.TypeOf(core.UpdateImageDetails{})),
	newTarget("core", "UpdateInstanceConfigurationDetails", reflect.TypeOf(core.UpdateInstanceConfigurationDetails{})),
	newTarget("core", "UpdateInstanceConsoleConnectionDetails", reflect.TypeOf(core.UpdateInstanceConsoleConnectionDetails{})),
	newTarget("core", "UpdateInstanceDetails", reflect.TypeOf(core.UpdateInstanceDetails{})),
	newTarget("core", "UpdateInstancePoolDetails", reflect.TypeOf(core.UpdateInstancePoolDetails{})),
	newTarget("core", "UpdateInternetGatewayDetails", reflect.TypeOf(core.UpdateInternetGatewayDetails{})),
	newTarget("core", "UpdateIpSecConnectionDetails", reflect.TypeOf(core.UpdateIpSecConnectionDetails{})),
	newTarget("core", "UpdateIpSecConnectionTunnelDetails", reflect.TypeOf(core.UpdateIpSecConnectionTunnelDetails{})),
	newTarget("core", "UpdateIpSecConnectionTunnelSharedSecretDetails", reflect.TypeOf(core.UpdateIpSecConnectionTunnelSharedSecretDetails{})),
	newTarget("core", "UpdateIpv6Details", reflect.TypeOf(core.UpdateIpv6Details{})),
	newTarget("core", "UpdateLocalPeeringGatewayDetails", reflect.TypeOf(core.UpdateLocalPeeringGatewayDetails{})),
	newTarget("core", "UpdateNatGatewayDetails", reflect.TypeOf(core.UpdateNatGatewayDetails{})),
	newTarget("core", "UpdateNetworkSecurityGroupDetails", reflect.TypeOf(core.UpdateNetworkSecurityGroupDetails{})),
	newTarget("core", "UpdatePrivateIpDetails", reflect.TypeOf(core.UpdatePrivateIpDetails{})),
	newTarget("core", "UpdatePublicIpDetails", reflect.TypeOf(core.UpdatePublicIpDetails{})),
	newTarget("core", "UpdatePublicIpPoolDetails", reflect.TypeOf(core.UpdatePublicIpPoolDetails{})),
	newTarget("core", "UpdateRemotePeeringConnectionDetails", reflect.TypeOf(core.UpdateRemotePeeringConnectionDetails{})),
	newTarget("core", "UpdateRouteTableDetails", reflect.TypeOf(core.UpdateRouteTableDetails{})),
	newTarget("core", "UpdateSecurityListDetails", reflect.TypeOf(core.UpdateSecurityListDetails{})),
	newTarget("core", "UpdateServiceGatewayDetails", reflect.TypeOf(core.UpdateServiceGatewayDetails{})),
	newTarget("core", "UpdateSubnetDetails", reflect.TypeOf(core.UpdateSubnetDetails{})),
	newTarget("core", "UpdateTunnelCpeDeviceConfigDetails", reflect.TypeOf(core.UpdateTunnelCpeDeviceConfigDetails{})),
	newTarget("core", "UpdateVcnDetails", reflect.TypeOf(core.UpdateVcnDetails{})),
	newTarget("core", "UpdateVirtualCircuitDetails", reflect.TypeOf(core.UpdateVirtualCircuitDetails{})),
	newTarget("core", "UpdateVlanDetails", reflect.TypeOf(core.UpdateVlanDetails{})),
	newTarget("core", "UpdateVnicDetails", reflect.TypeOf(core.UpdateVnicDetails{})),
	newTarget("core", "UpdateVolumeAttachmentDetails", reflect.TypeOf(core.UpdateVolumeAttachmentDetails{})),
	newTarget("core", "UpdateVolumeBackupDetails", reflect.TypeOf(core.UpdateVolumeBackupDetails{})),
	newTarget("core", "UpdateVolumeBackupPolicyDetails", reflect.TypeOf(core.UpdateVolumeBackupPolicyDetails{})),
	newTarget("core", "UpdateVolumeDetails", reflect.TypeOf(core.UpdateVolumeDetails{})),
	newTarget("core", "UpdateVolumeGroupBackupDetails", reflect.TypeOf(core.UpdateVolumeGroupBackupDetails{})),
	newTarget("core", "UpdateVolumeGroupDetails", reflect.TypeOf(core.UpdateVolumeGroupDetails{})),
	newTarget("core", "UpdateVolumeKmsKeyDetails", reflect.TypeOf(core.UpdateVolumeKmsKeyDetails{})),
	newTarget("core", "UpdateVtapDetails", reflect.TypeOf(core.UpdateVtapDetails{})),
	newTarget("core", "BlockVolumeReplicaDetails", reflect.TypeOf(core.BlockVolumeReplicaDetails{})),
	newTarget("core", "BootVolumeReplicaDetails", reflect.TypeOf(core.BootVolumeReplicaDetails{})),
	newTarget("core", "CrossConnectMappingDetails", reflect.TypeOf(core.CrossConnectMappingDetails{})),
	newTarget("core", "GetPublicIpByIpAddressDetails", reflect.TypeOf(core.GetPublicIpByIpAddressDetails{})),
	newTarget("core", "GetPublicIpByPrivateIpIdDetails", reflect.TypeOf(core.GetPublicIpByPrivateIpIdDetails{})),
	newTarget("core", "IpSecConnectionTunnelErrorDetails", reflect.TypeOf(core.IpSecConnectionTunnelErrorDetails{})),
	newTarget("core", "VirtualCircuitAssociatedTunnelDetails", reflect.TypeOf(core.VirtualCircuitAssociatedTunnelDetails{})),
	newTarget("core", "VolumeGroupReplicaDetails", reflect.TypeOf(core.VolumeGroupReplicaDetails{})),
	newTarget("core", "AllowedIkeIpSecParameters", reflect.TypeOf(core.AllowedIkeIpSecParameters{})),
	newTarget("core", "AppCatalogListing", reflect.TypeOf(core.AppCatalogListing{})),
	newTarget("core", "AppCatalogListingResourceVersion", reflect.TypeOf(core.AppCatalogListingResourceVersion{})),
	newTarget("core", "AppCatalogListingResourceVersionAgreements", reflect.TypeOf(core.AppCatalogListingResourceVersionAgreements{})),
	newTarget("core", "AppCatalogSubscription", reflect.TypeOf(core.AppCatalogSubscription{})),
	newTarget("core", "BlockVolumeReplica", reflect.TypeOf(core.BlockVolumeReplica{})),
	newTarget("core", "BootVolume", reflect.TypeOf(core.BootVolume{})),
	newTarget("core", "BootVolumeAttachment", reflect.TypeOf(core.BootVolumeAttachment{})),
	newTarget("core", "BootVolumeBackup", reflect.TypeOf(core.BootVolumeBackup{})),
	newTarget("core", "BootVolumeKmsKey", reflect.TypeOf(core.BootVolumeKmsKey{})),
	newTarget("core", "BootVolumeReplica", reflect.TypeOf(core.BootVolumeReplica{})),
	newTarget("core", "ByoipAllocatedRangeCollection", reflect.TypeOf(core.ByoipAllocatedRangeCollection{})),
	newTarget("core", "ByoipRange", reflect.TypeOf(core.ByoipRange{})),
	newTarget("core", "ByoipRangeCollection", reflect.TypeOf(core.ByoipRangeCollection{})),
	newTarget("core", "CaptureFilter", reflect.TypeOf(core.CaptureFilter{})),
	newTarget("core", "ClusterNetwork", reflect.TypeOf(core.ClusterNetwork{})),
	newTarget("core", "ComputeBareMetalHostCollection", reflect.TypeOf(core.ComputeBareMetalHostCollection{})),
	newTarget("core", "ComputeCapacityReport", reflect.TypeOf(core.ComputeCapacityReport{})),
	newTarget("core", "ComputeCapacityReservation", reflect.TypeOf(core.ComputeCapacityReservation{})),
	newTarget("core", "ComputeCapacityTopology", reflect.TypeOf(core.ComputeCapacityTopology{})),
	newTarget("core", "ComputeCapacityTopologyCollection", reflect.TypeOf(core.ComputeCapacityTopologyCollection{})),
	newTarget("core", "ComputeCluster", reflect.TypeOf(core.ComputeCluster{})),
	newTarget("core", "ComputeClusterCollection", reflect.TypeOf(core.ComputeClusterCollection{})),
	newTarget("core", "ComputeGlobalImageCapabilitySchema", reflect.TypeOf(core.ComputeGlobalImageCapabilitySchema{})),
	newTarget("core", "ComputeGlobalImageCapabilitySchemaVersion", reflect.TypeOf(core.ComputeGlobalImageCapabilitySchemaVersion{})),
	newTarget("core", "ComputeHpcIslandCollection", reflect.TypeOf(core.ComputeHpcIslandCollection{})),
	newTarget("core", "ComputeImageCapabilitySchema", reflect.TypeOf(core.ComputeImageCapabilitySchema{})),
	newTarget("core", "ComputeNetworkBlockCollection", reflect.TypeOf(core.ComputeNetworkBlockCollection{})),
	newTarget("core", "ConsoleHistory", reflect.TypeOf(core.ConsoleHistory{})),
	newTarget("core", "Cpe", reflect.TypeOf(core.Cpe{})),
	newTarget("core", "CrossConnect", reflect.TypeOf(core.CrossConnect{})),
	newTarget("core", "CrossConnectGroup", reflect.TypeOf(core.CrossConnectGroup{})),
	newTarget("core", "CrossConnectLocation", reflect.TypeOf(core.CrossConnectLocation{})),
	newTarget("core", "CrossConnectMapping", reflect.TypeOf(core.CrossConnectMapping{})),
	newTarget("core", "CrossConnectPortSpeedShape", reflect.TypeOf(core.CrossConnectPortSpeedShape{})),
	newTarget("core", "CrossConnectStatus", reflect.TypeOf(core.CrossConnectStatus{})),
	newTarget("core", "DedicatedVmHost", reflect.TypeOf(core.DedicatedVmHost{})),
	newTarget("core", "Device", reflect.TypeOf(core.Device{})),
	newTarget("core", "DhcpOptions", reflect.TypeOf(core.DhcpOptions{})),
	newTarget("core", "Drg", reflect.TypeOf(core.Drg{})),
	newTarget("core", "DrgAttachment", reflect.TypeOf(core.DrgAttachment{})),
	newTarget("core", "DrgAttachmentInfo", reflect.TypeOf(core.DrgAttachmentInfo{})),
	newTarget("core", "DrgRedundancyStatus", reflect.TypeOf(core.DrgRedundancyStatus{})),
	newTarget("core", "DrgRouteDistribution", reflect.TypeOf(core.DrgRouteDistribution{})),
	newTarget("core", "DrgRouteDistributionStatement", reflect.TypeOf(core.DrgRouteDistributionStatement{})),
	newTarget("core", "DrgRouteRule", reflect.TypeOf(core.DrgRouteRule{})),
	newTarget("core", "DrgRouteTable", reflect.TypeOf(core.DrgRouteTable{})),
	newTarget("core", "FastConnectProviderService", reflect.TypeOf(core.FastConnectProviderService{})),
	newTarget("core", "FastConnectProviderServiceKey", reflect.TypeOf(core.FastConnectProviderServiceKey{})),
	newTarget("core", "Image", reflect.TypeOf(core.Image{})),
	newTarget("core", "ImageShapeCompatibilityEntry", reflect.TypeOf(core.ImageShapeCompatibilityEntry{})),
	newTarget("core", "Instance", reflect.TypeOf(core.Instance{})),
	newTarget("core", "InstanceConfiguration", reflect.TypeOf(core.InstanceConfiguration{})),
	newTarget("core", "InstanceConsoleConnection", reflect.TypeOf(core.InstanceConsoleConnection{})),
	newTarget("core", "InstanceCredentials", reflect.TypeOf(core.InstanceCredentials{})),
	newTarget("core", "InstanceMaintenanceReboot", reflect.TypeOf(core.InstanceMaintenanceReboot{})),
	newTarget("core", "InstancePool", reflect.TypeOf(core.InstancePool{})),
	newTarget("core", "InstancePoolInstance", reflect.TypeOf(core.InstancePoolInstance{})),
	newTarget("core", "InstancePoolLoadBalancerAttachment", reflect.TypeOf(core.InstancePoolLoadBalancerAttachment{})),
	newTarget("core", "InternetGateway", reflect.TypeOf(core.InternetGateway{})),
	newTarget("core", "IpSecConnection", reflect.TypeOf(core.IpSecConnection{})),
	newTarget("core", "IpSecConnectionDeviceConfig", reflect.TypeOf(core.IpSecConnectionDeviceConfig{})),
	newTarget("core", "IpSecConnectionDeviceStatus", reflect.TypeOf(core.IpSecConnectionDeviceStatus{})),
	newTarget("core", "IpSecConnectionTunnel", reflect.TypeOf(core.IpSecConnectionTunnel{})),
	newTarget("core", "IpSecConnectionTunnelSharedSecret", reflect.TypeOf(core.IpSecConnectionTunnelSharedSecret{})),
	newTarget("core", "Ipv6", reflect.TypeOf(core.Ipv6{})),
	newTarget("core", "LetterOfAuthority", reflect.TypeOf(core.LetterOfAuthority{})),
	newTarget("core", "LocalPeeringGateway", reflect.TypeOf(core.LocalPeeringGateway{})),
	newTarget("core", "MeasuredBootReport", reflect.TypeOf(core.MeasuredBootReport{})),
	newTarget("core", "NatGateway", reflect.TypeOf(core.NatGateway{})),
	newTarget("core", "NetworkSecurityGroup", reflect.TypeOf(core.NetworkSecurityGroup{})),
	newTarget("core", "NetworkSecurityGroupVnic", reflect.TypeOf(core.NetworkSecurityGroupVnic{})),
	newTarget("core", "NetworkingTopology", reflect.TypeOf(core.NetworkingTopology{})),
	newTarget("core", "PeerRegionForRemotePeering", reflect.TypeOf(core.PeerRegionForRemotePeering{})),
	newTarget("core", "PrivateIp", reflect.TypeOf(core.PrivateIp{})),
	newTarget("core", "PublicIp", reflect.TypeOf(core.PublicIp{})),
	newTarget("core", "PublicIpPool", reflect.TypeOf(core.PublicIpPool{})),
	newTarget("core", "PublicIpPoolCollection", reflect.TypeOf(core.PublicIpPoolCollection{})),
	newTarget("core", "RemotePeeringConnection", reflect.TypeOf(core.RemotePeeringConnection{})),
	newTarget("core", "RouteTable", reflect.TypeOf(core.RouteTable{})),
	newTarget("core", "SecurityList", reflect.TypeOf(core.SecurityList{})),
	newTarget("core", "SecurityRule", reflect.TypeOf(core.SecurityRule{})),
	newTarget("core", "Service", reflect.TypeOf(core.Service{})),
	newTarget("core", "ServiceGateway", reflect.TypeOf(core.ServiceGateway{})),
	newTarget("core", "Shape", reflect.TypeOf(core.Shape{})),
	newTarget("core", "Subnet", reflect.TypeOf(core.Subnet{})),
	newTarget("core", "SubnetTopology", reflect.TypeOf(core.SubnetTopology{})),
	newTarget("core", "TunnelCpeDeviceConfig", reflect.TypeOf(core.TunnelCpeDeviceConfig{})),
	newTarget("core", "UpgradeStatus", reflect.TypeOf(core.UpgradeStatus{})),
	newTarget("core", "Vcn", reflect.TypeOf(core.Vcn{})),
	newTarget("core", "VcnDnsResolverAssociation", reflect.TypeOf(core.VcnDnsResolverAssociation{})),
	newTarget("core", "VcnTopology", reflect.TypeOf(core.VcnTopology{})),
	newTarget("core", "VirtualCircuit", reflect.TypeOf(core.VirtualCircuit{})),
	newTarget("core", "VirtualCircuitBandwidthShape", reflect.TypeOf(core.VirtualCircuitBandwidthShape{})),
	newTarget("core", "VirtualCircuitPublicPrefix", reflect.TypeOf(core.VirtualCircuitPublicPrefix{})),
	newTarget("core", "Vlan", reflect.TypeOf(core.Vlan{})),
	newTarget("core", "Vnic", reflect.TypeOf(core.Vnic{})),
	newTarget("core", "VnicAttachment", reflect.TypeOf(core.VnicAttachment{})),
	newTarget("core", "Volume", reflect.TypeOf(core.Volume{})),
	newTarget("core", "VolumeBackup", reflect.TypeOf(core.VolumeBackup{})),
	newTarget("core", "VolumeBackupPolicy", reflect.TypeOf(core.VolumeBackupPolicy{})),
	newTarget("core", "VolumeBackupPolicyAssignment", reflect.TypeOf(core.VolumeBackupPolicyAssignment{})),
	newTarget("core", "VolumeGroup", reflect.TypeOf(core.VolumeGroup{})),
	newTarget("core", "VolumeGroupBackup", reflect.TypeOf(core.VolumeGroupBackup{})),
	newTarget("core", "VolumeGroupReplica", reflect.TypeOf(core.VolumeGroupReplica{})),
	newTarget("core", "VolumeKmsKey", reflect.TypeOf(core.VolumeKmsKey{})),
	newTarget("core", "Vtap", reflect.TypeOf(core.Vtap{})),
	newTarget("core", "AppCatalogListingResourceVersionSummary", reflect.TypeOf(core.AppCatalogListingResourceVersionSummary{})),
	newTarget("core", "ComputeGlobalImageCapabilitySchemaVersionSummary", reflect.TypeOf(core.ComputeGlobalImageCapabilitySchemaVersionSummary{})),
	newTarget("core", "AppCatalogListingSummary", reflect.TypeOf(core.AppCatalogListingSummary{})),
	newTarget("core", "AppCatalogSubscriptionSummary", reflect.TypeOf(core.AppCatalogSubscriptionSummary{})),
	newTarget("core", "ByoipAllocatedRangeSummary", reflect.TypeOf(core.ByoipAllocatedRangeSummary{})),
	newTarget("core", "ByoipRangeSummary", reflect.TypeOf(core.ByoipRangeSummary{})),
	newTarget("core", "CapacityReservationInstanceSummary", reflect.TypeOf(core.CapacityReservationInstanceSummary{})),
	newTarget("core", "ClusterNetworkSummary", reflect.TypeOf(core.ClusterNetworkSummary{})),
	newTarget("core", "ComputeCapacityReservationInstanceShapeSummary", reflect.TypeOf(core.ComputeCapacityReservationInstanceShapeSummary{})),
	newTarget("core", "ComputeCapacityReservationSummary", reflect.TypeOf(core.ComputeCapacityReservationSummary{})),
	newTarget("core", "ComputeCapacityTopologySummary", reflect.TypeOf(core.ComputeCapacityTopologySummary{})),
	newTarget("core", "ComputeClusterSummary", reflect.TypeOf(core.ComputeClusterSummary{})),
	newTarget("core", "ComputeGlobalImageCapabilitySchemaSummary", reflect.TypeOf(core.ComputeGlobalImageCapabilitySchemaSummary{})),
	newTarget("core", "ComputeImageCapabilitySchemaSummary", reflect.TypeOf(core.ComputeImageCapabilitySchemaSummary{})),
	newTarget("core", "CpeDeviceShapeSummary", reflect.TypeOf(core.CpeDeviceShapeSummary{})),
	newTarget("core", "DedicatedVmHostInstanceShapeSummary", reflect.TypeOf(core.DedicatedVmHostInstanceShapeSummary{})),
	newTarget("core", "DedicatedVmHostInstanceSummary", reflect.TypeOf(core.DedicatedVmHostInstanceSummary{})),
	newTarget("core", "DedicatedVmHostShapeSummary", reflect.TypeOf(core.DedicatedVmHostShapeSummary{})),
	newTarget("core", "DedicatedVmHostSummary", reflect.TypeOf(core.DedicatedVmHostSummary{})),
	newTarget("core", "InstanceConfigurationSummary", reflect.TypeOf(core.InstanceConfigurationSummary{})),
	newTarget("core", "InstancePoolSummary", reflect.TypeOf(core.InstancePoolSummary{})),
	newTarget("core", "InstanceSummary", reflect.TypeOf(core.InstanceSummary{})),
	newTarget("core", "PublicIpPoolSummary", reflect.TypeOf(core.PublicIpPoolSummary{})),
	newTarget("core", "TunnelRouteSummary", reflect.TypeOf(core.TunnelRouteSummary{})),
	newTarget("core", "TunnelSecurityAssociationSummary", reflect.TypeOf(core.TunnelSecurityAssociationSummary{})),

	// Containerinstances CRD support
	newTarget("containerinstances", "CreateContainerInstanceDetails", reflect.TypeOf(containerinstances.CreateContainerInstanceDetails{})),
	newTarget("containerinstances", "UpdateContainerInstanceDetails", reflect.TypeOf(containerinstances.UpdateContainerInstanceDetails{})),
	newTarget("containerinstances", "ContainerInstance", reflect.TypeOf(containerinstances.ContainerInstance{})),
	newTarget("containerinstances", "ContainerInstanceCollection", reflect.TypeOf(containerinstances.ContainerInstanceCollection{})),
	newTarget("containerinstances", "ContainerInstanceSummary", reflect.TypeOf(containerinstances.ContainerInstanceSummary{})),

	// Dataflow CRD support
	newTarget("dataflow", "CreateApplicationDetails", reflect.TypeOf(dataflow.CreateApplicationDetails{})),
	newTarget("dataflow", "CreatePoolDetails", reflect.TypeOf(dataflow.CreatePoolDetails{})),
	newTarget("dataflow", "CreatePrivateEndpointDetails", reflect.TypeOf(dataflow.CreatePrivateEndpointDetails{})),
	newTarget("dataflow", "CreateRunDetails", reflect.TypeOf(dataflow.CreateRunDetails{})),
	newTarget("dataflow", "CreateSqlEndpointDetails", reflect.TypeOf(dataflow.CreateSqlEndpointDetails{})),
	newTarget("dataflow", "CreateStatementDetails", reflect.TypeOf(dataflow.CreateStatementDetails{})),
	newTarget("dataflow", "UpdateApplicationDetails", reflect.TypeOf(dataflow.UpdateApplicationDetails{})),
	newTarget("dataflow", "UpdatePoolDetails", reflect.TypeOf(dataflow.UpdatePoolDetails{})),
	newTarget("dataflow", "UpdatePrivateEndpointDetails", reflect.TypeOf(dataflow.UpdatePrivateEndpointDetails{})),
	newTarget("dataflow", "UpdateRunDetails", reflect.TypeOf(dataflow.UpdateRunDetails{})),
	newTarget("dataflow", "UpdateSqlEndpointDetails", reflect.TypeOf(dataflow.UpdateSqlEndpointDetails{})),
	newTarget("dataflow", "Application", reflect.TypeOf(dataflow.Application{})),
	newTarget("dataflow", "Pool", reflect.TypeOf(dataflow.Pool{})),
	newTarget("dataflow", "PoolCollection", reflect.TypeOf(dataflow.PoolCollection{})),
	newTarget("dataflow", "PrivateEndpoint", reflect.TypeOf(dataflow.PrivateEndpoint{})),
	newTarget("dataflow", "PrivateEndpointCollection", reflect.TypeOf(dataflow.PrivateEndpointCollection{})),
	newTarget("dataflow", "Run", reflect.TypeOf(dataflow.Run{})),
	newTarget("dataflow", "SqlEndpoint", reflect.TypeOf(dataflow.SqlEndpoint{})),
	newTarget("dataflow", "SqlEndpointCollection", reflect.TypeOf(dataflow.SqlEndpointCollection{})),
	newTarget("dataflow", "Statement", reflect.TypeOf(dataflow.Statement{})),
	newTarget("dataflow", "StatementCollection", reflect.TypeOf(dataflow.StatementCollection{})),
	newTarget("dataflow", "WorkRequest", reflect.TypeOf(dataflow.WorkRequest{})),
	newTarget("dataflow", "WorkRequestCollection", reflect.TypeOf(dataflow.WorkRequestCollection{})),
	newTarget("dataflow", "WorkRequestError", reflect.TypeOf(dataflow.WorkRequestError{})),
	newTarget("dataflow", "WorkRequestErrorCollection", reflect.TypeOf(dataflow.WorkRequestErrorCollection{})),
	newTarget("dataflow", "WorkRequestLog", reflect.TypeOf(dataflow.WorkRequestLog{})),
	newTarget("dataflow", "WorkRequestLogCollection", reflect.TypeOf(dataflow.WorkRequestLogCollection{})),
	newTarget("dataflow", "ApplicationSummary", reflect.TypeOf(dataflow.ApplicationSummary{})),
	newTarget("dataflow", "PoolSummary", reflect.TypeOf(dataflow.PoolSummary{})),
	newTarget("dataflow", "PrivateEndpointSummary", reflect.TypeOf(dataflow.PrivateEndpointSummary{})),
	newTarget("dataflow", "RunLogSummary", reflect.TypeOf(dataflow.RunLogSummary{})),
	newTarget("dataflow", "RunSummary", reflect.TypeOf(dataflow.RunSummary{})),
	newTarget("dataflow", "SqlEndpointSummary", reflect.TypeOf(dataflow.SqlEndpointSummary{})),
	newTarget("dataflow", "StatementSummary", reflect.TypeOf(dataflow.StatementSummary{})),
	newTarget("dataflow", "WorkRequestSummary", reflect.TypeOf(dataflow.WorkRequestSummary{})),

	// Opensearch CRD support
	newTarget("opensearch", "CreateOpensearchClusterDetails", reflect.TypeOf(opensearch.CreateOpensearchClusterDetails{})),
	newTarget("opensearch", "UpdateOpensearchClusterDetails", reflect.TypeOf(opensearch.UpdateOpensearchClusterDetails{})),
	newTarget("opensearch", "OpensearchCluster", reflect.TypeOf(opensearch.OpensearchCluster{})),
	newTarget("opensearch", "OpensearchClusterCollection", reflect.TypeOf(opensearch.OpensearchClusterCollection{})),
	newTarget("opensearch", "OpensearchClusterSummary", reflect.TypeOf(opensearch.OpensearchClusterSummary{})),

	// Redis CRD support
	newTarget("redis", "CreateRedisClusterDetails", reflect.TypeOf(redis.CreateRedisClusterDetails{})),
	newTarget("redis", "UpdateRedisClusterDetails", reflect.TypeOf(redis.UpdateRedisClusterDetails{})),
	newTarget("redis", "RedisCluster", reflect.TypeOf(redis.RedisCluster{})),
	newTarget("redis", "RedisClusterCollection", reflect.TypeOf(redis.RedisClusterCollection{})),
	newTarget("redis", "RedisClusterSummary", reflect.TypeOf(redis.RedisClusterSummary{})),
}

var interfaceImplementations = map[string][]reflect.Type{
	qualifiedTypeName(reflect.TypeOf((*mysql.CreateDbSystemSourceDetails)(nil)).Elem()): {
		reflect.TypeOf(mysql.CreateDbSystemSourceFromBackupDetails{}),
		reflect.TypeOf(mysql.CreateDbSystemSourceFromNoneDetails{}),
		reflect.TypeOf(mysql.CreateDbSystemSourceFromPitrDetails{}),
		reflect.TypeOf(mysql.CreateDbSystemSourceImportFromUrlDetails{}),
	},
}

func SeedTargets() []Target {
	result := make([]Target, len(seedTargets))
	copy(result, seedTargets)
	return result
}

func TargetByName(qualifiedName string) (Target, bool) {
	for _, target := range seedTargets {
		if target.QualifiedName == qualifiedName {
			return target, true
		}
	}
	return Target{}, false
}

func knownInterfaceImplementations(interfaceType reflect.Type) []reflect.Type {
	known := interfaceImplementations[qualifiedTypeName(interfaceType)]
	result := make([]reflect.Type, len(known))
	copy(result, known)
	return result
}

func newTarget(packageName string, typeName string, typeRef reflect.Type) Target {
	return Target{
		QualifiedName: packageName + "." + typeName,
		PackageName:   packageName,
		TypeName:      typeName,
		ImportPath:    typeRef.PkgPath(),
		ReflectType:   typeRef,
	}
}

func qualifiedTypeName(typeRef reflect.Type) string {
	return path.Base(typeRef.PkgPath()) + "." + typeRef.Name()
}
