apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/datasafe.oracle.com_alertpolicies.yaml
- bases/datasafe.oracle.com_alertpolicyrules.yaml
- bases/datasafe.oracle.com_attributesets.yaml
- bases/datasafe.oracle.com_auditarchiveretrievals.yaml
- bases/datasafe.oracle.com_auditprofiles.yaml
- bases/datasafe.oracle.com_datasafeprivateendpoints.yaml
- bases/datasafe.oracle.com_discoveryjobs.yaml
- bases/datasafe.oracle.com_librarymaskingformats.yaml
- bases/datasafe.oracle.com_maskingcolumns.yaml
- bases/datasafe.oracle.com_maskingpolicies.yaml
- bases/datasafe.oracle.com_onpremconnectors.yaml
- bases/datasafe.oracle.com_peertargetdatabases.yaml
- bases/datasafe.oracle.com_referentialrelations.yaml
- bases/datasafe.oracle.com_reportdefinitions.yaml
- bases/datasafe.oracle.com_sdmmaskingpolicydifferences.yaml
- bases/datasafe.oracle.com_securityassessments.yaml
- bases/datasafe.oracle.com_securitypolicies.yaml
- bases/datasafe.oracle.com_securitypolicyconfigs.yaml
- bases/datasafe.oracle.com_securitypolicydeployments.yaml
- bases/datasafe.oracle.com_sensitivecolumns.yaml
- bases/datasafe.oracle.com_sensitivedatamodels.yaml
- bases/datasafe.oracle.com_sensitivetypegroups.yaml
- bases/datasafe.oracle.com_sensitivetypes.yaml
- bases/datasafe.oracle.com_sensitivetypesexports.yaml
- bases/datasafe.oracle.com_sqlcollections.yaml
- bases/datasafe.oracle.com_targetalertpolicyassociations.yaml
- bases/datasafe.oracle.com_targetdatabasegroups.yaml
- bases/datasafe.oracle.com_targetdatabases.yaml
- bases/datasafe.oracle.com_unifiedauditpolicies.yaml
- bases/datasafe.oracle.com_userassessments.yaml
