apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: Mesh
metadata:
  name: {{ include "service-mesh-poc.name" . }}-mesh
  namespace: {{ .Values.serviceMeshPoc.namespace }}
  labels:
    {{- include "service-mesh-poc.labels" . | nindent 4 }}
spec:
  compartmentId: {{ .Values.serviceMeshPoc.compartmentId }}
  description: "This is Mesh"
  mtls:
    minimum: PERMISSIVE
  certificateAuthorities:
    - id: {{ .Values.serviceMeshPoc.mesh.caOcid }}
