apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: VirtualService
metadata:
  name: {{ include "service-mesh-poc.name" . }}-vs-details
  namespace: {{ .Values.serviceMeshPoc.namespace }}
  labels:
    {{- include "service-mesh-poc.labels" . | nindent 4 }}
spec:
  compartmentId: {{ .Values.serviceMeshPoc.compartmentId }}
  description: "This is Details Virtual Service"
  mesh:
    ref:
      name: {{ include "service-mesh-poc.fullname" . }}-mesh
  defaultRoutingPolicy:
    type: UNIFORM
  hosts:
    - {{ .Values.serviceMeshPoc.virtualService.details.host }}
  mtls:
    mode: {{ .Values.serviceMeshPoc.virtualService.details.mtlsMode }}
