#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/aidocument.oracle.com_projects.yaml
- bases/ailanguage.oracle.com_projects.yaml
- bases/aispeech.oracle.com_transcriptionjobs.yaml
- bases/aivision.oracle.com_projects.yaml
- bases/analytics.oracle.com_analyticsinstances.yaml
- bases/apigateway.oracle.com_apigatewaydeployments.yaml
- bases/apigateway.oracle.com_apigateways.yaml
- bases/artifacts.oracle.com_containerimagesignatures.yaml
- bases/artifacts.oracle.com_containerrepositories.yaml
- bases/artifacts.oracle.com_repositories.yaml
- bases/bastion.oracle.com_bastions.yaml
- bases/bastion.oracle.com_sessions.yaml
- bases/bds.oracle.com_bdsinstances.yaml
- bases/certificatesmanagement.oracle.com_cabundles.yaml
- bases/containerengine.oracle.com_clusters.yaml
- bases/containerengine.oracle.com_nodepools.yaml
- bases/containerinstances.oracle.com_containerinstances.yaml
- bases/core.oracle.com_drgs.yaml
- bases/core.oracle.com_instances.yaml
- bases/core.oracle.com_internetgateways.yaml
- bases/core.oracle.com_natgateways.yaml
- bases/core.oracle.com_networksecuritygroups.yaml
- bases/core.oracle.com_routetables.yaml
- bases/core.oracle.com_securitylists.yaml
- bases/core.oracle.com_servicegateways.yaml
- bases/core.oracle.com_subnets.yaml
- bases/core.oracle.com_vcns.yaml
- bases/database.oracle.com_autonomousdatabases.yaml
- bases/databasetools.oracle.com_databasetoolsconnections.yaml
- bases/dataflow.oracle.com_applications.yaml
- bases/datascience.oracle.com_projects.yaml
- bases/devops.oracle.com_buildpipelines.yaml
- bases/devops.oracle.com_deployartifacts.yaml
- bases/devops.oracle.com_deploypipelines.yaml
- bases/devops.oracle.com_projects.yaml
- bases/devops.oracle.com_repositories.yaml
- bases/devops.oracle.com_triggers.yaml
- bases/dns.oracle.com_steeringpolicies.yaml
- bases/dns.oracle.com_steeringpolicyattachments.yaml
- bases/dns.oracle.com_tsigkeys.yaml
- bases/dns.oracle.com_views.yaml
- bases/dns.oracle.com_zones.yaml
- bases/email.oracle.com_dkims.yaml
- bases/email.oracle.com_emaildomains.yaml
- bases/email.oracle.com_senders.yaml
- bases/email.oracle.com_suppressions.yaml
- bases/events.oracle.com_rules.yaml
- bases/functions.oracle.com_applications.yaml
- bases/functions.oracle.com_functions.yaml
- bases/generativeai.oracle.com_dedicatedaiclusters.yaml
- bases/generativeai.oracle.com_endpoints.yaml
- bases/generativeai.oracle.com_models.yaml
- bases/governancerulescontrolplane.oracle.com_governancerules.yaml
- bases/governancerulescontrolplane.oracle.com_inclusioncriteria.yaml
- bases/healthchecks.oracle.com_httpmonitors.yaml
- bases/healthchecks.oracle.com_pingmonitors.yaml
- bases/identity.oracle.com_compartments.yaml
- bases/integration.oracle.com_integrationinstances.yaml
- bases/iot.oracle.com_digitaltwinadapters.yaml
- bases/iot.oracle.com_digitaltwininstances.yaml
- bases/iot.oracle.com_digitaltwinmodels.yaml
- bases/iot.oracle.com_digitaltwinrelationships.yaml
- bases/iot.oracle.com_iotdomaingroups.yaml
- bases/iot.oracle.com_iotdomains.yaml
- bases/keymanagement.oracle.com_ekmsprivateendpoints.yaml
- bases/keymanagement.oracle.com_vaults.yaml
- bases/licensemanager.oracle.com_licenserecords.yaml
- bases/licensemanager.oracle.com_productlicenses.yaml
- bases/limits.oracle.com_quotas.yaml
- bases/limitsincrease.oracle.com_limitsincreaserequests.yaml
- bases/loadbalancer.oracle.com_backends.yaml
- bases/loadbalancer.oracle.com_backendsets.yaml
- bases/loadbalancer.oracle.com_certificates.yaml
- bases/loadbalancer.oracle.com_hostnames.yaml
- bases/loadbalancer.oracle.com_listeners.yaml
- bases/loadbalancer.oracle.com_loadbalancers.yaml
- bases/loadbalancer.oracle.com_pathroutesets.yaml
- bases/loadbalancer.oracle.com_routingpolicies.yaml
- bases/loadbalancer.oracle.com_rulesets.yaml
- bases/loadbalancer.oracle.com_sslciphersuites.yaml
- bases/lockbox.oracle.com_approvaltemplates.yaml
- bases/lockbox.oracle.com_lockboxes.yaml
- bases/loganalytics.oracle.com_ingesttimerules.yaml
- bases/loganalytics.oracle.com_loganalyticsembridges.yaml
- bases/loganalytics.oracle.com_loganalyticsentities.yaml
- bases/loganalytics.oracle.com_loganalyticsentitytypes.yaml
- bases/loganalytics.oracle.com_loganalyticsloggroups.yaml
- bases/loganalytics.oracle.com_loganalyticsobjectcollectionrules.yaml
- bases/loganalytics.oracle.com_scheduledtasks.yaml
- bases/logging.oracle.com_loggroups.yaml
- bases/logging.oracle.com_logs.yaml
- bases/logging.oracle.com_logsavedsearches.yaml
- bases/logging.oracle.com_unifiedagentconfigurations.yaml
- bases/managedkafka.oracle.com_kafkaclusterconfigs.yaml
- bases/managedkafka.oracle.com_kafkaclusters.yaml
- bases/managementagent.oracle.com_datasources.yaml
- bases/managementagent.oracle.com_managementagentinstallkeys.yaml
- bases/managementagent.oracle.com_namedcredentials.yaml
- bases/managementdashboard.oracle.com_managementdashboards.yaml
- bases/managementdashboard.oracle.com_managementsavedsearches.yaml
- bases/marketplace.oracle.com_acceptedagreements.yaml
- bases/marketplace.oracle.com_publications.yaml
- bases/marketplaceprivateoffer.oracle.com_attachments.yaml
- bases/marketplaceprivateoffer.oracle.com_offers.yaml
- bases/marketplacepublisher.oracle.com_artifacts.yaml
- bases/marketplacepublisher.oracle.com_listingrevisionattachments.yaml
- bases/marketplacepublisher.oracle.com_listingrevisionnotes.yaml
- bases/marketplacepublisher.oracle.com_listingrevisionpackages.yaml
- bases/marketplacepublisher.oracle.com_listingrevisions.yaml
- bases/marketplacepublisher.oracle.com_listings.yaml
- bases/marketplacepublisher.oracle.com_terms.yaml
- bases/marketplacepublisher.oracle.com_termversions.yaml
- bases/monitoring.oracle.com_alarms.yaml
- bases/monitoring.oracle.com_alarmsuppressions.yaml
- bases/mysql.oracle.com_dbsystems.yaml
- bases/networkloadbalancer.oracle.com_backends.yaml
- bases/networkloadbalancer.oracle.com_backendsets.yaml
- bases/networkloadbalancer.oracle.com_listeners.yaml
- bases/networkloadbalancer.oracle.com_networkloadbalancers.yaml
- bases/nosql.oracle.com_tables.yaml
- bases/objectstorage.oracle.com_buckets.yaml
- bases/ocvp.oracle.com_clusters.yaml
- bases/ocvp.oracle.com_esxihosts.yaml
- bases/ocvp.oracle.com_sddcs.yaml
- bases/oda.oracle.com_authenticationproviders.yaml
- bases/oda.oracle.com_channels.yaml
- bases/oda.oracle.com_digitalassistants.yaml
- bases/oda.oracle.com_importedpackages.yaml
- bases/oda.oracle.com_odainstanceattachments.yaml
- bases/oda.oracle.com_odainstances.yaml
- bases/oda.oracle.com_odaprivateendpointattachments.yaml
- bases/oda.oracle.com_odaprivateendpoints.yaml
- bases/oda.oracle.com_odaprivateendpointscanproxies.yaml
- bases/oda.oracle.com_skillparameters.yaml
- bases/oda.oracle.com_skills.yaml
- bases/oda.oracle.com_translators.yaml
- bases/ons.oracle.com_subscriptions.yaml
- bases/ons.oracle.com_topics.yaml
- bases/opensearch.oracle.com_opensearchclusters.yaml
- bases/operatoraccesscontrol.oracle.com_operatorcontrolassignments.yaml
- bases/operatoraccesscontrol.oracle.com_operatorcontrols.yaml
- bases/opsi.oracle.com_awrhubs.yaml
- bases/opsi.oracle.com_awrhubsources.yaml
- bases/opsi.oracle.com_chargebackplanreports.yaml
- bases/opsi.oracle.com_chargebackplans.yaml
- bases/opsi.oracle.com_databaseinsights.yaml
- bases/opsi.oracle.com_enterprisemanagerbridges.yaml
- bases/opsi.oracle.com_exadatainsights.yaml
- bases/opsi.oracle.com_hostinsights.yaml
- bases/opsi.oracle.com_newsreports.yaml
- bases/opsi.oracle.com_operationsinsightsprivateendpoints.yaml
- bases/opsi.oracle.com_operationsinsightswarehouses.yaml
- bases/opsi.oracle.com_operationsinsightswarehouseusers.yaml
- bases/opsi.oracle.com_opsiconfigurations.yaml
- bases/optimizer.oracle.com_profiles.yaml
- bases/osmanagementhub.oracle.com_lifecycleenvironments.yaml
- bases/osmanagementhub.oracle.com_managedinstancegroups.yaml
- bases/osmanagementhub.oracle.com_managementstations.yaml
- bases/osmanagementhub.oracle.com_profiles.yaml
- bases/osmanagementhub.oracle.com_scheduledjobs.yaml
- bases/osmanagementhub.oracle.com_softwaresources.yaml
- bases/psql.oracle.com_dbsystems.yaml
- bases/queue.oracle.com_queues.yaml
- bases/recovery.oracle.com_protecteddatabases.yaml
- bases/recovery.oracle.com_protectionpolicies.yaml
- bases/recovery.oracle.com_recoveryservicesubnets.yaml
- bases/redis.oracle.com_redisclusters.yaml
- bases/resourceanalytics.oracle.com_monitoredregions.yaml
- bases/resourceanalytics.oracle.com_resourceanalyticsinstances.yaml
- bases/resourceanalytics.oracle.com_tenancyattachments.yaml
- bases/resourcescheduler.oracle.com_schedules.yaml
- bases/sch.oracle.com_serviceconnectors.yaml
- bases/securityattribute.oracle.com_securityattributenamespaces.yaml
- bases/securityattribute.oracle.com_securityattributes.yaml
- bases/servicecatalog.oracle.com_privateapplications.yaml
- bases/servicecatalog.oracle.com_servicecatalogs.yaml
- bases/stackmonitoring.oracle.com_alarmconditions.yaml
- bases/stackmonitoring.oracle.com_baselineablemetrics.yaml
- bases/stackmonitoring.oracle.com_configs.yaml
- bases/stackmonitoring.oracle.com_discoveryjobs.yaml
- bases/stackmonitoring.oracle.com_maintenancewindows.yaml
- bases/stackmonitoring.oracle.com_metricextensions.yaml
- bases/stackmonitoring.oracle.com_monitoredresources.yaml
- bases/stackmonitoring.oracle.com_monitoredresourcetypes.yaml
- bases/stackmonitoring.oracle.com_monitoringtemplates.yaml
- bases/stackmonitoring.oracle.com_processsets.yaml
- bases/streaming.oracle.com_streams.yaml
- bases/usageapi.oracle.com_customtables.yaml
- bases/usageapi.oracle.com_queries.yaml
- bases/usageapi.oracle.com_schedules.yaml
- bases/usageapi.oracle.com_usagecarbonemissionsqueries.yaml
- bases/waa.oracle.com_webappaccelerationpolicies.yaml
- bases/waa.oracle.com_webappaccelerations.yaml
- bases/waas.oracle.com_addresslists.yaml
- bases/waas.oracle.com_certificates.yaml
- bases/waas.oracle.com_customprotectionrules.yaml
- bases/waas.oracle.com_httpredirects.yaml
- bases/waas.oracle.com_waaspolicies.yaml
- bases/waf.oracle.com_networkaddresslists.yaml
- bases/waf.oracle.com_webappfirewallpolicies.yaml
- bases/waf.oracle.com_webappfirewalls.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_streams.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_streams.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
