/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package limits

import (
	"context"

	limitsv1beta1 "github.com/oracle/oci-service-operator/api/limits/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// LimitDefinitionReconciler reconciles a LimitDefinition object.
type LimitDefinitionReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=limits.oracle.com,resources=limitdefinitions,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=limits.oracle.com,resources=limitdefinitions/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=limits.oracle.com,resources=limitdefinitions/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *LimitDefinitionReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	limitDefinition := &limitsv1beta1.LimitDefinition{}
	return r.Reconciler.Reconcile(ctx, req, limitDefinition)
}

// SetupWithManager sets up the controller with the Manager.
func (r *LimitDefinitionReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&limitsv1beta1.LimitDefinition{})
	return builder.
		WithEventFilter(predicate.GenerationChangedPredicate{}).
		Complete(r)
}
