/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package limits

import (
	"context"

	limitsv1beta1 "github.com/oracle/oci-service-operator/api/limits/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// QuotaReconciler reconciles a Quota object.
type QuotaReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=limits.oracle.com,resources=quotas,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=limits.oracle.com,resources=quotas/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=limits.oracle.com,resources=quotas/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *QuotaReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	quota := &limitsv1beta1.Quota{}
	return r.Reconciler.Reconcile(ctx, req, quota)
}

// SetupWithManager sets up the controller with the Manager.
func (r *QuotaReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&limitsv1beta1.Quota{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
