/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package refreshactivity

import (
	"context"
	"fmt"

	fusionappssdk "github.com/oracle/oci-go-sdk/v65/fusionapps"
	fusionappsv1beta1 "github.com/oracle/oci-service-operator/api/fusionapps/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// RefreshActivityServiceClient is the handwritten extension seam for RefreshActivity runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*RefreshActivityServiceManager).WithClient.
type RefreshActivityServiceClient interface {
	CreateOrUpdate(context.Context, *fusionappsv1beta1.RefreshActivity, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *fusionappsv1beta1.RefreshActivity) (bool, error)
}

type defaultRefreshActivityServiceClient struct {
	generatedruntime.ServiceClient[*fusionappsv1beta1.RefreshActivity]
}

var _ RefreshActivityServiceClient = defaultRefreshActivityServiceClient{}

var newRefreshActivityServiceClient = func(manager *RefreshActivityServiceManager) RefreshActivityServiceClient {
	sdkClient, err := fusionappssdk.NewFusionApplicationsClientWithConfigurationProvider(manager.Provider)
	hooks := newRefreshActivityRuntimeHooks(manager, sdkClient)
	config := buildRefreshActivityGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize RefreshActivity OCI client: %w", err)
	}
	delegate := defaultRefreshActivityServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*fusionappsv1beta1.RefreshActivity](config),
	}
	return wrapRefreshActivityGeneratedClient(hooks, delegate)
}
