apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/database.oracle.com_applicationvips.yaml
- bases/database.oracle.com_autonomouscontainerdatabasedataguardassociations.yaml
- bases/database.oracle.com_autonomouscontainerdatabaseresourceusages.yaml
- bases/database.oracle.com_autonomouscontainerdatabases.yaml
- bases/database.oracle.com_autonomouscontainerdatabaseversions.yaml
- bases/database.oracle.com_autonomousdatabasebackups.yaml
- bases/database.oracle.com_autonomousdatabasecharactersets.yaml
- bases/database.oracle.com_autonomousdatabaseclones.yaml
- bases/database.oracle.com_autonomousdatabasedataguardassociations.yaml
- bases/database.oracle.com_autonomousdatabaserefreshableclones.yaml
- bases/database.oracle.com_autonomousdatabaseregionalwallets.yaml
- bases/database.oracle.com_autonomousdatabases.yaml
- bases/database.oracle.com_autonomousdatabasewallets.yaml
- bases/database.oracle.com_autonomousdbpreviewversions.yaml
- bases/database.oracle.com_autonomousdbversions.yaml
- bases/database.oracle.com_autonomousexadatainfrastructures.yaml
- bases/database.oracle.com_autonomousexadatainfrastructureshapes.yaml
- bases/database.oracle.com_autonomouspatches.yaml
- bases/database.oracle.com_autonomousvirtualmachines.yaml
- bases/database.oracle.com_autonomousvmclusteracdresourceusages.yaml
- bases/database.oracle.com_autonomousvmclusterresourceusages.yaml
- bases/database.oracle.com_autonomousvmclusters.yaml
- bases/database.oracle.com_backupdestinations.yaml
- bases/database.oracle.com_backups.yaml
- bases/database.oracle.com_cloudautonomousvmclusteracdresourceusages.yaml
- bases/database.oracle.com_cloudautonomousvmclusterresourceusages.yaml
- bases/database.oracle.com_cloudautonomousvmclusters.yaml
- bases/database.oracle.com_cloudexadatainfrastructures.yaml
- bases/database.oracle.com_cloudexadatainfrastructureunallocatedresources.yaml
- bases/database.oracle.com_cloudvmclusteriormconfigs.yaml
- bases/database.oracle.com_cloudvmclusters.yaml
- bases/database.oracle.com_cloudvmclusterupdatehistoryentries.yaml
- bases/database.oracle.com_cloudvmclusterupdates.yaml
- bases/database.oracle.com_consoleconnections.yaml
- bases/database.oracle.com_consolehistories.yaml
- bases/database.oracle.com_consolehistorycontents.yaml
- bases/database.oracle.com_containerdatabasepatches.yaml
- bases/database.oracle.com_databases.yaml
- bases/database.oracle.com_databasesoftwareimages.yaml
- bases/database.oracle.com_databaseupgradehistoryentries.yaml
- bases/database.oracle.com_dataguardassociations.yaml
- bases/database.oracle.com_dbhomepatches.yaml
- bases/database.oracle.com_dbhomepatchhistoryentries.yaml
- bases/database.oracle.com_dbhomes.yaml
- bases/database.oracle.com_dbnodes.yaml
- bases/database.oracle.com_dbservers.yaml
- bases/database.oracle.com_dbsystemcomputeperformances.yaml
- bases/database.oracle.com_dbsystempatches.yaml
- bases/database.oracle.com_dbsystempatchhistoryentries.yaml
- bases/database.oracle.com_dbsystems.yaml
- bases/database.oracle.com_dbsystemshapes.yaml
- bases/database.oracle.com_dbsystemstorageperformances.yaml
- bases/database.oracle.com_dbsystemupgradehistoryentries.yaml
- bases/database.oracle.com_dbversions.yaml
- bases/database.oracle.com_exadatainfrastructureocpus.yaml
- bases/database.oracle.com_exadatainfrastructures.yaml
- bases/database.oracle.com_exadatainfrastructureunallocatedresources.yaml
- bases/database.oracle.com_exadataiormconfigs.yaml
- bases/database.oracle.com_externalbackupjobs.yaml
- bases/database.oracle.com_externalcontainerdatabases.yaml
- bases/database.oracle.com_externaldatabaseconnectors.yaml
- bases/database.oracle.com_externalnoncontainerdatabases.yaml
- bases/database.oracle.com_externalpluggabledatabases.yaml
- bases/database.oracle.com_flexcomponents.yaml
- bases/database.oracle.com_giversions.yaml
- bases/database.oracle.com_infrastructuretargetversions.yaml
- bases/database.oracle.com_keystores.yaml
- bases/database.oracle.com_maintenancerunhistories.yaml
- bases/database.oracle.com_maintenanceruns.yaml
- bases/database.oracle.com_oneoffpatches.yaml
- bases/database.oracle.com_pdbconversionhistoryentries.yaml
- bases/database.oracle.com_pluggabledatabases.yaml
- bases/database.oracle.com_systemversions.yaml
- bases/database.oracle.com_vmclusternetworks.yaml
- bases/database.oracle.com_vmclusterpatches.yaml
- bases/database.oracle.com_vmclusterpatchhistoryentries.yaml
- bases/database.oracle.com_vmclusters.yaml
- bases/database.oracle.com_vmclusterupdatehistoryentries.yaml
- bases/database.oracle.com_vmclusterupdates.yaml
