/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package identity

import (
	"context"

	identityv1beta1 "github.com/oracle/oci-service-operator/api/identity/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// IdpGroupMappingReconciler reconciles a IdpGroupMapping object.
type IdpGroupMappingReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=identity.oracle.com,resources=idpgroupmappings,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=identity.oracle.com,resources=idpgroupmappings/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=identity.oracle.com,resources=idpgroupmappings/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *IdpGroupMappingReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	idpGroupMapping := &identityv1beta1.IdpGroupMapping{}
	return r.Reconciler.Reconcile(ctx, req, idpGroupMapping)
}

// SetupWithManager sets up the controller with the Manager.
func (r *IdpGroupMappingReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&identityv1beta1.IdpGroupMapping{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
