/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package resourcemanager

import (
	"context"

	resourcemanagerv1beta1 "github.com/oracle/oci-service-operator/api/resourcemanager/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ConfigurationSourceProviderReconciler reconciles a ConfigurationSourceProvider object.
type ConfigurationSourceProviderReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=resourcemanager.oracle.com,resources=configurationsourceproviders,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=resourcemanager.oracle.com,resources=configurationsourceproviders/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=resourcemanager.oracle.com,resources=configurationsourceproviders/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *ConfigurationSourceProviderReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	configurationSourceProvider := &resourcemanagerv1beta1.ConfigurationSourceProvider{}
	return r.Reconciler.Reconcile(ctx, req, configurationSourceProvider)
}

// SetupWithManager sets up the controller with the Manager.
func (r *ConfigurationSourceProviderReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&resourcemanagerv1beta1.ConfigurationSourceProvider{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
