/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package cluster

import (
	"context"
	"fmt"

	ocvpsdk "github.com/oracle/oci-go-sdk/v65/ocvp"
	ocvpv1beta1 "github.com/oracle/oci-service-operator/api/ocvp/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ClusterServiceClient is the handwritten extension seam for Cluster runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*ClusterServiceManager).WithClient.
type ClusterServiceClient interface {
	CreateOrUpdate(context.Context, *ocvpv1beta1.Cluster, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *ocvpv1beta1.Cluster) (bool, error)
}

type defaultClusterServiceClient struct {
	generatedruntime.ServiceClient[*ocvpv1beta1.Cluster]
}

var _ ClusterServiceClient = defaultClusterServiceClient{}

var newClusterServiceClient = func(manager *ClusterServiceManager) ClusterServiceClient {
	sdkClient, err := ocvpsdk.NewClusterClientWithConfigurationProvider(manager.Provider)
	hooks := newClusterRuntimeHooks(manager, sdkClient)
	config := buildClusterGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize Cluster OCI client: %w", err)
	}
	delegate := defaultClusterServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*ocvpv1beta1.Cluster](config),
	}
	return wrapClusterGeneratedClient(hooks, delegate)
}
