/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package desktoppool

import (
	"context"
	"fmt"

	desktopssdk "github.com/oracle/oci-go-sdk/v65/desktops"
	desktopsv1beta1 "github.com/oracle/oci-service-operator/api/desktops/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DesktopPoolServiceClient is the handwritten extension seam for DesktopPool runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DesktopPoolServiceManager).WithClient.
type DesktopPoolServiceClient interface {
	CreateOrUpdate(context.Context, *desktopsv1beta1.DesktopPool, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *desktopsv1beta1.DesktopPool) (bool, error)
}

type defaultDesktopPoolServiceClient struct {
	generatedruntime.ServiceClient[*desktopsv1beta1.DesktopPool]
}

var _ DesktopPoolServiceClient = defaultDesktopPoolServiceClient{}

var newDesktopPoolServiceClient = func(manager *DesktopPoolServiceManager) DesktopPoolServiceClient {
	sdkClient, err := desktopssdk.NewDesktopServiceClientWithConfigurationProvider(manager.Provider)
	hooks := newDesktopPoolRuntimeHooks(manager, sdkClient)
	config := buildDesktopPoolGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DesktopPool OCI client: %w", err)
	}
	delegate := defaultDesktopPoolServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*desktopsv1beta1.DesktopPool](config),
	}
	return wrapDesktopPoolGeneratedClient(hooks, delegate)
}
