apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/resourcemanager.oracle.com_configurationsourceproviders.yaml
- bases/resourcemanager.oracle.com_privateendpoints.yaml
- bases/resourcemanager.oracle.com_stacks.yaml
- bases/resourcemanager.oracle.com_templates.yaml
