//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/oracle/oci-service-operator/pkg/shared"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatform) DeepCopyInto(out *BlockchainPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatform.
func (in *BlockchainPlatform) DeepCopy() *BlockchainPlatform {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockchainPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformComponentDetails) DeepCopyInto(out *BlockchainPlatformComponentDetails) {
	*out = *in
	if in.Osns != nil {
		in, out := &in.Osns, &out.Osns
		*out = make([]BlockchainPlatformComponentDetailsOsn, len(*in))
		copy(*out, *in)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]BlockchainPlatformComponentDetailsPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformComponentDetails.
func (in *BlockchainPlatformComponentDetails) DeepCopy() *BlockchainPlatformComponentDetails {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformComponentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformComponentDetailsOsn) DeepCopyInto(out *BlockchainPlatformComponentDetailsOsn) {
	*out = *in
	out.OcpuAllocationParam = in.OcpuAllocationParam
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformComponentDetailsOsn.
func (in *BlockchainPlatformComponentDetailsOsn) DeepCopy() *BlockchainPlatformComponentDetailsOsn {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformComponentDetailsOsn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformComponentDetailsOsnOcpuAllocationParam) DeepCopyInto(out *BlockchainPlatformComponentDetailsOsnOcpuAllocationParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformComponentDetailsOsnOcpuAllocationParam.
func (in *BlockchainPlatformComponentDetailsOsnOcpuAllocationParam) DeepCopy() *BlockchainPlatformComponentDetailsOsnOcpuAllocationParam {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformComponentDetailsOsnOcpuAllocationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformComponentDetailsPeer) DeepCopyInto(out *BlockchainPlatformComponentDetailsPeer) {
	*out = *in
	out.OcpuAllocationParam = in.OcpuAllocationParam
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformComponentDetailsPeer.
func (in *BlockchainPlatformComponentDetailsPeer) DeepCopy() *BlockchainPlatformComponentDetailsPeer {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformComponentDetailsPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformComponentDetailsPeerOcpuAllocationParam) DeepCopyInto(out *BlockchainPlatformComponentDetailsPeerOcpuAllocationParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformComponentDetailsPeerOcpuAllocationParam.
func (in *BlockchainPlatformComponentDetailsPeerOcpuAllocationParam) DeepCopy() *BlockchainPlatformComponentDetailsPeerOcpuAllocationParam {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformComponentDetailsPeerOcpuAllocationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformHostOcpuUtilizationInfo) DeepCopyInto(out *BlockchainPlatformHostOcpuUtilizationInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformHostOcpuUtilizationInfo.
func (in *BlockchainPlatformHostOcpuUtilizationInfo) DeepCopy() *BlockchainPlatformHostOcpuUtilizationInfo {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformHostOcpuUtilizationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformList) DeepCopyInto(out *BlockchainPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlockchainPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformList.
func (in *BlockchainPlatformList) DeepCopy() *BlockchainPlatformList {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockchainPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformReplicas) DeepCopyInto(out *BlockchainPlatformReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformReplicas.
func (in *BlockchainPlatformReplicas) DeepCopy() *BlockchainPlatformReplicas {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformSpec) DeepCopyInto(out *BlockchainPlatformSpec) {
	*out = *in
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.Replicas = in.Replicas
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformSpec.
func (in *BlockchainPlatformSpec) DeepCopy() *BlockchainPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockchainPlatformStatus) DeepCopyInto(out *BlockchainPlatformStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	in.ComponentDetails.DeepCopyInto(&out.ComponentDetails)
	out.Replicas = in.Replicas
	if in.HostOcpuUtilizationInfo != nil {
		in, out := &in.HostOcpuUtilizationInfo, &out.HostOcpuUtilizationInfo
		*out = make([]BlockchainPlatformHostOcpuUtilizationInfo, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockchainPlatformStatus.
func (in *BlockchainPlatformStatus) DeepCopy() *BlockchainPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(BlockchainPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Osn) DeepCopyInto(out *Osn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Osn.
func (in *Osn) DeepCopy() *Osn {
	if in == nil {
		return nil
	}
	out := new(Osn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Osn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsnList) DeepCopyInto(out *OsnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Osn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsnList.
func (in *OsnList) DeepCopy() *OsnList {
	if in == nil {
		return nil
	}
	out := new(OsnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsnOcpuAllocationParam) DeepCopyInto(out *OsnOcpuAllocationParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsnOcpuAllocationParam.
func (in *OsnOcpuAllocationParam) DeepCopy() *OsnOcpuAllocationParam {
	if in == nil {
		return nil
	}
	out := new(OsnOcpuAllocationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsnSpec) DeepCopyInto(out *OsnSpec) {
	*out = *in
	out.OcpuAllocationParam = in.OcpuAllocationParam
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsnSpec.
func (in *OsnSpec) DeepCopy() *OsnSpec {
	if in == nil {
		return nil
	}
	out := new(OsnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsnStatus) DeepCopyInto(out *OsnStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	out.OcpuAllocationParam = in.OcpuAllocationParam
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsnStatus.
func (in *OsnStatus) DeepCopy() *OsnStatus {
	if in == nil {
		return nil
	}
	out := new(OsnStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peer) DeepCopyInto(out *Peer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peer.
func (in *Peer) DeepCopy() *Peer {
	if in == nil {
		return nil
	}
	out := new(Peer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Peer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerList) DeepCopyInto(out *PeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Peer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerList.
func (in *PeerList) DeepCopy() *PeerList {
	if in == nil {
		return nil
	}
	out := new(PeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerOcpuAllocationParam) DeepCopyInto(out *PeerOcpuAllocationParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerOcpuAllocationParam.
func (in *PeerOcpuAllocationParam) DeepCopy() *PeerOcpuAllocationParam {
	if in == nil {
		return nil
	}
	out := new(PeerOcpuAllocationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerSpec) DeepCopyInto(out *PeerSpec) {
	*out = *in
	out.OcpuAllocationParam = in.OcpuAllocationParam
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerSpec.
func (in *PeerSpec) DeepCopy() *PeerSpec {
	if in == nil {
		return nil
	}
	out := new(PeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerStatus) DeepCopyInto(out *PeerStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	out.OcpuAllocationParam = in.OcpuAllocationParam
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerStatus.
func (in *PeerStatus) DeepCopy() *PeerStatus {
	if in == nil {
		return nil
	}
	out := new(PeerStatus)
	in.DeepCopyInto(out)
	return out
}
