/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package workloadmapping

import (
	"context"
	"fmt"

	containerenginesdk "github.com/oracle/oci-go-sdk/v65/containerengine"
	containerenginev1beta1 "github.com/oracle/oci-service-operator/api/containerengine/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// WorkloadMappingServiceClient is the handwritten extension seam for WorkloadMapping runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*WorkloadMappingServiceManager).WithClient.
type WorkloadMappingServiceClient interface {
	CreateOrUpdate(context.Context, *containerenginev1beta1.WorkloadMapping, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *containerenginev1beta1.WorkloadMapping) (bool, error)
}

type defaultWorkloadMappingServiceClient struct {
	generatedruntime.ServiceClient[*containerenginev1beta1.WorkloadMapping]
}

var _ WorkloadMappingServiceClient = defaultWorkloadMappingServiceClient{}

var newWorkloadMappingServiceClient = func(manager *WorkloadMappingServiceManager) WorkloadMappingServiceClient {
	sdkClient, err := containerenginesdk.NewContainerEngineClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*containerenginev1beta1.WorkloadMapping]{
		Kind:    "WorkloadMapping",
		SDKName: "WorkloadMapping",
		Log:     manager.Log,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &containerenginesdk.CreateWorkloadMappingRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.CreateWorkloadMapping(ctx, *request.(*containerenginesdk.CreateWorkloadMappingRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &containerenginesdk.GetWorkloadMappingRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetWorkloadMapping(ctx, *request.(*containerenginesdk.GetWorkloadMappingRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &containerenginesdk.ListWorkloadMappingsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListWorkloadMappings(ctx, *request.(*containerenginesdk.ListWorkloadMappingsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &containerenginesdk.UpdateWorkloadMappingRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.UpdateWorkloadMapping(ctx, *request.(*containerenginesdk.UpdateWorkloadMappingRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &containerenginesdk.DeleteWorkloadMappingRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.DeleteWorkloadMapping(ctx, *request.(*containerenginesdk.DeleteWorkloadMappingRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize WorkloadMapping OCI client: %w", err)
	}
	return defaultWorkloadMappingServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*containerenginev1beta1.WorkloadMapping](config),
	}
}
