/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package volumegroupreplica

import (
	"context"
	"fmt"

	coresdk "github.com/oracle/oci-go-sdk/v65/core"
	corev1beta1 "github.com/oracle/oci-service-operator/api/core/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// VolumeGroupReplicaServiceClient is the handwritten extension seam for VolumeGroupReplica runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*VolumeGroupReplicaServiceManager).WithClient.
type VolumeGroupReplicaServiceClient interface {
	CreateOrUpdate(context.Context, *corev1beta1.VolumeGroupReplica, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *corev1beta1.VolumeGroupReplica) (bool, error)
}

type defaultVolumeGroupReplicaServiceClient struct {
	generatedruntime.ServiceClient[*corev1beta1.VolumeGroupReplica]
}

var _ VolumeGroupReplicaServiceClient = defaultVolumeGroupReplicaServiceClient{}

var newVolumeGroupReplicaServiceClient = func(manager *VolumeGroupReplicaServiceManager) VolumeGroupReplicaServiceClient {
	sdkClient, err := coresdk.NewBlockstorageClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*corev1beta1.VolumeGroupReplica]{
		Kind:    "VolumeGroupReplica",
		SDKName: "VolumeGroupReplica",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.GetVolumeGroupReplicaRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetVolumeGroupReplica(ctx, *request.(*coresdk.GetVolumeGroupReplicaRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.ListVolumeGroupReplicasRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListVolumeGroupReplicas(ctx, *request.(*coresdk.ListVolumeGroupReplicasRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize VolumeGroupReplica OCI client: %w", err)
	}
	return defaultVolumeGroupReplicaServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*corev1beta1.VolumeGroupReplica](config),
	}
}
