apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/certificates.oracle.com_cabundles.yaml
- bases/certificates.oracle.com_certificateauthoritybundles.yaml
- bases/certificates.oracle.com_certificateauthoritybundleversions.yaml
- bases/certificates.oracle.com_certificatebundles.yaml
- bases/certificates.oracle.com_certificatebundleversions.yaml
