/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package organization

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	tenantmanagercontrolplanev1beta1 "github.com/oracle/oci-service-operator/api/tenantmanagercontrolplane/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type OrganizationServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client OrganizationServiceClient
}

var _ servicemanager.OSOKServiceManager = (*OrganizationServiceManager)(nil)

func NewOrganizationServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *OrganizationServiceManager {
	manager := &OrganizationServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newOrganizationServiceClient(manager)
	return manager
}

func NewOrganizationServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *OrganizationServiceManager {
	return NewOrganizationServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *OrganizationServiceManager) WithClient(client OrganizationServiceClient) *OrganizationServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *OrganizationServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *OrganizationServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *OrganizationServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *OrganizationServiceManager) convert(obj runtime.Object) (*tenantmanagercontrolplanev1beta1.Organization, error) {
	resource, ok := obj.(*tenantmanagercontrolplanev1beta1.Organization)
	if !ok {
		return nil, fmt.Errorf("expected *tenantmanagercontrolplanev1beta1.Organization, got %T", obj)
	}
	return resource, nil
}

func (c *OrganizationServiceManager) status(resource *tenantmanagercontrolplanev1beta1.Organization) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
