apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/objectstorage.oracle.com_buckets.yaml
- bases/objectstorage.oracle.com_multipartuploadparts.yaml
- bases/objectstorage.oracle.com_multipartuploads.yaml
- bases/objectstorage.oracle.com_namespacemetadata.yaml
- bases/objectstorage.oracle.com_namespaces.yaml
- bases/objectstorage.oracle.com_objectlifecyclepolicies.yaml
- bases/objectstorage.oracle.com_objects.yaml
- bases/objectstorage.oracle.com_objectstoragetiers.yaml
- bases/objectstorage.oracle.com_objectversions.yaml
- bases/objectstorage.oracle.com_preauthenticatedrequests.yaml
- bases/objectstorage.oracle.com_replicationpolicies.yaml
- bases/objectstorage.oracle.com_replicationsources.yaml
- bases/objectstorage.oracle.com_retentionrules.yaml
- bases/objectstorage.oracle.com_workrequesterrors.yaml
- bases/objectstorage.oracle.com_workrequestlogs.yaml
- bases/objectstorage.oracle.com_workrequests.yaml
