/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package shape

import (
	"context"
	"fmt"

	psqlsdk "github.com/oracle/oci-go-sdk/v65/psql"
	psqlv1beta1 "github.com/oracle/oci-service-operator/api/psql/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ShapeServiceClient is the handwritten extension seam for Shape runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*ShapeServiceManager).WithClient.
type ShapeServiceClient interface {
	CreateOrUpdate(context.Context, *psqlv1beta1.Shape, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *psqlv1beta1.Shape) (bool, error)
}

type defaultShapeServiceClient struct {
	generatedruntime.ServiceClient[*psqlv1beta1.Shape]
}

var _ ShapeServiceClient = defaultShapeServiceClient{}

var newShapeServiceClient = func(manager *ShapeServiceManager) ShapeServiceClient {
	sdkClient, err := psqlsdk.NewPostgresqlClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*psqlv1beta1.Shape]{
		Kind:    "Shape",
		SDKName: "Shape",
		Log:     manager.Log,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &psqlsdk.ListShapesRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListShapes(ctx, *request.(*psqlsdk.ListShapesRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize Shape OCI client: %w", err)
	}
	return defaultShapeServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*psqlv1beta1.Shape](config),
	}
}
