/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OracleDbAzureVaultAssociationSpec defines the desired state of OracleDbAzureVaultAssociation.
type OracleDbAzureVaultAssociationSpec struct {
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment that contains Oracle DB Azure Vault Association resource.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// Oracle DB Azure Vault Association resource name.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Oracle DB Azure Vault that contains Oracle DB Azure Vault Association resource.
	// +kubebuilder:validation:Required
	OracleDbAzureVaultId string `json:"oracleDbAzureVaultId"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Oracle DB Azure Connector that contains Oracle DB Azure Vault Association resource.
	// +kubebuilder:validation:Required
	OracleDbAzureConnectorId string `json:"oracleDbAzureConnectorId"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// OracleDbAzureVaultAssociationStatus defines the observed state of OracleDbAzureVaultAssociation.
type OracleDbAzureVaultAssociationStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Oracle DB Azure Vault Association resource.
	Id string `json:"id,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment that contains Oracle DB Azure Vault Association resource.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Oracle DB Azure Vault Association resource name.
	DisplayName string `json:"displayName,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Oracle DB Azure Connector that contains Oracle DB Azure Vault Association resource.
	OracleDbAzureConnectorId string `json:"oracleDbAzureConnectorId,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Oracle DB Azure Vault that contains Oracle DB Azure Vault Association resource.
	OracleDbAzureVaultId string `json:"oracleDbAzureVaultId,omitempty"`
	// The Associated resource is accessible or not.
	IsResourceAccessible bool `json:"isResourceAccessible,omitempty"`
	// The current lifecycle state of the Oracle DB Azure Vault Association resource.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// Description of the current lifecycle state in more detail.
	LifecycleStateDetails string `json:"lifecycleStateDetails,omitempty"`
	// Time when the Oracle DB Azure Vault Association resource was created in RFC 3339 (https://tools.ietf.org/html/rfc3339) timestamp format, e.g. '2020-05-22T21:10:29.600Z'
	TimeCreated string `json:"timeCreated,omitempty"`
	// Time when the Oracle DB Azure Vault Association resource was last modified, expressed in RFC 3339 (https://tools.ietf.org/html/rfc3339) timestamp format, e.g. '2020-05-22T21:10:29.600Z'
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// Description of the latest modification of the Oracle DB Azure Vault Association resource.
	LastModification string `json:"lastModification,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the OracleDbAzureVaultAssociation",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the OracleDbAzureVaultAssociation",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// OracleDbAzureVaultAssociation is the Schema for the oracledbazurevaultassociations API.
type OracleDbAzureVaultAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   OracleDbAzureVaultAssociationSpec   `json:"spec,omitempty"`
	Status OracleDbAzureVaultAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// OracleDbAzureVaultAssociationList contains a list of OracleDbAzureVaultAssociation.
type OracleDbAzureVaultAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OracleDbAzureVaultAssociation `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OracleDbAzureVaultAssociation{}, &OracleDbAzureVaultAssociationList{})
}
