/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package datasource

import (
	"context"
	"fmt"

	cloudguardsdk "github.com/oracle/oci-go-sdk/v65/cloudguard"
	cloudguardv1beta1 "github.com/oracle/oci-service-operator/api/cloudguard/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DataSourceServiceClient is the handwritten extension seam for DataSource runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DataSourceServiceManager).WithClient.
type DataSourceServiceClient interface {
	CreateOrUpdate(context.Context, *cloudguardv1beta1.DataSource, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *cloudguardv1beta1.DataSource) (bool, error)
}

type defaultDataSourceServiceClient struct {
	generatedruntime.ServiceClient[*cloudguardv1beta1.DataSource]
}

var _ DataSourceServiceClient = defaultDataSourceServiceClient{}

var newDataSourceServiceClient = func(manager *DataSourceServiceManager) DataSourceServiceClient {
	sdkClient, err := cloudguardsdk.NewCloudGuardClientWithConfigurationProvider(manager.Provider)
	hooks := newDataSourceRuntimeHooks(manager, sdkClient)
	config := buildDataSourceGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DataSource OCI client: %w", err)
	}
	delegate := defaultDataSourceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*cloudguardv1beta1.DataSource](config),
	}
	return wrapDataSourceGeneratedClient(hooks, delegate)
}
