/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package announcementsservice

import (
	"context"

	announcementsservicev1beta1 "github.com/oracle/oci-service-operator/api/announcementsservice/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AnnouncementSubscriptionReconciler reconciles a AnnouncementSubscription object.
type AnnouncementSubscriptionReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=announcementsservice.oracle.com,resources=announcementsubscriptions,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=announcementsservice.oracle.com,resources=announcementsubscriptions/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=announcementsservice.oracle.com,resources=announcementsubscriptions/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *AnnouncementSubscriptionReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	announcementSubscription := &announcementsservicev1beta1.AnnouncementSubscription{}
	return r.Reconciler.Reconcile(ctx, req, announcementSubscription)
}

// SetupWithManager sets up the controller with the Manager.
func (r *AnnouncementSubscriptionReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&announcementsservicev1beta1.AnnouncementSubscription{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
