/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FunctionSpec defines the desired state of Function.
type FunctionSpec struct {
	// The display name of the function. The display name must be unique within the application containing the function. Avoid entering confidential information.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// The OCID of the application this function belongs to.
	// +kubebuilder:validation:Required
	ApplicationId string `json:"applicationId"`
	// Maximum usable memory for the function (MiB).
	// +kubebuilder:validation:Required
	MemoryInMBs int64 `json:"memoryInMBs"`
	// The qualified name of the Docker image to use in the function, including the image tag.
	// The image should be in the OCI Registry that is in the same region as the function itself.
	// Example: `phx.ocir.io/ten/functions/function:0.0.1`
	// +kubebuilder:validation:Optional
	Image string `json:"image,omitempty"`
	// The image digest for the version of the image that will be pulled when invoking this function.
	// If no value is specified, the digest currently associated with the image in the OCI Registry will be used.
	// Example: `sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7`
	// +kubebuilder:validation:Optional
	ImageDigest string `json:"imageDigest,omitempty"`
	// +kubebuilder:validation:Optional
	SourceDetails FunctionSourceDetails `json:"sourceDetails,omitempty"`
	// Function configuration. These values are passed on to the function as environment variables, this overrides application configuration values.
	// Keys must be ASCII strings consisting solely of letters, digits, and the '_' (underscore) character, and must not begin with a digit. Values should be limited to printable unicode characters.
	// Example: `{"MY_FUNCTION_CONFIG": "ConfVal"}`
	// The maximum size for all configuration keys and values is limited to 4KB. This is measured as the sum of octets necessary to represent each key and value in UTF-8.
	// +kubebuilder:validation:Optional
	Config map[string]string `json:"config,omitempty"`
	// Timeout for executions of the function. Value in seconds.
	// +kubebuilder:validation:Optional
	TimeoutInSeconds int `json:"timeoutInSeconds,omitempty"`
	// +kubebuilder:validation:Optional
	ProvisionedConcurrencyConfig FunctionProvisionedConcurrencyConfig `json:"provisionedConcurrencyConfig,omitempty"`
	// +kubebuilder:validation:Optional
	TraceConfig FunctionTraceConfig `json:"traceConfig,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// FunctionSourceDetails defines nested fields for Function.SourceDetails.
type FunctionSourceDetails struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	SourceType string `json:"sourceType,omitempty"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the PbfListing this
	// function is sourced from.
	// +kubebuilder:validation:Optional
	PbfListingId string `json:"pbfListingId,omitempty"`
}

// FunctionProvisionedConcurrencyConfig defines nested fields for Function.ProvisionedConcurrencyConfig.
type FunctionProvisionedConcurrencyConfig struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// +kubebuilder:validation:Optional
	Strategy string `json:"strategy,omitempty"`
	// Configuration specifying a constant amount of provisioned concurrency.
	// +kubebuilder:validation:Optional
	Count int `json:"count,omitempty"`
}

// FunctionTraceConfig defines nested fields for Function.TraceConfig.
type FunctionTraceConfig struct {
	// Define if tracing is enabled for the resource.
	// +kubebuilder:validation:Optional
	IsEnabled bool `json:"isEnabled,omitempty"`
}

// FunctionStatus defines the observed state of Function.
type FunctionStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the function.
	Id string `json:"id,omitempty"`
	// The display name of the function. The display name is unique within the application containing the function.
	DisplayName string `json:"displayName,omitempty"`
	// The current state of the function.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The OCID of the application the function belongs to.
	ApplicationId string `json:"applicationId,omitempty"`
	// The OCID of the compartment that contains the function.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The qualified name of the Docker image to use in the function, including the image tag.
	// The image should be in the OCI Registry that is in the same region as the function itself.
	// Example: `phx.ocir.io/ten/functions/function:0.0.1`
	Image string `json:"image,omitempty"`
	// The image digest for the version of the image that will be pulled when invoking this function.
	// If no value is specified, the digest currently associated with the image in the OCI Registry will be used.
	// Example: `sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7`
	ImageDigest   string                `json:"imageDigest,omitempty"`
	SourceDetails FunctionSourceDetails `json:"sourceDetails,omitempty"`
	// The processor shape (`GENERIC_X86`/`GENERIC_ARM`) on which to run functions in the application, extracted from the image manifest.
	Shape string `json:"shape,omitempty"`
	// Maximum usable memory for the function (MiB).
	MemoryInMBs int64 `json:"memoryInMBs,omitempty"`
	// Function configuration. Overrides application configuration.
	// Keys must be ASCII strings consisting solely of letters, digits, and the '_' (underscore) character, and must not begin with a digit. Values should be limited to printable unicode characters.
	// Example: `{"MY_FUNCTION_CONFIG": "ConfVal"}`
	// The maximum size for all configuration keys and values is limited to 4KB. This is measured as the sum of octets necessary to represent each key and value in UTF-8.
	Config map[string]string `json:"config,omitempty"`
	// Timeout for executions of the function. Value in seconds.
	TimeoutInSeconds             int                                  `json:"timeoutInSeconds,omitempty"`
	ProvisionedConcurrencyConfig FunctionProvisionedConcurrencyConfig `json:"provisionedConcurrencyConfig,omitempty"`
	TraceConfig                  FunctionTraceConfig                  `json:"traceConfig,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// The base https invoke URL to set on a client in order to invoke a function. This URL will never change over the lifetime of the function and can be cached.
	InvokeEndpoint string `json:"invokeEndpoint,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The time the function was created, expressed in RFC 3339 (https://tools.ietf.org/html/rfc3339)
	// timestamp format.
	// Example: `2018-09-12T22:47:12.613Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The time the function was updated, expressed in RFC 3339 (https://tools.ietf.org/html/rfc3339)
	// timestamp format.
	// Example: `2018-09-12T22:47:12.613Z`
	TimeUpdated string `json:"timeUpdated,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the Function",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the Function",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// Function is the Schema for the functions API.
type Function struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   FunctionSpec   `json:"spec,omitempty"`
	Status FunctionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// FunctionList contains a list of Function.
type FunctionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Function `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Function{}, &FunctionList{})
}
