---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - zpr.oracle.com
  resources:
  - configurations
  - zprpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zpr.oracle.com
  resources:
  - configurations/finalizers
  - zprpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - zpr.oracle.com
  resources:
  - configurations/status
  - zprpolicies/status
  verbs:
  - get
  - patch
  - update
