/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package objectstorage

import (
	"context"

	objectstoragev1beta1 "github.com/oracle/oci-service-operator/api/objectstorage/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// BucketReconciler reconciles a Bucket object.
type BucketReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=objectstorage.oracle.com,resources=buckets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=objectstorage.oracle.com,resources=buckets/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=objectstorage.oracle.com,resources=buckets/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *BucketReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	bucket := &objectstoragev1beta1.Bucket{}
	return r.Reconciler.Reconcile(ctx, req, bucket)
}

// SetupWithManager sets up the controller with the Manager.
func (r *BucketReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&objectstoragev1beta1.Bucket{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
