/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package servicecatalog

import (
	"context"
	"fmt"

	servicecatalogsdk "github.com/oracle/oci-go-sdk/v65/servicecatalog"
	servicecatalogv1beta1 "github.com/oracle/oci-service-operator/api/servicecatalog/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ServiceCatalogServiceClient is the handwritten extension seam for ServiceCatalog runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*ServiceCatalogServiceManager).WithClient.
type ServiceCatalogServiceClient interface {
	CreateOrUpdate(context.Context, *servicecatalogv1beta1.ServiceCatalog, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *servicecatalogv1beta1.ServiceCatalog) (bool, error)
}

type defaultServiceCatalogServiceClient struct {
	generatedruntime.ServiceClient[*servicecatalogv1beta1.ServiceCatalog]
}

var _ ServiceCatalogServiceClient = defaultServiceCatalogServiceClient{}

var newServiceCatalogServiceClient = func(manager *ServiceCatalogServiceManager) ServiceCatalogServiceClient {
	sdkClient, err := servicecatalogsdk.NewServiceCatalogClientWithConfigurationProvider(manager.Provider)
	hooks := newServiceCatalogRuntimeHooks(manager, sdkClient)
	config := buildServiceCatalogGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize ServiceCatalog OCI client: %w", err)
	}
	delegate := defaultServiceCatalogServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*servicecatalogv1beta1.ServiceCatalog](config),
	}
	return wrapServiceCatalogGeneratedClient(hooks, delegate)
}
