/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package instancepoolinstance

import (
	"context"
	"fmt"

	coresdk "github.com/oracle/oci-go-sdk/v65/core"
	corev1beta1 "github.com/oracle/oci-service-operator/api/core/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// InstancePoolInstanceServiceClient is the handwritten extension seam for InstancePoolInstance runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*InstancePoolInstanceServiceManager).WithClient.
type InstancePoolInstanceServiceClient interface {
	CreateOrUpdate(context.Context, *corev1beta1.InstancePoolInstance, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *corev1beta1.InstancePoolInstance) (bool, error)
}

type defaultInstancePoolInstanceServiceClient struct {
	generatedruntime.ServiceClient[*corev1beta1.InstancePoolInstance]
}

var _ InstancePoolInstanceServiceClient = defaultInstancePoolInstanceServiceClient{}

var newInstancePoolInstanceServiceClient = func(manager *InstancePoolInstanceServiceManager) InstancePoolInstanceServiceClient {
	sdkClient, err := coresdk.NewComputeManagementClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*corev1beta1.InstancePoolInstance]{
		Kind:    "InstancePoolInstance",
		SDKName: "InstancePoolInstance",
		Log:     manager.Log,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.GetInstancePoolInstanceRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.GetInstancePoolInstance(ctx, *request.(*coresdk.GetInstancePoolInstanceRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &coresdk.ListInstancePoolInstancesRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListInstancePoolInstances(ctx, *request.(*coresdk.ListInstancePoolInstancesRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize InstancePoolInstance OCI client: %w", err)
	}
	return defaultInstancePoolInstanceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*corev1beta1.InstancePoolInstance](config),
	}
}
