apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/dataflow.oracle.com_applications.yaml
- bases/dataflow.oracle.com_pools.yaml
- bases/dataflow.oracle.com_privateendpoints.yaml
- bases/dataflow.oracle.com_runlogs.yaml
- bases/dataflow.oracle.com_runs.yaml
- bases/dataflow.oracle.com_sqlendpoints.yaml
- bases/dataflow.oracle.com_statements.yaml
- bases/dataflow.oracle.com_workrequesterrors.yaml
- bases/dataflow.oracle.com_workrequestlogs.yaml
- bases/dataflow.oracle.com_workrequests.yaml
