/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package dashboardgroup

import (
	"context"
	"fmt"

	dashboardservicesdk "github.com/oracle/oci-go-sdk/v65/dashboardservice"
	dashboardservicev1beta1 "github.com/oracle/oci-service-operator/api/dashboardservice/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DashboardGroupServiceClient is the handwritten extension seam for DashboardGroup runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DashboardGroupServiceManager).WithClient.
type DashboardGroupServiceClient interface {
	CreateOrUpdate(context.Context, *dashboardservicev1beta1.DashboardGroup, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *dashboardservicev1beta1.DashboardGroup) (bool, error)
}

type defaultDashboardGroupServiceClient struct {
	generatedruntime.ServiceClient[*dashboardservicev1beta1.DashboardGroup]
}

var _ DashboardGroupServiceClient = defaultDashboardGroupServiceClient{}

var newDashboardGroupServiceClient = func(manager *DashboardGroupServiceManager) DashboardGroupServiceClient {
	sdkClient, err := dashboardservicesdk.NewDashboardGroupClientWithConfigurationProvider(manager.Provider)
	hooks := newDashboardGroupRuntimeHooks(manager, sdkClient)
	config := buildDashboardGroupGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DashboardGroup OCI client: %w", err)
	}
	delegate := defaultDashboardGroupServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*dashboardservicev1beta1.DashboardGroup](config),
	}
	return wrapDashboardGroupGeneratedClient(hooks, delegate)
}
