apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/redis.oracle.com_redisclusters.yaml
- bases/redis.oracle.com_workrequesterrors.yaml
- bases/redis.oracle.com_workrequestlogs.yaml
- bases/redis.oracle.com_workrequests.yaml
