/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package iotdomaingroup

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	iotv1beta1 "github.com/oracle/oci-service-operator/api/iot/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type IotDomainGroupServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client IotDomainGroupServiceClient
}

var _ servicemanager.OSOKServiceManager = (*IotDomainGroupServiceManager)(nil)

func NewIotDomainGroupServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *IotDomainGroupServiceManager {
	manager := &IotDomainGroupServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newIotDomainGroupServiceClient(manager)
	return manager
}

func NewIotDomainGroupServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *IotDomainGroupServiceManager {
	return NewIotDomainGroupServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *IotDomainGroupServiceManager) WithClient(client IotDomainGroupServiceClient) *IotDomainGroupServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *IotDomainGroupServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *IotDomainGroupServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *IotDomainGroupServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *IotDomainGroupServiceManager) convert(obj runtime.Object) (*iotv1beta1.IotDomainGroup, error) {
	resource, ok := obj.(*iotv1beta1.IotDomainGroup)
	if !ok {
		return nil, fmt.Errorf("expected *iotv1beta1.IotDomainGroup, got %T", obj)
	}
	return resource, nil
}

func (c *IotDomainGroupServiceManager) status(resource *iotv1beta1.IotDomainGroup) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
