/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package faultdomain

import (
	"context"
	"fmt"

	identitysdk "github.com/oracle/oci-go-sdk/v65/identity"
	identityv1beta1 "github.com/oracle/oci-service-operator/api/identity/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// FaultDomainServiceClient is the handwritten extension seam for FaultDomain runtime behavior.
// Add a manual file in this package that implements the interface and wire it through
// (*FaultDomainServiceManager).WithClient.
type FaultDomainServiceClient interface {
	CreateOrUpdate(context.Context, *identityv1beta1.FaultDomain, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *identityv1beta1.FaultDomain) (bool, error)
}

type defaultFaultDomainServiceClient struct {
	generatedruntime.ServiceClient[*identityv1beta1.FaultDomain]
}

var _ FaultDomainServiceClient = defaultFaultDomainServiceClient{}

var newFaultDomainServiceClient = func(manager *FaultDomainServiceManager) FaultDomainServiceClient {
	sdkClient, err := identitysdk.NewIdentityClientWithConfigurationProvider(manager.Provider)
	config := generatedruntime.Config[*identityv1beta1.FaultDomain]{
		Kind:    "FaultDomain",
		SDKName: "FaultDomain",
		Log:     manager.Log,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &identitysdk.ListFaultDomainsRequest{} },
			Call: func(ctx context.Context, request any) (any, error) {
				return sdkClient.ListFaultDomains(ctx, *request.(*identitysdk.ListFaultDomainsRequest))
			},
		},
	}
	if err != nil {
		config.InitError = fmt.Errorf("initialize FaultDomain OCI client: %w", err)
	}
	return defaultFaultDomainServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*identityv1beta1.FaultDomain](config),
	}
}
