apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/secrets.oracle.com_secretbundlebynames.yaml
- bases/secrets.oracle.com_secretbundles.yaml
- bases/secrets.oracle.com_secretbundleversions.yaml
