/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package oracledbawskey

import (
	"context"

	dbmulticloudsdk "github.com/oracle/oci-go-sdk/v65/dbmulticloud"
	dbmulticloudv1beta1 "github.com/oracle/oci-service-operator/api/dbmulticloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type OracleDbAwsKeyRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *dbmulticloudv1beta1.OracleDbAwsKey, string) (any, error)
	BuildUpdateBody func(context.Context, *dbmulticloudv1beta1.OracleDbAwsKey, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*dbmulticloudv1beta1.OracleDbAwsKey]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*dbmulticloudv1beta1.OracleDbAwsKey]
	StatusHooks         generatedruntime.StatusHooks[*dbmulticloudv1beta1.OracleDbAwsKey]
	ParityHooks         generatedruntime.ParityHooks[*dbmulticloudv1beta1.OracleDbAwsKey]
	Async               generatedruntime.AsyncHooks[*dbmulticloudv1beta1.OracleDbAwsKey]
	DeleteHooks         generatedruntime.DeleteHooks[*dbmulticloudv1beta1.OracleDbAwsKey]
	Create              runtimeOperationHooks[dbmulticloudsdk.CreateOracleDbAwsKeyRequest, dbmulticloudsdk.CreateOracleDbAwsKeyResponse]
	Get                 runtimeOperationHooks[dbmulticloudsdk.GetOracleDbAwsKeyRequest, dbmulticloudsdk.GetOracleDbAwsKeyResponse]
	List                runtimeOperationHooks[dbmulticloudsdk.ListOracleDbAwsKeysRequest, dbmulticloudsdk.ListOracleDbAwsKeysResponse]
	Update              runtimeOperationHooks[dbmulticloudsdk.UpdateOracleDbAwsKeyRequest, dbmulticloudsdk.UpdateOracleDbAwsKeyResponse]
	Delete              runtimeOperationHooks[dbmulticloudsdk.DeleteOracleDbAwsKeyRequest, dbmulticloudsdk.DeleteOracleDbAwsKeyResponse]
	WrapGeneratedClient []func(OracleDbAwsKeyServiceClient) OracleDbAwsKeyServiceClient
}

type OracleDbAwsKeyRuntimeHooksMutator func(*OracleDbAwsKeyServiceManager, *OracleDbAwsKeyRuntimeHooks)

var oracledbawskeyRuntimeHooksMutators []OracleDbAwsKeyRuntimeHooksMutator

func registerOracleDbAwsKeyRuntimeHooksMutator(mutator OracleDbAwsKeyRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	oracledbawskeyRuntimeHooksMutators = append(oracledbawskeyRuntimeHooksMutators, mutator)
}
func newOracleDbAwsKeyDefaultRuntimeHooks(sdkClient dbmulticloudsdk.DbMulticloudAwsProviderClient) OracleDbAwsKeyRuntimeHooks {
	return OracleDbAwsKeyRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*dbmulticloudv1beta1.OracleDbAwsKey]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*dbmulticloudv1beta1.OracleDbAwsKey]{},
		StatusHooks:     generatedruntime.StatusHooks[*dbmulticloudv1beta1.OracleDbAwsKey]{},
		ParityHooks:     generatedruntime.ParityHooks[*dbmulticloudv1beta1.OracleDbAwsKey]{},
		Async:           generatedruntime.AsyncHooks[*dbmulticloudv1beta1.OracleDbAwsKey]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*dbmulticloudv1beta1.OracleDbAwsKey]{},
		Create: runtimeOperationHooks[dbmulticloudsdk.CreateOracleDbAwsKeyRequest, dbmulticloudsdk.CreateOracleDbAwsKeyResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateOracleDbAwsKeyDetails", RequestName: "CreateOracleDbAwsKeyDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request dbmulticloudsdk.CreateOracleDbAwsKeyRequest) (dbmulticloudsdk.CreateOracleDbAwsKeyResponse, error) {
				return sdkClient.CreateOracleDbAwsKey(ctx, request)
			},
		},
		Get: runtimeOperationHooks[dbmulticloudsdk.GetOracleDbAwsKeyRequest, dbmulticloudsdk.GetOracleDbAwsKeyResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "OracleDbAwsKeyId", RequestName: "oracleDbAwsKeyId", Contribution: "path", PreferResourceID: true}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request dbmulticloudsdk.GetOracleDbAwsKeyRequest) (dbmulticloudsdk.GetOracleDbAwsKeyResponse, error) {
				return sdkClient.GetOracleDbAwsKey(ctx, request)
			},
		},
		List: runtimeOperationHooks[dbmulticloudsdk.ListOracleDbAwsKeysRequest, dbmulticloudsdk.ListOracleDbAwsKeysResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "OracleDbAwsKeyId", RequestName: "oracleDbAwsKeyId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "OracleDbAwsConnectorId", RequestName: "oracleDbAwsConnectorId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request dbmulticloudsdk.ListOracleDbAwsKeysRequest) (dbmulticloudsdk.ListOracleDbAwsKeysResponse, error) {
				return sdkClient.ListOracleDbAwsKeys(ctx, request)
			},
		},
		Update: runtimeOperationHooks[dbmulticloudsdk.UpdateOracleDbAwsKeyRequest, dbmulticloudsdk.UpdateOracleDbAwsKeyResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "OracleDbAwsKeyId", RequestName: "oracleDbAwsKeyId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateOracleDbAwsKeyDetails", RequestName: "UpdateOracleDbAwsKeyDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request dbmulticloudsdk.UpdateOracleDbAwsKeyRequest) (dbmulticloudsdk.UpdateOracleDbAwsKeyResponse, error) {
				return sdkClient.UpdateOracleDbAwsKey(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[dbmulticloudsdk.DeleteOracleDbAwsKeyRequest, dbmulticloudsdk.DeleteOracleDbAwsKeyResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "OracleDbAwsKeyId", RequestName: "oracleDbAwsKeyId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request dbmulticloudsdk.DeleteOracleDbAwsKeyRequest) (dbmulticloudsdk.DeleteOracleDbAwsKeyResponse, error) {
				return sdkClient.DeleteOracleDbAwsKey(ctx, request)
			},
		},
		WrapGeneratedClient: []func(OracleDbAwsKeyServiceClient) OracleDbAwsKeyServiceClient{},
	}
}

func newOracleDbAwsKeyRuntimeHooks(manager *OracleDbAwsKeyServiceManager, sdkClient dbmulticloudsdk.DbMulticloudAwsProviderClient) OracleDbAwsKeyRuntimeHooks {
	hooks := newOracleDbAwsKeyDefaultRuntimeHooks(sdkClient)
	for _, mutator := range oracledbawskeyRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildOracleDbAwsKeyGeneratedRuntimeConfig(
	manager *OracleDbAwsKeyServiceManager,
	hooks OracleDbAwsKeyRuntimeHooks,
) generatedruntime.Config[*dbmulticloudv1beta1.OracleDbAwsKey] {
	return generatedruntime.Config[*dbmulticloudv1beta1.OracleDbAwsKey]{
		Kind:            "OracleDbAwsKey",
		SDKName:         "OracleDbAwsKey",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &dbmulticloudsdk.CreateOracleDbAwsKeyRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*dbmulticloudsdk.CreateOracleDbAwsKeyRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &dbmulticloudsdk.GetOracleDbAwsKeyRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*dbmulticloudsdk.GetOracleDbAwsKeyRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &dbmulticloudsdk.ListOracleDbAwsKeysRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*dbmulticloudsdk.ListOracleDbAwsKeysRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &dbmulticloudsdk.UpdateOracleDbAwsKeyRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*dbmulticloudsdk.UpdateOracleDbAwsKeyRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &dbmulticloudsdk.DeleteOracleDbAwsKeyRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*dbmulticloudsdk.DeleteOracleDbAwsKeyRequest))
			},
		},
	}
}

func wrapOracleDbAwsKeyGeneratedClient(
	hooks OracleDbAwsKeyRuntimeHooks,
	delegate OracleDbAwsKeyServiceClient,
) OracleDbAwsKeyServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
